### ISSUE TITLE
Improve error message with empty file on demux creation

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1002]
If the demultiplexing step fails to retrieve any sequences and you pass an empty file to the demux file creation step, the following error will be presented:

```
 ValueError(zero-size array to reduction operation maximum which has no identity)
```

It would be much nicer if the error indicated what the problem is.

**Comment by antgonza** [comment]
This was solved some time ago. [This is the line](https://github.com/qiita-spots/qp-target-gene/blob/master/qp_target_gene/split_libraries/util.py#L109) that solves it.
