### ISSUE TITLE
Refactor get_accessible_filepath_ids

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1010]

**Comment by squirrelo** [comment]
Can you add more detail to this? I feel liek it's going to get lost in the pile of issues since it's super vague.

**Comment by antgonza** [comment]
Is this related to: https://github.com/biocore/qiita/issues/601?

**Comment by antgonza** [comment]
@josenavas could you add a list of what's needed? Thanks!

**Comment by josenavas** [comment]
The function `get_accessible_filepath_ids` is quite expensive and there is probably a better way of doing the work in there.
