### ISSUE TITLE
New GENSC Null Value Controlled Vocab

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1013]
We should implement this in Qiita. IMHO, this also underscores the need for an easier way to update studies in EBI (after they have already been submitted) to deal with the "temporarily obscured" and "to be reported" values here, in addition to other use cases. This is verbatim from the email:

> We would like to bring to your attention that from May 2015 the ENA will support a new null value vocabulary in ENA sample metadata checklists.
> 
> Based on recent discussions with the expert/research communities and feedback from submitters the ENA will from May 2015 support reporting of null values with a controlled vocabulary that we believe suits well needs of the user community we serve as well as development and service needs of the database.
> 
> The null value vocabulary aims to describe the following cases (concepts):
> 
> not applicable (metadata information is inappropriate to report, can indicate that the standard itself fails to model or represent the information appropriately)
> 
> not available: not collected (metadata information of an expected format was not given because it has not been collected) 
> not available: to be reported (metadata information of an expected format was not given, a value will be given at the later stage)
> not available: restricted access (metadata information exists but can not be released openly)
> 
> obscured (metadata information has been provided deliberately with low precision)
> temporarily obscured (metadata information has been provided deliberately with low precision, a higher precision value will be provided at a later stage)
> 
> The last two, which consider level of precision, will be used, for example, for geo-references (latitude, longitude and country/sea). 

Marking low priority for now, since the changes are still being discussed and are not due out until May anyways.

**Comment by antgonza** [comment]
[This](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html#ebi-ena-null-values-vocabulary) has been in place for some time now, closing.
