### ISSUE TITLE
tabs in study description

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1015]
In most use cases, based on my last few week tests, the user will be mainly working on the last object added into a working tab. Thus, when clicking on a tab in the study description (let's say: Processed data) the focus should be in the last tab within the new tabs vs. the first one. This should make it more user friendly.

**Comment by ackermag** [comment]
Agree - this would be helpful

On Thu, Mar 26, 2015 at 6:04 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> In most use cases, based on my last few week tests, the user will be
> mainly working on the last object added into a working tab. Thus, when
> clicking on a tab in the study description (let's say: Processed data) the
> focus should be in the last tab within the new tabs vs. the first one. This
> should make it more user friendly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1015>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>
