### ISSUE TITLE
In hindsight, <study_id>.<sample_id> was a very bad idea

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1017]
All of the existing studies we've submitted to EBI through the QIIMEdb were <sample_id>.<something_else>. What this means is that our expectations of the IDs are inverted if using QIIMEdb derived EBI submissions in combination with qiita derived ones. 

Creating this issue so that people are aware. At this point, I do not believe there is anything we can do in qiita since we've been submitting studies. 

I cannot think of a way out of this for American Gut without special casing, which is going to get ugly.

**Comment by josenavas** [comment]
Should we close this in favor of #1022, given that it looks like we got an agreement there?

**Comment by antgonza** [comment]
Closing this in favor of #1022
