### ISSUE TITLE
<study id>.<sample id> in preprocessed and processed data

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1022]
When loading a sample/prep template, Qiita will prepend study identifiers at the beginning of every sample name (if these didn't already exist). We should perhaps be consistent and do the same thing when loading preprocessed and processed data using the command line utilities. Otherwise you have a high probability of ending up with useless data i.e. tables and sequences that don't have a match with your sample metadata.

Updating the biom files is not a problem [`update_ids`](http://biom-format.org/documentation/generated/biom.table.Table.update_ids.html#biom.table.Table.update_ids) will take care of this. However sequences are a different problem, so I'm tagging this as a question for the time-being and a bug that needs to be resolved.

At the very least the commands should verify that all samples names exist in the sample/prep templates these are being added to.

---

We may want to revisit the `<study id>.<sample id>` approach as @wasade brought up #1017 as a palpable and outstanding problem.

**Comment by wasade** [comment]
Updating demux sequence is easy and quick as its just renaming groups in the HDF5 file. Raw sequences is expensive as you have to walk the full file.

Regarding #1017, I think we're screwed as backtracking now will probably just cause even more issues. For AG, we have 3 types of sample IDs:

<sample_id>.<arbitrary_number>  # qiimedb
<sample_id>  # qiita pre november change
<study_id>.<sample_id>  # qiita post november change

I've added in remapping methods to coerce all of the IDs in to a consistent format for AG. While we can add more methods for remapping, I worry about silent issues and the cognitive load not just for AG but for anyone else pulling data out of EBI.

**Comment by antgonza** [comment]
I thought we agree on making names consistent on the DB and adding a
new column that shows the old sample names, perhaps the column can be
named EBI_sample_name?

**Comment by rob-knight** [comment]
Yes that is what we agreed.


On Mar 30, 2015, at 10:40 PM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>> wrote:

I thought we agree on making names consistent on the DB and adding a
new column that shows the old sample names, perhaps the column can be
named EBI_sample_name?

**Comment by antgonza** [comment]
@ElDeveloper is this still an issue?

**Comment by ElDeveloper** [comment]
Yes, this would still be an issue, as the command line utilities allow for users to load data that matches none of the identifiers represented in the sample/prep templates.

**Comment by josenavas** [comment]
Thanks @ElDeveloper 

I see that this has the label "high:priority" but at the same time is added to the beta milestone - can you re-define which is the priority of this issue (either by adding it to the SLOAN milestone or by removing the label)

**Comment by ElDeveloper** [comment]
Updated, thanks!

**Comment by antgonza** [comment]
This was solved via the plugins and their validation. Closing now.
