### ISSUE TITLE
"Scale coords by percent explained" and biplots error

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1023]
If you check "Scale coords by percent explained", the arrows in the biplots do not get resized.

**Comment by josenavas** [comment]
@antgonza is this a qiita or emperor issue?

**Comment by antgonza** [comment]
Is a problem with The Force ... moving to Emperor (https://github.com/biocore/emperor/issues/387)

**Comment by antgonza** [comment]
Is a problem with The Force ... moving to Emperor (https://github.com/biocore/emperor/issues/387)
