### ISSUE TITLE
Impossible to test data patches

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1024]
Test data is loaded into the database after applying all patches, so any patches that rely on data to create new rows/alter existing rows will never be tested for correctness.

**Comment by antgonza** [comment]
This is the broader comment of: https://github.com/biocore/qiita/issues/717

**Comment by josenavas** [comment]
This is also a broader discussion - if we can switch the tests for not relying on SQL and do them independent of the actual data held in SQL, we can create a populate test db that loads at the very beginning and then all patches are applied.

**Comment by squirrelo** [comment]
This has actually worked out really well in practice for AG tests, so I'd say go that way.

**Comment by antgonza** [comment]
Group resolution: this will be a valuable addition but it's low priority. The idea will be to populate the DB, then make sure that the latests tests pass (meaning that the test were successful after the patch).

**Comment by antgonza** [comment]
This was fixed here: https://github.com/biocore/qiita/pull/2006
