### ISSUE TITLE
Add "request EBI submission" button

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1027]
Similar to the "request approval" button for approve the metadata. This will allow to request that with a single click, rather than contacting us. This also means a new page in the admin page

**Comment by ElDeveloper** [comment]
If it's private or if it's public, users should be able to submit to EBI, because the data should already be approved by an admin. Granted that the required columns are present.

**Comment by adamrp** [comment]
Also, this should just be a "Submit to EBI" button rather than "Request EBI
Submission" button (once the study is *at least* private and has the
necessary columns for EBI submission)

**Comment by antgonza** [comment]
Superseded by https://github.com/biocore/qiita/issues/2721
