### ISSUE TITLE
Fireworks for successful upload

### ISSUE THREAD

**Issue by nbokulich** [biocore/qiita#1028]
There are no fireworks to congratulate users who successfully upload data, like qiime-db did. They don't need to be fireworks. Maybe a dancing cheetah? But there should be something. Nothing says a job well done quite like fireworks...

**Comment by ElDeveloper** [comment]
:+1:

**Comment by squirrelo** [comment]
:+1:

**Comment by wasade** [comment]
:fireworks:

**Comment by ElDeveloper** [comment]
> :fireworks: 

word

**Comment by antgonza** [comment]
Gonna close for now.
