### ISSUE TITLE
email verify link missing http{s}://

### ISSUE THREAD

**Issue by audy** [biocore/qiita#1035]
https://github.com/biocore/qiita/blob/0d2491a5a45c87c3fe8ac486f9de8d94c5ff8b94/qiita_pet/handlers/auth_handlers.py#L46-L50

This causes email programs not to make the link clickable.

**Comment by antgonza** [comment]
Thank you for your comment. I believe that feature is email client
dependent. Generally we test with gmail where the link is clickable.

Anyway, do you have a suggestion on how to make it generally clickable
for all clients?

**Comment by wasade** [comment]
Can't check code right now, but is it prefixed with `mailto:`?

**Comment by antgonza** [comment]
It's an url not an email:
send_email(username, "QIITA: Verify Email Address", "Please "
"click the following link to verify email address: "
"%s/auth/verify/%s?email=%s"
% (qiita_config.base_url, info['user_verify_code'],
url_escape(username)))

**Comment by audy** [comment]
lots of things work in gmail that don't work in mutt :wink:. Just thought I would point it out. QIITA is nice work btw. I'm already finding it incredibly useful.

**Comment by josenavas** [comment]
Thanks @audy ! It is still on heavy development so please, do not hesitate on reporting issues so we can make it even more useful! And of course, contributions are more than welcome! We are planning to include some developer documentation soon, so it is easier for new developers start on the system.

**Comment by ElDeveloper** [comment]
:+1: another fellow mutt user! :fireworks:

**Comment by audy** [comment]
> Anyway, do you have a suggestion on how to make it generally clickable
for all clients?

Either use an actual html anchor tag and send an HTML email or prepend `http://` to the URL so that most browsers can recognize it as a URL.

**Comment by squirrelo** [comment]
I'm surprised the `qiita_config.base_url`setting is missing the http:// or https:// leader on the main system. That would fix this problem.

**Comment by ElDeveloper** [comment]
Yes, should we also add a comment right above that setting in the config
file saying something along the lines of:

```
# don't forget to specify the protocol i.e. http or https
base_url = http://debugatron-200.com/ 
```

**Comment by squirrelo** [comment]
Sounds good to me.

**Comment by antgonza** [comment]
This was solved in the main deploy but the issue was never closed. Closing now.
