### ISSUE TITLE
Fix --insdc option in qiita load_preprocessed 

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1051]
Currently it is a boolean option, it should really be a "choice" type, in general we need to:
- [ ] Set a patch to correct existing entries as `true` to `submitted` (where should we get the accession numbers from)?
- [ ] Change the option type so we dynamically retrieve the available options from the DB.
- [ ] Rename the option to reflect the type.

**Comment by adamrp** [comment]
The option is "submitted_to_insdc_status", which, as @wasade pointed out on the call today, implies that the variable should take boolean values. So to add a comment to this issue, the option should probably be renamed to something like "insdc_submission_status" to avoid confusion.

**Comment by antgonza** [comment]
CLI will be minimized: https://github.com/biocore/qiita/issues/1999, closing.
