### ISSUE TITLE
Make studies awaiting approval more obvious

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1065]
It is not obvious in the interface when there is a study awaiting approval. It should be clearer so that studies aren't in the queue longer than necessary.

**Comment by josenavas** [comment]
@adamrp can you elaborate? We already have an Admin page that lists only those studies that are waiting for their processed data to be approved...

The only think that I can think of is once an "Admin" logs in, show a message on top of the page stating that there are studies waiting for approval. Is that what you mean?

**Comment by ackermag** [comment]
Can we generate an email as a heads up - I am not always working only on
Qiita?


On Thu, Apr 16, 2015 at 9:38 AM, josenavas <notifications@github.com> wrote:

> @adamrp <https://github.com/adamrp> can you elaborate? We already have an
> Admin page that lists only those studies that are waiting for their
> processed data to be approved...
>
> The only think that I can think of is once an "Admin" logs in, show a
> message on top of the page stating that there are studies waiting for
> approval. Is that what you mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1065#issuecomment-93780500>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by adamrp** [comment]
Basically, this came up because @ackermag was not aware that there was a study awaiting approval, even though she was using Qiita. In other words, she would have to go to that admin page in order to see the studies awaiting approval. It would be ideal if it was somehow indicated in the menu bar that there were studies awaiting approval, or if on the main login page for admins, if it said in red text "There are ## studies awaiting approval" or something

**Comment by josenavas** [comment]
Awesome thanks! I think a banner on top would be great! Adding to Alpha 0.2 as I think it's easy and it will improve the Qiita usage :smile:

**Comment by ElDeveloper** [comment]
Maybe a feed on the home page, we are currently not using the home page
for anything.

**Comment by antgonza** [comment]
ha! after reading the full thread, this issue is basically the original idea behind this: https://github.com/biocore/qiita/issues/2358. Thus, closing this one.
