### ISSUE TITLE
Qiita's cluster must have at least 2 workers

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1066]
If you set it to use only 1 and try to submit a meta-analysis, the job will never change from Queued to Running.

**Comment by josenavas** [comment]
I thought this was already specified in the documentation at some point? Probably worth to put some checks in place...

**Comment by ElDeveloper** [comment]
Perhaps the checks in qiita_test_install should verify that there's at
least 2 workers?

**Comment by squirrelo** [comment]
Could also make it so you must start at least 2 workers with qiita_env start_cluster command.

**Comment by ElDeveloper** [comment]
That sounds ok, but qiita_test_install should throw an error if there
are not at least 2 workers.
