### ISSUE TITLE
qiita_env make and database name conflict

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1067]
I ran into a situation where a user named 'qiita' had a database named 'qiita' in a postgres server, and in my configuration file I had the the database setting set as `DATABASE = qiita`. When I tried to run `qiita_env make`, the command would fail saying something along the lines of 'database qiita already exists', so I decided to do `qiita_env drop`, however since this was a new system the command would fail saying that the "settings table" was not there.

After talking with @josenavas, the solution was to change the name of the database in the configuration file from `qiita` to :arrow_right:  `qiita_xxxxx` (though really any name would work).

The solution should be to either allow for the database to be dropped regardless of whether or not the settings table exists (which might be problematic), or to come up with a self-explanatory error message.

**Comment by antgonza** [comment]
Fixed by https://github.com/biocore/qiita/pull/2507
