### ISSUE TITLE
Search on list_studies.html gives no visual feedback

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1069]
Currently, if I do a search, there is no explicit visual feedback. There *might* be implicit feedback (if the search results in changes to the list of studies being displayed), but explicit feedback would be great (e.g., a very obvious/colorful/bold statement that indicates "Only showing studies that comprise samples hit by the following criteria: XXXXXXX").

Another improvement would be to show on this page how many of each study's samples are selected by the criteria specified.

**Comment by squirrelo** [comment]
Sample count is currently shown by processed data id when you expand the study information, since it may vary for each processed data. I agree with the more explicit change for search results though.
