### ISSUE TITLE
Update sample template takes very long when there are more than~250 samples

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1081]
I have been waiting >20 mins for 1143 samples to update

**Comment by josenavas** [comment]
Thanks @ackermag 
For the time being, I've added this issue to the Alpha 0.1 milestone. My guess is that after the refactor that I'm doing in the metadata_template object this will go smoother. If after such refactor this is still an issue, we can re-assign to Alpha 0.2 and investigate the issue further.

**Comment by ElDeveloper** [comment]
@josenavas and I just tested with the latest version of master and a study with 1626 samples, the time went from 1 minute and 53 seconds (before relax-md-reqs) to 54 seconds. While this does reduce the amount of time it takes to update the sample template, it is still slow. @josenavas thinks that most of the time is spent opening/closing connections and this will likely be resolved with @antgonza's upcoming PR, I am bumping this to 0.2 for the time being.

**Comment by antgonza** [comment]
@ElDeveloper could you test again to see if this is solved? Thanks.

**Comment by ElDeveloper** [comment]
Just tested this and it is still a problem.

**Comment by antgonza** [comment]
Thanks. How long is it taking now?

**Comment by ElDeveloper** [comment]
About the same amount of time.

**Comment by josenavas** [comment]
By the same amount of time you mean 54 seconds?

**Comment by ElDeveloper** [comment]
Ok, nix that it really took around 2-3 minutes (on microbio.me).

**Comment by josenavas** [comment]
Ok, I think the only solution for making this happening faster is actually making sure that everything happens in a single transaction block. I don't see any other way of improving this w/o doing a considerable refactor. Let's test again once we make sure that everything in the code base is executed in transaction blocks.

If this is still an issue, then we will need to do some refactoring. which I more or less know how should be done, but is some kind of time consuming and we have other things that are more important than this.

**Comment by wasade** [comment]
Would it be possible to profile to determine what specifically is slow?

**Comment by josenavas** [comment]
Moving this to alpha 0.3

**Comment by josenavas** [comment]
Can this be closed?
