### ISSUE TITLE
In place documentation to use Keemei

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1086]
[Keemei](https://github.com/jairideout/Keemei) has a great potential to be used to curate templates. We should redirect there so users can use it to get their templates Qiita-compliant.

Ideally, we would be able to just pull the data directly from google spreadsheets, so the user don't really need to download the template and upload it again on Qiita.

**Comment by antgonza** [comment]
Fixed in last deploy:
<img width="681" alt="screen shot 2018-02-19 at 8 39 34 am" src="https://user-images.githubusercontent.com/2014559/36385740-a76b8c8e-1550-11e8-899d-c2619012be48.png">
