### ISSUE TITLE
Pre-process all target gene datasets

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1087]
Qiita should be able to run split libraries in all raw data target gene data types.

**Comment by antgonza** [comment]
@josenavas could you clarify/expand this issue? Not sure what you mean.

**Comment by josenavas** [comment]
One of the main problems is that in Qiita we make the difference between 16S, 18S and ITS, but we are not listing all the other possible target genes. The suggestion is to rename all of them to target_gene and have a different way of telling the subtype (16S, 18S, ITS, or others). A user that do not have one of the current 3 subtypes listed may think that his data can't be processed, while the processing pipeline is the same (we only change parameters).

**Comment by antgonza** [comment]
This is basically https://github.com/biocore/qiita/issues/1569 so closing this one.
