### ISSUE TITLE
Allow processing pre-processed data against any database

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1088]
This is more or less supported. Probably we need an easier way or a UI for admins way to create and add new reference/parameter sets to the database.

**Comment by antgonza** [comment]
Jus to clarify, what we want in this issue is to allow reprocessing of an already preprocessed table, right?

**Comment by josenavas** [comment]
My bad, poorly described. I think we have another issue for what you're describing @antgonza #1026 
What this issue tries to explain is that we should be able to run pick otus against any reference DB (Silva, UNITE), not only Greengenes as we currently have.

This is supported, and new databases can be added through the CLI. I added the label `qiita.microbio.me` as this is something that applies to the server. On the other hand, I think it would be useful to have an admin page to do this, instead of relying only in the CLI. IMOO it would be easier to add future reference DB.

This will also require modifications to the parameters, as I don't think we want to duplicate all the parameters in the interface every time that we add a new reference DB. I think we can have a drop-down menu for the parameters, and another drop down menu for the Reference DB to use.

Does this sound reasonable?

**Comment by antgonza** [comment]
This is already supported, closing now. Reopen if you feel otherwise.
