### ISSUE TITLE
Delete meta-analysis

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1091]
So if a user wants to remove a private study that has meta-analyses, he can delete first the meta-analyses and then remove all the other study items.

**Comment by antgonza** [comment]
I think the plan is to allow to remove any analysis, right? The current constrains about deleting a process data will not allow to delete it as long as it has an analysis ...

**Comment by josenavas** [comment]
Yes, any analysis. At this point we do not allow to create an analysis from another one (i.e. the analysis chain table) and we don't have a way to share analysis or make them public (although this is a goal at the end), so we should allow to delete any analysis right now.
