### ISSUE TITLE
spurious empty raw data IDs generated for 10128

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1093]
Not sure how those got created. Data were loaded using `qiita db load_raw`

**Comment by antgonza** [comment]
Could you post the full command(s)?

**Comment by wasade** [comment]
Here is an example of one:

```bash
./qiita db load_raw --fp ../../ag_16_17/ag17/Pool_S1_L001_R2_001.fastq.gz --fp_type raw_reverse_seqs --filetype FASTQ --study 10129
```

**Comment by antgonza** [comment]
CLI will be minimized: https://github.com/biocore/qiita/issues/1999, closing.
