### ISSUE TITLE
Expand study info only if proc data exists

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1100]
Currently, every study shows that expand when clicked no matter what it has. We should only show this expand info if there is actually processed data attached to the study.

**Comment by antgonza** [comment]
@squirrelo I'm not sure what you mean, could you clarify? Perhaps a screenshot will be useful.

**Comment by squirrelo** [comment]
I don't think this fits any more, since we make processed data public now, not studies.

**Comment by antgonza** [comment]
OK, thanks. Can we close?
