### ISSUE TITLE
Provide a better feedback on the already selected samples @ study listing page

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1102]
Adding the issue although I strongly disagree to merge something that a group of developers already see that is confusing...

**Comment by squirrelo** [comment]
With the new contributing.md, can you provide an explanation of the problem and why it is a problem?

**Comment by josenavas** [comment]
The main problem is that once you choose a sample in the study listing page you don't have any kind of feedback knowing which samples you've already selected.

**Comment by antgonza** [comment]
This was solved via the current (new, it's not really that new but this issue was never closed) analysis interface ....
