### ISSUE TITLE
Empty cells in final column of metadata will lead to failed upload

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1105]
Reports expecting X columns of metadata getting NNNNNN 9e.g. expecting 73, getting 537

**Comment by antgonza** [comment]
Just tested and this only happens if the extra columns have white spaces.

**Comment by adswafford** [comment]
Can we just have any empty columns get stripped off?

**Comment by antgonza** [comment]
fixed in https://github.com/biocore/qiita/pull/2472
