### ISSUE TITLE
submit to EBI reverse reads

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1117]
From @rob-knight. We need to submit reverse reads to EBI. The current solution which is fine but not super clean is to have 2 prep templates in the same qiita study and process separately the forward+reverse and reverse reads. Then submit each of them separately. We should have a single button for this.

**Comment by josenavas** [comment]
The prep template will be the same? If so, we probably just want to run it behind the scenes automatically, every time that we run split libraries, so the submit to EBI functionality still receive a single preprocessed data.

**Comment by antgonza** [comment]
Note that [_generate_spot_descriptor](https://github.com/biocore/qiita/blob/407f782f5aba9c35233e86cfb4adac8da5b3fa4b/qiita_ware/ebi.py#L449) sets the direction of the read so my guess is that we can add the reverse in the same direction just changing that value.

**Comment by josenavas** [comment]
Uhm... @antgonza note that the method you're pointing out is just applied for LS454 data, so I don't think it's going to work for Illumina...

**Comment by antgonza** [comment]
You are right but the idea still stands of using:
```
        read_type = ET.SubElement(read_spec, 'READ_TYPE')
        read_type.text = 'Forward'
```
and
```
        read_type = ET.SubElement(read_spec, 'READ_TYPE')
        read_type.text = 'Reverse'
```

**Comment by josenavas** [comment]
Yup. I think the best path to move forward is to run split libraries in both of them and store "Forward reads" and "Reverse" reads in the PreprocessedData, this way we have all the information. Does this sounds like a good solution?

**Comment by antgonza** [comment]
Yes. However, note that we will like to start submitting the non QC reads but that's a different issue. Now, it will be great to solve both at the same time.

**Comment by josenavas** [comment]
Good point. As an option to solve this, is to run split libraries twice. One with QC and the other one relaxing the QC as much as possible to deactivate it (we currently don't have 2 different scripts for this). We then store all this information in the preprocessed data. For processing, we use the QC controlled ones, while for EBI submission we use the non-QC. Does this make sense?

**Comment by antgonza** [comment]
Just to leave it here for discussion, this is pretty easy for per_sample_FASTQ but the issue still is when we need to demux.

**Comment by antgonza** [comment]
I think once we fix https://github.com/biocore/qiita/issues/2677 (for which, we have a PR https://github.com/biocore/qiita/pull/2717), it's going to be the best/closest we can do to submit forward and reverse ... thus, I'm going to close this issue as https://github.com/biocore/qiita/issues/2677 supersedes it.
