### ISSUE TITLE
Problem with moi adding a study

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1124]
The following shows up in the tornado console when I select a study from the study list:

```python
ERROR:tornado.application:Uncaught exception in /moi-ws/
Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/websocket.py", line 303, in wrapper
    return callback(*args, **kwargs)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/moi/websocket.py", line 66, in on_message
    self.group.action(verb, args)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 189, in action
    raise TypeError("args is unknown type: %s" % type(args))
TypeError: args is unknown type: <type 'dict'>
```

**Comment by ElDeveloper** [comment]
PS, this is showing up when I merged the branch from #1122 and #1123 ... can someone else reproduce? This can very well be my system.

**Comment by wasade** [comment]
The payload being sent from the client includes a key value pair in the json object where the value is of type `dict`. moi has no mechanisms for dealing with this type of value. The js that issued this send is violating the moi protocol. Investigating

**Comment by wasade** [comment]
The cart is opening a websocket against the moi websocket handler, and not against the selected samples handler. Relevant lines in the merged PR:

https://github.com/biocore/qiita/pull/1058/files#diff-ec26581cd61e512b79f2ce31592a7552R67

https://github.com/biocore/qiita/pull/1058/files#diff-e1ededb407a16f3fc308d42303650f9dR78

Basically, the websocket handler that is used server side is hard coded. I do not understand right now how the cart could have functioned as it doesn't seem like the cart's handler was used?

cc @squirrelo

**Comment by wasade** [comment]
Nevermind!

@ElDeveloper, I think your #1123 is incomplete. The argument order was changed, but the code that uses moi.init was not updated. See:

https://github.com/biocore/qiita/pull/1058/files#diff-6a7c39174f9f7c334ef7091f87f54951R38

**Comment by ElDeveloper** [comment]
Thanks for looking into it, just pushed a fix.

**Comment by ElDeveloper** [comment]
And it seems to be working.
