### ISSUE TITLE
Limit the interface to disable functionality...

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1128]
...if columns are missing in the templates

**Comment by josenavas** [comment]
At this point, what we can limit is:
-  [ ] EBI submission
-  [ ] Make a process data public
-  [ ] Pre-processing

**Comment by antgonza** [comment]
I will say that EBI submission should be conditional on data type, but perhaps that's a bigger issue.

**Comment by josenavas** [comment]
Can you elaborate? Do you mean just allow EBI submission if it is a target gene datatype?

**Comment by antgonza** [comment]
The other way around, sorry for not being clear. Allow submission even without "split libraries" for other data-types ...

**Comment by josenavas** [comment]
Uhm, I think I don't understand you... The current system allows EBI submission from the pre-processed data only, are you proposing a change in there?

**Comment by josenavas** [comment]
This was solved in #1142
