### ISSUE TITLE
Allow update prep template through UI

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1130]
Some thought: disable if some functionality (i.e. preprocessing/EBI submission) has been already done on the prep template.

**Comment by antgonza** [comment]
Where should the buttons be? I can see two options, either in the raw data tab (where the prep template is added) or in the preprocessed data tab. I like option 1 but one of the requirements is that the buttons are only shown if the data hasn't been submitted to EBI/VAMPS, thus option 2. Preferences?

**Comment by josenavas** [comment]
There should be in the prep template tab. We can always check on the handler if we need to show those buttons or not, as it is done for a lot of other optional buttons in different points of the system.

As in the SampleTemplate buttons, they should be disallowed if any preprocessed data resulting from them has been uploaded to EBI/VAMPS and if the study is public.

**Comment by josenavas** [comment]
Sorry, on my last comment I meant if the prep template is public or not (it has a status property) so no need to look at the processed data/study.

**Comment by antgonza** [comment]
Just to be sure, you are saying that the buttons should be in the raw data tab within each of the prep templates linked to that specific raw data, right?

**Comment by josenavas** [comment]
I'm right now refactoring the interface, as part of my other pr. I hope to
have it soon, it is taking me longer than expected due to all the new code
in the interface.

It would be ideal if we can first make sure that the functionality is in
there so we just need to add the buttons at the end

**Comment by antgonza** [comment]
That's fine. Could you send you PR tomorrow?
