### ISSUE TITLE
Cannot Download Directory

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1132]
I just generated a processed data for a study I'm working on (study ID 1902, pd_id 152). There are three downloadable files: the biom, the log, and the directory. I can download the biom and the log, but get a 404 when I try to download the directory.

**Comment by antgonza** [comment]
@adamrp not sure if this is a qiita.colorado.edu specific bug or a code/resources bug. The folder that is pointing to exists but nginx is not expecting to list a folder. Now, these folders have 3+ files but I think we should only allow their gzip version. So perhaps the solution is that we gzip all existing files and update the links in a patch.

**Comment by adamrp** [comment]
The download handler was never set up to work with directories. Currently, the download handler works by looking at the filepaths table. Some of the paths in that table are directories. If a user has access to a directory in the filepaths table and they try to download any of the files in that directory (or subdirectories) it will work. However, if they try to download the directory itself, it won't work. The simplest way to allow the download of directories would be to gzip the directory and add the gzipped file to the filepaths table.

**Comment by adamrp** [comment]
I don't think we want to gzip everything because there is code that assumes that files in that table are *not* gzipped, but if the filepath is of a "directory" type, then we might need to do something smarter if a download of the directory is requested

**Comment by antgonza** [comment]
What about automatically generating an index.html page with links to the files?

**Comment by wasade** [comment]
:+1:, like FileLinks

**Comment by josenavas** [comment]
I think the smart think to do when a user request to download a file of type filepath will be to do a "tar" (not gziped) and then serve that. If it is of type directory it will be easy to detect.

**Comment by antgonza** [comment]
The problem with that option is that we will need to create a job so tornado doesn't block while taring ...

**Comment by wasade** [comment]
Creating/submitting the job is straight forward :)

**Comment by antgonza** [comment]
That's not the issue ... the question is how are we gonna deliver (page with possible download [possible duplication] or email [also duplication])?

**Comment by wasade** [comment]
A little spinny thing until the job completes? pubsub is already there, and
the moi list is embeddable in a div now too

**Comment by antgonza** [comment]
How to avoid duplication of tar or tgz files?

**Comment by wasade** [comment]
Where is the duplication happening, and do we care about long term storage?
Could just put in a scratch space and let the system clean up the tgz 1-2
weeks out since that wouldn't delete the actual files packed up

**Comment by antgonza** [comment]
Good point but sounds like a lot of work that could simply be solved with an index.html file ...

**Comment by wasade** [comment]
if moi is working as it should, then this should just be 2 lines of code:
instantiating the list in the template, and submitting with a download url.
without knowing anything of the surrounding logic, i can't say if that is
the case, and since we haven't integrated the list anywhere afaik, there is
of course potential for additional headache.

that being said, i did :+1: the index.html already as it has the benefit of
allowing someone to grab what they want, and not having to grab everything
at once. this solution likely requires more code than moi (again, a design
goal of moi but it assumes its reached sufficient maturity)

**Comment by josenavas** [comment]
IMO, we need both solutions, index + tar. The reason is that it can become a pain to download every single file if there is a lot of files. Probably, when the directory is generated, we also generate a .tar file and included it in the directory so it becomes automatically downloadable with the index.html? I think with this solution we can have the best of both worlds.

**Comment by adamrp** [comment]
Out of curiosity, why not gzip the tar file? Can't think of a reason not
to.

**Comment by josenavas** [comment]
I suggested tar because it was on the fly, by just doing a tar, there is no compression, which means that it is way faster to generate. If we go the route of adding it to the directory, we can then gzip it. Does it make sense?

**Comment by antgonza** [comment]
My plan was to generate the tgz at the same time than the files were generated. Now, putting all suggestions together I think the easiest is to:
1. Generate the individual files + a tgz when the preprocessing happens
2. Generate an index.html pointing to all this files within the folder.
Does this make sense? Note that the PR should have a patch to generate the tgz and the index.html files

**Comment by wasade** [comment]
This strategy duplicates all the result data indefinitely, and things like
biom and demux won't compress further with gz as they're already internally
compressed using gz. Not necessarily opposed, just want to make sure this
is recognized as it is a nontrivial long term burden.

**Comment by mortonjt** [comment]
Another option is to gzip while downloading.

If I remember correctly, gzip can be splittable. So it should be possible to download pieces of the file as it is being downloaded.  This strategy is commonly used in map reduce systems to reduce data bandwidth.

**Comment by antgonza** [comment]
Like this option, do you think this will be possible via ngnix?

**Comment by mortonjt** [comment]
I'd be surprised if that option wasn't available.

Looking [here](https://www.nginx.com/resources/admin-guide/compression-and-decompression/)
it seems that this functionality is directly built into ngnix

**Comment by antgonza** [comment]
Cool, thanks! Interested in fixing?

**Comment by mortonjt** [comment]
I'm willing to take a look into it.  Just as a heads up, I'll be off of the grid on Monday-Friday.

**Comment by antgonza** [comment]
K - thanks, assigning to you.
