### ISSUE TITLE
QIIME config using /tmp

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1133]
The QIIME config on qiita.ucsd.edu is using /tmp as the temp directory. The mount that /tmp resides on has only 50GB. Is this okay, or should we set up a different mount for QIIME's temp directory? Currently, about 4GB are used.

**Comment by wasade** [comment]
:+1:. This will impact worker nodes more than the webserver, and their
local disk is 40GB.

**Comment by adamrp** [comment]
As per our meeting today, the tmp directory will be moved to its own mount at `/projects/qiita_data/tmp`

**Comment by antgonza** [comment]
The qiime config has been updated and now:
temp_dir:      /projects/qiita_data/tmp/

This change was done via the .qiime_config file in qiita home
