### ISSUE TITLE
Brand new environment cannot access studies

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1134]
If I starta  brand new environment with the following command:

```bash
qiita_env make --load-ontologies --download-reference --add-demo-user
```

And then create a studyk, I cannot view it i.e. I cannot go to http://localhost:21174/study/description/10000 as I get the following traceback:

```python
Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/.virtualenvs/alpha-0.1-rc2/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/Users/yoshikivazquezbaeza/.virtualenvs/alpha-0.1-rc2/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/yoshikivazquezbaeza/.virtualenvs/alpha-0.1-rc2/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/yoshikivazquezbaeza/.virtualenvs/alpha-0.1-rc2/lib/python2.7/site-packages/qiita_pet/handlers/analysis_handlers.py", line 227, in get
    info = Analysis(self.current_user.default_analysis).summary_data()
  File "/Users/yoshikivazquezbaeza/.virtualenvs/alpha-0.1-rc2/lib/python2.7/site-packages/qiita_db/user.py", line 349, in default_analysis
    return conn_handler.execute_fetchone(sql, [self._id])[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

@squirrelo, can you have a look?

**Comment by ElDeveloper** [comment]
Correction, this is happening in different places not only when viewing a study, however viewing a study is still not possible.

**Comment by ElDeveloper** [comment]
@josenavas, if you can also have a look that would be awesome.

**Comment by squirrelo** [comment]
You don't seem to have a default analysis attached to the user. Did you run all the patches?

**Comment by ElDeveloper** [comment]
Yes qiita_env make should run all the patches. But I've also tried
running qiita_env patch and the problem persists.

**Comment by ElDeveloper** [comment]
I executed the following insert on the psql shell:

```sql
insert into qiita.analysis (email, name, description, dflt, analysis_status_id) VALUES ('demo@microbio.me', 'demo@microbio.me-dflt', 'dflt', 't', 1);
```

However I still can't see my study.

**Comment by squirrelo** [comment]
Traced to the default analysis not being created by the environment scripts. The above SQL needs to be run [here](https://github.com/biocore/qiita/blob/master/qiita_db/environment_manager.py#L234) after the demo user is added.

**Comment by adamrp** [comment]
isn't there also a patch that creates the default analyses for each user? and won't that patch fail if we add code to create the default analyses in to the environment manager?

**Comment by squirrelo** [comment]
The patches are run before the addition of the demo user, so we need to manually add the default analysis. At least that's my understanding of the problem.

**Comment by adamrp** [comment]
ah, correct you are! I believe @squirrelo's suggestion will work

**Comment by ElDeveloper** [comment]
Can someone submit a PR to my branch at #1135, I'm AFK ATM.

Yoshiki Vázquez-Baeza

**Comment by squirrelo** [comment]
Doing now

**Comment by squirrelo** [comment]
You already added this: https://github.com/biocore/qiita/pull/1135/files#diff-694f6ed1529987bc3435746a74426405R234

**Comment by ElDeveloper** [comment]
Oh, well, that does not solve the problem with the study page not rendering.

**Comment by ElDeveloper** [comment]
Can someone reproduce this problem? i.e. not being able to access a study after running:

```bash
qiita_env make --load-ontologies --download-reference --add-demo-user
```
