### ISSUE TITLE
Clean up instantiation of connection objects

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1136]
Once #1131 is merged, we should go through and clean up instances in the codebase of:

```python
conn_handler = SQLConnectionHandler() if conn_handler is None else conn_handler
```

And the variants. Either the `conn_handler` should be passed in, or a new object created. Since the database connections are not reopened on instantiation (unless necessary), the overhead of just doing `SQLConnectionHandler()` will be minor

cc @antgonza, who originally recommended opening this

**Comment by josenavas** [comment]
There might be cases in which that's not possible, but worth doublechecking.

**Comment by ElDeveloper** [comment]
Is this a bug or an enhancement?

**Comment by wasade** [comment]
Style/refactor

**Comment by ElDeveloper** [comment]
Got it, thanks!

**Comment by antgonza** [comment]
I have already started working on this.

**Comment by antgonza** [comment]
Closed by https://github.com/biocore/qiita/pull/1140
