### ISSUE TITLE
Move artifact creation/move away form the handlers

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1145]
No processing should be done in the handlers. Instead, we should create functions that returns the parameters for rendering the interface. This will allow to add tests for those lines.

**Comment by ElDeveloper** [comment]
:+1:

**Comment by wasade** [comment]
:+1:

**Comment by antgonza** [comment]
@josenavas can we close this?

**Comment by josenavas** [comment]
No, there is still a lot of work happening on the handlers. This come up in a recent discussion with @squirrelo regarding his new refactor, but I couldn't find the issue then. Even if with the new refactor the work is reduced, there is still a lot of other handlers that will not be modified and need to be refactored to reduce the amount of work.

**Comment by antgonza** [comment]
@josenavas, has this been solved?

**Comment by josenavas** [comment]
Not fully - I think there are still places where the work can be reduced.

**Comment by antgonza** [comment]
OK, can you list them so we know how close are we? Thanks!

**Comment by antgonza** [comment]
At this point, I think the only processing still happening on handlers is the artifact creation/move. Changing the name.

**Comment by antgonza** [comment]
This was solved some time ago, closing.
