### ISSUE TITLE
Multiple sample templates attached to a study

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1148]
From my understanding, we should only have one sample template attached at any given time, with file backups of the old ones. What's happening now, it seems, is every single one is created as a new sample template.
![screencapture-qiita-ucsd-edu-study-description-1799-1430756906885](https://cloud.githubusercontent.com/assets/3079066/7457295/42d620a8-f240-11e4-9b4d-3bffad538b23.png)

**Comment by josenavas** [comment]
Nope, we said that we are going to store all of them and we are just going to change the interface: https://github.com/biocore/qiita/issues/1082

Please, search for issues before opening a new one.
