### ISSUE TITLE
Improve error message when using a restricted column name

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1149]
If the user uses a restricted column name (e.g. `group`) the error is the entire SQL and it is hard to know exactly what is going on.

**Comment by ackermag** [comment]
Can we make a list of restricted column names for Wiki?


On Mon, May 4, 2015 at 12:08 PM, josenavas <notifications@github.com> wrote:

> If the user uses a restricted column name (e.g. group) the error is the
> entire SQL and it is hard to know exactly what is going on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1149>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
Making a list of restricted column names is going to be a bit hard, since we cannot use any of the words controlled by the SQL vocabulary. I think the best path forward would be to scape those columns (i.e. quote them) so they can be inserted in the DB.
This will also help on allowing case sensitivity in the column names (right now everything is lowercased...)

**Comment by josenavas** [comment]
Another think to take into account here is that column names cannot start with a number, it has to be a letter or quoted. I think we should start moving towards quoting the column names, but probably useful to get the input of the entire group...

**Comment by ElDeveloper** [comment]
I believe quoting will make our user's life easier, would this
complicate any of the existing code?

**Comment by ackermag** [comment]
Will it make it harder in Excel? As you know, we need the text wizard for
all files like this where column names are quoted, or will this be outside
of the template processing?

On Wed, May 6, 2015 at 9:54 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> I believe quoting will make our user's life easier, would this
> complicate any of the existing code?
>
> On (May-06-15|19:04), josenavas wrote:
> > Another think to take into account here is that column names cannot
> start with a number, it has to be a letter or quoted. I think we should
> start moving towards quoting the column names, but probably useful to get
> the input of the entire group...
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/biocore/qiita/issues/1149#issuecomment-99680065
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1149#issuecomment-99717840>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
@ackermag this will not impact the way you generate the templates, quoting is internally to the code, when we are generating the SQL command, not in the templates. Thanks for getting involved through, so we can avoid confusions :smile:

**Comment by josenavas** [comment]
@squirrelo I see that you're assigned into this. This means that you have to mess a lot with the metadata template code. Are you comfortable doing that? Note that this is getting bigger and is not only improving the error message, is actually changing the entire code-base so we support upper/lower casing and all that stuff... Also, I think this has to be moved to alpha 0.3 at least.

**Comment by squirrelo** [comment]
I'm cool with it, especially if it's moved to alpha 0.3

**Comment by antgonza** [comment]
This has been solved in recent changes, like: [get_pgsql_reserved_words](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template/util.py#L389)
