### ISSUE TITLE
POTU_ files are being generated in qiita user home directory

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1153]

**Comment by josenavas** [comment]
I think this is a change that we will need to do in the cluster_jobs file. I think it is using the '-k' parameter to submit jobs. If we remove that parameter, those files should be created whatever the job is submitted. The other option is to modify the cluster jobs to redirect those files to a working directory.

**Comment by wasade** [comment]
You can specify the directory with "-o <foo> -e <foo>". The current working
directory likely already is $HOME. Putting these under a general working
directory will result in a very large number of files quickly, and for them
to be the most useful for debugging, it would be best if they were analysis
and/or study specific

**Comment by antgonza** [comment]
Now they are gonna live in /projects/qiita_data/tmp/
