### ISSUE TITLE
"Modify" button appears on sharing column for public studies

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1154]
This button should not be there if the study is public. Currently, if I try to change the sharing settings on a public study that I do not own, no changes are made to the database, no feedback is given to me as a user, and an error is logged (e.g., `ERROR: HTTP 403: Forbidden (User adam.robbinspianka@colorado.edu does not own study 1030`)

Also, IMHO, the only person that should be able share non-public (i.e., sandboxed, awaiting approval, or private) studies is the sole owner of the study.

**Comment by josenavas** [comment]
@adamrp :+1: on removing the "Modify" button. However, I would say that anybody with access to the study should be able to share it further.

**Comment by adamrp** [comment]
Maybe. I'll add the "group discussion" tag to this issue, and that'll solve the issue, right?? :sweat_smile:

I think the truly ideal solution here would be to have a more detailed permission system similar to UNIX-style `user/group/other` and `read/write` (probably don't need `execute`) combinations, recognizing that such an enhancement would require significant work, both DB and code modifications.

**Comment by squirrelo** [comment]
I think we can safely remove sharing for public studies right now, and just not show anything there. We can discuss the detailed permissions as well, but thats a good quick solution.

**Comment by antgonza** [comment]
Closing as this is not an issue anymore.
