### ISSUE TITLE
show sample template summary and show prep template summary both reference sample and prep

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1156]
Should be either sample or prep

**Comment by antgonza** [comment]
@ackermag could you give an example? I'm not sure what you are referring to.

**Comment by ackermag** [comment]
I think what I was referring to has been fixed.  Download of prep on GUI
shows only prep info (without duplicated columns except sample_name) and
download of sample_template shows only sample info).  My confusion is that
the mapping file has "prep" in the name, not distinguishable from
prep_template by casual observation.  Could we use "map" or "MF" in the
name for the mapping file instead of "prep"?


On Mon, Oct 12, 2015 at 6:08 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> @ackermag <https://github.com/ackermag> could you give an example? I'm
> not sure what you are referring to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1156#issuecomment-147394261>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
This already has been solved.
