### ISSUE TITLE
default analysis is created before user's email address is verified

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1157]
I feel like the default analysis should only be created if the user status is 4 (and not 5)

**Comment by squirrelo** [comment]
:+1:, and not that hard to implement. Should also mean less clutter in the analysis table.

**Comment by adamrp** [comment]
Really, it's not that the status has to be 4, but just not 5.

**Comment by squirrelo** [comment]
Yeah, I can move the creation to the email verification function instead of create.

**Comment by josenavas** [comment]
:+1: to do it on validation.

**Comment by josenavas** [comment]
just wondering, which DB changes are required in here?

**Comment by squirrelo** [comment]
None

**Comment by josenavas** [comment]
Ok, thanks @squirrelo just removed the label.

**Comment by squirrelo** [comment]
Fixed as part of #1266
