### ISSUE TITLE
Allow users to specify their own EBI credentials

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1160]
So that users can submit with alternative credentials instead of the Knight lab set.

**Comment by antgonza** [comment]
@wasade each deploy can have their own EBI credentials for submission, will this suffice or do you mean that the user should be able to supply their own credentials through the GUI, the system should validate them and then submit?

**Comment by wasade** [comment]
Latter

**Comment by antgonza** [comment]
Thanks for the clarification. Is this a nice to have or did a user requested for this? I'm just not sure how useful will this be compared to the user uploading directly ...

**Comment by wasade** [comment]
Right now, our submissions say that the submitting center is "Colorado Center for Microbial Ecology, University of Colorado at Boulder" (at least as of [AG round 17](http://www.ebi.ac.uk/ena/data/view/ERP010416)). That is an issue in and of itself that is separate from this issue. The greater context though is that a user may want to have their data associated with them, not with UCSD, or CU. At this time, a user using `http://qiita.microbio.me` will implicitly have their data associated to us, and _we_ own the accessions not the submitter.

I don't know what you mean by "user uploading directly", do you mean having the user go the EBI and manually upload files processed by qiita? Or do you mean requiring that a user do a custom deploy of qiita in order to specify credentials?

**Comment by antgonza** [comment]
CCME, UCB: Agree we should change the credentials to microbio.me or something like that ... 

direct upload: I was thinking in the former but either should work. IMOO having your own credentials is something advanced ...

**Comment by wasade** [comment]
Can you even manually do that via EBI? Do we provide the files that allow them to do that? If you can do it, then yes, one solution is to provide the files they need to do the upload manually however we then loose the knowledge of what the subsequent produced accession is. 

Note: the present system means that any user who submits via `qiita.microbio.me`, who subsequently discovers a problem with the data (as is quite common given the version history seen with NCBI accessions), will need to contact us and ask us to login to EBI and do whatever tinkering is necessary. The users cannot get access to the accessions to modify them as they are owned by our account, and we obviously cannot distribute those credentials.

**Comment by antgonza** [comment]
K, adding group discussion label so we can discuss next meeting.

**Comment by rob-knight** [comment]
SRA has concept of study center, sequencing center, analysis center. We
should let users choose the other two if not sequenced here but remember
choices are supposed to be from predefined list. And it's an advanced
feature.

On Aug 13, 2015, at 12:10 PM, Antonio Gonzalez <notifications@github.com>
wrote:

CCME, UCB: Agree we should change the credentials to microbio.me or
something like that ...

direct upload: I was thinking in the former but either should work. IMOO
having your own credentials is something advanced ...

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1160#issuecomment-130744727>.

**Comment by rob-knight** [comment]
Needs input from EBI - I only investigated this with NCBI, and that was in
2009...

On Aug 13, 2015, at 12:15 PM, Daniel McDonald <notifications@github.com>
wrote:

Can you even manually do that via EBI? Do we provide the files that allow
them to do that? If you can do it, then yes, one solution is to provide the
files they need to do the upload manually however we then loose the
knowledge of what the subsequent produced accession is.

Note: the present system means that any user who submits via
qiita.microbio.me, who subsequently discovers a problem with the data (as
is quite common given the version history seen with NCBI accessions), will
need to contact us and ask us to login to EBI and do whatever tinkering is
necessary. The users cannot get access to the accessions to modify them as
they are owned by our account, and we obviously cannot distribute those
credentials.

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1160#issuecomment-130746587>.

**Comment by josenavas** [comment]
I just realized that the configuration file defines:
```
# The name of the sequencing center to use when doing EBI submissions
EBI_CENTER_NAME = CCME-COLORADO
```

Which means that all submissions will be done with that value. That column is a prep template column for EBI submission (see [here](http://qiita.microbio.me/static/doc/html/tutorials/prepare-templates.html#id2)). I think we should fix this in the upcoming EBI refactor...

**Comment by antgonza** [comment]
Group resolution: We help the users do the submission by reviewing their data so we should keep using our credentials, if they want to use theirs, they can submit their own data. Closing.
