### ISSUE TITLE
error in column should be "int4" blank cell not working

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1173]
so when an integer/float value appears in the pandas DataFrame, we insert a NULL in the database. If this needs to go in now, the only solution will be to put a -1, for example, since this value will not make sense on that column

**Comment by josenavas** [comment]
This is as a result of pandas type inference. The good solution will be to check the values at insertion time. This will make the insertion slower, but this is a price that we need to pay.

**Comment by antgonza** [comment]
@josenavas Is this still happening?

**Comment by josenavas** [comment]
I don't think so
