### ISSUE TITLE
common error list and suggested verbal comment for fix suggestions

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1174]
Create a list of errors in processing and how to fix.  Also suggest wording for clarification of error.  Please assign to me

**Comment by josenavas** [comment]
Thanks @ackermag 

Ideally we should be improving the error messages. However, it is really hard to catch all them. It will be great if you can compite that list, so we can go later over it and try to figure out a way to catch all possible errors and present a useful error to the user.

**Comment by antgonza** [comment]
@ackermag do you think this is still needed?

**Comment by ackermag** [comment]
@antgonza - I think we have addressed all the problematic/uninformative messages.  I can report individual errors as they come up/if they come up

**Comment by antgonza** [comment]
Great, thanks! Closing and please open a new issue when you find those.
