### ISSUE TITLE
Something wrong with user verification emails or links

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1184]
We're getting a lot of these:
```
ERROR:
HTTP 400: Bad Request (Missing argument email)
TRACE:
Traceback (most recent call last):

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
callback()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
self._when_complete(method(*self.path_args, **self.path_kwargs),

File "/home/qiita/qiita_main/qiita_pet/handlers/auth_handlers.py", line 65, in get
email = self.get_argument("email").strip().lower()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 354, in get_argument
raise MissingArgumentError(name)

MissingArgumentError: HTTP 400: Bad Request (Missing argument email)
```
The URI being accessed is
```
uri: /auth/verify/caLdGqNVcOqZT29eSLZg
```
It is indeed missing the `email` argument. However, when I look at the users in the DB whose verification codes match the ones specified in these kinds of errors, they are all verified. So it looks like it is successfully verifying them even without the email argument?

**Comment by antgonza** [comment]
Just tested this by creating a new user and then trying to validate it with out the email parameter. This was unsuccessful (400 error), then I added the param and used a wrong email and failed again (wrong code error); at the same time I was checking the DB so I was sure that the verification wasn't happening. Finally, I used the correct values and the verification was successful both in the GUI and the DB.

I think what you are looking at is that you can use any uri (for example /auth/verify/my-error) and will error out, which I think is fine.
