### ISSUE TITLE
Search Qiita for specific taxa

### ISSUE THREAD

**Issue by anneestes** [biocore/qiita#1187]
Dear Qiita developers,

I would like to be able to search across the sequences deposited to Qiita for a specific bacterial taxa. Ideally, I'd like to be able to select the different taxonomic level to search - down to the strain level if present. Also I cannot find a list of categories that might be able to be used to search the different studies deposited.

Is such a search possible with the Qiita repository?

Thanks for building this fabulous tool and database!

Anne Estes
Post-doctoral Fellow
Institute for Genome Sciences

**Comment by squirrelo** [comment]
While that search ability is planned, we currently do not have it implemented. Currently you can only search metadata and study information. A list of available categories (which is in the process of being cleaned up) is available by clicking the `Available Metadata`  link above the search bar.

**Comment by antgonza** [comment]
this has been superseded by the redbiom interface and is gonna be available in the next release.
