### ISSUE TITLE
prep_template with only sample_name fails

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1195]
If you try to add a prep template with only sample_name (minimal information needed for a prep template) the add fails with:

```
QiitaDBExecutionError: 
Error running SQL query in queue CREATE_PREP_TEMPLATE_296: CREATE TABLE qiita.prep_368 (sample_id varchar NOT NULL, , CONSTRAINT fk_prep_368 FOREIGN KEY (sample_id) REFERENCES qiita.study_sample (sample_id) ON UPDATE CASCADE)
ARGS: None
Error: syntax error at or near ","
LINE 1: ...TABLE qiita.prep_368 (sample_id varchar NOT NULL, , CONSTRAI...
```

The current solution is to add a prep_template with 2 columns.

**Comment by josenavas** [comment]
Good catch! Which should be the solution here? Check if the user doesn't have any extra column and raise an error, or just add a dummy column so the system doesn't fail?

**Comment by antgonza** [comment]
This is only valid when we upload a biom table (the scenario when the user doesn't need any other info) so ideally if the user select to use a biom it can skip this step ... Additionally, we will need to have a nicer error about 2+ columns.

**Comment by josenavas** [comment]
After taking a quick look to the system, the user doesn't need to upload a prep template if he wants to just upload a biom table.

**Comment by antgonza** [comment]
Fixed here: https://github.com/biocore/qiita/issues/1195
