### ISSUE TITLE
ebi submission fails if sample exists in sample template but not in prep template

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1196]
If the sample template has extra samples than the prep template you want to submit the code fails without reporting any errors to the GUI.

**Comment by josenavas** [comment]
Do you have an exact traceback for this? I added the code that filters the sample template to only submit the samples that are present in the prep template, so I'm really confused that this is failing.

**Comment by antgonza** [comment]
Nop.

**Comment by antgonza** [comment]
Fixed in #1451
