### ISSUE TITLE
Multiple mapping files are available for a single prep

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1209]
See study 958's raw data tab. There are multiple buttons for downloading "QIIME mapping file", but it seems like there should only be one.

![image](https://cloud.githubusercontent.com/assets/2574407/7816369/2ad488f8-038b-11e5-91b2-aa0aacc2c361.png)

I think:
1. When a new sample template is processed, all existing QIIME mapping files for that study should be regenerated
2. When a new prep template is processed, any existing mapping files that were generated from that prep template need to be regenerated.

**Comment by josenavas** [comment]
Assigning to me as it should be resolved with the current PR that I'm working on.

**Comment by josenavas** [comment]
This has been already fixed
