### ISSUE TITLE
Processing parameters availability on search page

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1210]
Right now, to view the full details of processing parameters, one has to go to the analysis page, and then you can see the parameters in this modal:

![image](https://cloud.githubusercontent.com/assets/2574407/7816691/1278a828-038d-11e5-8525-7cf71f87dc2a.png)

But on the search page, you can only see these details:

![image](https://cloud.githubusercontent.com/assets/2574407/7816683/01b4ba5e-038d-11e5-999a-ce99aba614f8.png)

Users at a recent workshop would have preferred to see the processing parameters on the search page, so that they knew beforehand that they were selecting processed data that had been created with compatible/consistent parameters.

**Comment by josenavas** [comment]
As an idea: we can use the same modal as a UI module on both pages.

**Comment by antgonza** [comment]
This issues is already resolved, see:
![screen shot 2017-01-26 at 4 45 51 am](https://cloud.githubusercontent.com/assets/2014559/22330216/60370e84-e382-11e6-92be-c639dc7cbd89.png)
