### ISSUE TITLE
Show pre-processing parameters information

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1229]
Currently, the interface is not showing the parameters used for pre-process a raw data. This information should be included in the PreProcessed data tab. The information is already available in the DB using the `preprocessed_params_table` and `preprocessed_params_id` from the `PreprocessedData` table.

**Comment by antgonza** [comment]
I think https://github.com/biocore/qiita/issues/1985 is basically the same issue than this, @josenavas could you close this one if that's the case and if not could you explain the differences?

**Comment by josenavas** [comment]
Ok to close - this was referring to the old interface so now it has been (or going to be) fixed in the other issue
