### ISSUE TITLE
Adding a pipeline for processing already demultiplexed files

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1230]
Using the QIIME's command `multiple_split_libraries_fastq.py`

**Comment by antgonza** [comment]
Well, as always, it's not that easy. First of all, there could be different cases:
* (1) Multiple files with primers still in the sequences.
  * (1.1) From the same run (same direction) forward and reverse primers of same length.
  * (1.2) From the same run (same direction) forward and reverse primers of different lengths.
  * (1.3) From multiple runs (possible multiple directions) forward and reverse primers of same length.
  * (1.4) From multiple runs (possible multiple directions) forward and reverse primers of  multiple lengths.
* (2) Multiple files without primers.

I think we should only support (2) and perhaps (1.1). For 2 we will need to only run multiple_split_libraries_fastq.py and for (1.1) we are going to need to run extract_barcodes.py with the length of the primer as barcode (thanks @walterst), discard the resulting barcode file (primers), and then run multiple_split_libraries_fastq.py

What do people think?

**Comment by josenavas** [comment]
Agree on taking baby steps on these. We should start supporting 2. Once this is in, we should add 1.1. In terms of supporting the other ones, I think it will depend on users request. Note that I think it should be easy to know the primer length for each sample if we are using the run_prefix and the primer column from the prep template for each sample.

Does this make sense?

**Comment by antgonza** [comment]
I think I can try adding 2 and 1.1 on the same PR, if everyone agrees. Let's see how difficult will it be ... 

Anyway, using the run_prefix and the primer will not give enough information (for example, direction)

**Comment by antgonza** [comment]
After a few emails we decided that implementing 2 and having documentation on how to do case 1 was enough, thus closing. Closed by https://github.com/biocore/qiita/pull/1258

**Comment by josenavas** [comment]
Can you add an issue with the case 1 pipeline and assign it to beta? We might want to implement it in the future, so we don't loose track of it.

**Comment by antgonza** [comment]
I personally believe that we should add the issue if we see a need for that use case, if not we will have open issues for things we will not do.

**Comment by rob-knight** [comment]
I think adding the pipeline for already-demultiplexed files will help a lot of people who are using basespace and/or commercial facilities, and who we want to support…

**Comment by antgonza** [comment]
@rob-knight Preprocessing already-demultiplexed files was merged yesterday and was deployed on the main site this early morning. The discussion is that the current pipeline expects "clean" (no barcodes and no primers) sequences and we are wondering if we should add another one that accepts files with primers. Note that currently we have documentation (also already deployed) to help users remove their primers from the per sample files.

**Comment by rob-knight** [comment]
Sorry. OK, I don’t know of a specific use case for that.
