### ISSUE TITLE
Add publication table

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1231]
* Adding a centralize table to store all publications. Useful to provide
      the user a list of citations when his analysis is done, to store the
      publication of a study and the citations for the tools.

**Comment by josenavas** [comment]
@antgonza 
What do you think about this table having as required TITLE, DOI and FIRST AUTHOR. Then as optional PMID.

**Comment by antgonza** [comment]
:+1: (should the first author be registered in the system?)

**Comment by josenavas** [comment]
I don't think so. I would suggest that the first author should be a free text attribute. We don't want to implement a publication database, so although there might be some issues we this implementation, the main reason of this table to exist is to have an external pointer to a well defined publication database (DOI number).

**Comment by squirrelo** [comment]
It should just have DOI and PMID stored, no author info, and look paper info up as it's requested using the pubmed or DOI restful interfaces. That way we don't have to worry about inconsistencies popping up between whats in our DB and what the actual paper is.

**Comment by antgonza** [comment]
@josenavas can we close this?

**Comment by josenavas** [comment]
Yup! There are still some other parts of the system in which the publication table can be used, but it has been already created, so it's just a matter of adding links.
