### ISSUE TITLE
Error in admin error display page:

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1234]
Error:
![screen shot 2015-06-04 at 6 58 49 am](https://cloud.githubusercontent.com/assets/2014559/7986621/d17092b8-0a95-11e5-8f31-19c4ec537c75.png)

**Comment by josenavas** [comment]
Does this happens in your machine or only in qiita.microbio.me?

**Comment by antgonza** [comment]
qiita.microbio.me. Note that the diversity of errors in the main site is wider than in mine.

**Comment by josenavas** [comment]
Sorry, I think I worded the question really bad. I wanted to asked if you are able to reproduce the error locally or if you can only see it in the live system.

**Comment by antgonza** [comment]
Haven't really tried to generate it in my local computer ...

**Comment by wasade** [comment]
Is there already an issue for this? I flagged it a few weeks back but can't
recall if it was during a meeting or what. @squirrelo, iirc, you said you
knew what the fix was?

**Comment by squirrelo** [comment]
I thought I did fix it, but apparently not. This is a different error with datatables. I'll take a look.

**Comment by josenavas** [comment]
Thanks @squirrelo assigned to you

**Comment by squirrelo** [comment]
This has been fixed
