### ISSUE TITLE
Ensure unique IDs for metaanalysis

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1236]
If a study has 2 process data from 2 different prep templates and the prep templates have the same sample name (which they should) the analysis will merge the 2 biom into one. The correct functionality should be to keep them apart.

**Comment by josenavas** [comment]
I think this requires some kind of thought... If that is the correct behavior, how do we rename samples in a way that we can actually do the analysis?

I might be misunderstanding something, but I think that in some case it can be useful to do that merge. For those cases, do you think it will be useful to add a flag in the interface so the user can activate the merging of the samples?

**Comment by antgonza** [comment]
Not sure we will need to merge ... in theory it's possible but not sure in which cases we will actually want to do

**Comment by josenavas** [comment]
That's why I propose a flag, so in case that there is a use case that we are missing, the user can still do it...

**Comment by antgonza** [comment]
The problem was that #1237 is hiding the actual error with this one, which is that the biom table is not being created due to this [check](https://github.com/biocore/qiita/blob/master/qiita_db/analysis.py#L801). Not sure what's the best solution but one that comes to mind is: add a new column on the fly to the mapping file and prepend to the sample name the process data id, except if the user checks an option where samples with the same name will be merged into a single sample ...

**Comment by antgonza** [comment]
Is [this](https://github.com/biocore/qiita/issues/164) related to this issue?

**Comment by josenavas** [comment]
Not really, the issue discussed here is if 2 samples have the same name. The other issue is talking about the reference files (i.e. the reference tree) being hardcoded for GreenGenes.
