### ISSUE TITLE
analysis.dropped_samples should always return same type

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1237]
Not sure if related to #1236 but if you select those 2 bioms and select to do beta the system errors out cause the analysis has no biom tables associated. 

Note that analysis.dropped_samples returns None if there are no biom files associated vs. returning []. Which causes a 500 error [here](https://github.com/biocore/qiita/blob/master/qiita_pet/handlers/analysis_handlers.py#L146)

**Comment by josenavas** [comment]
I'm not fully understanding this error. Is the problem that since there are no dropped samples, the beta diversity job fails? If so, it might be enough to just change the return type of analysis.dropped_samples to be always a list?

**Comment by antgonza** [comment]
I have no idea why is failing in one scenario (beta only) but in other is not (beta + other analyses). The None issue was something that I saw while trying to traceback why it was failing. Anyway, while discussing with @squirrelo we decided to add so we can keep track of it.

**Comment by josenavas** [comment]
Oh, I get the issue now... weird...

**Comment by antgonza** [comment]
Renamed this issue as having analysis.dropped_samples return None vs [] is hiding the actual problem with https://github.com/biocore/qiita/issues/1236.
