### ISSUE TITLE
Inconsistency in help info for barcode header in prep template 

### ISSUE THREAD

**Issue by jessicalmetcalf** [biocore/qiita#1239]
It is unclear from the help page info whether to use "barcode" or "barcodesequence" as the column header name in a prep template. https://github.com/biocore/qiita/wiki/Preparing-Qiita-template-files lists "barcode" but the downloadable prep template example has a column header called "barcodesequence." The correct header is "barcode", please update the downloadable example template.

**Comment by antgonza** [comment]
Thanks for catching this discrepancy.

**Comment by josenavas** [comment]
Thanks @jessicalmetcalf it looks like the example files are old.
