### ISSUE TITLE
Change 'edit study page' to include PMID/PMCID/doi

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1248]
Not just pmid
All or one?

**Comment by josenavas** [comment]
I would suggest DOI to be required. We can add the others as optional.

**Comment by antgonza** [comment]
Just to be sure, required for what?

**Comment by josenavas** [comment]
Early in the morning, my writing skills are still sleeping.

What I mean is that when we introduce a new publication, I would suggest that the user should introduce first DOI over PMID or PMCID. The reason is that any kind of publication (AFAIK) will have a DOI, where PMID is not ensured to exist.

Does that make sense?

**Comment by antgonza** [comment]
Think so. Will this mean that we should move the PMID from the study to its own table with multiple entries?

**Comment by josenavas** [comment]
Yes, on the last meeting I suggested creating a new "publication" table (issue https://github.com/biocore/qiita/issues/1231). The details of that table are still not clear. But we should discuss these details on that issue.

**Comment by ackermag** [comment]
For now I am putting in pmid if available *and* doi or pmcid for studies
processed from the old db

On Sun, Jun 7, 2015 at 7:47 AM, josenavas <notifications@github.com> wrote:

> Yes, on the last meeting I suggested creating a new "publication" table
> (issue #1231 <https://github.com/biocore/qiita/issues/1231>). The details
> of that table are still not clear. But we should discuss these details on
> that issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1248#issuecomment-109762655>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
@josenavas can we close this?

**Comment by josenavas** [comment]
The issue exposed here has been fixed.

However, I think the way the information is introduced should be changed. IMO, we should have a better way to enter the 2-tuples that represent each publication (DOI, pubmed), since right now, the interface only supports introducing the DOI information.
