### ISSUE TITLE
--no-build-docs is not honored

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1259]
``` bash
(python27)09:49:28 scripts@more_moi$ ./qiita pet webserver start --no-build-docs
Building documentation ...
Error: Could not build documentation: Failed to execute: make -C /Users/mcdonadt/ResearchWork/software/qiita/qiita_pet/support_files/doc/ html
stdout: sphinx-build -b html -d build/doctrees  -W source build/html
Running Sphinx v1.2.3
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [html]: targets for 7 source files that are out of date
updating environment: 7 added, 0 changed, 0 removed
reading sources... [ 14%] faq
reading sources... [ 28%] index
reading sources... [ 42%] tutorials/account-creation
reading sources... [ 57%] tutorials/analyze-data
reading sources... [ 71%] tutorials/getting-started
reading sources... [ 85%] tutorials/index
reading sources... [100%] tutorials/prepare-templates

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents...
stderr:
Theme error:
unsupported theme option 'navbar_pagenav_name' given
make: *** [html] Error
```

**Comment by josenavas** [comment]
@ElDeveloper any clue?

**Comment by ElDeveloper** [comment]
Odd, it seems like this is because the `--no-build-docs` is not being processed as part of `qiita pet`, when I try the following, it works:

```
(qiita)yoshikivazquezbaeza:qiita@issue-1259$ qiita pet webserver --no-build-docs start
Qiita started on port 21174
```

Notice the only difference is the flag is coming before "start" ...

**Comment by wasade** [comment]
that works, but is unexpected...

**Comment by josenavas** [comment]
Uhm... Taken into account that `--no-build-docs` is a parameter for `qiita pet webserver` it is not that surprising...

**Comment by wasade** [comment]
It is as the command is not intuitive

**Comment by wasade** [comment]
@antgonza, I'm seeing a JS error but I've got no idea of how the situation may arise. It's unable to get the [`state_node`](https://github.com/biocore/mustached-octo-ironman/blob/master/moi/support_files/moi_list.js#L41). I don't see how that's resulting in it not redirecting, but that's at least something that's off

**Comment by wasade** [comment]
@josenavas, to be most specific, the reason that command structure is non-intuitive as when the `webserver` subcommand is expanded, this form will not make sense:

```bash
qiita pet webserver --no-build-docs stop
```

In other words, `--no-build-docs` is specific to `start`

**Comment by josenavas** [comment]
In that case the situation of the parameter is not correct. If you take a look to the code, the parameter `--no-build-docs` is a parameter for the command `webserver` not to `start`. If we want it to be in `start` we should move it there.

We should probably have the command `qiita pet webserver build_docs`...

**Comment by antgonza** [comment]
This is already fixed:
```
qiita pet webserver --build-docs
/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/IPython/parallel/client/client.py:446: RuntimeWarning: 
            Controller appears to be listening on localhost, but not on this machine.
            If this is true, you should specify Client(...,sshserver='you@192.168.1.3')
            or instruct your controller to listen on an external IP.
  RuntimeWarning)
/Users/antoniog/svn_programs/qiita/qiita_core/configuration_manager.py:230: UserWarning: Random cookie secret generated.
  warnings.warn("Random cookie secret generated.")
Building documentation ...
Documentation successfully built
```
