### ISSUE TITLE
CSS problems in qiita.microbio.me

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1261]
The header looks a bit off:

![screen shot 2015-06-15 at 9 09 30 am](https://cloud.githubusercontent.com/assets/375307/8164493/469be37a-133e-11e5-91b5-a5fc51155564.png)

**Comment by adamrp** [comment]
What URL are you looking at? I'm not seeing the Documentation up on
qiita.microbio.me, but maybe I'm missing it?

**Comment by ElDeveloper** [comment]
The URL I'm looking at is this:
http://qiita.microbio.me/static/doc/html/index.html

**Comment by adamrp** [comment]
Thanks -- I agree it looks off. Is this supposed to be linked from the main page somewhere, or are we waiting until it looks right before creating that link?

**Comment by ElDeveloper** [comment]
It is linked, see More Info > Help :goat:.

**Comment by adamrp** [comment]
:sweat_smile: heh... I knew that....

**Comment by josenavas** [comment]
@ElDeveloper I have the same issue locally (it looks like I didn't catch it earlier), so I don't think the problem is specific for qiita.microbio.me

**Comment by ElDeveloper** [comment]
Can you post the output of `pip freeze`?

**Comment by josenavas** [comment]
Sure
```
$ pip freeze
You are using pip version 6.1.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
alabaster==0.7.4
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
bcrypt==1.1.1
certifi==2015.4.28
cffi==0.9.2
click==4.0
Cython==0.22
decorator==3.4.2
docutils==0.12
flake8==2.4.0
future==0.13.1
gnureadline==6.3.3
h5py==2.5.0
hiredis==0.2.0
ipython==2.4.1
Jinja2==2.7.3
MarkupSafe==0.23
matplotlib==1.4.3
mccabe==0.3
mock==1.0.1
natsort==4.0.0
networkx==1.9.1
nose==1.3.6
numpy==1.9.2
pandas==0.16.1
pep8==1.5.7
psycopg2==2.6
pycparser==2.12
pyflakes==0.8.1
Pygments==2.0.2
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2015.4
pyzmq==14.6.0
qiime-default-reference==0.1.2
redis==2.10.3
scikit-bio==0.2.3
scipy==0.15.1
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-bootstrap-theme==0.4.6
sphinx-rtd-theme==0.1.8
toredis==0.1.2
tornado==4.1
WTForms==2.0.2
```

**Comment by ElDeveloper** [comment]
Excellent, thanks a lot @josenavas, it seems like the problem is the
version of `sphinx-bootstrap-theme`. 0.4.6 seems to have that bug but
0.4.5 doesn't. Just opened an issue on their tracker: https://github.com/ryan-roemer/sphinx-bootstrap-theme/issues/133

**Comment by josenavas** [comment]
Thanks for checking this @ElDeveloper

**Comment by ElDeveloper** [comment]
Not a problem, for the time being I would suggest doing `pip install
sphinx-bootstrap-theme==0.4.5`, I don't want to set this version in
setup.py I rather fix it when the developers respond with a resolution.

**Comment by josenavas** [comment]
Agree, hopefully they're responsive!
