### ISSUE TITLE
Drop storage of # of samples promised/delivered

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1263]
Currently we are storing in the study table the numbers of samples promised and the number of samples delivered.

The new structure should be:
1. Store in the study table the number of samples initially discussed. Not required and nullable.
2. Look at the sample template to know the number of samples delivered
3. Look at the prep templates to know the number of samples in which sequence data is available
4. Look at the demux HDF5 file to get the number of samples that successfully preprocess.
5. Look at the biom file to get the number of samples that successfully processed.

We should first get 1, 2 and 3; and try to get 4 and 5 later. Note that 3, 4 and 5 are not just a simple counter as a single sample can appear in multiple prep templates, so we should be careful in not counting the same sample multiple times.

**Comment by adswafford** [comment]
@josenavas Can you clarify what this issue is? Is it related to the redbiom GUI display issue for the number of samples?

**Comment by josenavas** [comment]
No, this is a couple of columns that we have in the study table but that we never used. I think we should drop those two columns from the study table and forget about them. What do others think?

**Comment by rob-knight** [comment]
It was intended for EMP studies but seldom used so can be dropped.

On Oct 3, 2017, at 7:27 PM, Jose Navas <notifications@github.com<mailto:notifications@github.com>> wrote:


No, this is a couple of columns that we have in the study table but that we never used. I think we should drop those two columns from the study table and forget about them. What do others think?
