### ISSUE TITLE
Pandas' read_csv can infer datatypes

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1265]
We were incorrectly assuming that data types were not being inferred when we used `converters=defaultdict(lambda: str)` (see [here](https://github.com/biocore/qiita/blob/91c5528e61178580c7c9c339381cee20355f8505/qiita_ware/processing_pipeline.py#L48-51) and [here](https://github.com/biocore/qiita/blob/1d864aaf4766e288adcd7d7b80d36ab20a4f597f/qiita_db/analysis.py#L807-810)), however this is not true. The risk here is that we may have instances where important columns like `#SampleID` can be inferred as integers/floats and would not match any of the information that we have stored in the database.

After talking with @josenavas, the solution might be to write a formatter (analogous to `load_template_to_dataframe`) that takes the data from the database and not from disk. See also #449

**Comment by adamrp** [comment]
I want to reiterate an opinion I've expressed before: bugs surrounding the use of pandas to load metadata templates into dataframes have been fairly common. I don't think we need pandas for metadata.

**Comment by josenavas** [comment]
Managing templates with pandas simplifies a lot of code. I disagree on stop using a powerful library just because we don't how to use it, and instead creating our own code that can have similar or worse code.

**Comment by wasade** [comment]
Sure, but we're primarily just using read_csv, right? It's like having a
Porsche that you only drive to the grocery store at the end of the block.

**Comment by antgonza** [comment]
Nothing to do with this discussion, but that sounds nice ... :smile:

**Comment by ElDeveloper** [comment]
Then how else do you use your Porsche?

**Comment by wasade** [comment]
I don't think I'd have one for long as I could see it being taken by the
cops from driving really really fast to the grocery store... at the end of
the block...

**Comment by josenavas** [comment]
Nice about the Porsche :-)

However, one of the main things that we are taking advantage of it is the type inference itself, when we are loading the template for first time. We just want to limit the type inference in a few columns, but we want it in all the other ones.

Another use is when splitting the mapping file by run prefix for processing.

And I'm pretty sure that it is used in other places.

Also, AFAIK it has been also discussed to use pandas as an underlying representation for metadata in QIIME 2, so better to already have our code to support it...

**Comment by antgonza** [comment]
This was solved here: https://github.com/biocore/qiita/pull/1865. Now everything is string ...
