### ISSUE TITLE
sort errors in preprocessing

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1267]
Currently if there are not the same number of mapping files and raw data (for example: MMF vs sff), it will tell you that they are not the same but if there are a log of them, there is no easy way to find them. Suggest only showing those that are different.

**Comment by josenavas** [comment]
Note that the code is not checking for name matching, the run prefix it is only assuming that the sorting of the files if the same.

**Comment by antgonza** [comment]
I don't think this is an issue anymore, please reopen otherwise.
