### ISSUE TITLE
CSS lost after unlinking sequences

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1270]
Before linking sequences a nicely Bootstrap-formatted table is shown with the filenames and a selector for the file types, however when you unlink the files, this styling is lost, see this animated gif:

![problem](https://cloud.githubusercontent.com/assets/375307/8221556/f7079146-1514-11e5-88e5-5fa57b0ef391.gif)

Note that I caught this when reviewing #1258, but this is still prevalent in master.

**Comment by josenavas** [comment]
Yeah, just a note, is not that the CSS is lost, is that it is not using a bootstrap table.

**Comment by antgonza** [comment]
Solved on https://github.com/biocore/qiita/pull/1258
