### ISSUE TITLE
qiime_params.txt does not exist in qiita.microbio.me

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1274]
I tried analyzing a metagenomic study and I got the following error message from beta_diversity.py:

```bash
beta_diversity_through_plots.py: error: option --parameter_fp: file does not exist: '/projects/qiita_data/reference/params_qiime.txt'
```

It seems like this file doesn't exist in qiita.microbio.me, and it probably doesn't exist in anyone's environment. These are the lines where this [is happening](https://github.com/biocore/qiita/blob/91c5528e61178580c7c9c339381cee20355f8505/qiita_ware/analysis_pipeline.py#L119-L121)

**Comment by josenavas** [comment]
On of those awesome hardcoded things in the analysis pipeline that was done for a demo...

**Comment by antgonza** [comment]
Agree

**Comment by antgonza** [comment]
Wrong button, sorry. We can add that file and get a better fix ...

**Comment by ElDeveloper** [comment]
I just added a file to microbio.me with the following contents:

```
beta_diversity:metrics  bray_curtis,gower,canberra,pearson,euclidean
```

I'll close this for the time being as the real issue is described in #164
