### ISSUE TITLE
Change the column run_prefix to run_name

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1280]
Currently we are using a column named `run_prefix` to indicate what file(s) contain sequences for a sample, the suggested improvement is to change the name of this column to be `run_name` and make it such that filenames are an exact match and not just the prefix of the filename (like with the FASTQ file per-sample pipeline).

**Comment by josenavas** [comment]
Note that I'm not sure if this will completely work for non per-sample fastq. In multiplexed runs, this will actually be a run prefix, as the forward/reverse reads and barcodes will have a different suffix.

Thus, do we want to have `run_prefix` for multiplexed runs and `run_name` for per-sample fastq? It should fairly easy to do with the metadata template `Restriction` object...

**Comment by ElDeveloper** [comment]
You are right! I think that makes sense, however not sure if this truly
makes things easier for user or more "confusing" :S

**Comment by antgonza** [comment]
Whatever we decide has to stay as this will make things easier on the long run. However, I like the idea of having a single multipurpose column and I do not care on the name.

**Comment by josenavas** [comment]
We can probably still change it to `run_name` and if it's a per-sample-FASTQ we do an exact match of the file name, and if it is a multiplexed file we do a prefix check. Technically, the run name is correct, and what changes are suffixes...

**Comment by antgonza** [comment]
Group resolution: This "kind" of makes sense but the change will cause more issues with users, docs, etc. Closing.
