### ISSUE TITLE
improve documentation - include example inputs

### ISSUE THREAD

**Issue by geoffrosen** [biocore/qiita#1292]
In the documentation, it would be really helpful if more specifics or possibly example files were available. For example, at the end of "Per sample FASTQ files with barcode information" it could say "You now upload your fastq file that has been stripped of barcodes (but still has primers?) along with your barcodes file. Also, be sure that barcodes are included in your mapping file.".

**Comment by geoffrosen** [comment]
Another example of this is for the extract_barcodes.py command in "Per sample FASTQ files with barcode information", which requires barcodes in label. If there are no barcodes in label, perhaps suggest using -c barcode_single_end. Also in "Per sample FASTQ files without barcode but with primer information" it would be nice to have explicit that -c barcode_single_end needs to be used.

**Comment by antgonza** [comment]
I think it will be nice to have and perhaps we can add/solve during #1419

**Comment by antgonza** [comment]
Hi @tkosciol, would you mind checking that this is covered in one of the documentation files? Thanks!

**Comment by tkosciol** [comment]
no, it's not.
relevant site: https://qiita.ucsd.edu/static/doc/html/tutorials/no-raw-sequences.html

**Comment by antgonza** [comment]
We believe this has been solved between the [CMI tutorials](cmi-workshop.readthedocs.io) and [this help](https://qiita.ucsd.edu/static/doc/html/tutorials/getting-started.html#preprocessing-data). However, if you feel we should add more info please open a new issue and let us know how to improve. Thanks!
