### ISSUE TITLE
bulk delete

### ISSUE THREAD

**Issue by geoffrosen** [biocore/qiita#1293]
It would be nice to be able to quickly select many files to delete from the upload screen (maybe this should be called file manager). As it stands now you can delete many files, but it requires a lot of clicking.

**Comment by antgonza** [comment]
Good point. Do you think a simple select all will suffice? Or/and should we allow to select based on which extensions are allowed in the system? For example: fastq,fastq.gz,txt ...

**Comment by geoffrosen** [comment]
I think the second option is better (select by file extension), but either one will be a significant improvement.

**Comment by josenavas** [comment]
Just to throw my 2 cents in here.

Using datatables might be useful, as it will give us the power of sorting the files by multiple parameters.

**Comment by adswafford** [comment]
Highlighting this issue again. Looks like it was last looked at before the Sloan workshop when it was also requested.

**Comment by antgonza** [comment]
Just note that this issue wasn't solved in https://github.com/biocore/qiita/pull/2291
