### ISSUE TITLE
Add comments attribute to the study

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1295]
Being able to add comments to the study can be useful for the user to keep track of different things that the tried about the study.

**Comment by antgonza** [comment]
@josenavas, I know is not the same but perhaps the tags are useful here?

**Comment by josenavas** [comment]
I think the idea of this was to add more verbose comments. I do not recall exactly the examples that we had, but I think it was a free text in which the study owner could add some more background to the study and/or notes on the current status.

**Comment by antgonza** [comment]
closing as this is a subset of https://github.com/biocore/qiita/issues/2234
