### ISSUE TITLE
Make Collections object portal aware

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1297]
We are currently not using the collections object, but when it is implemented in qiita-ware and qiita-pet we should discuss how we want Collections interact with portals. The two proposed methods so far are:

1) Explicitly link Collections to a portal using another collections_portal table
2) Indirectly link collections to a portal by making sure that only analyses from a single portal (excluding QIITA unless an analysis is only in QIITA)

**Comment by josenavas** [comment]
Given that option 2 requires a lot of more checks (i.e. check all the analysis, see to which portal they belong, make sure that all are from the same, etc, etc) I think option 1 is the best one as it minimizes the effort and the likelihood of introducing bugs.

**Comment by antgonza** [comment]
Collection was completely deprecated in the last analysis refactor, thus closing.
