### ISSUE TITLE
gzipped sff files are not supported

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1299]
`process_sff.py` does support gzipped files, but we are computing incorrectly the output file name.

The offending line is this one: https://github.com/biocore/qiita/blob/master/qiita_ware/processing_pipeline.py#L321

The code in QIIME used for compute the output file name is this one:
```python
        sff_fp = join(sff_dir, filename)
        base_filename = splitext(filename)[0]
        if filename.endswith('.gz'):
            base_filename = splitext(base_filename)[0]
        base_output_fp = join(output_dir, base_filename)
```

**Comment by antgonza** [comment]
Note that if we fix this it will be good to also allow the upload of this kind of files, which is not currently possible. The reason we had one of this in the current system is because it was dragged from the old DB.

**Comment by josenavas** [comment]
Good point, that should be a simply change in the configuration file.
