### ISSUE TITLE
Send lists to postgres properly

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1304]
Psycopg2 has a nice feature: it will pass lists as an SQL ARRAY object, but it will pass tuples as a simple list.

For example:
    some_list = [1, 2, 3]
    sql = “DELETE FROM foo WHERE bar IN %s”
    conn_handler.execute(sql, [tuple(some_list)])

The resulting SQL is:
    “DELETE FROM foo WHERE bar IN (1,2,3)”

This is super handy, as we’ve been doing unsafe list comprehensions to get around the list -> ARRAY issue (see [here](https://github.com/biocore/qiita/blob/master/qiita_db/data.py#L1424) as an example). We should replace all these with proper tuple use.

**Comment by wasade** [comment]
That is awesome, good find

**Comment by antgonza** [comment]
@squirrelo the link doesn't exist anymore, could you update it or copy the new code here? Thanks.

**Comment by squirrelo** [comment]
A quick glance seems like the codebase was updated to use this but the issue was never closed. I'll do a more thorough check in a bit to confirm.

**Comment by antgonza** [comment]
Got it, thanks!

**Comment by antgonza** [comment]
Closing as this was already implemented.
