### ISSUE TITLE
Clean up naming in qiita click commands

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1305]
We talked about removing the underscores a while ago, so this is a followup to that. If you pass `name=foo` to a click command decorator, you can rename the call to whatever you want, regardless of the function name.
Example:

``` python
@click.command(name='foo')
...
def bar(thing):
    # does things
```

can be called as `foo --thing 1` despite the function being called bar.

**Comment by antgonza** [comment]
@squirrelo I think this is already done, right? If so, can you close?

**Comment by squirrelo** [comment]
No, this still needs to be done. See for example [here](https://github.com/biocore/qiita/blob/master/scripts/qiita#L118)

**Comment by charles-cowart** [comment]
It appears that Click has been recently updated, breaking functions beginning with the '_' character. Testing fix that replaces '_' character with 'Q' (for Qiita) character.

**Comment by antgonza** [comment]
This was solved when we moved to Python3 and used the latests click ...
