### ISSUE TITLE
Use update_wrapper with Transaction

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1317]
This [line](https://github.com/biocore/qiita/blob/improve-sql-queues/qiita_db/sql_connection.py#L595) should make use of `update_wrapper` which will propagate things like the docstring

**Comment by josenavas** [comment]
I'm using `wraps` on [this](https://github.com/biocore/qiita/blob/improve-sql-queues/qiita_db/sql_connection.py#L588) which should accomplish the same, at least accordingly to their documentation

**Comment by wasade** [comment]
Ah, nice, didn't see that (or know about it)
