### ISSUE TITLE
Make post commit and rollback functions accept arguments

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1325]
Currently, to add functions to the post transaction functions, you need to use partials, e.g.
```python
from functools import partial

func = partial(remove, fp)
TRN.add_post_commit_func(func)
```

This uses partials in a non-standard way - as a full function call instead of a partial function call - and creates less readable code. Instead, the `add_post_commit_func` should accept arguments directly, changing the above code to 

```python
TRN.add_post_commit_func(remove, args={'fp': '/path/to/file'})
```

This is much more explicit, easier to read code that follows standard python conventions, and should therefore be more maintainable.

**Comment by antgonza** [comment]
@squirrelo can this be closed?
