### ISSUE TITLE
Combined queries won't work in search bar

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1339]
For example if I search for `study_title includes bear`, I'll get one study, then if I search `age_in_years > 10` I'll get two studies, however if I put them both together like this `study_title includes bear OR age_in_years > 10` I'll only retrieve the studies that match one of the two queries. See this animated gif for an example:

![search](https://cloud.githubusercontent.com/assets/375307/8560295/f81cde8e-24db-11e5-89a4-d47269103f1c.gif)

**Comment by antgonza** [comment]
This is related to the old search functionality, which has been superseded by redbiom. Closing.
