### ISSUE TITLE
Ugly error on prep template duplicate samples

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1341]
```
An error occurred parsing the prep template: prep_template_CP_SCRIPT.txt
Error running SQL query in queue CREATE_PREP_TEMPLATE_375_142905488: INSERT INTO qiita.prep_template_sample (prep_template_id, sample_id) VALUES (%s, %s)
ARGS: [723L, '375.C1A']
Error: duplicate key value violates unique constraint "idx_common_prep_info"
DETAIL: Key (prep_template_id, sample_id)=(723, 375.C1A) already exists.
```
This should be caught and shown as "Duplicate sample names found!"

**Comment by josenavas** [comment]
We should check for all duplicate sample IDs and show a single error.

**Comment by ackermag** [comment]
This should also report all duplicated samples, not just one


On Wed, Jul 8, 2015 at 9:00 AM, Joshua Shorenstein <notifications@github.com
> wrote:

> """
> An error occurred parsing the prep template: prep_template_CP_SCRIPT.txt
> Error running SQL query in queue CREATE_PREP_TEMPLATE_375_142905488:
> INSERT INTO qiita.prep_template_sample (prep_template_id, sample_id) VALUES
> (%s, %s)
> ARGS: [723L, '375.C1A']
> Error: duplicate key value violates unique constraint
> "idx_common_prep_info"
> DETAIL: Key (prep_template_id, sample_id)=(723, 375.C1A) already exists.
> """
> This should be caught and shown as "Duplicate sample names found!"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1341>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by squirrelo** [comment]
http://stackoverflow.com/a/9836685
Leaving that there for future reference.

**Comment by josenavas** [comment]
We have 'find_duplicates' from skbio @squirrelo

**Comment by squirrelo** [comment]
Oh, that works too
