### ISSUE TITLE
Non UTF8 character error is HUGE

### ISSUE THREAD

**Issue by amnona** [biocore/qiita#1343]
<img width="1433" alt="screen shot 2015-07-08 at 9 42 11 am" src="https://cloud.githubusercontent.com/assets/5832946/8576288/bc3d70b6-2555-11e5-9590-838b1aafae2d.png">

**Comment by josenavas** [comment]
the reason why the message is huge is because that template contains a lot error. 

Probably we can store that information in some place and just add a link to open it in another page? That information is useful because is telling the user where are the problems.

**Comment by ackermag** [comment]
Jose - this error means that every sample has the same problem in one of
the fields which are filled with the same "value" in the entire column -
would it be possible to report that all samples have a problem in the same
column (in this case library_construction_protocol):
Error message:
"Problems with prep_template: library_construction_protocol has the
following disallowed characters"
Just a suggestion
Gail

On Wed, Jul 8, 2015 at 9:48 AM, josenavas <notifications@github.com> wrote:

> the reason why the message is huge is because that template contains a lot
> error.
>
> Probably we can store that information in some place and just add a link
> to open it in another page? That information is useful because is telling
> the user where are the problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1343#issuecomment-119655920>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
yes, I've been talking with @squirrelo and we can write some kind of summary and be  a bit smarter on showing the error. Just a note, even that we can try to be as smart as we can to reduce the length of the error, there are situations in which it still can be huge (i.e. there are actually a lot of different errors). In such cases I think it's ok if the error message is long because it will tell you everything that is wrong, so you don't need to iteratively try it.

**Comment by ackermag** [comment]
One error that is iterative is when sample names are duplicated.  It will
report the first sample that is duplicated, then the third (after
reloading), etc.  I usually look for other duplicates when I get that error
but perhaps that should be fixed.
Gail

On Wed, Jul 8, 2015 at 7:20 PM, josenavas <notifications@github.com> wrote:

> yes, I've been talking with @squirrelo <https://github.com/squirrelo> and
> we can write some kind of summary and be a bit smarter on showing the
> error. Just a note, even that we can try to be as smart as we can to reduce
> the length of the error, there are situations in which it still can be huge
> (i.e. there are actually a lot of different errors). In such cases I think
> it's ok if the error message is long because it will tell you everything
> that is wrong, so you don't need to iteratively try it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1343#issuecomment-119786523>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
Yup, @squirrelo opened another issue for that: https://github.com/biocore/qiita/issues/1341

I'm going to comment this there.
