### ISSUE TITLE
unable to delete prep template because of linked raw data

### ISSUE THREAD

**Issue by amnona** [biocore/qiita#1345]
when trying to delete a prep template (using the X) which has raw data linked to it, the delete is just ignored without any explanation. ideally - it should give a warning and unlink automatically?

Also, even after unlinking files, you still can't delete the prep template. It says it is still linked, but shows no linked files in the tab.

**Comment by josenavas** [comment]
We don't want to remove anything automatically, however I agree that an error is needed.

**Comment by squirrelo** [comment]
Here is a screenshot of the issue:
<img width="1440" alt="screen shot 2015-07-08 at 12 54 43 pm" src="https://cloud.githubusercontent.com/assets/3079066/8580653/a3c71b5c-2570-11e5-9c41-2c5ab2594ad7.png">

**Comment by squirrelo** [comment]
OK, I figured out you need to delete the raw data using that X before you delete prep template, but that is super unintuitive. We need to auto-delete the raw data on prep template deletion, since it is a 1-to-1 relationship.

**Comment by antgonza** [comment]
I think we should remove when trying to delete a prep template and has not linked data or auto delete it when you unlink the files. I _think_ the former will make more sense.

**Comment by squirrelo** [comment]
yeah, autodelete along with the prep template if there are no linked files makes the most sense to me.

**Comment by josenavas** [comment]
After a discussion in today's meeting, we remove the RawData when unlinking all files, there is no point on maintaining an empty RawData.

**Comment by antgonza** [comment]
@josenavas can this be closed?

**Comment by josenavas** [comment]
Nope, this is a limitation imposed by the interface, suggest closing once it has been fixed in @squirrelo's refactor.

**Comment by antgonza** [comment]
This was fixed in the new GUI.
