### ISSUE TITLE
Odd error preprocessing SFF files

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1349]
Status: failed: Job GEN_DEMUX_FILE: Error Job results: ValueError(zero-size array to reduction operation maximum which has no identity) Python output: None Standard output: Standard error: Job INSERT_PREPROCESSED: Error Job results: ImpossibleDependency() Python output: None Standard output: Standard error: 
Your barcodes do not seem to match your prep template info

We need to remove the python error above the clean error

**Comment by josenavas** [comment]
This error showed with the old processing pipeline - this should be cleaner now. Re-open if it is not the case.
