### ISSUE TITLE
Study Building Page UI

### ISSUE THREAD

**Issue by JWDebelius** [biocore/qiita#1350]
I found the study building page UI very non-initutive and difficult to use.

The tabs frustrated me a lot. I would prefer a sidebar or header bar with separate pages that move me through each of the steps. It would help create a more concrete step for each process. I have about 3 notes about how much I hate the tab layout after working with the page for a little over 3 hours.

I think I would have found it easier if each page had one action and only one action. The workflow (as I see it) is as follows:
* Build study --> Static study landing page
* Upload sample template
* Upload prep template
* Link files to prep template
* Demultiplexing and QC (aka Preprocessing)
* Annotation and Alignment (aka Processing)

It would be great if the progress bar could somehow indicate the status of each of these steps. So, if I leave the page and log in, I know that I already have a sample template and prep template that are accepted, but that my data is still preprocessing... or something. A visual queue would help me go to the right page on repeat visits.

I don't think that I could use this on my own, without help documentation. I'm not sure that if I attended a workshop and saw this demo'd that I'd be able to go home and replicate it. And, I'm not sure that even if I accomplished the first two tasks I'd be willing to continue using this system. *That's* how difficult I find the tabs.

**Comment by JWDebelius** [comment]
@cuttlefishh, @RNAer, @amnona may have other feedback.

**Comment by antgonza** [comment]
Closing as the new GUI has been deployed. Please add individual issues for new features. Thanks!
