### ISSUE TITLE
Disable button during processing/preprocessing

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1351]
The button is still there and still active even when the cluster is working. See example picture. This button should be disables/removed when the cluster is working.

<img width="220" alt="screen shot 2015-07-08 at 1 39 11 pm" src="https://cloud.githubusercontent.com/assets/3079066/8581669/16656744-2577-11e5-8d2d-e34a0f362196.png">

**Comment by antgonza** [comment]
Solved in: https://github.com/biocore/qiita/pull/1738
