### ISSUE TITLE
auto update does not always update...

### ISSUE THREAD

**Issue by amnona** [biocore/qiita#1359]
When i did preprocessing/processing for a few studies, qiita showed for a long time the "Waiting on Preprocessing..." page. Maybe because i closed my mac/connected to a different wifi, it does not automatically update.
if i try to reload the page, i get "ERROR: CODE 405!"
then when i press back (on the browser), it showed me "not preprocessed". However, if i went to the "edit" study information and cancel, it now showed as preprocessed...

**Comment by antgonza** [comment]
The specific example has been solved so closing, but if there are other cases where the "auto-update" doesn't work please open independent issues. Thanks!
