### ISSUE TITLE
cannot add user 

### ISSUE THREAD

**Issue by ivanvujkc** [biocore/qiita#1360]
Hi, I can't seem to add myself as a user or to add a PI. I've had to resort to "PLACEHOLDER" for the PI. I also don't see a "My Studies" tab after I log in. Is adding new users/PIs blocked for the time being?

**Comment by josenavas** [comment]
Hi @ivanvujkc 

Are you trying to add yourself as PI or lab person? If so, how are you trying to do it?

**Comment by ivanvujkc** [comment]
I only see an option to add a 'lab person', which does not work when I try
to add me. Could you let me know how to add both?

Thanks!

On Fri, Jul 10, 2015 at 7:29 PM, josenavas <notifications@github.com> wrote:

> Hi @ivanvujkc <https://github.com/ivanvujkc>
>
> Are you trying to add yourself as PI or lab person? If so, how are you
> trying to do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1360#issuecomment-120550146>.
>



-- 
Ivan Vujkovic-Cvijin
ivan.vu.cv@gmail.com

**Comment by josenavas** [comment]
Hi @ivanvujkc 

The option to add a 'lab person' works for both, PI and lab person, probably we can improve the interface to make this more clear.

Which error appears when you try to add yourself as a lab person? You can send a screen snapshot.

**Comment by ivanvujkc** [comment]
Hi Jose, thanks for your responses. I don't get an error message, it just
doesn't add the user after I click "Update Study" from the edit study
section. I see no other buttons that I can press to create the new user
(clicking "add person" again does nothing). I must be missing something
obvious, but I'd love your help!

Best,
Ivan

On Sun, Jul 12, 2015 at 12:57 PM, josenavas <notifications@github.com>
wrote:

> Hi @ivanvujkc <https://github.com/ivanvujkc>
>
> The option to add a 'lab person' works for both, PI and lab person,
> probably we can improve the interface to make this more clear.
>
> Which error appears when you try to add yourself as a lab person? You can
> send a screen snapshot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1360#issuecomment-120740585>.
>



-- 
Ivan Vujkovic-Cvijin
ivan.vu.cv@gmail.com

**Comment by ivanvujkc** [comment]
Whoaaa it just worked! Unfortunately, I don't know why it was not working
(for several days/attempts in the Chrome browser), nor why it did work this
time, though it may have been an issue with Chrome.

Ivan

On Sun, Jul 12, 2015 at 4:12 PM, Ivan Vujkovic-Cvijin <ivan.vu.cv@gmail.com>
wrote:

> Hi Jose, thanks for your responses. I don't get an error message, it just
> doesn't add the user after I click "Update Study" from the edit study
> section. I see no other buttons that I can press to create the new user
> (clicking "add person" again does nothing). I must be missing something
> obvious, but I'd love your help!
>
> Best,
> Ivan
>
> On Sun, Jul 12, 2015 at 12:57 PM, josenavas <notifications@github.com>
> wrote:
>
>> Hi @ivanvujkc <https://github.com/ivanvujkc>
>>
>> The option to add a 'lab person' works for both, PI and lab person,
>> probably we can improve the interface to make this more clear.
>>
>> Which error appears when you try to add yourself as a lab person? You can
>> send a screen snapshot.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/biocore/qiita/issues/1360#issuecomment-120740585>.
>>
>
>
>
> --
> Ivan Vujkovic-Cvijin
> ivan.vu.cv@gmail.com
>



-- 
Ivan Vujkovic-Cvijin
ivan.vu.cv@gmail.com

**Comment by ackermag** [comment]
Glad to hear it worked - I will look into it.


On Sun, Jul 12, 2015 at 1:14 PM, ivanvujkc <notifications@github.com> wrote:

> Whoaaa it just worked! Unfortunately, I don't know why it was not working
> (for several days/attempts in the Chrome browser), nor why it did work this
> time, though it may have been an issue with Chrome.
>
> Ivan
>
> On Sun, Jul 12, 2015 at 4:12 PM, Ivan Vujkovic-Cvijin <
> ivan.vu.cv@gmail.com>
> wrote:
>
> > Hi Jose, thanks for your responses. I don't get an error message, it just
> > doesn't add the user after I click "Update Study" from the edit study
> > section. I see no other buttons that I can press to create the new user
> > (clicking "add person" again does nothing). I must be missing something
> > obvious, but I'd love your help!
> >
> > Best,
> > Ivan
> >
> > On Sun, Jul 12, 2015 at 12:57 PM, josenavas <notifications@github.com>
> > wrote:
> >
> >> Hi @ivanvujkc <https://github.com/ivanvujkc>
> >>
> >> The option to add a 'lab person' works for both, PI and lab person,
> >> probably we can improve the interface to make this more clear.
> >>
> >> Which error appears when you try to add yourself as a lab person? You
> can
> >> send a screen snapshot.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/biocore/qiita/issues/1360#issuecomment-120740585>.
> >>
> >
> >
> >
> > --
> > Ivan Vujkovic-Cvijin
> > ivan.vu.cv@gmail.com
> >
>
>
>
> --
> Ivan Vujkovic-Cvijin
> ivan.vu.cv@gmail.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1360#issuecomment-120759005>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by ElDeveloper** [comment]
I will close this issue for now, please feel free to re-open it if the problem re-appears.
