### ISSUE TITLE
Delete log entries that are bigger than a certain size

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1363]
These got added when we're logging 403 errors. The problem is if there is a problem with resumable, and returns a 403 error, the contents of the file is added to the logging table. This means that we are logging a CHUNK_SIZE (not sure how big is the chunk size) every 10ms...

We also need a way of stopping resumable if there is an error like that.

**Comment by antgonza** [comment]
This is not hurting anything and are fine to keep so closing after discussing with @biocore/qiita-dev.
