### ISSUE TITLE
Need to remove some editing buttons

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1382]
Currently there are still buttons for update sample template and add samples/columns on non-user-owned public studies, as well as update investigation type on the prep templates. This should be removed for integrity sake. Screenshots below:

![screencapture-qiita-ucsd-edu-study-description-2148-1437318336160](https://cloud.githubusercontent.com/assets/3079066/8766459/695321a2-2ded-11e5-8f96-f7a2e750cbab.png)

![screencapture-qiita-ucsd-edu-study-description-2148-1437318292133](https://cloud.githubusercontent.com/assets/3079066/8766460/6b5c00fe-2ded-11e5-804c-0b73a601bef9.png)

**Comment by antgonza** [comment]
Solved in: https://github.com/biocore/qiita/pull/1738
