### ISSUE TITLE
The uploader is not respecting memory

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1384]
Given a recent process kill, the uploader is either:

- storing the chunks being uploaded in memory as opposed to disk
- has a memory leak

Both of those scenarios are unscalable. Fingers point at the uploader as:

- there was at least one active upload going on, and it corresponded to the last log entries from the webserver
- the webserver was "Killed"
- at approximately the time the webserver was killed (no timestamps, but guessing due to time of day), a python process was forcefully killed by the kernel oom-killer

**Comment by antgonza** [comment]
@josenavas have you been able to test this?

**Comment by antgonza** [comment]
This hasn't happened since this was reported, almost a year ago. My guess is that there was a conflict between the ipython controllers being ran in the main node together with the webservers. Now, we are running only the webservers in the main node, the controllers are in the queue. Can we close?

**Comment by antgonza** [comment]
I'm going to close as this hasn't been an issue for a year now. Please reopen if you think otherwise.
