### ISSUE TITLE
Persistent URLs when a user is not logged-in

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1385]
If a puser is not logged-in to the system but has a URL that points to a resource that needs authentication, the URL will be lost upon authentication. Meaning that the user will have to re-copy-paste the URL into the navigation bar.

The solution is to wait for authentication and then redirect the user to the URL that they initially entered.

**Comment by antgonza** [comment]
Closing this as is basically a duplicated of https://github.com/biocore/qiita/issues/2121. OK, #2121 is the duplicated but it has more use cases.
