### ISSUE TITLE
Add ability to filter out taxa as part of an analysis creation

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1387]
The user should be able to select from a predetermined list of common contaminants to filter out and Qiita should be able to remove those from the combined OTU table before any command is executed.

**Comment by antgonza** [comment]
I think this will be a great feature but we need two cases to either keep or remove:
- [] Filter by OTU id
- [] Filter by taxonomy name
Now, I think we can ask the user to add the taxonomy or IDs, or list the ones that are available in their selected studies and they could search/filter based on these. If we agree on the latter (IMOO nicer) it sounds like we should add a checkbox that says that the user wants to filter their biom (this is related to reusing the biom) and then create the selected biom, allow them to filter and then proceed with the analysis. Opinions? Should we discuss during the next meeting?

**Comment by antgonza** [comment]
This is related to: https://github.com/biocore/qiita/issues/2184 and will be great to solve together.

**Comment by antgonza** [comment]
Closing as this is possible via the q2 plugin.
