### ISSUE TITLE
Analysis results page shouldn't use IFrames

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1389]
The analysis results page shouldn't be using IFrames, because the state of each individual visualization is lost after you change from taxonomic summaries to beta diversity or to alpha rarefaction.

**Comment by antgonza** [comment]
What will be the best solution to fix this? Note that right now you can open the visualization in a new page ... kind of related.

**Comment by ElDeveloper** [comment]
IIRC, this stems from a conversation we had one day where someone
modified the visual elements of a PCoA plot (in unweighted UniFrac), and
when they wanted to look at a different metrics, they noticed they had
just lost their changes to the previous plot. This is not limited to
Emperor plots, but with any visualization where you can change the
visuals, you are bound to lose them if you switch between
visualizations.

**Comment by antgonza** [comment]
right, but not sure what will be the other option, do you have any suggestions on how to fix?

**Comment by ElDeveloper** [comment]
I don't know if this is possible, but keeping each visualization as a
div, and then collapsing/uncollapsing those divs would do it.
Alternatively, everytime you click on a visualization, these are added
to some sort of "tab manager" that lets you browse through (something
like Emperor's sidebar).

**Comment by antgonza** [comment]
I think that might work but we will need to see how to implemented with the new pipelines, thanks.

**Comment by antgonza** [comment]
I'm linking this issue with https://github.com/biocore/qiita/issues/1388 as I believe they are overlapping at this point. @ElDeveloper, would you mind closing one or clarifying the difference? Thanks!

**Comment by antgonza** [comment]
The issue here is that we don't have any real alternative but (A) open in a new window (which is an option now) and (B) each tool save it's status and allow to reload, like emperor. Thus closing in Qiita.
