### ISSUE TITLE
Add documentation that describes the processing pipeline

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1399]
Similarly to the diagram from the old system:

![](https://raw.githubusercontent.com/qiime/qiime_web_app/master/www/img/QIIME_DB_processing_protocol.png)

**Comment by antgonza** [comment]
:+1: but I think we should make it dynamic. I mean, that if we change something in the pipelines it automatically refreshes the diagram. We could discuss during the next qiita meeting.

**Comment by ElDeveloper** [comment]
Oh that sounds nifty!! Yes, we should do that!

Yoshiki.

**Comment by antgonza** [comment]
@josenavas how easy/difficult is to have this with the new plugin system ?

**Comment by josenavas** [comment]
I think this should be done by the plugins.
Small changes need to be done to support this, but I think it will be possible once the plugins are extended to include the recommended pipeline and or the steps involved during the processing (working on it this week).

**Comment by antgonza** [comment]
I think this document covers this issue: https://qiita.ucsd.edu/static/doc/html/processing-recommendations.html, please close if you agree. Obviously, we need to keep updated as we add new features/plugins.

**Comment by antgonza** [comment]
Closing, please re-open/add-a-new-issue with specific details if this needs to be reopened.
