### ISSUE TITLE
download mapping file and biom tables associated with an analysis

### ISSUE THREAD

**Issue by clozupone** [biocore/qiita#1401]
It would be nice for the user to have the ability to download the mapping file and the biom tables associated with an analysis.

**Comment by rob-knight** [comment]
Isn’t this possible already? If not, it should be high priority…

**Comment by clozupone** [comment]
There was a closed issue saying it was now possible but looks like functionality got lost at some point.

Sent from my iPhone

On Aug 4, 2015, at 8:49 AM, "Rob Knight" <notifications@github.com<mailto:notifications@github.com>> wrote:

Isn't this possible already? If not, it should be high priority...

> On Aug 3, 2015, at 3:15 PM, clozupone <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> It would be nice for the user to have the ability to download the mapping file and the biom tables associated with an analysis.
>
> -
> Reply to this email directly or view it on GitHub <https://github.com/biocore/qiita/issues/1401>.
>


-

**Comment by ackermag** [comment]
This is possible now and I have responded directly to Cathy and pointed to
the documentation.
Gail

On Tue, Aug 4, 2015 at 7:54 AM, clozupone <notifications@github.com> wrote:

> There was a closed issue saying it was now possible but looks like
> functionality got lost at some point.
>
> Sent from my iPhone
>
> On Aug 4, 2015, at 8:49 AM, "Rob Knight" <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> Isn't this possible already? If not, it should be high priority...
>
> > On Aug 3, 2015, at 3:15 PM, clozupone <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> >
> > It would be nice for the user to have the ability to download the
> mapping file and the biom tables associated with an analysis.
> >
> > -
> > Reply to this email directly or view it on GitHub <
> https://github.com/biocore/qiita/issues/1401>.
> >
>
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/biocore/qiita/issues/1401#issuecomment-127639336>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1401#issuecomment-127640706>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
Just to clarify, this is a real issue and I'm going to start working on it.

I plan to create two links in the main analysis list where you can download the map and the biom files. Does this sound fine?

**Comment by clozupone** [comment]
Sounds great. Thanks Antonio!

On Aug 6, 2015, at 10:54 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Just to clarify, this is a real issue and I'm going to start working on it.

I plan to create two links in the main analysis list where you can download the map and the biom files. Does this sound fine?

**Comment by rob-knight** [comment]
Yes, how did this functionality get lost and can we make sure regression
tests ensure that similar loss of important functionality doesn't happen in
future?

On Aug 6, 2015, at 12:54 PM, Antonio Gonzalez <notifications@github.com>
wrote:

Just to clarify, this is a real issue and I'm going to start working on it.

I plan to create two links in the main analysis list where you can download
the map and the biom files. Does this sound fine?

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1401#issuecomment-128440405>.

**Comment by antgonza** [comment]
After chatting with @adamrp we realized that the original issue was closed when the internal functionality was created and it has never been possible via the GUI.

**Comment by rob-knight** [comment]
Ok so I guess that suggests a different set of problems and solutions...

On Aug 6, 2015, at 2:40 PM, Antonio Gonzalez <notifications@github.com>
wrote:

After chatting with @adamrp <https://github.com/adamrp> we realized that
the original issue was closed when the internal functionality was created
and it has never been possible via the GUI.

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1401#issuecomment-128470153>.
