### ISSUE TITLE
Option to select all when there are lots of per sample files

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1404]
Is it possible to make the system ignore seq files in list that are not required?

**Comment by josenavas** [comment]
Agree on adding a select all, but the user will still need to remove specific files (should be lower in number, otherwise why they've been uploaded?). In addition, the file list should be sorted by file name.

**Comment by josenavas** [comment]
And in addition, I will suggest that we might be able to use data tables, so the user can search by a given file name in order to unselect it.

**Comment by antgonza** [comment]
This has been superseded by https://github.com/biocore/qiita/issues/1837, so closing.
