### ISSUE TITLE
fix to not getting email for confirmation

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1413]
As @josenavas mentioned, most of the emails we are getting in the qiita.help account is about not getting the account confirmation email. From what I can see is that the reports normally come from academic emails; my guess is: more stringent filters. I think a solution will be to ask users to add the email address to their contact list before registering.

**Comment by josenavas** [comment]
Agree, there isn't much that we can do here, just adding a message on the sign-up page.

One thing is that most of those academic email systems don't even put the message in the spam folder, they just get completely filtered before getting to the user. I'm not sure if adding the email address to their contact list before registering will suffice.

Another option will be to get a "ucsd" and configure Qiita to use the SMTP server from the university, rather than the one in the linux distribution...

**Comment by antgonza** [comment]
Perhaps the UCSD or the qiita.help account will be good options too.

**Comment by josenavas** [comment]
I think the qiita.help can work. I think we also have the configuration for setting up the SMTP using google commented out in the configuration file, so that would be easy to test...

**Comment by wasade** [comment]
CU had an open relay for registered systems on campus, and UCSD may as well
which would just solve the problem. It may be good to verify that the DNS
entry for qiita.microbio.me is properly describing it as an MX record. It
isn't necessary, but I could totally understand why mail servers would just
blindly filter out mail coming from a host w/o an MX record (if that's
actually the case).

**Comment by antgonza** [comment]
Currently we are using donotreply@qiita.mirobio.me to send emails, if we change to qiita.help@gmail.com and use google we are set and will not need to rely on the UCSD system. What do you think?

**Comment by josenavas** [comment]
:+1:

**Comment by antgonza** [comment]
We continue getting reports about this. Note that @josenavas and I tried to configure Gmail in the system  unsuccessfully. Currently, checking if we can do something with UCSD.

**Comment by antgonza** [comment]
It seems like we finally solved all issues. At this point if a user doesn't get an email is because their email server has some restrictions, like not accepting emails from .me servers (remember that they are sent from @qiita.micriobio.me), which I think we can live with. Closing for now.
