### ISSUE TITLE
Add error page with detailed UTF-8 error message

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1414]
When there is an UTF-8 error loading templates, it will be useful to provide a link in the error to a page with detailed UTF-8 errors. Ideally, we want to provide a comprehensive list of errors and potentially marking the characters that is not UTF-8 like SQL does with incorrect syntax.

**Comment by squirrelo** [comment]
Would be good to have all the errors shown on this page in more detail, e.g. all the duplicate barcodes, duplicate everything. Basically have a longer detailed info for allpossible error messages.

**Comment by antgonza** [comment]
@josenavas, I think this is solved in the latests version, right? Could you confirm?

**Comment by antgonza** [comment]
This has been solved.
