### ISSUE TITLE
Set up doctests

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1415]
In order to set up the doctests, we just need to first check if the database is a test database and then drop and rebuild the test database.

However, if the first check fails, we should stop the execution of the doctest. This can be accomplished with the [FAIL_FAST](https://docs.python.org/3/library/doctest.html#doctest.FAIL_FAST) flag. The main problem is that this flag is not available until python 3.4, so until our code is python 3.4 compatible we can't execute doctests that modify the database.

**Comment by antgonza** [comment]
Closing after discussing with @josenavas. 

One of the "features" in the testing framework in Qiita is that we automatically reset the database on those tests that change the DB and this will not be possible with/within the doctests. Additionally, this [issue](https://github.com/biocore/qiita/issues/77) is to remove all these cases, which should be fixed once we merge this [PR](https://github.com/biocore/qiita/pull/2469).
