### ISSUE TITLE
Change CLI parameters in qiita maintenance sysmessage

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1421]
Currently we are providing a `--time` parameter, in seconds, and the developer needs to compute how many seconds are needed for the deadline.

Ideally we want to provide the time in a standard format, for example: `MM/DD/YYYY-HH:MM:SS` and put that time as the deadline.

**Comment by antgonza** [comment]
After using this feature since it's creation I think changing this to hours vs. seconds will make the most sense. I normally set it up for 1-2 hours or 1-2 days. Thus, hours should suffice.
