### ISSUE TITLE
Instantiating with string value works

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1423]
Currently we can instantiate objects with strings of integers or straight integers and, because of how psycopg2 works, we can still use the objects either way. However, some internal functions require it to be an integer for processing. We need to add a check to make sure the passed id is actually an integer, and not a string.

**Comment by adamrp** [comment]
@squirrelo this is regarding the instantiation of ORM objects, correct (i.e., classes that extend `QiitaObject` or `QiitaStatusObject`)?

**Comment by josenavas** [comment]
Yes
