### ISSUE TITLE
refactor update

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1428]
updating a template is taking a really long time and it seems that it can be improved by:
1. removing a full comparison of the mapping file: just compare the columns that are being updated
2. doing bulk vs. single updates 
3. any other?

**Comment by ackermag** [comment]
Combine update and add? Make possible delete rows samples.

**Comment by josenavas** [comment]
Delete rows is trickier, as it can affect any (pre)processed data and analysis that has been generated from the given sample/prep template.

**Comment by josenavas** [comment]
@antgonza I was thinking on doing some profiling as I also noticed that is extremely slow and I'm unsure what is exactly the bottleneck of the process.

**Comment by antgonza** [comment]
@ackermag I think we can join update/add but deleting samples might be complicated as @josenavas points out. However, I think removing columns should be easy.

@josenavas that sounds great, it will be good if we can have it done by today's meeting so we can discuss

**Comment by josenavas** [comment]
@antgonza columns can potentially affect some analysis too though...

**Comment by antgonza** [comment]
Yup and the reason we have https://github.com/biocore/qiita/issues/1129

**Comment by antgonza** [comment]
@josenavas can we close?
