### ISSUE TITLE
provide .tre information for download when conduct analysis in Qiita

### ISSUE THREAD

**Issue by guanhuac** [biocore/qiita#1441]
Is it possible in the future to have .tre for download as well? Now more and more methods use the tree information to enhance the power for the OTU analysis, so .biom may not be enough.

**Comment by antgonza** [comment]
Good point. However, we are planning to keep doing close reference picking (as this facilitates combining different datasets) and pushing in improving GG (but this is a different conversation). Anyway, the tree is the 97% GG 13_8.

**Comment by antgonza** [comment]
We have added this info in the documentation.
