### ISSUE TITLE
demux enforces split libs output - do we want this?

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1442]
I'm writing some tests for the new ebi submission and realized that [these lines](https://github.com/biocore/qiita/blob/master/qiita_ware/demux.py#L362) enforce that the fasta passed is a split libraries output. Not sure if we really want this ...

**Comment by adamrp** [comment]
What is the alternative format for demultiplexed data that we deal with? I suppose we could *also* support per-sample files if we need to in the future, but currently demux is really only used on split libraries output, right?

**Comment by antgonza** [comment]
One use case is submitting to EBI sequences from other data types that has't been demultiplexed.

**Comment by josenavas** [comment]
@antgonza The lines that you pointed out are from the `demux` file format so it only applies to demultiplexed data. Other data types will not be represented with that file format. Is like saying that FASTQ should be used for representing contingency tables...

How are other datatypes represented for submission? Agreed that the EBI code should be general, but the section of the code that you pointed shouldn't be modified as it is _not_ part of EBI.

**Comment by antgonza** [comment]
I can see saving other types of data as hdf5 (demux?) format. Note that this is currently a requirement for ebi submission ... let's discuss this afternoon.

**Comment by wasade** [comment]
demux was defined by the output of split libraries. the barcode information
can be abstracted out, but we need to provide a mechanism for retrieving it
somehow (fasta/fastq comments are far from ideal but they are pragmatic).
Note, it isn't the fasta but the fastq that it is consuming.

On Wed, Aug 26, 2015 at 10:44 AM, Antonio Gonzalez <notifications@github.com

**Comment by josenavas** [comment]
@antgonza I think there is some confusion. HDF5 is a binary file format (general). `demux` is a representation of FASTQ data in HDF5, so it can't be used to represent any general information.

However, we can define other HDF5 formats for representing other datatypes.

**Comment by wasade** [comment]
minor addition to @josenavas's comment, demux can represent FASTA as well,
the qual entries are just nulled

**Comment by antgonza** [comment]
Thanks for the comments. I can see the confusion of names: demux, hdf5, dereplicated. Trying to be more clear: I think we can change the demux to make it de-replicated per sample, this should allow us to also store shotgun. It sounds like with some minimal changes this will be possible. Perhaps the best thing about this is that we will be able to search for exact seqs matches in those files. What do you think?

**Comment by wasade** [comment]
I don't think anything right now prevents the format from representing
shotgun, right?

Regarding searching for sequences, the ddl is oriented for sample lookup,
not sequence. Sequence search is O(N) where N is the number of sequences,
unless you know what sample it is in, in which case you restrict the space
but its still linear. We could represent a smarter data structure on disk
but we didn't explore that at the time of development as the OTU map is
that data structure and provides O(1) search.

**Comment by antgonza** [comment]
I think requiring `orig_bc`, `new_bc` and `bc_diffs` does prevent it, right?

**Comment by wasade** [comment]
Shotgun samples can be multiplexed using barcodes -- is there a different
effective way to multiplex them?

**Comment by antgonza** [comment]
Got it! :disappointed: The issue is that we are not generating this file at demux but generating it so we are not passing the seqs for the forward and the barcodes. The real solution will be to generate this file at dereplication or demuxing.

**Comment by wasade** [comment]
Totally agree, but I do not think it is worth developer effort modifying
split libraries for this
