### ISSUE TITLE
Preprocessed data confusing documentation

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1443]
The documentation for Preprocessed data says that data_type and prep_template are [optional](https://github.com/biocore/qiita/blob/master/qiita_db/data.py#L700) but the code verifies that neither of those are None ... should fix the documentation or remove those validations.

**Comment by josenavas** [comment]
We should fix the documentation. Under the numpy doc standard, both of these parameters are optional. However, one of them must be provided. It probably should go under the "Notes" or in the description of the parameter, to read something like:
`required if FOO is not provided`.

**Comment by antgonza** [comment]
This issue has been superseded by the code and it doesn't apply any more. Closing.
