### ISSUE TITLE
Would be nice if study summary table displayed info matching info in the metadata file

### ISSUE THREAD

**Issue by clozupone** [biocore/qiita#1445]
We had some confusion when searching the study table by title due to the fact that it is searching against the title in the metadata file, and this does not match the title in the study summary table itself. If would be nice if this information was in sync.

**Comment by antgonza** [comment]
Thanks for the feedback and agree. Note that you can search by the study summary name using the search box on the right of the window

<img width="1330" alt="screen shot 2015-08-26 at 11 06 45 am" src="https://cloud.githubusercontent.com/assets/2014559/9500438/b986c8dc-4be2-11e5-9a05-be5d9543a49b.png">

**Comment by clozupone** [comment]
Cool - thanks! I wasn't understanding that but now I see.

On Aug 26, 2015, at 11:08 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Thanks for the feedback and agree. Note that you can search by the study summary name using the search box on the right of the window

[screen shot 2015-08-26 at 11 06 45 am]<https://cloud.githubusercontent.com/assets/2014559/9500438/b986c8dc-4be2-11e5-9a05-be5d9543a49b.png>

**Comment by antgonza** [comment]
this has been superseded by the redbiom interface.
