### ISSUE TITLE
Accept FastUnifrac-like files

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1449]
After discussing with @rob-knight, we think it is better to adapt Qiita to accept the FastUnifrac files and make the analysis available through Qiita, rather than to setup the FastUnifrac site again.

I will work on this during this week as the current FastUnifrac site is down and we want to make this available to users again fairly soon.

**Comment by rob-knight** [comment]
Note that this will not require standards-compliant metadata so it will provide an easy path for users to get files they already have into the sandbox, from where we can encourage them to get the metadata standards-compliant to combine with other resources.

**Comment by antgonza** [comment]
That will be cool. Just to confirm, you will need to upload your general mapping file (not validated), a tree and distance matrix, right?

**Comment by rob-knight** [comment]
Ideally we would also want to provide support for going from sequences, but yes, giving people a lightweight way to go from the files you mention would be great.

**Comment by josenavas** [comment]
Correct. At least I would like to have a replica of the FastUnifrac analysis/output in Qiita, so users don't have the feeling that they lost functionality. We can then extend functionality as required.

**Comment by rob-knight** [comment]
Sounds ideal; thanks!

**Comment by antgonza** [comment]
On the Qiita meeting of 09/17/16, it was decided that we will **not** add FastUnifrac to Qiita but rather make it available through the Galaxy main site. Thus, closing this issue in Qiita.
