### ISSUE TITLE
We should store the metadata as string instead of doing type inference...

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1458]
There are multiple reasons for this, and I'll bring up the discussion on the next meeting. Some arguments:
 - Column types are dynamic. Currently, the column types are set up the first time that they appear and they never change again. However, there are columns that can transition in types, e.g. from int to float.
 - We already had a lot of problem due to the type inference.
 - If the vocab outlined in this issue https://github.com/biocore/qiita/issues/1013 needs to be implemented, everything needs to be a string.
 - The only reason why we want type inference is for the search engine. We look around and there're ways of doing the type casting on the fly for numeric comparisons that _in theory_ are not going to impact the search performance.

I know that I was one of the first advocates for the type inference, but given the last point in the above list, I don't think the type inference is buying us anything, while it is hurting us quite a bit...

**Comment by antgonza** [comment]
Fixed here https://github.com/biocore/qiita/pull/1865
