### ISSUE TITLE
Sharing raw files at raw data level was not the best idea

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1459]
Sharing RawData objects between prep templates is not the best approach. It should be done at the file level. I just come across a study in which I have to duplicate files because new data came in:
- I have per sample FASTQ's. I did a first analysis on such data. Now, more samples are added to the study, so I want to create a new prep template so I can keep the old analysis. However, I need to duplicate the files in the RawData because I can't add new files to an existing RawData.
- Adding files to the existing RawData is not the best solution either, as this new files has nothing to do with the previous prep template so I shouldn't add them there. Another example where this is not acceptable, is if the RawData is from a different study.

**Comment by antgonza** [comment]
I think the way to go with this is to be able to modify a raw data (add more data). Obviously, this will require to do a few tests (have the data been shared, is it preprocessed, etc)

**Comment by josenavas** [comment]
I don't think that will be correct, since you'll be modifying the same raw data that another study is using and it is correct for it, and the processing can break if there are more files than it should.

We can discuss this more in a meeting.

**Comment by antgonza** [comment]
@josenavas, can we close this?

**Comment by josenavas** [comment]
No - I think the correct solution is modifying the behavior of the "import" artifact functionality. We can discuss this in the next meeting.

**Comment by antgonza** [comment]
@josenavas could you update this issue with what we need to do or close it? Thanks
