### ISSUE TITLE
Should update/extend be allowed in templates submitted to EBI?

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1461]
My first guess was not, they shouldn't.
However, with the refactor and being able to potentially update the data in EBI, I can see an argument to allowing these updates/extensions to happen.

**Comment by antgonza** [comment]
IMOO Yes but not fields that are for preprocessing.

**Comment by antgonza** [comment]
I think this is currently allowed for admins only, which I think is the best way to go about, at least currently. Can we close?

**Comment by antgonza** [comment]
Resolution: leave as is.
