### ISSUE TITLE
Error on attempting to preprocess data leads to multiple preprocessed files

### ISSUE THREAD

**Issue by borax** [biocore/qiita#1473]
Upon attempting to process data for study 10297 I got this opaque error: 

*failed: u'0b0d0464-272e-4b76-adde-5f4c4536ce59': (<type 'exceptions.KeyError'>, KeyError(u'0b0d0464-272e-4b76-adde-5f4c4536ce59',), <traceback object at 0x17934fc8>)*

I got very similar messages while trying to preprocess data for study 10299. I messed with the parameters and files and tried again several times getting the same error. A few hours later I checked back and had several prepocessed files, even though I got a failure message each time I tried. I deleted the extras and tried to process the data and got this:

*Status: failed: u'a3a5b08e-86ad-4aeb-a73d-3b7766fefba6': (<type 'exceptions.KeyError'>, KeyError(u'a3a5b08e-86ad-4aeb-a73d-3b7766fefba6',), <traceback object at 0x4f70878>)<br/>*

I don't want to try to process it again in case it's just going to create multiple jobs again, but I don't know if it'll work either. 

Also, as an aside, are you folks still monitoring qiita.help@gmail.com? It's the place your documentation sends me, but I don't know if that's the best way to ask questions.

Thanks,

Zac

**Comment by antgonza** [comment]
Thanks for the report, we are already investigating and yes we are still monitoring that account.

**Comment by antgonza** [comment]
The system has been restarted and you shouldn't get that error ...
