### ISSUE TITLE
recover from ipython workers loosing heartbeat 

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1474]
Sometime, and we do not know exactly why, the ipython workers loose their heartbeat and ipython restarts them. 

Discussing with @josenavas we think the issue is that we only retrieve the objects of the workers at start up so if they die and restart we are submitting to dead jobs.

**Comment by wasade** [comment]
Possible to open an issue with ipython-dev?

**Comment by antgonza** [comment]
We realized that this could be a problem when opening the ipython workers to a queue as it has never happened in a local machine/installation. During the last system update we moved the workers to the local machine. Thus, I'm closing this issue. Please reopen if it happens again.
