### ISSUE TITLE
Add INSTRUMENT_MODEL as a constraint for EBI submission

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1483]
@antgonza from your recent email it looks like this column is required, so we should update the documentation and the constants for EBI so the system checks for this column.

**Comment by antgonza** [comment]
I think the best solution is to add the proper values based on the pre-processing pipeline. We currently support 2 values: Illumina and 454. From list here: ftp://ftp.sra.ebi.ac.uk/meta/xsd/sra_1_5/SRA.common.xsd. What do you think?

**Comment by josenavas** [comment]
That is confusing, I thought that such information was in the PLATFORM column.
Do you know which is the difference between those 2?

**Comment by antgonza** [comment]
You need both values. [See](https://github.com/biocore/qiita/blob/master/qiita_ware/ebi.py#L526) how we add platform and then hardcode the INSTRUMENT_MODEL. However, we should be adding, if LS454 = type454Model. I guess the idea of hardcoding it is that if we add platform you can "guess" the instrument model.

**Comment by josenavas** [comment]
Makes sense - we should probably grab EBI nomenclature and just create a dictionary that given the PLATFORM we set up the instrument_model if it is not provided in the prep template (if a user provides it - we just provide such information).
Sounds good?

**Comment by antgonza** [comment]
That's the dream ...

**Comment by ackermag** [comment]
I will send list

**Comment by antgonza** [comment]
@ackermag Thanks but I think this is it:
LS454 = com:type454Model (*)
ILLUMINA = com:typeIlluminaModel (*)
HELICOS = com:typeHelicosModel
ABI_SOLID = com:typeAbiSolidModel
COMPLETE_GENOMICS = com:typeCGModel
OXFORD_NANOPORE = com:typeOxfordNanoporeModel
PACBIO_SMRT = com:typePacBioModel
ION_TORRENT = com:typeIontorrentModel
CAPILLARY = com:typeCapillaryModel

(*) We support -- Note that 'UNKNOWN' is supported by Qiita but not is not in EBI's list, what about deleting it?

**Comment by ackermag** [comment]
That is the list of PLATFORMS not instrument models which is as follows:

Controlled vocabulary for LS454 INSTRUMENT_MODEL:

   454 GS

   454 GS 20454 GS FLX

   454 GS FLX+

   454 GS FLX Titanium

   454 GS Junior

   unspecified







<!-- Controlled vocabulary for OXFORD_NANOPORE INSTRUMENT_MODEL:

   MinION

   GridION

   unspecified

On Thu, Oct 1, 2015 at 9:58 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> @ackermag <https://github.com/ackermag> Thanks but I think this is it:
> LS454 = com:type454Model (
> *) ILLUMINA = com:typeIlluminaModel (*)
> HELICOS = com:typeHelicosModel
> ABI_SOLID = com:typeAbiSolidModel
> COMPLETE_GENOMICS = com:typeCGModel
> OXFORD_NANOPORE = com:typeOxfordNanoporeModel
> PACBIO_SMRT = com:typePacBioModel
> ION_TORRENT = com:typeIontorrentModel
> CAPILLARY = com:typeCapillaryModel
>
> (*) We support -- Note that 'UNKNOWN' is supported by Qiita but not is not
> in EBI's list, what about deleting it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1483#issuecomment-144786295>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by ackermag** [comment]
I am also concerned about this platform:
LS454 (for Roche 454 sequencing - we currently specify platform as FLX or
Titanium to process.  Then when I send to EBI I manually change to LS454 or
the submission fails.
DO we need to implement a code change


On Thu, Oct 1, 2015 at 10:20 AM, Gail Ackermann <gail.ackermann50@gmail.com>
wrote:

> That is the list of PLATFORMS not instrument models which is as follows:
>
> Controlled vocabulary for LS454 INSTRUMENT_MODEL:
>
>    454 GS
>
>    454 GS 20454 GS FLX
>
>    454 GS FLX+
>
>    454 GS FLX Titanium
>
>    454 GS Junior
>
>    unspecified
>
> 
>
> 
>
> 
>
> <!-- Controlled vocabulary for OXFORD_NANOPORE INSTRUMENT_MODEL:
>
>    MinION
>
>    GridION
>
>    unspecified
>
> On Thu, Oct 1, 2015 at 9:58 AM, Antonio Gonzalez <notifications@github.com
> > wrote:
>
>> @ackermag <https://github.com/ackermag> Thanks but I think this is it:
>> LS454 = com:type454Model (
>> *) ILLUMINA = com:typeIlluminaModel (*)
>> HELICOS = com:typeHelicosModel
>> ABI_SOLID = com:typeAbiSolidModel
>> COMPLETE_GENOMICS = com:typeCGModel
>> OXFORD_NANOPORE = com:typeOxfordNanoporeModel
>> PACBIO_SMRT = com:typePacBioModel
>> ION_TORRENT = com:typeIontorrentModel
>> CAPILLARY = com:typeCapillaryModel
>>
>> (*) We support -- Note that 'UNKNOWN' is supported by Qiita but not is
>> not in EBI's list, what about deleting it?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/biocore/qiita/issues/1483#issuecomment-144786295>.
>>
>
>
>
> --
> Gail Ackermann
> Knight Lab
> UCSD
> glackermann@ucsd.edu <ackermag@ucsd.edu>
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
@ackermag, thanks! This means that we either add this to the required field to the templates or we continue sending unspecified ... and yes that will require some code changes.

**Comment by antgonza** [comment]
Closed by https://github.com/biocore/qiita/pull/1484
