### ISSUE TITLE
The Stats page is broken

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1493]
I __think__ the issue is that now there can be null values in the latitude/longitude columns, so we will need to fix this.

**Comment by antgonza** [comment]
I was taking a look at this as it's important to fix but not sure if fixing get_lat_longs to only retrieve not None values or fixing _get_stats to skip them will be the way to go ... opinions?

**Comment by josenavas** [comment]
I think the best one is to fix get_lat_longs
