### ISSUE TITLE
Errors while updating prep template

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1497]
While trying to update a prep template I realized that we do this with [two steps](https://github.com/biocore/qiita/blob/master/qiita_pet/handlers/study_handlers/description_handlers.py#L432): extend, then update. This behavior causes 2 issues:
- [ ] When you extend a single column, for example instrument_model, you get a few warnings that are not accurate: 

```
qiita_db/metadata_template/util.py:141: QiitaDBWarning: Sample names were already prefixed with the study id.
  QiitaDBWarning)
qiita_db/metadata_template/base_metadata_template.py:575: QiitaDBWarning: Some functionality will be disabled due to missing columns:
    Demultiplexing with multiple input files disabled. If your raw data includes multiple raw input files, you will not be able to preprocess your raw data: primer, run_prefix, barcode;
    Demultiplexing disabled. You will not be able to preprocess your raw data: primer, barcode;
    EBI submission disabled: platform, library_construction_protocol, experiment_design_description, center_name, primer.
See the Templates tutorial for a description of these fields.
  QiitaDBWarning)
qiita_db/metadata_template/base_metadata_template.py:716: QiitaDBWarning: The following columns have been added to the existing template: instrument_model
  QiitaDBWarning)
```
- [ ] Then, my guess is that the extend did everything we need, the update doesn't do anything and brakes with:

```
ValueError: Error running SQL query:
Query: UPDATE qiita.prep_1060 AS t SET

                     FROM (VALUES )
                        AS c(sample_id, )
                     WHERE c.sample_id = t.sample_id

Arguments: []
Error: syntax error at or near "FROM"
LINE 3:                      FROM (VALUES )
                             ^
```

**Comment by antgonza** [comment]
@josenavas can this be closed?

**Comment by josenavas** [comment]
I think the second part of this issue was fixed (i.e. the `ValueError`). However, the warnings issue is still not fixed. In order to fix that, I think the validation of the sample/prep information should be slightly changed:
 - Instead of only checking the values uploaded by the user, we need to merge his information with the one already present in the database in order to check if there are any missing columns.

Unsure how easy/fast is to change this.

**Comment by antgonza** [comment]
@josenavas is this fixed?

**Comment by josenavas** [comment]
No - should we create a new milestone (metadata refactor) and add the metadata-related issues to it?

**Comment by antgonza** [comment]
I think that will be great. Can you do it?

**Comment by antgonza** [comment]
This was solved in the October 1st release.
