### ISSUE TITLE
can't change processed data status if there is no biom table

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1503]
As we are doing everything close reference there are datasets (ITS for example) that will get no hits and will fail to generate a biom table. Without a biom table users can't request data to be made private. 

The best solution is to allow subsampled open reference but this might take some time, other option is that if the biom table is empty (we can catch the error: ValueError: Zero sized dimension for non-unlimited dimension) we generate a place holder for it with a warning in the page. This should allow users to ask for the process data to be public. I _think_ both options will be good in the long run. 

On a second thought perhaps the other option is move the private button to the preprocess data.

What do you think?

**Comment by josenavas** [comment]
With the artifact changes the visibility of the data will be in a per item basis - I don't know if we want to put some quick hack in place or just wait until that work is done.

**Comment by antgonza** [comment]
@josenavas can we close this?

**Comment by josenavas** [comment]
I would suggest leaving this open since this is currently present in the system. It will disappear once we change the interface.

i.e. the backend currently supports those changes but the interface is limiting this behavior, I think this should remain open so during the refactor that @squirrelo is mainly working on this gets fixed there. Assigning to @squirrelo

**Comment by squirrelo** [comment]
My understanding was that all artifacts now store their status regardless of type. Is this correct? If so I can roll this into the admin actions pull request.

**Comment by josenavas** [comment]
How is the status of each artifact changed now in the interface? If there is no way of doing it that needs to be fixed. Suggest doing it in a different PR as this is not admin specific tools.

**Comment by squirrelo** [comment]
The changes to do this should be in #1593

**Comment by antgonza** [comment]
This was solve in: https://github.com/biocore/qiita/pull/1738
