### ISSUE TITLE
confusing behavior when unlinking/deleting raw data

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1504]
If a raw data is shared between two prep templates and you want to unlink from one of them, you can't and it doesn't raise any warnings or messages. Additionally, you can get rid of the raw data by deleting it and not affecting the other prep template, which is fine but confusing due to the normal behavior.

**Comment by antgonza** [comment]
Now when you share an artifact you actually make a copy so this issue can be deleted. @josenavas, can you confirm?

**Comment by josenavas** [comment]
That's correct
