### ISSUE TITLE
add a job/task manager

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1505]
It will be great so we can keep track of everything is running and their state.

**Comment by josenavas** [comment]
Should this be part of MOI as it is the one that manages the firing of the jobs?

**Comment by antgonza** [comment]
Perhaps but we will need also a way to display it via CLI/WEB.

**Comment by wasade** [comment]
moi has a cli and the js to display a joblist was part of the initial design

**Comment by josenavas** [comment]
Agree - @antgonza the interface for the analysis jobs lives in moi, so we can do something similar here - and have an Admin site that loads such moi interface.

**Comment by antgonza** [comment]
Makes sense ...

**Comment by colinbrislawn** [comment]
This should include a 'Clear failed jobs' option (that way when you are troubleshooting Prep Info Files, you can clear all the errors you accumulate along the way.)

**Comment by jwdebelius** [comment]
Bumping this as something to expose to users.

It would be really awesome if this could let you see the job, runtime, and possibly who spawned it for sandbox/private studies. I'd also like to be able to stop, bump, or delete jobs. (If, maybe, I accidentally spawned off a job I hadn't meant to start).

Also :+1: on Colin's suggestion to clear failed jobs.

**Comment by colinbrislawn** [comment]
>and possibly who spawned it for sandbox/private studies

👍 Also a very good idea. Today I discovered an artifact locked by old job that I'm not sure who started.

**Comment by antgonza** [comment]
We will use moi lists and the DB to generate the tasks.
