### ISSUE TITLE
If a user edits a PCoA plot via Emperor allow to submit a fix to the main study.

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1509]
Related to https://github.com/biocore/emperor/issues/427

If a users edits a metadata it should allow to request to make those modifications in the main metadata for the given studies.

**Comment by josenavas** [comment]
IMO it should be a propose change - not a direct change. I can see some users removing standard values because they don't fit their set of values.

**Comment by antgonza** [comment]
Yup, send email to owner/admin and one of them can accept the change.

**Comment by adswafford** [comment]
is this now handled somehow with filtering? I don't think I've seen anyone edit metadata in Emperor?

**Comment by antgonza** [comment]
Nop, this is basically communication between emperor and the db.

**Comment by antgonza** [comment]
closing as this is a subset of #2410
