### ISSUE TITLE
phred_offset failure, should we fix?

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1512]
Background: I'm working again on processing the RISK files in qiita and figure out the last issue so we can process. As a reminder, the Broad sent us per sample files as the raw data. The issue is that by default skbio auto detects the phred_offset value (either 33 or 64) which normally works great but on these files it seems like the reads were generated using 33 but the header was generated using the 64 standard. Thus, it doesn't work and we need to preprocess by hand. 

Now, the question is: do we expect this to happen often? If that's the case we need a fix. The fix is simple: add a new column in the qiita.preprocessed_sequence_illumina_params table so we can pass this value; add a new row in that column for per sample FASTQ where we make the phred_offset 32 and leave the other defauls; and finally changing to this new processing params the list of studies that have been processed with it: 1998 and 1939.

Note that we didn't add it cause it was never used before and this is a really _special_ case.

**Comment by ElDeveloper** [comment]
I don't think this is something we should commonly expect to happen, not
sure what others think. At the very least I'm not aware of any other
study that has a similar setup.
