### ISSUE TITLE
Metadata search fails: target_subfragment = V2 yields no studies

### ISSUE THREAD

**Issue by shafferm** [biocore/qiita#1513]
Using qiita's metadata search I wanted to find other studies using the V2 region to compare to. Study ID 797 has the metadata column target_subfragment are it is always equal to V2. I can find that in the sample template summary and by downloading the metadata file. Study ID 77 shows these same things. target_subfragment is also in avaliable metadata list.

I use the query "target_subfragment = V2" in metadata search and no studies are found.

**Comment by josenavas** [comment]
@squirrelo can you comment here? AFAIK the metadata search currently doesn't work over prep template values, and such columns is usually in there. Is that correct?

**Comment by squirrelo** [comment]
Yes, that is correct. Currently the search only searches over the sample template and study information(title, abstract, etc), but that will be expanded once major database refactors are done.

**Comment by shafferm** [comment]
So does this mean that many members of the list of avaliable metadata are not searchable in spite of being listed under avaliable metadata?

**Comment by antgonza** [comment]
this has been superseded by the redbiom interface.
