### ISSUE TITLE
Cannot download Qiime mapping file from my own study

### ISSUE THREAD

**Issue by EmbrietteH** [biocore/qiita#1520]
Study ID 10331.

I uploaded prep and sample templates, but when attempting to download the Qiime mapping file cannot do so:

<img width="563" alt="screenshot 2015-10-30 11 11 49" src="https://cloud.githubusercontent.com/assets/11282319/10854134/133a06ea-7ef7-11e5-898b-753f8f061937.png">

**Comment by antgonza** [comment]
The bug is that you can only download PrepTemplates that have a raw data: https://github.com/biocore/qiita/blob/master/qiita_db/meta_util.py#L111

For a quick solution, add a raw data.

**Comment by josenavas** [comment]
Linking this other issue as probably they're related: https://github.com/biocore/qiita/issues/1010

**Comment by antgonza** [comment]
@josenavas can this be closed?

**Comment by josenavas** [comment]
Yup, tested and this problem is not present anymore :smile:
