### ISSUE TITLE
Allow column/sample deletions in the sample/prep templates

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1539]
This is something that is inevitable in some cases.

At the qiita_db level, I think we should provide a function that takes a list of samples and/or a list of column names and removes those samples/columns.

At the qiita_pet level, I think we need a new interface in which the user can select the sample and/or columns from a multiselect list and then delete those columns.

If the study is sandboxed, then the user should be free to make this changes. If the study is already private or public (i.e. it has been verified by an admin) the user should contact the admin to make any further modification.

**Comment by ackermag** [comment]
I agree with this plan and how to implement it.  Without this there is a lot of reprocessing especially when users upload qiime mapping files only.

**Comment by josenavas** [comment]
That is actually a really good point @ackermag I think it may also be worth to have another interface in which the user can transfer columns from the sample template to the prep template, for those cases in which the user uploads a QIIME mapping file. The system only grabs the minimum columns that it knows that belong to a prep template, but there may be others that also belong in there.

**Comment by antgonza** [comment]
I'm working on this and decided that the delete should happen column by column for security and that the only place deleting a sample is OK is in the sample info file (*). Do we agree? Please respond by the end of the day today.

(*) Deleting a sample from a prep info file has a lot of implications.

**Comment by antgonza** [comment]
After discussion with @josenavas we will allow to delete samples from the prep template if it hasn't been processed to avoid issues with deletions in the artifacts.

**Comment by antgonza** [comment]
Closing as this has been already solved and deployed.
