### ISSUE TITLE
Template parsing errors can't handle unicode in headers

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1560]
Many of the errors raised in parsing, including the non-unicode character check, print the column header as part of the error. In qiita pet, some of these errors are explicitly converted to string (see [here](https://github.com/biocore/qiita/blob/master/qiita_pet/handlers/study_handlers/description_handlers.py#L222) as an example). This means that if the column headers have unicode characters, the system throws a secondary error trying to print the original error.

**Comment by antgonza** [comment]
We haven't seen this kind of errors in a while, since the changes to the loading and parsing of files. Thus, closing.
