### ISSUE TITLE
The admin error pages, writes JS raw

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1568]
The page is writing all JS raw so the browser interprets it. 

How did we notice it?
`<meta http-equiv="refresh" content='0;URL=http://www.ebi.ac.uk/errors/failure.html'>`

**Comment by ackermag** [comment]
Is this for the study 10141?


On Tue, Dec 8, 2015 at 6:58 PM, Antonio Gonzalez <notifications@github.com>
wrote:

> The page is writing all JS raw so the browser interprets it.
>
> How did we notice it?
> <meta http-equiv="refresh" content='0;URL=
> http://www.ebi.ac.uk/errors/failure.html'>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1568>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
Yup, nothing to do with the study. However, EBI's reply has a redirect/refresh and the reason the page moves to another page ...
