### ISSUE TITLE
errors when raw files have spaces in their name

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1570]
If a prep template with spaces in it's name is uploaded, split libraries is going to fail. Not sure of the consequences of doing the same in a sample template.

**Comment by josenavas** [comment]
I'm confused about this - why would split libraries fail? The name of the prep template is not used anywhere because we regenerate the file with our own naming convention (<study_id>_prep_<prep_id>_<date>.txt).

My guess is that the spaces are actually in the run_prefix values in the prep template?

**Comment by antgonza** [comment]
You are 100% right. The issue is that the raw data got an extra txt file. This raises 2 things: (1) that if a fastq(.gz) file has spaces this command will fail and (2) we should only list sequence files when a user has to select which raw files.

**Comment by josenavas** [comment]
I think 1 can be easily fixed by adding quotes around the file names when we are calling command line commands.

I think I don't follow you in number 2...

**Comment by ElDeveloper** [comment]
Right, 1 can be fixed with the quotes, and since the new plugin system
centralizes this, fixing the problem should be fairly straight forward
right?

**Comment by antgonza** [comment]
Agree on solution for 1. 2: The GUI should only show you sequence file extensions so users can't by mistake select a txt here. Similar to what we do with the sample/prep information files, only show txt.

**Comment by antgonza** [comment]
updating issue name so it matches discussion.

**Comment by antgonza** [comment]
This is also a problem when the sample/prep information files have spaces in their names.
