### ISSUE TITLE
Alter Study.prep_templates action

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#1575]
calling an instantiated study object's `prep_templates` function should return a dict of artifacts, keyed by plugin type, e.g.
```python
{'TargetGene.16S': [PrepTemplate1, PrepTemplate2, ...], ...}

**Comment by josenavas** [comment]
I think that after our offline discussion we agreed that this is not needed?

**Comment by squirrelo** [comment]
It would still save a couple DB calls, but yeah, it's not strictly needed.
