### ISSUE TITLE
How to document the RESTapi

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1588]
It looks like there is no agreement on how to document the few RESTapi functions that we have added to the system so far. I agree that using the `Returns` from the numpy doc is not the most accurate, although it currently works well to at least document our code.

I've been looking around, and given that we are already using Sphinx for our documentation (numpy docs is just build on top of them) I think that for our RESTapi functions we can use this Sphinx extensions: https://pythonhosted.org/sphinxcontrib-httpdomain/

What do people think? We can enforce 2 different documentation standards: numpy doc for the vast majority of the code and the Sphinx extension for the RESTapi endpoints. It even has an extension for tornado.

**Comment by antgonza** [comment]
I think having both doesn't hurt and it will be easier to follow up for development in the long run. I guess we should have a list of things and functions that need documentation so we don't forget. @josenavas and @squirrelo, could you add such a list?

**Comment by antgonza** [comment]
Closing as we have a full description of [all the endpoints](https://qiita.ucsd.edu/static/doc/html/dev/rest.html).
