### ISSUE TITLE
Improve guidance while resetting password

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#1592]
I just reset my password with Qiita. The first new passwords I tried to use directed me to a error 500 page without explanation. My third attempt used a password with numbers, letters, and capitals letters, which worked fine.

I'm not sure what was wrong with these initial passwords (too short maybe?). A visual indication of the 8 character minimum would be nice. I never saw the error message mentioned here:
https://github.com/biocore/qiita/blob/master/qiita_pet/static/js/password_validation.js

Thanks!
Happy new year!

**Comment by antgonza** [comment]
@colinbrislawn thanks for reporting. Closing in favor of: https://github.com/biocore/qiita/issues/1802 as that one has more info.
