### ISSUE TITLE
Ability to download beta-diversity text file

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#16]
Ported from Qiita-pet.

```
squirrelo commented a month ago
Current Qiime database does not give the beta-diversity distance matrix. Could this be made available in the new release?
 Yoshiki Vázquez Baeza
 
ElDeveloper commented a month ago
I'm pretty sure the distance matrix is part of the zipped file that comes as a result of a meta-analysis if you decided to compute any beta-diversity metric to plot it in a three dimensional space. But I agree that there should be a direct link to this file instead of just to the 3d plot.
```

**Comment by tracykteal** [comment]
+1 on being able to download the distance matrix or the FASTQ files for all the samples selected for analysis. Right now I don't see a zipped file that can be downloaded, just an index.html page link after running the meta-analysis.

**Comment by antgonza** [comment]
This should be really easy at this point. The tables exist and are available but we just need to put a link to  #_beta_div.../unweighted_unifrac_dm.txt or weighted_unifrac_dm.txt.

**Comment by tracykteal** [comment]
Right, I could download them once you told me the URL, but there wasn't an indication that this was possible on the site. I think this would be a really important feature! Then people could do their own statistics and data analysis which is really key.

**Comment by antgonza** [comment]
Agree. Note that next week we will have a code sprint to solve this and other issues ... in case you want to join us virtually. Here are some notes: https://hackpad.com/Biocore-code-sprint-v15.3-X4ypG5V0mSz

**Comment by JWDebelius** [comment]
I'd like to be assigned to this.

**Comment by tracykteal** [comment]
Great to see this being implemented. Let me know if you need a beta (alpha?) tester.
