### ISSUE TITLE
Allow download BIOM tables in classical txt file

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1600]
Adding a dropdown with the file format would be useful.

**Comment by adswafford** [comment]
Would this be something to let users download .biom files as .tsv? If so, then I second this!

**Comment by wasade** [comment]
This should be disallowed based on dimensionality though. It would abuse our resources and bandwidth to allow this on things like AG. Perhaps allow this to top out at 100 samples or 1000 features?

**Comment by adswafford** [comment]
That seems reasonable. Having a feature cap is better to me than limiting the samples, or having an absolute, i.e. for 100 samples you can take 1000 features, but for 1000 samples only the top (and/or bottom?) 100 features?

**Comment by adswafford** [comment]
Now that we're moving further away from txt and more towards qza, I think this is no longer an issue that we need to solve.
