### ISSUE TITLE
Errors get hidden in step 3 of split_libraries_fastq.py

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1610]
If step 3 of `split_libraries_fastq` in `qiita_plugins/target_gene/tgp/split_libraries/split_libraries_fastq.py` fails, we don't get the actual error but: ` The split libraries output directory does not contain the demultiplexed fastq file.`, which is accurate cause the previous step failed. However it will be good to know why it failed, for example:
```
skbio.parse.sequences._exception.FastqParseError: Failed qual conversion for seq id: M00365:7:000000000-A44J0:1:1101:15990:1748 1:N:0:0. This may be because you passed an incorrect value for phred_offset.
```

**Comment by josenavas** [comment]
Good catch - this should be an easy fix. The main issue is that when the function `system_call` is executed, the `return_value` is not checked. This should be as easy as adding an if statement in and raise the specific error. Assigning to me.
