### ISSUE TITLE
Check for spaces in column names

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1614]
We should check if there is any space in column names. If so, I see two options:
1) Error and tell the user which columns are wrong and why
2) Automatically change those for underscores, notifying the user.

I usually don't like to modify the user's metadata, but I have the feeling that this is a simple and harmless one, so I would suggest going through 2. What do others think?

**Comment by ackermag** [comment]
Agree with 2 - no-brainer


On Wed, Jan 20, 2016 at 8:59 PM, Jose Navas <notifications@github.com>
wrote:

> We should check if there is any space in column names If so, I see two
> options:
> 1) Error and tell the user which columns are wrong and why
> 2) Automatically change those for underscores, notifying the user
>
> I usually don't like to modify the user's metadata, but I have the feeling
> that this is a simple and harmless one, so I would suggest going through 2
> What do others think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1614>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
This was solved via get_invalid_column_names() in https://github.com/biocore/qiita/pull/1851 and using option 1. This decision was made as we rather report all wrong column names at once (including those with spaces) than changing what the user uploaded.
