### ISSUE TITLE
Sample selection interface is broken

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1620]
when you try to remove a sample from the list, a "sever communication error" appears:

![image](https://cloud.githubusercontent.com/assets/2501478/12595603/165e185a-c431-11e5-8dd1-0a4663b2c30b.png)

**Comment by josenavas** [comment]
I've been looking at this issue - I can't reproduce in my machine but I can consistently reproduce in the live system. I will take a closer look tomorrow and I will be playing in the test environment to see if I can reproduce there and look the actual source of the issue.

**Comment by ackermag** [comment]
Test environment clearly doesn't mirror live system.


On Tue, Jan 26, 2016 at 9:10 PM, Jose Navas <notifications@github.com>
wrote:

> I've been looking at this issue - I can't reproduce in my machine but I
> can consistently reproduce in the live system. I will take a closer look
> tomorrow and I will be playing in the test environment to see if I can
> reproduce there and look the actual source of the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1620#issuecomment-175401166>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
@ackermag can you elaborate on that statement? Note that I still have not tried there (I will do that today).

**Comment by ackermag** [comment]
When I select a study for analysis and want to remove unwanted samples, I
get this error:
Server communication error. Sample removal will not be recorded. Please try
again later.
Create Analysis
If you cannot recreate it seems like there is something different between
test environment and live - remember I have not been directed to the test
system

On Wed, Jan 27, 2016 at 8:28 AM, Jose Navas <notifications@github.com>
wrote:

> @ackermag <https://github.com/ackermag> can you elaborate on that
> statement? Note that I still have not tried there (I will do that today).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1620#issuecomment-175725927>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
@cuttlefishh, just re-reported this. @josenavas did you check the test environment?

**Comment by antgonza** [comment]
A user just re-reported this issue, @josenavas, have you been able to double check it?

**Comment by antgonza** [comment]
This was solved when moving out of moi
