### ISSUE TITLE
Adding necessary mechanisms to install a plugin

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1625]
Include, but not limited to:
 - [ ] Create software
 - [ ] Create commands (with their parameters and default parameters set)
 - [ ] Add new filepath types
 - [ ] Add new artifact types
 - [ ] Add filepath type - artifact type relationship

**Comment by mortonjt** [comment]
Can this be closed?

**Comment by antgonza** [comment]
Yes, thanks for pointing it out. The new thing we are working on is to -automatically- install them: https://github.com/biocore/qiita/pull/1909.

**Comment by josenavas** [comment]
It hasn't been yet merged on master
