### ISSUE TITLE
Supported sequence file types is confusing

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/qiita#1629]
It's confusing as to which file types are supported. One can upload fastq, sff, fasta, qual -- but then in the fine print it says only fastq is supported. And is it only the multi-sample fastq (before demultiplexing) that is supported? This should be more clear. Thanks!

**Comment by antgonza** [comment]
Thanks for your report. Could you list which pages/documents that have this confusing information?

**Comment by cuttlefishh** [comment]
On the upload page it list a bunch of file types in parentheses but then below is more limited ...

Uploading files for: cr test study (crtest) 

Currently we can process (fastq, fastq.gz, txt, tsv, sff, fasta, fna, qual):
* fastq or fastq.gz (gziped fastq) for sequences. Note that zip files can not be processed
* tab separated text files for sample and prep templates, the extension should be txt

**Comment by cuttlefishh** [comment]
In the Tutorials page, under <https://qiita.ucsd.edu/static/doc/html/tutorials/getting-started.html#adding-a-preparation-template-and-linking-it-to-raw-data> it mentions "SFF, FASTQ, etc" but below at <https://qiita.ucsd.edu/static/doc/html/tutorials/getting-started.html#preprocessing-data> it says "Currently we only support fastq files for target gene preprocessing".

**Comment by antgonza** [comment]
@cuttlefishh, do you think this is solved in the latests documentation? If not, could you give us some extra suggestions? Thanks.

**Comment by antgonza** [comment]
Closing as I believe it has been solved in the latests documentation. Please reopen if you feel otherwise.
