### ISSUE TITLE
Get filepaths properly for reference files. 

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#164]
Right now the demo is hacky and assumes one file per processed data and per datatype. Needs fixing in analysis_handlers.py

**Comment by antgonza** [comment]
@squirrelo this now can be closed, right? Please reopen if not.

**Comment by squirrelo** [comment]
Nope, still needed for getting the desired reference database. See [this](https://github.com/biocore/qiita/blob/master/qiita_ware/analysis_pipeline.py#L107) line.

**Comment by antgonza** [comment]
OK, thanks. Renamed the issue to make it clearer

**Comment by antgonza** [comment]
I'm impress that this is still an open issue. Any takers?

**Comment by antgonza** [comment]
This should be solved once we merge: https://github.com/biocore/qiita/pull/1678
