### ISSUE TITLE
save template warnings and show them all the time

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1661]
This came up in the last qiita meeting. Basically, if a template has warnings (no EBI submission, no demux, etc), this info is showed once but not stored, which could create confusion. A good solution is to store this info and show it all the time in the template admin.

**Comment by ackermag** [comment]
I agree - although there is an easy workaround (i.e.resubmitting or
updating), having that warning visible when you get to the page will save
time.
Gail

On Wed, Feb 24, 2016 at 6:53 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> This came up in the last qiita meeting. Basically, if a template has
> warnings (no EBI submission, no demux, etc), this info is showed once but
> not stored, which could create confusion. A good solution is to store this
> info and show it all the time in the template admin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1661>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
This was already solved.
