### ISSUE TITLE
Should we remove `emp_person` from the study object?

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1668]
It has never been used in the current system and it is one of those old attributes that we carried on form the old database. This information should be stored in JIRA regarding to the specific project, as this is not something that applies to all the studies added in Qiita.

**Comment by ackermag** [comment]
Agree - this actually was misused.  Was meant to refer to the Person who
suggested on the EMP steering committee (Janet, Jack or Rob).


On Sat, Feb 27, 2016 at 1:21 PM, Jose Navas <notifications@github.com>
wrote:

> It has never been used in the current system and it is one of those old
> attributes that we carried on form the old database. This information
> should be stored in JIRA regarding to the specific project, as this is not
> something that applies to all the studies added in Qiita.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1668>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
As a group we decided to remove.

**Comment by antgonza** [comment]
Moving to Alpha 0.4 as it's not blocking anything important at this point.
