### ISSUE TITLE
Modify get_filepaths in MetadataTemplate to optionally retrieve latest filepaths

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1675]
Currently it returns a sorted list of all the filepaths. It will be useful to add an optional parameter to return only the current ones, given that we only want all of them in rare cases.

**Comment by antgonza** [comment]
@josenavas, do you still think this is necessary?

**Comment by antgonza** [comment]
While working on https://github.com/biocore/qiita/issues/2214 I realized that this can be closed as we are now gonna display all the preps vs. just the latests.
