### ISSUE TITLE
add non-GUI method for downloading data

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#1695]
A member of the qiime forum requested a way to download qiita data from the terminal. 
https://groups.google.com/d/msg/qiime-forum/yGET2CORs4A/FEc94-n2DQAJ

Community members are also intersted in an API for downloading qiita data. 
https://github.com/joey711/phyloseq/issues/491 

(If this is a duplicate of a known issue, feel free to close it.)
Thank you all!
Colin

**Comment by antgonza** [comment]
Basically, this means having a restful interface. Closing in favor of: https://github.com/biocore/qiita/issues/1251

**Comment by colinbrislawn** [comment]
Oh perfect. I knew you must have thought of this, I just didn't have the right words. 
Thanks Antonio,
Colin
