### ISSUE TITLE
Fix top menu - screen shot attached

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1699]
<img width="792" alt="screen shot 2016-03-21 at 8 26 10 am" src="https://cloud.githubusercontent.com/assets/2014592/13923667/d6ea4638-ef3e-11e5-8242-c9a23f604129.png">
After adding current and future plansto menu, text starts stacking when you resize the window

**Comment by antgonza** [comment]
We need to fix but have you tried making the window bigger? That should be a temporal solution ...

**Comment by ackermag** [comment]
I will try next time it happens


On Mon, Mar 21, 2016 at 8:30 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> We need to fix but have you tried making the window bigger? That should be
> a temporal solution ...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1699#issuecomment-199340806>
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>
