### ISSUE TITLE
Make lab person requiered

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1709]
I think this is a good thing to have because PI denotes lab submitting, lab personnel maybe may be changed to 'submitter' who uploaded the data.  This allows us to identify source of data (PI) and the person who uploaded the study.  Often uploader moves to new lab (new position, where they may be PI) and continues to use qiita.  I believe it is good to track this history.  It also has an implication for seq_center, center_name because it will allow us to solve problems with processing.
Do not remove this requirement - it is very easy to add PI even if they have no account

**Comment by antgonza** [comment]
Updated title to make it clearer. This was originally discussed here: https://github.com/biocore/qiita/pull/1708

**Comment by antgonza** [comment]
Resolution: do not change. This was before we had JIRA and for external users we have the owner and PI.
