### ISSUE TITLE
Question and answer section for studies

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1752]
Not my idea (someone at the Sloan meeting brought this up), but I think it's a good one:

Each study should have a **Q & A** section where users of public studies get to ask questions to the authors, these questions are stored along with the study and serve as a reference for future users of the study. For example someone could ask questions about the meaning of a column in metadata file, and the author could answer publicly for future users to see this information.

**Comment by adswafford** [comment]
It looks like this is covered by #2234?

**Comment by antgonza** [comment]
This issue is superseded by https://github.com/biocore/qiita/issues/2234
