### ISSUE TITLE
Looking for BIOM file download from QIITA for all case studies

### ISSUE THREAD

**Issue by prakruthikr** [biocore/qiita#1753]
Hi All,
There were files called BIOM files for every case study where the data was stored @ QIITA. I was about to download the data but now i see that the site itself has been changed and there are no more BIOM files. or i am not sure whether they are upgrading to make it better further with BIOM files. Can anyone help me on this? If anyone is aware of BIOM file data or can I access the Earth microbiome database in other way, can anyone guide me the steps please? I need this data for my Microbial data analysis. If anyone has the previous 100 BIOM files, that would also help! You can send me details to my email as well @ krprakruthi@gmail.com.
Thanks,
Prakruthi K R
India

**Comment by antgonza** [comment]
We changed the GUI based on suggestions from users and developers. Here is a screenshot of how to download a biom. 
![download-biom](https://cloud.githubusercontent.com/assets/2014559/14351546/2e5bc03a-fc8d-11e5-86c1-bef3bea29992.gif)

Now, if you want to download a combination of studies, you should select those to build a meta-analysis and then download the newly generated files.

**Comment by prakruthikr** [comment]
Thanks  a lot for this information Antonio Gonzalez!
My interest lies in downloading BIOM files for all entries and then parse
the BIOM to filter the keywords based on our interest. Is there a way to
download BIOM of all entries at once or is it available @ any database as
such (BIOM files)? If yes, can you guide me further.

We are looking at automating this manual download using python script.
Still starting to work on script. Before that I thought I shall check if
any other way to access/download these.
Have a nice day!
Thanks again!
Prakruthi K R
Bangalore, Karnataka, India

**Comment by antgonza** [comment]
The only way to do this is via an analysis: you will need to select all your studies/samples from the study list page and then create an analysis. This will merge all your selected studies and create a new biom/map with the selected samples. Now, we have an open issue to generate a [restful interface](https://github.com/biocore/qiita/issues/1251), which is in the works and should allow you to automate your download.

**Comment by prakruthikr** [comment]
oh great! I need data from all studies, hence I wl try to select all 253
and wl create analysis and see hw it works. thanks for details.
prakruthi

**Comment by prakruthikr** [comment]
Hi Antonio,

I have another query regarding creating analysis for all studies together.
Can you please create one BIOM file for all studies and send me path to
download it so that I can download directly and use it?
If not please guide me steps to create the analysis and downloading one
BIOM for all studies in your website.
Also, we want to know whether we can retrieve the raw sequence data for
these BIOM files? if yes, please guide me the steps?

Thanks,
Prakruthi

**Comment by antgonza** [comment]
Just replied to your other issue on the same topic: https://github.com/biocore/qiita/issues/1830

**Comment by prakruthikr** [comment]
what about the raw sequences?

**Comment by antgonza** [comment]
We only provide public access to the demux sequences, not the raw files (we consider them raw enough), just like what we upload to EBI/ENA. You can download these files from the study page.
