### ISSUE TITLE
meta-analysis failure

### ISSUE THREAD

**Issue by jminich444** [biocore/qiita#1757]
I attempted to process my "malawi manure" dataset against 7 other datasets for a total of ~2000 samples. I created a new analysis, added each analysis, and then kicked off the run. When I view the run in my "see previous analyses", the run appears as if its running. When I click on the link to that analysis, it says that it has failed. When I click on failed, it gives no reason.
![screen shot 2016-04-08 at 9 12 06 am](https://cloud.githubusercontent.com/assets/18352435/14390087/2f5877c0-fd6a-11e5-854a-c230e6c3d595.png)
![screen shot 2016-04-08 at 9 04 39 am](https://cloud.githubusercontent.com/assets/18352435/14390092/360159b6-fd6a-11e5-8d74-1ea2b223cd03.png)
![screen shot 2016-04-08 at 9 14 08 am](https://cloud.githubusercontent.com/assets/18352435/14390105/4a0fe706-fd6a-11e5-8c56-07470783be88.png)

**Comment by antgonza** [comment]
Thanks for posting. After reviewing the error logs it seems like the error was due to the error solved here: https://github.com/biocore/qiita/pull/1749. This fix should be available after tomorrow's morning update. Closing this now. Please reopen if you run into it again.
