### ISSUE TITLE
since most recent update -troubling behaviour when trying to download data

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1786]
Earlier today, Antonio fixed but problem has recurred.
Behavior:
Study loads abut when any link is clicked (e.g. download sample) no response except rotating balls

**Comment by josenavas** [comment]
Hi @ackermag 

I just tested and I didn't had any problem downloading the data - Can you try re-loading the entire page and trying again? Otherwise I can check with you tomorrow.

**Comment by antgonza** [comment]
Note that this was a consequence of what https://github.com/biocore/qiita/pull/1789 is fixing.
