### ISSUE TITLE
Create user manual

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#179]
A document that explains how to use the system.

**Comment by squirrelo** [comment]
This is done with the wiki and google doc we have, correct?

**Comment by ElDeveloper** [comment]
Not really, we want something like QIIME, emperor or sickit-bio's
sphinx-based documentation.

**Comment by squirrelo** [comment]
Ah, so this is for dev documentation, not user documentation. Can you change the title and/or explanation field on this to reflect that?

**Comment by ElDeveloper** [comment]
Hmmmm this is really both, I feel. What we need to do is initialize a
barebones sphinx document in the repo. Then start creating tutorial
documents both for users and developers. API docs, numpy docs, etc.
