### ISSUE TITLE
Download merged QIIME/biom files for a single study.

### ISSUE THREAD

**Issue by jwdebelius** [biocore/qiita#1805]
It would be awesome if, on multi-prep mapping files, there was a way to download a merged QIIME mapping file for the study.

The American Gut is probably the biggest use case for this right now, but we're seeing more and more studies with multiple preps and runs over time. I also see it being very useful for meta analysis situations.

**Comment by josenavas** [comment]
In the meantime, you can create a meta-analysis with all the bioms of a study and it will create a BIOM and a Mapping file with the entire study.

**Comment by antgonza** [comment]
Don't rarefy so you get the raw biom, if that's your goal and create

**Comment by antgonza** [comment]
To fully fix this issue we should allow to download as zip the merged mapping files and merged biom tables. Renaming the issue and moving to Alpha 0.4 cause this will required more changes.

**Comment by josenavas** [comment]
Just to put more information here - given that now we support multiple ways of processing the data I don't think the good approach is to merge all of them, but rather create a tar file that all files can be downloaded at once, so the user doesn't need to go over multiple places in the interface. The user can then merge the mapping file / biom tables in their end if they want to.
