### ISSUE TITLE
If the EBI submission fails - show an error

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1810]
Currently it just returns and the admin user has no clue if it fail or not unless directed to `Admin -> view errors`

**Comment by josenavas** [comment]
Adding a bit more information here: Right now, this is what is shown in the study description page: `EBI: failed: XML parsing, log id: 119306`. The log message then includes the entire XML, which is a pain to read to find the errors. I think a couple of things can be improved:
1. In the `Admin -> view errors` page, allow the Admin to introduce a log id and show the error message of that error.
2. The error is not always an XML parsing error - we should be parsing the XML and look for the 'ERROR' tags. Then use this ones to create a meaningful error message.

In 2, we are restricted to whatever EBI returns. When there is a problem with a single sample, EBI complains with an `ERROR` tag, but it is not telling you which sample is failing. @antgonza do you think that we can communicate with them to add at least the `sample_alias` information to the error message so the user knows which is the offending sample?

**Comment by antgonza** [comment]
This makes a lot of sense. Now, I'm pretty certain but not sure and perhaps you can check this, that if you open the xml file the error is going to be within a sample_alias ...

**Comment by josenavas** [comment]
Maybe I misread the document, but it looks like the error tags are appended at the end of the document. We can double-check later though...

**Comment by antgonza** [comment]
Closed by: https://github.com/biocore/qiita/pull/2523
