### ISSUE TITLE
Improve documentation for prepare-information-files

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#1813]
I've had a frustrating morning with qiita documentation, and wanted to see how I can help. 

[Prepare information files on website](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html)
[Prepare information files source on github](https://github.com/biocore/qiita/blob/master/qiita_pet/support_files/doc/source/tutorials/prepare-information-files.rst)

This page describes the requirements of `sample information file` and `prep information file` but raises more questions than it answers.
- How does these files differ in purpose?
- How does these files differ in contents? (Could they be identical or include identical columns? Is it better to increase or decrease redundancy between these file?) 
- How do these files relate to the [qiita philosophy](https://qiita.ucsd.edu/static/doc/html/qiita-philosophy/index.html)? 

I'm getting the sense that the distinction between these is super intuitive to the developers, but less clear to novice users like me. I'm interesting in contributing to documentation so that this system is clear to everyone.

Thanks!

**Comment by antgonza** [comment]
Thank you for writing and letting us know. Did you take a look at https://qiita.ucsd.edu/static/doc/html/faq.html? 

BTW any suggestions will be greatly appreciated.

**Comment by colinbrislawn** [comment]
The FAQ page is very helpful. Thank you Antonio.

With fresh eyes this afternoon, I have a better understanding of how these two templates fit into the qiita philosophy. I'll describe the system as best I understand it in a PR and I would appreciate any guidance you have to give. 

Thank you!

**Comment by antgonza** [comment]
That will be great, thanks! Again, any suggestions to make things clearer are welcome.

**Comment by colinbrislawn** [comment]
Should I refer to the biological metadata file as `sample information file` or `sample template` or 'metadata'?

(Consistent, unambiguous wording is important, especially for beginners. The old qiime docs calls these `metadata` and `mapping` file. Was there a reason for introducing two new terms for the same files, because 😱 )

**Comment by antgonza** [comment]
Good catch and the 3 names are from historical reasons and we know there are some left over occurrences. 

Let's start with the most confusing, template vs. information file. The name template comes from the old DB and basically it became a thing to call your information files, even as they are not templates anymore cause they have all the information we need. Thus, a couple of months ago we decided to move to information files, which is actually correct. We will really appreciate all corrections in the documentation about this.

Now, the template or mapping file, AKA the QIIME mapping file, it's a combination of the sample and one preparation information file. The idea of Qiita, as you can see from the documentation is that you have 1 sample but multiple preps. Thus, expanding that idea.

Again, thanks for the help.

**Comment by colinbrislawn** [comment]
Thanks for the info. I understand now why qiita specifically separates 'sample info' and 'prep information' files and why a clean break from the 'metadata / mapping' confusion is needed. Now I'm finally grasping this data structure, I think I can actually help describe it.  

As of now, ['Sample information file'](https://github.com/biocore/qiita/search?utf8=%E2%9C%93&q=%22sample+information+file%22&type=Code) is only used on the FAQ and Prepare information files page. This wording on other doc pages, on the live site, and in the variable names selves all use ['Sample template'](https://github.com/biocore/qiita/search?utf8=%E2%9C%93&q=%22sample+template%22&type=Code). So what's the correct nomenclature going forward?

**Comment by antgonza** [comment]
_Sample information file_ is the correct name and what we want to have everywhere in the documentation/descriptions/etc. As you can imagine there are a lot of places in the code, which in general is hidden from users, were we still use the _sample template_ name and changing it will be a heroic task as it will require changing the code and have a (set of) patch(es) to change them in the database.

**Comment by antgonza** [comment]
This issue is related to: https://github.com/biocore/qiita/issues/1785

**Comment by colinbrislawn** [comment]
Right, right. Updating all the backend code is overkill and probably not worth it, but fixing the public facing stuff is important. I'll start the conversion over to 'Sample information file' with the documentation pages. 
Thanks!

**Comment by colinbrislawn** [comment]
The [Qiita phyilosophy](https://qiita.ucsd.edu/static/doc/html/qiita-philosophy/index.html) should heavily emphisize the distinction between Samples and Preps. We could add this to the graphic and add a section under 'A Study' to emphasize the one-to-many relationship between them.

Who has the source that made that graphic? I could updated it.

**Comment by antgonza** [comment]
Seems like I never added it to the repo (logos folder), I'll send it to you via email.

**Comment by colinbrislawn** [comment]
The old [prepare-templates.html page](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-templates.html) should mention that 'templates' have been depreciated in favor of 'information files' and redirect to [the new prepare-information-files.html page](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html).

That old templates page is no longer on github, so I'm not sure how to submit a PR for this...

**Comment by antgonza** [comment]
Interesting, the reason the old one exists is because we don't delete the old builds. I think the best will be to create a new one with the old name and add that info. Thanks!

**Comment by colinbrislawn** [comment]
Do successful builds on github push to qiita.ucsd.edu? I'm used to them pushing to gh-pages, so I assumed no automation. 

I'll try making a `prepare-templates.rst` file now and see if I can overwrite the old page... 

Thanks Antonio. You have been both helpful and supportive here.

**Comment by antgonza** [comment]
No, the documentation is built when we (re)start (update) the system. Just FYI, we are planning a restart for this weekend.

**Comment by colinbrislawn** [comment]
Very cool. Thanks for telling me more about this system. So, if I understand correctly: my PRs get built automatically and you can review and merge them. Every so often, you take the newest stable build and launch it to the live site?

**Comment by antgonza** [comment]
That's correct.

**Comment by colinbrislawn** [comment]
Thanks for all the feedback Antonio. I appreciate all your help here. 

Now that this page is almost fixed, what about the rest of the sit?. 'Template' is still the common term on the site itself and on the [Getting started page](https://github.com/biocore/qiita/blob/master/qiita_pet/support_files/doc/source/tutorials/getting-started.rst). What's a good way to move forward?

**Comment by antgonza** [comment]
I guess we will need to change all the documentation 😐. Also, we just changed the GUI and those updates are not reflected 😢. We will really appreciate help with this ...

**Comment by colinbrislawn** [comment]
Haha right. This is a great 'tech minimal' way I am help out. Your team has done a very good job using modern technologies, so this may be pretty possible (not a lot of rendered images to update, for example).

Maybe you could create a new issue for this and make an overview task list? Then could start a mammoth PR.

**Comment by antgonza** [comment]
Thank you for your help with this!! This is super important but we have to manage new features vs. documentation, and ~~must~~ some times we get behind. Added https://github.com/biocore/qiita/issues/1828, where I think we have a comprehensive list but will be worth a second check.

**Comment by colinbrislawn** [comment]
Oh I've been there on my own projects. One this one, I can help keep the ball rolling on documentation. Once this PR get's resolved, I'll close this issue, and focus on work on #1828.

Thanks Antonio.

**Comment by antgonza** [comment]
No, thank you! 😉 . BTW: [see](https://github.com/biocore/qiita/blob/master/CONTRIBUTING.md#the-qiita-development-rules) and you can automatically close issues once the PR is merge if you add to one of your commits something like `fix #issue-number`.

**Comment by colinbrislawn** [comment]
Yeah, I alway remember to do that when submitting the PR, not when committing the changes. I'll try that next time.

**Comment by colinbrislawn** [comment]
Closing in favor of #1828
