### ISSUE TITLE
raw data names are not complete in new GUI

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1816]
if the raw data names are too long the names are cut out which makes selection difficult, we should display the full name on selection or hover.

**Comment by ackermag** [comment]
agree wholeheartedly!  I have been zooming out - which also works


On Fri, Apr 29, 2016 at 5:17 PM, Antonio Gonzalez <notifications@github.com>
wrote:

> if the raw data names are too long the names are cut out which makes
> selection difficult, we should display the full name on selection or hover.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1816>
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
👍 It may also be worth to explore dynamic spacing from the network visualization library. Right now is hardcoded to a given distance. Probably also having the text in 2 lines something like:
```
|-------------------|
|   Artifact name   | 
|  (Artifact type)  |
|-------------------|
```

**Comment by antgonza** [comment]
Turns out this is already solved by hovering on top of the file it shows the full name but it take a while to actually show. Perhaps showing the tooltip right away is the way to go.
