### ISSUE TITLE
Don't show SQL command in error for GUI

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1817]
When there is an error in SQL we are showing the full SQL command and the error, we should keep log in the full thing in the db so admins have access but we should only show the error in the GUI.

**Comment by josenavas** [comment]
Agree on not showing the error - however, I think we really need to improve the checks in the metadata information files before executing the SQL commands - otherwise users will not be able to correct their files.

**Comment by antgonza** [comment]
This is still required and a nice to have so moving to priority-medium and Alpha 0.4.
