### ISSUE TITLE
Add recommendation for finding NCBI 'taxon_id'

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#1820]
The Sample Info File needs a NCBI `taxon_id` for EBI submission. Where is a good way to find that?
https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html 

In my case, I'm looking for the right taxonomy for a microbial mat metagenome. These [past studies](https://www.ncbi.nlm.nih.gov/bioproject/?term=microbial+mat+hot+lake) have previously characterized same environment and link to [this tax ID](https://www.ncbi.nlm.nih.gov/taxonomy/527640). Does that look right? Is there a better way to verify this?

**Comment by antgonza** [comment]
What about http://www.ebi.ac.uk/ols/beta/index?

**Comment by cuttlefishh** [comment]
This is the link: http://www.ncbi.nlm.nih.gov/taxonomy

**Comment by cuttlefishh** [comment]
I would provide the link next to both `taxon_id` and `scientific_name`. I would also place those two together (move `description` up one).

**Comment by colinbrislawn** [comment]
Nice. I can submit a PR for this later this week.

**Comment by antgonza** [comment]
Fixed on: https://github.com/biocore/qiita/pull/1879
