### ISSUE TITLE
Query regarding BIOM file bulk download and 16s sequence information download

### ISSUE THREAD

**Issue by prakruthikr** [biocore/qiita#1830]
Hi Team,
1. We are currently working on downloading BIOM files from QIITA? we want to download BIOM files of all studies at once? Is there a way to do it? This BIOM file will be very helpful for our taxonomic studies.
2. Also, I want to know if there are 16s sequence information available for all studies? If yes, pl let me know the steps to download it? Again all studies at once is it possible?
Please can you email me details to krprakruthi@gmail.com
Thanks,
Prakruthi K R

**Comment by prakruthikr** [comment]
Hi, can anyone please update me on my above query? Pl guide me the steps to download the BIOM file (with all at once - thro create analysis).
Also, pl let me know whether we can retrieve the 16s raw seq data from this site or from BIOM files? how to download them?
This has become very critical for our microbial research project. Any response or help will be greatly appreciated.

thanks,
prakuthi

**Comment by antgonza** [comment]
1. You can only download one by one within each of the studies or create an analysis with the studies you want, do not rarefy and download the merged table/qiime-mapping-file. Note that this will take some time and will download a really large file with all the studies, then you will need to split.
2. Again, only one by one, no possibility of downloading via analysis.

Finally, I'm closing this issue as it's a specific point of https://github.com/biocore/qiita/issues/1251.
