### ISSUE TITLE
support fasta.gz and fna.gz files

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#1838]
...or provide documentation as to why data in these types of files are probably not a good fit for qiita, and why another type of file should be used.

**Comment by josenavas** [comment]
@antgonza this should be just a simple change in the uploader, correct?

**Comment by antgonza** [comment]
Yes, but we currently don't have a processing pipeline for these so not sure how helpful that will be.

**Comment by colinbrislawn** [comment]
I was considering using the Preperation type 'Demultiplexed and QC sequences' but uploading a unzipped 'preprocessed fasta' file was unappetizing.

**Comment by colinbrislawn** [comment]
Maybe I'm misunderstanding data type intended for 'Demultiplexed - Demultiplexed and QC sequeneces' [sic]. I assumed that the output of `split_libraries*py` would be the input to this data type.  

![screen shot 2016-05-23 at 2 27 02 pm](https://cloud.githubusercontent.com/assets/10355152/15485237/0a4dd630-20f3-11e6-97ea-7e398bd2b4bb.png)


What's the intended input for 'Demultiplexed and QC sequences'?

**Comment by antgonza** [comment]
Yes, we prefer the demux to happen in Qiita, way cleaner. And, we expect the output of split_libraries_fastq.py as it has a parameter (--store_demultiplexed_fastq) to store the fastq.

**Comment by colinbrislawn** [comment]
I understand. For this data set in my screenshot, would it be appropriate to upload these `seqs*` files directly into the 'preprocessed fastq' and 'preprocessed fasta' file slots?

**Comment by colinbrislawn** [comment]
Is this as simple as adding it to [the list of accepted extensions](https://github.com/biocore/qiita/blob/master/qiita_core/support_files/config_test.cfg#L40), or would unzipping need to be encorperated to downstream processing steps?

**Comment by josenavas** [comment]
At this point it will not be enough with adding it to the list of accepted extensions, since the code actually expects them to not be gzipped.

**Comment by adswafford** [comment]
Isn't there an option to add a .fasta/.fna and a .qual file to address this issue?

**Comment by colinbrislawn** [comment]
@adswafford Yes, I think that would solve this specific issue.

I opened this issue, and later #2124 and #2125 and #2126, when I was trying to get a tricky data set onto qiita. I was kind of flailing around and not making much progress. I eventually put this data set in a different location.

With a RESTful API, a good linux cli, and much more flexible demultiplexing, all of these problems would be solved. You could choose to close all of these and focus on the underlying functionalit which would have made this upload possible. I trust your discretion.

Or maybe strange datasets are not in the purview of qiita. That's ok too!

Thank you for supporting qiita. Let me know how I can help.

**Comment by antgonza** [comment]
Hey @colinbrislawn and @adswafford , I'm gonna start working on fixing the issues with uploading per_sample_FASTQ, which should solve #2125 and #2126. However, this one is basically superseded by https://github.com/biocore/qiita/issues/953, thus closing. Thank you both for your input!
