### ISSUE TITLE
hide admin/ebi buttons

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1846]
@twbattaglia (thanks!) reported that he can see as a regular user the submit to EBI buttons, we need to hide. 
![screen shot 2016-05-25 at 2 51 49 pm](https://cloud.githubusercontent.com/assets/2014559/15554179/08d9bf6a-2280-11e6-9166-6bab6422fcb2.png)

**Comment by ackermag** [comment]
Soon.... hide soon.

On Wed, May 25, 2016 at 12:53 PM, Antonio Gonzalez <notifications@github.com
> wrote:

> @twbattaglia <https://github.com/twbattaglia> (thanks!) reported that he
> can see as a regular user the submit to EBI buttons, we need to hide.
> [image: screen shot 2016-05-25 at 2 51 49 pm]
> <https://cloud.githubusercontent.com/assets/2014559/15554179/08d9bf6a-2280-11e6-9166-6bab6422fcb2.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1846>
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
Note that the buttons are there but the functionality is not available to non admins.
