### ISSUE TITLE
Make "16S" link a button-style link

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/qiita#1849]
It would be helpful if the 16S link appeared like a "raised" button (like the ones above) when there was data there. It could have the current "flat" appearance when there's no data.

**Comment by josenavas** [comment]
@cuttlefishh I'm unsure were is the location of this link - can you provide a screenshot? Thanks!

**Comment by cuttlefishh** [comment]
Sure, it's on the left side of the study page. It would be great if the 16S link were a button like the ones above, that would become active when there's data and be flat when not.

**Comment by cuttlefishh** [comment]
Here is a question from a user, who seems to be having the same problem: not realizing that the "16S" link is actually a link to the data. I think having a button design instead of a simple hyperlink will improve this.

    On another matter, could you direct me to where I can download the EMP datasets, since I've visited and logged in to Qiita but I don't see how I can download the datasets, I just see the descriptions.

**Comment by cuttlefishh** [comment]
Cool. Is this live on qiita.ucsd.edu?
