### ISSUE TITLE
Add the study id as a column in the mapping file

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1866]
It will be useful for meta-analysis, in and outside Qiita

**Comment by cuttlefishh** [comment]
Thanks for adding this, Jose!

**Comment by antgonza** [comment]
Hi guys, just to get a bit more info here. Currently when you do a meta-analysis in qiita this is added to the map files on the fly but I'm wondering if we want to add by default to the mapping file? Basically, add to the map file even if not use by meta-analysis.

**Comment by cuttlefishh** [comment]
I think it would be nice to have in the mapping file by default.

**Comment by josenavas** [comment]
The previous decision on this was to add to the sample template.
