### ISSUE TITLE
Qiita only work on Chrome

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1868]
During a workshop we sadly figured out that Qiita only works in Chrome.

**Comment by josenavas** [comment]
which problems did you see? I.e. in which specific pages? I just entered to qiita using Firefox and Safari and I can navigate through the study information.

**Comment by antgonza** [comment]
- Explorer: most things don't work and even the file selectors (add prep/sample info) are not accurate, they literally show a different name.
- Firefox and Safari: I have noticed that some of the warnings/errors of the prep/sample info pages and the messages of samples added to analysis are not being showed. 

BTW as you can imagine I'm not sure if they are using the latest version of these tools or an older version. 

Anyway, we should have a warning or something ...

**Comment by josenavas** [comment]
Ok thanks - we will need to investigate more - thanks for the directions on where to look. Just for reference, we have [this function](https://github.com/biocore/qiita/blob/master/qiita_pet/templates/sitebase.html#L36) that is performing the browser checks, so we probably need to revisit the versions at least.

**Comment by colinbrislawn** [comment]
Older versions of OSX are no longer supported by Chrome. By requiring >= 51, Mac OS X 10.6, 10.7, and 10.8 can no longer use qiita. :-(

👍  for cross browser support. 
>Anyway, we should have a warning or something ...

Yes, or graceful degradation, and not full overlay.

**Comment by antgonza** [comment]
What's the latest Chrome version supported by those old 👴  versions?

Reopening so we solve.

**Comment by colinbrislawn** [comment]
My OSX 10.8.5 mac is running Chrome 47. Looks like [Chrome 50 dropped support for several platforms](http://arstechnica.com/gadgets/2016/04/chrome-50-ends-support-for-windows-xp-os-x-10-6-other-old-versions/).

Either progressive enhancement or graceful degradation using common standards would be _so much better_, although I know it's easier said than done. Thanks for helping out folks with older computers. :older_man:  :computer:

**Comment by antgonza** [comment]
No problem, we will downgrade to 50. Just note that those really old version don't even have security updates and you should think in updating soon ...

**Comment by colinbrislawn** [comment]
>you should think of updating soon.

Agreed.

Also, I think v50 is when support was stopped. Downgrading to >= 49 would be a better fit.

**Comment by antgonza** [comment]
K.
