### ISSUE TITLE
NCBI taxonomy documentation

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/qiita#1869]
Suggest the following changes to https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html#required-fields-for-ebi-submission:

* Place taxon_id and scientific_name together. It's strange that description is between them.
* Provide a link to the NCBI taxonomy site: http://www.ncbi.nlm.nih.gov/taxonomy
* Description for taxon_id: NCBI taxon ID for the sample. Should indicate metagenome being investigated. Examples: 410658 for soil metagenome, 749906 for gut metagenome, 412755 for marine sediment metagenome, 408172 for marine metagenome (seawater), or 449393 for freshwater metagenome. If unspecified use 408169.
* Description for scientific_name: Common name for the provided NCBI taxon ID (must match taxon_id above). Examples: soil metagenome, gut metagenome, marine sediment metagenome, marine metagenome.

**Comment by ackermag** [comment]
Luke
 we have had to change unspecified (blank) to :Taxon_id 256318 and
scientific_name: metagenome.  This is required by EBI and ratified by EBI.
For all blanks I am using:
Env_biome: urban biome
env_feature: research facility
env_material (not env_matter): sterile water
env_package: misc environment
Gail

On Thu, Jun 23, 2016 at 5:39 PM, Luke Thompson <notifications@github.com>
wrote:

> Suggest the following changes to
> https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html#required-fields-for-ebi-submission
> :
>
>    - Place taxon_id and scientific_name together. It's strange that
>    description is between them.
>    - Provide a link to the NCBI taxonomy site:
>    http://www.ncbi.nlm.nih.gov/taxonomy
>    - Description for taxon_id: NCBI taxon ID for the sample. Should
>    indicate metagenome being investigated. Examples: 410658 for soil
>    metagenome, 749906 for gut metagenome, 412755 for marine sediment
>    metagenome, 408172 for marine metagenome (seawater), or 449393 for
>    freshwater metagenome. If unspecified use 408169.
>    - Description for scientific_name: Common name for the provided NCBI
>    taxon ID (must match taxon_id above). Examples: soil metagenome, gut
>    metagenome, marine sediment metagenome, marine metagenome.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/qiita/issues/1869>, or mute the thread
> <https://github.com/notifications/unsubscribe/AB69gNd5rpcuk9NgdMV17U4pKHyCarExks5qOydagaJpZM4I9Xj_>
> .
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
Thanks @cuttlefishh and @ackermag, I think this info is important and should be in the documentation.

**Comment by cuttlefishh** [comment]
Thanks Gail. The blank requirements for taxon_id and scientific_name can go in those descriptions. The blank requirements for env fields can go in those descriptions. I can make these changes and issue a PR. Can someone point me to the website code?
