### ISSUE TITLE
Do not transfer the entire template as an argument

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1873]
In the test API, this template is passed as an argument. This is ok for testing purposes, but it is not for a real system. See discussion [here](https://github.com/biocore/qiita/pull/1872/files/7df405dba9289a31cc81fa268a415afa5c2b6e34#r69017973).

**Comment by antgonza** [comment]
@josenavas, can we close this?

**Comment by josenavas** [comment]
Yes! Sorry - forgot to close when I took a look at this.
