### ISSUE TITLE
Instructions for installing Qiita not working properly

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1875]
When trying to install Qiita using the current instructions this is what I'm receiving:
```
conda create --yes --name qiita python=2.7 pip nose flake8 pyzmq networkx pyparsing natsort mock future libgfortran seaborn 'pandas>=0.18' 'matplotlib>=1.1.0' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1' hdf5
Fetching package metadata: ....
Solving package specifications: .
Error:  Package missing in current osx-64 channels: 
  - libgfortran

You can search for this package on anaconda.org with

    anaconda search -t conda libgfortran

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

@HannesHolste do you have any clue?

**Comment by HannesHolste** [comment]
That means the binary for libgfortran, a dependency for one of those conda packages, cannot be found in the default conda channels. Certain OS distros such as osx-64 require additional channels to be specified

Instructions here:
https://github.com/biocore/qiita/blob/master/INSTALL.md#conda

**Comment by josenavas** [comment]
Ok looks like that is missing in our instructions - will you be able to add that?

**Comment by HannesHolste** [comment]
It's in the FAQ / troubleshooting part of the install.md because it only pertains to certain distributions such as osx-64.

Are you suggesting to move it up and make it a part of the regular instructions?

**Comment by josenavas** [comment]
Ok thanks
