### ISSUE TITLE
The warnings in the sample template do not get reseted

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1880]
The warnings are getting appended rather than reset.

**Comment by antgonza** [comment]
It seems like this was a glitch with redis and it's not happening anymore. Thus, closing.

**Comment by ackermag** [comment]
Not true
I fixed Study 894 and even though error is corrected it has not reset.
Gail

On Fri, Jul 8, 2016 at 11:48 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> Closed #1880 <https://github.com/biocore/qiita/issues/1880>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/qiita/issues/1880#event-717381594>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB69gIrsnCqVhFpegkiDyKRQ-90-kSs_ks5qTptsgaJpZM4JGQYp>
> .
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
Just chatted with @ackermag and the current issue is that when you update/fix the current warning, the message doesn't disappear.

**Comment by ackermag** [comment]
I have more information on this error:
It appears that the error is reset after 2 tries.  So if an error is detected on the first reload of updated data it will be retained (not reset) after the upload.  If you then reload and there is a second error, both errors will be retained on sample interface in GUI, even though one has been corrected in the db.  If you then need to correct something else and reload the sample, the first error will be removed but the second will be retained, etc...

SO it seems like there is a plus 1 on the rest.  Let me know if this is confusing.   I can also produce documentation in the form of screenshots.

**Comment by adswafford** [comment]
Added labels to show that this is a persistent and annoying bug.

**Comment by josenavas** [comment]
Fixed in #2247
