### ISSUE TITLE
natsorted fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1894]
We are using natsorted in two lines in our code. [In this instance](https://github.com/biocore/qiita/blob/26bcb12741ed525c69a4fcf43e7cce5c251c4b0d/qiita_pet/handlers/api_proxy/sample_template.py#L286), it will fail with a UnicodeDecodeError if the values have non valid chars.

**Comment by ElDeveloper** [comment]
@antgonza do you know of any characters that can trigger this error, I've been trying to reproduce this in an interactive session without any luck:

I was hoping this would fail or raise an error:

```python
In [1]: from natsort import natsorted

In [3]: natsorted(['Yóshiki', 'Yoshiki']
   ...: )
Out[3]: ['Yoshiki', 'Y\xc3\xb3shiki']
```

Then I tried a simpler example, and judging by the hex values of the characters, it seems like it is getting the order "right".

```python
In [10]: natsorted(['ë', 'é', 'e'])
Out[10]: ['e', '\xc3\xa9', '\xc3\xab']
```

**Comment by antgonza** [comment]
From the logs:
` 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)`

**Comment by josenavas** [comment]
Is it possible that it is a version problem? The current version on the live system is 3.5.1. Which version do you have @ElDeveloper ?

**Comment by ElDeveloper** [comment]
I just changed my installation to 3.5.1 and tried a few things, but
couldn't get it to fail. I even tried a few emojis.

**Comment by antgonza** [comment]
What about the default python encoding of both systems?

**Comment by antgonza** [comment]
Just checked the logs and turns out that the problem is/was study https://qiita.ucsd.edu/study/description/1632 and that the errors in the logs are from: 160527. Thus, decided to recheck/click everywhere in that study and couldn't reproduce the issue ===> Closing.
