### ISSUE TITLE
main site link in the main site is broken

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1897]
It takes you to a page that doesn't exist.

**Comment by antgonza** [comment]
Also, it will be good to add a message explaining that you need to be logged in to see the data.

**Comment by ackermag** [comment]
Is this the error message that directs you to the main page?

**Comment by antgonza** [comment]
The link below is the one that is broken: ![screen shot 2016-07-14 at 1 57 50 pm](https://cloud.githubusercontent.com/assets/2014559/16853758/06376ce0-49cb-11e6-9449-4df8bf1131a0.png)
