### ISSUE TITLE
Ignore warnings on QIIME map generation

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1907]
Some of the warnings raised during the QIIME map file generation are misleading because they do not apply to all studies.

**Comment by antgonza** [comment]
@josenavas, I think this is the same than: https://github.com/biocore/qiita/issues/2090, @2090 has more info, right? Should we close?

**Comment by antgonza** [comment]
This is no longer an issue as we don't generate a QIIME mapping file.
