### ISSUE TITLE
field with new line breaks preprocessing

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1913]
if we have a column with a new line in this format:

```
"This is my line.
"
```

preprocessing (split libraries) fails.

**Comment by josenavas** [comment]
How did that made it into the DB? I'm concerned because if a column has a new line, that is creating a new row, so I'm unsure on how the parsers worked with that case.

**Comment by antgonza** [comment]
The quotes do the trick!

**Comment by josenavas** [comment]
interesting...

**Comment by antgonza** [comment]
Just found a new one on this point: lines with `\t` break the analysis.

**Comment by antgonza** [comment]
The easiest solution for this issue is to simply remove all `\t` and `\n` from all values in the tables and remove them when adding the info files, what do you guys think?

**Comment by josenavas** [comment]
Agree on removing those plus adding a warning letting the user know that we remove those.
