### ISSUE TITLE
remove duplicated code from plugins

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1919]
Currently due to the structure of the plugins, they tend to duplicate a lot of code. @josenavas has some ideas of how to solve this issue.

**Comment by antgonza** [comment]
@josenavas, can we close this issue? If not, could you add which blocks of code still need to be refactor? Thanks!

**Comment by josenavas** [comment]
I think with the latest changes that I made on the qiita_client and plugin class this has been fixed! Sorry forgot to point to this issue.
