### ISSUE TITLE
interface bugs and fine tuning

### ISSUE THREAD

**Issue by qiyunzhu** [biocore/qiita#1920]
Dear all, I have played around with Qiita, and spotted the following things, that can be improved, to my point of view. Please see in-picture comments:
![screen shot 2016-09-06 at 12 02 33 pm](https://cloud.githubusercontent.com/assets/4396343/18289934/5b5d979a-7436-11e6-9715-a5b897d4ada1.png)
(Please ignore the "16S rRNA" comment...)

The heading styles look awkward: h1 is too large, h3 is too small. I think the master CSS table could be revised.
![screen shot 2016-09-06 at 1 29 05 pm](https://cloud.githubusercontent.com/assets/4396343/18290025/a8627dda-7436-11e6-884d-08f9f252dea1.png)

Some font families are inconsistent. I think san-serif fonts (like Arial) may be used instead of serif fonts (like Times)
![screen shot 2016-09-06 at 11 23 40 am](https://cloud.githubusercontent.com/assets/4396343/18289992/891656c2-7436-11e6-9ac3-04a8a6f35c6b.png)
![screen shot 2016-09-06 at 12 03 45 pm](https://cloud.githubusercontent.com/assets/4396343/18289998/8c736bd4-7436-11e6-8e3f-1615e6b21d0f.png)

Finally, the link to the documentation on the front page is broken:
![screen shot 2016-09-06 at 12 08 14 pm](https://cloud.githubusercontent.com/assets/4396343/18290044/c90d7f44-7436-11e6-99ae-48b6d757ca34.png)
In the URL, the quotes should be taken off.

**Comment by josenavas** [comment]
Thanks for reporting @qiyunzhu!!!

Most of those screenshots belong to the analysis pipeline, which we are going to rewrite soon. I will not bother right now on fixing those, but we will instead fix once we are rewriting that part. I am planning on starting soon on rewriting that part, so we should meet and, while I'm changing the backend to make it work with the new infrastructure, you can be working on improving the interface, so everything is consistent and faster. Does it make sense? We can meet later this week to discuss this and start getting this done pretty fast!

**Comment by qiyunzhu** [comment]
Hi @josenavas , Got it! Sounds a great plan! Let's meet and discuss it!

**Comment by antgonza** [comment]
@josenavas and @qiyunzhu, can we close this?

**Comment by antgonza** [comment]
I _think_ all issues here have been solved. @qiyunzhu, if you have specific comments please open an issue for each of them.
