### ISSUE TITLE
Clarify license of data set uploaded to qiita

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#1928]
When someone uploads their data set to Qiita, what is the license on that data set?

[Github encourages licenses on repos](https://help.github.com/articles/open-source-licensing/) to decrease ambiguity about terms of (re)use.
[Zenodo requires users to select one of the 'Creative Commons Attribution-*` licenses](https://zenodo.org/deposit/new), but only if the data set is going to be made public.

So what's up with the data sets on Qiita?

Edit: So the SRA is run by INSDC, and looks like INSDC data may be public-domain:
From the SRA paper [10.1093/nar/gkq1019](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3013647/): 

> The mission of INSDC is to preserve _public-domain_ sequencing data ...

From the [INSDC Policy page](http://www.insdc.org/policy.html):

> The INSD will not attach statements to records that restrict access to the data, limit the use of the information in these records, or prohibit certain types of publications based on these records. Specifically, _no use restrictions or licensing requirements_ will be included in any sequence data records, and no restrictions or licensing fees will be placed on the redistribution or use of the database by any party. 

Emphasis mine.

**Comment by antgonza** [comment]
Good question and extremely timely as we were having an internal discussion to add Liability information to the website. Our plan is to follow what EBI-ENA does, at the end of the day, that's the final repository. Anyway, here's EBI-ENA's take on your question: http://www.ebi.ac.uk/ena/standards-and-policies. 

Just out of curiosity, what's the source of your question?

**Comment by colinbrislawn** [comment]
> what's the source of your question?
 
I wanted to mirror some data to Zenodo, and they force users to select a license if they want to make the data public. Given that Qiita does _not_ force users to do this, I wanted to check on the policy. 

>http://www.ebi.ac.uk/ena/standards-and-policies.

Yep, that's the same one I found and quoted. Essentially this is a public domain license, or a [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/). Does that sound right?

**Comment by antgonza** [comment]
I think so but note that we plan to have an official response soon (we are checking with different venues to be 100% sure).

**Comment by colinbrislawn** [comment]
Those Terms of Use are well written. Thank you for this clarification.
