### ISSUE TITLE
qiita_pet in setup.py package_data is wrong

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1984]
While doing a clean install via: `pip install -e .` @josenavas found that the package_data description of qiita_pet is wrong (it's not copying all the files), see [here](https://github.com/biocore/qiita/blob/master/setup.py#L78). I think we can implement something like this: http://stackoverflow.com/a/22260596

**Comment by antgonza** [comment]
@josenavas, could you confirm if this is still an issue?

**Comment by josenavas** [comment]
I've done a couple of clean installs and I have not hit this issue again.
