### ISSUE TITLE
Improve artifact/processing graphs

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1986]
Things to do:
- [x] They should be the same graph, rather that two different types. (Ideally we create a class)
- [x] Interaction with the graph is activated when you click on the graph, so it doesn't mess with the scrolling.

**Comment by adswafford** [comment]
That would address the scrolling issue that I know @ackermag has run into a lot right?

**Comment by antgonza** [comment]
This should be solved before: https://github.com/biocore/qiita/issues/2185

**Comment by josenavas** [comment]
This has been fixed in dev
