### ISSUE TITLE
Search-by fields

### ISSUE THREAD

**Issue by jwdebelius** [biocore/qiita#199]
If I'm looking for a study I see the following as possible things to search by:
- Metadata (i.e. return all human samples with purple polka dot syndrome)
- Published paper (i.e PMID)
- PI overseeing project (i.e. Knight)
- Study ID # as published previously
- Study title

I'm making these suggestions assuming three main reasons for using the database: meta-analysis of a specific set of data, doing a new analysis of a dataset that's been recently sequenced, or reviewing what's been done on published data.

**Comment by antgonza** [comment]
this has been superseded by the redbiom interface and should be available in the next release (the code has been merged)
