### ISSUE TITLE
rethink the artifact display in the study admin

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1996]
Currently each artifact has it's own ellipsoid, which works great when we thought that all plugins/processing only created one artifact. Now, we know that plugins/processes can create multiple ones, which makes it confusing. 

Perhaps an easy solution is to simply create an ellipsoid for each processing job and list the created artifacts in the summary of that job.

**Comment by josenavas** [comment]
What do you think about the display in the processing pipeline? I think that should be good, cause you have the job that generated it. Does it make sense?

**Comment by antgonza** [comment]
I think so but not sure we need to display the job and the artifacts, perhaps just the job and display the artifacts in the summary. Let's discuss tomorrow.

**Comment by josenavas** [comment]
You need to display the artifacts so you can actually (1) process from that artifact and (2) show the summary of that artifact

**Comment by antgonza** [comment]
Group resolution: go with @josenavas idea. @tanaes suggest toggling processes/artifacts.

**Comment by josenavas** [comment]
Linking to https://github.com/biocore/qiita/issues/1986
