### ISSUE TITLE
Support for storing images and 3D models

### ISSUE THREAD

**Issue by mortonjt** [biocore/qiita#1997]
In few studies in qiita, there are 3D models and pictures that allow for vizualization in ili.  While the coordinates can be stored in qiita, the images cannot be atm.

It would be nice if the STL files or images could stored in qiita.  But should this be done?

**Comment by josenavas** [comment]
I think the best solution here is to add ili as a plugin once the analysis part is moved to plugins. Then this objects will just be a type of artifact that ili needs to be able to run.

**Comment by antgonza** [comment]
I think adding the possibility of adding "random" files to the study, something like attachments, will be useful. However, I would like to set some ground rules for those attachments but at the same time be open to add/link whatever. Something that comes to mind is simply limit to 4M the max size of the attachment. Note that this will mean that we will get rid of the extension check in the uploader ...

**Comment by adswafford** [comment]
Is there an Ili plugin page this can be added to?

**Comment by antgonza** [comment]
Closing in favor of: https://github.com/biocore/qiita/issues/2215
