### ISSUE TITLE
Color code outputs after processing

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2003]
Generation of demux and biom artefacts in the GUI should be color-coded to output e.g. deblur, sortme rna

**Comment by ackermag** [comment]
Perhaps label according to output

**Comment by josenavas** [comment]
I think color coding will make the page look like a Christmas tree, specially as the number of possible commands to execute grow. However we can set some kind of tag that would help the user to distinguish them.

**Comment by antgonza** [comment]
@josenavas good point and perhaps a feature that we can have ready and activate only during the Christmas holidays.

**Comment by ackermag** [comment]
We could label appropriately : default 90bp-demux, default 100bp-demux, default 150bp-demux so it is obvious without reading the text "Processing parameters: input_data: 204 length: 100" etc.  I think a user will find that more intuitive rsther than clicking through all options to see which is which.

**Comment by josenavas** [comment]
Agree - @antgonza I think this was an oversight on my end. I can easily change a bit the logic to use the job's output name to name the new artifact. If we agree with this solution, I will try to get the fix in sometime tomorrow.

**Comment by antgonza** [comment]
That will be great!!! More if it includes a patch for all current artifacts.

**Comment by josenavas** [comment]
hahaha what do I get extra if patch them? 🍻 ?

I will patch all current artifacts as long as the name is "dflt_name", otherwise it means that the user changed the name and I don't want to mess with it 😄

**Comment by antgonza** [comment]
Agree, 🍻 . How will the admin define the default name ?

**Comment by josenavas** [comment]
Sorry, I don't think I understand your question?

**Comment by antgonza** [comment]
@josenavas and I discussed offline. The question was related on how to define the name given to the new artifacts. We said that ideally it will be the name of the output + the name of the parameter set because plugins can have 1 to many outputs, and 1 to many parameter sets.

**Comment by adswafford** [comment]
Fix 2190 #2292 took care of some of the naming part, but we're still missing the trim length, etc. 

I think the color idea was shot down, but I'm flagging for group input as I think it would be helpful and I wasn't around in Nov yet to discuss :-) 

Back in the day @tanaes and I had a convo about humans being good at color recognition instead of black on white text in the context of an entirely different piece of software.

**Comment by antgonza** [comment]
This was solved in the last release, for example (new one has the trim length in the name):
![screen shot 2018-01-11 at 11 03 07 am](https://user-images.githubusercontent.com/2014559/34839619-7d9ad356-f6bf-11e7-9be1-8a9313b9157f.png)
