### ISSUE TITLE
ENA icon is applied to all processed preps not just EBI submitted

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2008]
This: 

[Untitled 3.pdf](https://github.com/biocore/qiita/files/625722/Untitled.3.pdf)

 PREP 73 NAME - ID 73 - public 
FASTQ - ID 2133
dflt_name - Demultiplexed
meant it had been submitted to EBI

Instead it seems to be there whether submitted or not. e.g. study 755 has not been submitted :
 PREP 81 NAME - ID 81 - public 
FASTQ - ID 2149
dflt_name - Demultiplexed
Is there a meaning to that icon - like ready to be submitted or is it just there to indicate which was submitted or can be submitted?

**Comment by antgonza** [comment]
This was solved here: https://github.com/biocore/qiita/pull/2001 but not deployed.
