### ISSUE TITLE
Installation issue: qiita-files not found

### ISSUE THREAD

**Issue by mdehollander** [biocore/qiita#2011]
I run into installation errors when following the instructions in INSTALL.md. 
I get this error:
`Collecting qiita-files (from qiita-spots==0.2.0.dev0)
  Could not find a version that satisfies the requirement qiita-files (from qiita-spots==0.2.0.dev0) (from versions: )
No matching distribution found for qiita-files (from qiita-spots==0.2.0.dev0)`

Looking at the pypi website I also don't see any package called qiita-files. Is this package renamed?

Am I correct that the qiita-files became a spots plugin? https://github.com/qiita-spots/qiita-files @josenavas ?

**Comment by josenavas** [comment]
@mdehollander qiita-files is still not in pypi. When running pip in qiita, add the flag `--process-dependency-links` and it will install it from github. It's kind of annoying that pip no longer supports the dependency links by default...

**Comment by mdehollander** [comment]
Great. That worked like a charm. I made a PR so that it as well in the docs.

**Comment by josenavas** [comment]
Thanks @mdehollander !!!!!
