### ISSUE TITLE
add users groups

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2017]
This will allow us to add specific functionality for certain groups. First example (use case): add a knight lab group so they can send the sample info file to the wet lab.

**Comment by antgonza** [comment]
@josenavas, this issue was open with the idea of solving what we are doing with the platemapper, do we still need this? I think we can close but rather ask ...

**Comment by josenavas** [comment]
if that was the only goal of user groups then yes we can close this

**Comment by antgonza** [comment]
that's the only thing that we had as a use example, closing.
