### ISSUE TITLE
Development version of moi is needed

### ISSUE THREAD

**Issue by mdehollander** [biocore/qiita#2019]
Although mentioned in INSTALL.md to install the dev version of moi, after running pip with setup.py moi-0.2.0 is installed. With that version there are version conflicts for the future package together with the biom-format package. If I reinstall moi-0.2.0.dev0 after `pip install -e .` the correct version is there. Maybe change those two lines in INSTALL.md: https://github.com/biocore/qiita/pull/2018

**Comment by antgonza** [comment]
Closed in: https://github.com/biocore/qiita/pull/2018
