### ISSUE TITLE
Allow multiple prep templates per study

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#203]
Potentially adding a new table and changing the dynamic table names from `sample_<STUDY_ID>` to `sample_<STUDY_ID>_<SAMPLE_TEMPLATE_ID>`

**Comment by ElDeveloper** [comment]
@ackeramang do you need access to old prep and sample templates? I think you store these in SVN, so allowing that from Qiita would be redundant, can you confirm?

**Comment by ElDeveloper** [comment]
@ackermag do you need access to old prep and sample templates? I think you store these in SVN, so allowing that from Qiita would be redundant, can you confirm?
