### ISSUE TITLE
Unable to differentiate between the artifact and non-artifact deblur tables

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#2043]
@antgonza kindly provided code to interrogate the qiita API to retrieve the deblur artifacts. From discussion, it appears there isn't a direct means to differentiate the `final.biom` table and the `final.only-16s.biom` table short of inferring from the filepath. This issue differentiating is also an issue at the meta-analysis level.

**Comment by antgonza** [comment]
This was solved as part of the new listing features, see below
![screen shot 2017-08-01 at 9 47 56 am](https://user-images.githubusercontent.com/2014559/28834152-c017ee2c-769e-11e7-8e3d-a3cfd6b64e93.png)
