### ISSUE TITLE
Initial QIITA REST api 

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#2089]
The following functionality should be enabled through a REST API (sorted by priority):

- [x] Fetch out all samples from study
- [x] Create a study - Some extra endpoints needed to accomplish this:
    - [x] Create StudyPerson
    - [x] Query current StudyPersons
    - [ ] Query the controlled vocabulary for environmental packages
- [x] Fetch specific metadata from list of samples (Edge case: can # be represented in pandas?)
- [x] Metadata status
- [x] Create the prep information
- [x] Create the raw data on the created prep information

At this point we will assume that this endpoints are only reachable by admins on the system

**Comment by antgonza** [comment]
@wasade and @ElDeveloper, with your previous and latests PR, which of these points have/are solved?

**Comment by ElDeveloper** [comment]
@antgonza, I just updated the list. 👍 I think we are not going to address "query the controlled vocabulary", as this falls into the type of things that can be modified from Qiita itself.

**Comment by antgonza** [comment]
Looks like this can be closed based on the list and the comments; please reopen otherwise.
