### ISSUE TITLE
prep information: BarcodeSequence, LinkerPrimer inconsistency

### ISSUE THREAD

**Issue by tkosciol** [biocore/qiita#2090]
When I upload a prep template, Qiita incorrectly returns a warning:
```
Some columns required to generate a QIIME-compliant mapping file are not present in the template. A placeholder value (XXQIITAXX) has been used to populate these columns. Missing columns: BarcodeSequence, LinkerPrimerSequence
Some functionality will be disabled due to missing columns:
Demultiplexing with multiple input files disabled.: barcode, primer, run_prefix;
Demultiplexing disabled.: barcode, primer;
EBI submission disabled: center_name, experiment_design_description, instrument_model, library_construction_protocol, platform, primer.
See the Templates tutorial for a description of these fields.
There are no differences between the data stored in the DB and the new data provided
```
in fact, it expects `barcode` and `primer` columns. So either it should read different columns, or change the warning message to:
```
(...) Missing columns: Barcode, Primer
Some functionality (...)
```
[reference Qiita study; ID 2574](https://qiita.ucsd.edu/study/description/10424#)

**Comment by antgonza** [comment]
I think this issue is the combination of other two, in specific: https://github.com/biocore/qiita/issues/1907 and https://github.com/biocore/qiita/issues/2628; the latter has been fixed and the former is still open. Closing; please open another issue with what's missing from #1907.
