### ISSUE TITLE
Feature request: visual feedback on download status

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2109]
File Upload page should provide visual feedback as to whether uploading is in progress or paused.

<img width="333" alt="screen shot 2017-04-19 at 8 05 43 am" src="https://cloud.githubusercontent.com/assets/27017606/25187154/0f940d1a-24d7-11e7-9cf5-618f04e0dbe1.png">

**Comment by antgonza** [comment]
great suggestion, thanks!
