### ISSUE TITLE
Make results viewing interface stateful

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#211]
Currently, if I view beta diversity results (and select certain options in emperor), then view my alpha rarefaction plots, then go back to my beta diversity results, it relaunches emperor, and I lose the settings I have selected.  It would be really cool if it could retain the state when switching between viewing these different sets of results.

**Comment by antgonza** [comment]
This feature relies on Emperor being able to do this, once this https://github.com/biocore/emperor/issues/3 is closed we can add here.

**Comment by ElDeveloper** [comment]
That issue wouldn't necessarily fix this problem. The reason why this is
happening in Qiita is because iFrames are created and destroyed every time
a visualization is clicked. The frames should instead be hidden and not
recreated.

**Comment by antgonza** [comment]
Closing this in favor of: https://github.com/biocore/qiita/issues/1389
