### ISSUE TITLE
Change the tag list on the study page list to be a multiple select2 dropdown

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#2114]
As seen below, the list is growing, which can be annoying once we get more tags. Using something like a [multiple selec2 dropdown]( https://select2.github.io/examples.html#select-boxes-with-labels
) can be useful. I'm unsure if this can be done directly on tag-it. 

![screen shot 2017-04-20 at 11 02 56 am](https://cloud.githubusercontent.com/assets/2501478/25245363/00cad8c6-25b9-11e7-9c5f-7a875d4c68c2.png)

**Comment by antgonza** [comment]
closed via: https://github.com/biocore/qiita/pull/2183
