### ISSUE TITLE
improve error message for prep_template errors

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#2124]
When uploading per_sample_FASTQ files, I was unable to save my results because the number of samples in my prep template did not match the number of files I had uploaded. However, there was no error message that told me what this problem was, or how to fix it.

When there is an error with prep inputs, provide a error message and a recommendation.

**Comment by antgonza** [comment]
I'm not sure what the solution for this will be or if the current PRs will fix them. @colinbrislawn, what do you think?

**Comment by colinbrislawn** [comment]
I think the other issues are off to a good start. More of those helpful error messages are great!

**Comment by antgonza** [comment]
thanks!
