### ISSUE TITLE
Error: Unicode unequal comparison...

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/qiita#2125]
I receive the following error on prep 3050 of [study 11114](https://qiita.ucsd.edu/study/description/11114#) 

`Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal`

This is the prep-info file that caused this error.
[qiita_prep_info_16s.txt](https://github.com/biocore/qiita/files/969010/qiita_prep_info_16s.txt)

Edit: Also, about half of the samples were matched to `run_prefix` and placed in the right columns, but the second half of samples were not. IDK if this is related to the unicode error, or different.

Edit: In the interface, some samples are listed twice; once in the 'Available Files', then again in the other columns. I still don't know if this is related.

**Comment by colinbrislawn** [comment]
Perhaps this happens when a a single `run_prefixes` matches similar samples.

This fails with a `run_prefix` of `T11`:
![screen shot 2017-05-05 at 11 38 28 am](https://cloud.githubusercontent.com/assets/10355152/25763072/51d874ec-3196-11e7-9255-c6267924598c.png)


This works with a `run_prefix` of `T11R` (now it's unique!):
![screen shot 2017-05-05 at 1 25 16 pm](https://cloud.githubusercontent.com/assets/10355152/25763077/56bdf298-3196-11e7-9a39-ebbe18295d5f.png)
![screen shot 2017-05-05 at 1 26 11 pm](https://cloud.githubusercontent.com/assets/10355152/25763122/71271060-3196-11e7-9b54-6e598f1b7f33.png)


If this issue has already been identified, feel free to close this issue.

**Comment by antgonza** [comment]
fixed in https://github.com/biocore/qiita/pull/2366
