### ISSUE TITLE
Using run_prefix with .sff is not supported

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2128]
454 run files have numerical suffixes added eg: G8VUN4101.sff, G8VUN4102.sff.  Run_prefix with LS454 platform should allow for use of the run_prefix value 'G8VUN41' for both files where there are no duplicated BARCODES.  System does not allow for this currently.  
Returns an error (study ID:1522):
Can't submit private task 'complete job:
Std output:
Std error:/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `qiita-private-launcher-qsub 'workon qiita' complete_job 0156ef86-06a8-4f0b-aeb9-8db5352f410a '{"artifacts": null, "success": false, "error": "Error creating artifact. Offending files:\nraw_sff: The number of provided files (22) doesn't match the number of run prefix values in the prep info (11): G8VUN4101.sff, G8VUN4102.sff, HKNXA0F02.sff, G9JO88H01.sff, HKAYD4H02.sff, G9JO88H02.sff, HKNXA0F01.sff, HEHQ1P302.sff, HKAYD4H01.sff, GG7DRJZ01.sff, GG7DRJZ02.sff, HEHQ1P301.sff, GI9GO2V01.sff, GI9GO2V02.sff, H7AT18E02.sff, GQ99BWZ01.sff, GQ99BWZ02.sff, H2CWED301.sff, H7AT18E01.sff, H2CWED302.sff, H68ZCFF02.sff, H68ZCFF01.sff`

**Comment by antgonza** [comment]
Just to also clearly have it here. This error is solved via: https://github.com/qiita-spots/qtp-target-gene/pull/22

**Comment by antgonza** [comment]
This was solved via: https://github.com/qiita-spots/qtp-target-gene/pull/22
