### ISSUE TITLE
Unique URLs for specific pages

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#213]
Once the demo/guest account is added, we need to make sure that they can't actually do anything once logged in other than view things.

**Comment by antgonza** [comment]
I think read only should exist in the system, is there a use for this?

**Comment by squirrelo** [comment]
Analyses that are public is my first thought. Those should be direct links given though, and would possibly require making an authenticated and non-authenticated results page.

**Comment by antgonza** [comment]
Agree. Note that I forgot a not in my last message, it should be `I think read only should NOT exist in the system,`

**Comment by squirrelo** [comment]
That does change the meaning then, yes. Also, read only effectively does exist in the system already as the "public" status currently.

**Comment by antgonza** [comment]
The more I think about this, the more I feel like we don't need guest accounts. What do you guys think? Note that the demo user is in the main deploy and if we agree I can delete it (checked and it seems that nothing is linked to this account) to close this issue.

**Comment by rob-knight** [comment]
We need it for reviewers.

**Comment by josenavas** [comment]
I think the demo user should be removed from the main deploy - it can be a mess if multiple users use it as its account.

In order to provide access to reviewers, the demo account doesn't work because it doesn't have access to those studies. I think we can create special accounts that expire in some time and have only access to reviewed studies/analysis. Does it makes sense?

**Comment by antgonza** [comment]
I don't think guest accounts are the solution for this. As far as I can understand it a guest account is basically an account that have limited privileges in the system. What we need is to be able to create "difficult" links to studies and analysis.

**Comment by josenavas** [comment]
IMO, "difficult" link is not the way to go, as anybody with the link can access to that data publicly - which shouldn't be.

Guest accounts - as you defined, an account that have limited privileges in the system is what will make more sense here. It will be an account that cannot do anything - just check the information on those studies/analysis that we provide access (the ones to be reviewed)

**Comment by rob-knight** [comment]
OK. The motivation for those is for people to try out the system without signing up, which is a substantial barrier for many people (whether you believe this or not, it’s definitely true).

**Comment by antgonza** [comment]
Consensus is to have create single links for pages that we want to share:
- [ ] analysis
- [ ] study main pages
- [ ] ... add others ...?
