### ISSUE TITLE
Provide .md5 checksum of files of dynamic nginx zip files

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#2133]
A user requested this over the help email account so that they could verify the integrity of their large file download.

**Comment by antgonza** [comment]
This is an interesting question because for biom/fna, raw files, etc. is an on the fly download ... so not sure how this will happen ... any ideas?

**Comment by wasade** [comment]
We compute once and store on the file system in proximity to the files being downloaded? On the fly is quite expensive

**Comment by antgonza** [comment]
It's quite cheap to generate as nginx takes care of everything. Let's discuss during a future Qiita dev-meeting.

**Comment by antgonza** [comment]
Let's check if nginx has something for this, cause if not ... 😢

**Comment by antgonza** [comment]
Just realized that this is a duplicate of https://github.com/biocore/qiita/issues/2920; closing this one as the other one has an explanation of how it currently works.
