### ISSUE TITLE
Upload raw files but dissappear when I try to process 16S data

### ISSUE THREAD

**Issue by rimanasra** [biocore/qiita#2137]
I uploaded my raw files (R1, R2, index file) on qiita but when I try to process the data (I click on Data types --> 16S --> In the prep info dialogue, there is a dropdown menu below the words No files attached to this preparation, labeled “Select type”. I select Fastq-none, but I don't see my raw files anywhere, so I can't drag or drop them. 
What do you think is the issue? 
![capture](https://cloud.githubusercontent.com/assets/28489284/26508130/74187f66-4221-11e7-860f-186a296c45f0.JPG)

**Comment by josenavas** [comment]
Hi @rimanasra 

It looks like the issue has been solved, as I can see the files attached to your prep info, so I will close the issue. If you have any further questions, please don't hesitate to contact us at qiita.help@gmail.com !

**Comment by rimanasra** [comment]
Hi Jose,

just to let you know. I wasn't able to upload the raw files, so what I
managed to do was upload them directly from a different study as there was
this option.

Thank you,
Rima
