### ISSUE TITLE
Order beta metrics

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2153]
Hi Qiita team.
I was confused for a moment that the same type of analysis for the same sequence files gave different PcoA plots. I than realized that I hit the wrong metric, because their ordering seems to be random. You might want to change this.
![screenshot from 2017-06-23 08 40 10](https://user-images.githubusercontent.com/11960616/27489609-f72ebfda-57ef-11e7-9c2b-9c3c95d39574.png)

**Comment by antgonza** [comment]
This has been superseded by the current/new analysis
