### ISSUE TITLE
"connection already closed" error when deleting artefact

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2162]
Error seems to be related to iPython workers.  Restarting iPython workers will solve the problem but not sure why it happens.  Will prevent all further work on study

**Comment by ackermag** [comment]
Screenshot attached
[Untitled copy.pdf](https://github.com/biocore/qiita/files/1129384/Untitled.copy.pdf)

**Comment by antgonza** [comment]
not an issue after moi removal
