### ISSUE TITLE
arrow keys when renaming artifacts

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2172]
When I select a node in the processing graph and hit "edit" to rename the artifact and then use left or right arrow keys the graph moves to left or right instead of the cursor in the textbox.

**Comment by antgonza** [comment]
Yup, saw that too and decided to solved it in my latest pr: https://github.com/biocore/qiita/pull/2170/files#diff-e232a534aae33dc2b00fd637a8d9a9adR176, the solution will be deployed during the weekend.

**Comment by sjanssen2** [comment]
didn't see that, because I was lazy and did not search for related issues / PRs. Do you think it is OK to just raise issues for whatever odd thinks I encounter or should I be more hesitant to float the issue stack?

**Comment by antgonza** [comment]
Adding should be fine. I plan to go over all the issues next week to assess, then do PRs/close ...

**Comment by antgonza** [comment]
This was closed in #2170.
