### ISSUE TITLE
download artifact name

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2174]
If the user put the effort into the processing graph to rename artifacts, those names should be used when downloading them as pre-filled name recommendations in the file selector window.

**Comment by antgonza** [comment]
This is an interesting one because normally one artifact has multiple files, for example a deblur artifact has the (1) html summary, (2) the seqs, and (3) the biom so if we wanted to add this the "best" solution can be to simple prepend those files with the artifact name during download. Will this work?

**Comment by sjanssen2** [comment]
I'd say 
- suggest the default artifact filenames if the user did not rename them
- use only the user chosen name if the artifact has just one file
- combine user chosen name + default artifact filename if the juster did edit the filename and the artifact has several files to chose from
I think this is closest to what the user expects from the system

**Comment by antgonza** [comment]
Thanks. In the past we added a single default name to all artifacts (dflt_name) but since we added https://github.com/biocore/qiita/issues/2190, now it adds a default name based on the processing step that generated the artifact. Thus, perhaps we can simply always prepend ... ?

**Comment by antgonza** [comment]
Perhaps an easier solution (from @josenavas) will be to add a new button to download all files and that the tgz/zip file gets the name of the full artifact, @sjanssen2, what do you think of these ideas?

**Comment by sjanssen2** [comment]
how about prefixing the filename with the artifact ID, thus a user would have an easy proxy for using md5sum to ensure that the file downloaded a year ago stems from the very same artefact in Qiita?
