### ISSUE TITLE
Automatically refresh status of processing/analysis on the display page

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2185]
Users should not have to manually refresh the page to see new artifacts in the processing or analysis networks

**Comment by antgonza** [comment]
Let's keep a list so they are easier to track:
- [ ] Sample info file while deleting columns
- [ ] Sample info file while updating
- [ ] Prep info file while deleting columns
- [ ] Prep info file while updating
- [ ] Deleting analysis, originally reported in #2332
- [ ] ... add others by editing this post ...

**Comment by antgonza** [comment]
This was solved in the previous release.
