### ISSUE TITLE
Add button to hide jobs in list

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2186]
There is no way for users to clear failed (error) jobs, interrupt stalled (running for days without heartbeat or stuck in queue)  jobs.

![image](https://user-images.githubusercontent.com/27017606/28883796-85cf89d4-7764-11e7-9f17-28a18edc8975.png)

**Comment by antgonza** [comment]
We have 2 options here: automatically hide or allow the user to hide. The former has less changes involved, what about automatically hiding all the errors, except that last 5 (or 10)?

**Comment by adswafford** [comment]
Automatically hiding failed jobs is fine to me since there isn't really much user-informative information there.

**Comment by antgonza** [comment]
This is now possible but the hidden button is not shown in the job list. Gonna keep this issue open and rename it to make it clearer.

**Comment by antgonza** [comment]
Closing in favor of: https://github.com/biocore/qiita/issues/2217
