### ISSUE TITLE
Running Qiime2 analyses that aren't appropriate doesn't generate error message

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2187]
Steps to reproduce:
1. Create new analysis from closed ref biom table
2. Select the biom artifact and click Process
3. Select alpha diversity (or beta diversity) from the dropdown
4. Click Add Command
5. The job will run, then fail silently, only appearing in the Jobs section as an error message once the user manually refreshes the page

![image](https://user-images.githubusercontent.com/27017606/28884114-87232e48-7765-11e7-9adc-67f2eed7fbe1.png)

**Comment by adswafford** [comment]
Another example: if you rarefy at a threshold greater than the maximum number of samples (make a typo) and no samples remain the job errors out but only appears under "Jobs using this" not under "Error Jobs". The "Error Jobs" section doesn't appear.

**Comment by adswafford** [comment]
Pinging @antgonza on the issue described in Qiita meeting regarding the Errored job section

**Comment by antgonza** [comment]
I think all this examples have been fixed by the new interfase; thus, closing.
