### ISSUE TITLE
Automatically name artifacts with originating process information instead of dflt_name

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2190]
Can we name artifacts more meaningfully, especially on the processing pipeline?

Example, when debluring data, the two files generated are both named dflt_name, so there is no feedback to the user as to which is the reference hit and which is all sequences unless they click on the artifact and read the available .biom files available. 

Instead we could name them more informatively: "16S_ref_deblur" and "all_seqs_deblur"

For closed ref "16S_closed_ref", rarefied data "rarefied_[#features]". The [#features, could be divided and appended with 'K'"

**Comment by adswafford** [comment]
One idea on this, in addition to more meaningful default renaming, can we provide a parameter in the plugin to let users label the artifact  themselves without having to wait for it to be made and then editing the name?

**Comment by antgonza** [comment]
Closed in https://github.com/biocore/qiita/pull/2292
