### ISSUE TITLE
Problem when processing per-FASTQ files

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#2201]
When I try to process add a prep, I observe a syntax error in a bash script.

```
 Can't submit private task 'complete_job':
Std output:
Std error: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `qiita-private-launcher-qsub 'workon qiita2' complete_job '31fe725b-0ad9-4000-9a1f-5706433a384b' '{"artifacts": null, "success": false, "error": "The number of provided files doesn't match the number of samples (118): 113 raw_forward_seqs, 0 raw_reverse_seqs (optional, 0 is ok)"}''
```

I am currently observing this in study 11282.

**Comment by ElDeveloper** [comment]
Turns out the problem was that some samples had more than one FASTQ file (my mistake), however the error was not clear about that.

**Comment by adswafford** [comment]
I'm going to flag this as a documentation issue and a duplication of #2283

**Comment by antgonza** [comment]
This is closed via: https://github.com/qiita-spots/qp-target-gene/pull/15. Note how each possibility is clearly described by the error message. Closing as this is not part of qiita but the qp-target-gene plugin.
