### ISSUE TITLE
Preps in studies view should show number of samples

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2210]
On the study view page, there should be a column showing the number of samples for each biom so the information and view is consistent with what users see on the analysis view

**Comment by antgonza** [comment]
Not an easy fix. This is an excellent question, there are 2 things that might be confusing here:
1. a prep number of samples
2. a biom number of samples

Displaying 1 is not as terrible as displaying 2. Remember that number of samples in the prep is something we define during processing and internal to the system: "easy to track". However, the number of samples in a biom is something dependent of the processing, like: how many samples didn't yield any seqs after split, how many of those actually recover seqs after deblur or close ref, etc.

So removing the easy fix label and it will be great if you could tell us which of the 2 you will have displayed and exactly where on the GUI

**Comment by adswafford** [comment]
Hmm, I think I needed to describe this issue better, so here are some screenshots:

Here I can see the number of samples:

![image](https://user-images.githubusercontent.com/27017606/29439378-0b6df3f0-8372-11e7-9357-ea0d2181c4a1.png)


But here I cannot:

![image](https://user-images.githubusercontent.com/27017606/29439395-1c4449b8-8372-11e7-8fcc-f8ca7f07a2a0.png)


Since the information is easy to show in the first view, is there something that prevents this same column from being shown in the second view?

**Comment by antgonza** [comment]
Right, so this is what I was trying to describe, that number displayed comes from the prep (which is displayed from a left over from and old version) but is not really accurate when talking about samples in the biom cause it's the samples in the prep. Anyway, if you, if the issue is to add the number of samples in the prep ... we can do that but wanted to be clear about it ...

**Comment by antgonza** [comment]
... perhaps calling the column: "Samples in Preparation Information", will cover both things

**Comment by adswafford** [comment]
Yep, that's fine. Just so the two views match since the first has more information than the second, but the second is what users see first.
