### ISSUE TITLE
Leading spaces in value generates UTF-8 error

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2211]
Should Trim off blanks before and after values at import

**Comment by antgonza** [comment]
Just tried to reproduce this and it seems like spaces is not the issue, my guess is that you actually had odd non-UTF8 chars in your values that were shown as spaces when you opened the file in your favorite program to change/fix this. I'm gonna see what we can do to replace/ignore all non UTF-8 chars.

**Comment by adswafford** [comment]
Replacing non UTF-8 characters with a question mark and then warning that this change was made is fine to me; or else go down the route of how to identify and remove the offending characters as you suggested in your email.
