### ISSUE TITLE
Sample information and prep information templates pages should show update log

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2214]
Users would like to be able to see a log of the filenames and timestamps for when they updated their metadata so they can tell when and which file they used to update it. Thi sis especially important when a user has not visited the study in some time.

**Comment by antgonza** [comment]
All of them? What about just the last one? Do you think we need to make them downloadable? 

Background: we actually store all of them but don't make them available to avoid confusions.

**Comment by adswafford** [comment]
A log of all of them is fine. I don't think we'd want to have them all be downloadable unless it would also be possible to permanently delete older files, such as when protected health information is included during the sandbox/private stage for a study and then needs to be removed from the study before it goes public.

**Comment by antgonza** [comment]
Fixed here: https://github.com/biocore/qiita/pull/2327
