### ISSUE TITLE
Need a place to provide and update a data dictionary

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2215]
Users should be able to upload and view a data dictionary that is a .tsv/.txt with the minimum of the column names 'metadata_category' and 'description'

This will be especially useful once studies become public and others are viewing and accessing the study

**Comment by antgonza** [comment]
Not really sure what this means. Perhaps an specific example will be useful, could you send one?

**Comment by adswafford** [comment]
Example of metadata and data dictionary attached
[data_dictionary.txt](https://github.com/biocore/qiita/files/1219263/data_dictionary.txt)
[metadata.txt](https://github.com/biocore/qiita/files/1219264/metadata.txt)

**Comment by antgonza** [comment]
This and https://github.com/biocore/qiita/issues/1997 are basically the same request: being able to add "attachments" to studies; which we agree is useful. I'm going to change this feature from must-have to nice-to-have for this release but have it as group-input so we can discuss the ground rules for the attachment system.

**Comment by antgonza** [comment]
@adswafford, looking at this issue and perhaps we have a tentative solution. I can imagine a user uploading their files to a permanent storage like https://figshare.com/ and then using this new feature to https://github.com/biocore/qiita/pull/2986 let other users know how to use those files. What do you think?

**Comment by adswafford** [comment]
That seems like a reasonable low-effort tie in (likely just updating the tutorial/help docs to suggest this?) until if/when we tackle making metadata dynamic?
