### ISSUE TITLE
Date and time information should be displayed when artifact is selected

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2216]
The information about when an artifact was created should be shown in the summary of the artifact in the processing and analysis workflows. This information is already displayed in the view studies tablewhen selecting biom artifacts to add to analyses so this should be easy to do.

**Comment by antgonza** [comment]
Just to confirm, do you mean that we should show it in the summary, for example there:
![screen shot 2017-08-16 at 9 01 11 am](https://user-images.githubusercontent.com/2014559/29370105-ad512780-8261-11e7-837f-6cbe4fc8e461.png)

**Comment by adswafford** [comment]
Yep, that would be great.

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/2243
