### ISSUE TITLE
Label the mail, clipboard, and server icons on hover and provide better GUI indications

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2218]
Titles like:
Inbox
Sample Clipboard/Analysis Queue/etc?
and Jobs/Process List 

respectively?

The server image should be green when processes are running and show the number of failed processes in a red icon like the mail icon does when there are unread messages.

**Comment by adswafford** [comment]
Correction, based on the fact that the Analysis dropdown says "Create From Selected Samples", the clipboard icon pop-up text should be titled "Selected Samples" for consistency

**Comment by josenavas** [comment]
Inbox / Selected samples / Jobs

**Comment by adswafford** [comment]
Can we also make the 'hover' action for the selected samples icon pop up whenever a new biom is added so that we give a visual indication that this is both where they can find what has been added, give them feedback about the button they pushed (even if I know the buttons also change), and give them an indication of where to click.

**Comment by josenavas** [comment]
Fixed in dev
