### ISSUE TITLE
Add return/go back/cancel button when in the workflow development view

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2219]
Users are tempted to click the back button when they can't find a way to cancel out of the workflow creation and this results in confusion since they return to the view analyses page instead of the analysis they're in.

I tagged it for the analysis plugin, but the same is true for the processing workflow creation.

**Comment by antgonza** [comment]
The back processing takes you back to the study list vs. the study you were processing.

**Comment by josenavas** [comment]
The workflow development page has been removed, so need for this anymore.
