### ISSUE TITLE
Tag error banner with analyses that are blocking

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2227]
When biom artifacts in the processing workflow are blocked from deletion due to their presence in an analysis, the error banner should say which analysis(es) are blocking it so the user can track it down.

**Comment by antgonza** [comment]
@adswafford, can this be closed? I _think_ it's solved in the new interfase ...

**Comment by adswafford** [comment]
Not yet: 
![image](https://user-images.githubusercontent.com/27017606/35012759-c35aa3fe-fabf-11e7-956c-40d5cf933d11.png)

The goal is to give some indication of how to resolve the blocking analys(ie)s

**Comment by antgonza** [comment]
Closing in favor of: https://github.com/biocore/qiita/issues/2228

**Comment by adswafford** [comment]
Agree
