### ISSUE TITLE
Provide list of analyses using biom artifact in summary

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2228]
In the processing network view, the artifact summary should list which analyses are using the artifact

**Comment by adswafford** [comment]
I should clarify that this list should appear below the network view, and I suppose the ones shown should just be the public ones. Do we have a concept in Qiita of an public analysis?

The use cases here are:
1) When I want to delete an artifact and I can't b/c it's in use, I want to know what's using it
2) When someone has used my data in a public metaanalysis, I'd like to know

The 'I' here should also be understood as from the perspective of an active user, not just me :-)

**Comment by antgonza** [comment]
I like this much better than https://github.com/biocore/qiita/issues/2227 and I _think_ it can be easy to solve ...

**Comment by antgonza** [comment]
fixed on https://github.com/biocore/qiita/pull/2752
