### ISSUE TITLE
Add warning to Downloads dropdown

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2230]
Since the file is  5.1 GB file, it is worth warning users who try to download it? Or include the size of the file in the dropdown information box as a heads-up

**Comment by PositiveGCP** [comment]
Do we need to add sort of modal when the user tries to download?

**Comment by danteese** [comment]
Do we need to add sort of modal when the user tries to download?

**Comment by antgonza** [comment]
A modal will be great but a confirm box will also do it.

**Comment by antgonza** [comment]
closed by https://github.com/biocore/qiita/pull/2372
