### ISSUE TITLE
Add navigation controls to network views

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2231]
We discussed this in Qiita meeting and we should be able to do this easily: http://visjs.org/examples/network/other/navigation.html

**Comment by josenavas** [comment]
Fun fact - according to our code these navigation controls should already show up. For some reason they're not showing up, but I don't see any error anywhere indicating why. I will keep investigating this issue but it looks like is silently failing in the internals of vis.Network :S

**Comment by josenavas** [comment]
Fixed in dev
