### ISSUE TITLE
Fix capitalization/wording in analysis plugin

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2237]
All of the options in the dropdowns should follow standard capitalization and spacing rules, and b alphabetized. Adding small hints for now, until Qiime2 gets better, should also reduce user confusion.

Parameters in the plug in should be made user-friendly as they are in the Qiime1 processing plugin.

![image](https://user-images.githubusercontent.com/27017606/29294396-0199cc2a-8104-11e7-8106-b40121782f90.png)
Should be:

Calculate alpha diversity (rarefied features only)
Calculate beta diversity (rarefied features only)
Filter samples by metadata
Rarefy features 
Summarize taxa (closed reference OTUs only)

![image](https://user-images.githubusercontent.com/27017606/29297108-88a252aa-8113-11e7-8e05-3fc754579480.png)

Choose command [<- this is already correct]
Biom artifact:
Parameter set  [<- this is already correct]
Diversity metric
Phylogenetic tree

![image](https://user-images.githubusercontent.com/27017606/29297178-063074ae-8114-11e7-9e44-25da1ba7af6c.png)

Abundance-based Coverage Estimator (ACE) metric
Berger-Parker dominance index
Brillouin's index
Chao 1 index
Chao 1 confidence interval
Dominance measure
Effective number of species (ENS)/Probability of intra-or interspecific encounter (PIE) metric 
Esty’s confidence interval
Fisher’s index
Gini index
Good’s coverage of counts
Heip’s evenness measure
Kempton-Taylor Q index 
Lladser's confidence interval
Lladser's point estimate
Margalef’s richness index
McIntosh's dominance index D
McIntosh’s evenness measure E
Menhinick’s richness index
Michaelis-Menten fit to rarefaction curve of observed OTUs
Number of distinct OTUs
Number of double occurrences (doubletons)
Number of single occurrences (singletons)
Number of observed OTUs, including singles and doubles
Pielou's evenness
Robbins’ estimator
Shannon's index
Simpson’s index
Simpson’s evenness measure E
Strong’s dominance index (Dw)

![image](https://user-images.githubusercontent.com/27017606/29297492-3c9b5ef8-8116-11e7-874d-0a820a493a04.png)

Choose command [<- this is already correct]
Biom artifact
Parameter set  [<- this is already correct]
Diversity metric
Phylogenetic tree

![image](https://user-images.githubusercontent.com/27017606/29297481-2585bf06-8116-11e7-9cb3-3960c562ac23.png)

Bray–Curtis dissimilarity 
Canberra distance
Chebyshev distance
City-block distance
Correlation coefficient
Cosine similarity
Dice measure
Euclidean  distance
Hamming distance
Jaccard similarity index
Kulczynski dissimilarity index
Manhattan distance
Mahalanobis distance
Matching components
Rogers-Tanimoto distance
Russell-Rao coefficients
Soergel distance
Species-by-species Euclidean
Sokal-Michener coefficient
Sokal-Sneath index
Squared Euclidean distance
Weighted Minkowski metric
Yule index

![image](https://user-images.githubusercontent.com/27017606/29297936-39d6ed2e-8119-11e7-8f42-2db1f4a961a1.png)

Choose command [<- this is already correct]
Biom artifact
Parameter set  [<- this is already correct]

![image](https://user-images.githubusercontent.com/27017606/29297951-4a07738a-8119-11e7-9be6-d428dd7c3e3b.png)

Choose command [<- this is already correct]
Biom artifact
Parameter set  [<- this is already correct]
Minimum feature frequency across samples
Minimum features per sample
SQLite WHERE-clause [provide link if possible]
Maximum feature frequency across samples
Maximum features per sample

![image](https://user-images.githubusercontent.com/27017606/29298069-1046ceb0-811a-11e7-8e7e-dd66e579328e.png)

Calculate alpha correlation

![image](https://user-images.githubusercontent.com/27017606/29298084-26ad08ae-811a-11e7-9db6-809e58108a05.png)
Choose command [<- this is already correct]
Biom artifact
Parameter set  [<- this is already correct]
Correlation method

![image](https://user-images.githubusercontent.com/27017606/29298109-57bb0644-811a-11e7-82a6-0ebbb836ffd9.png)
Pearson
Spearman (Pearson with ranks)

![image](https://user-images.githubusercontent.com/27017606/29298136-7dd616de-811a-11e7-8ab5-1d05052ca2d4.png)

Calculate correlation
Calculate group significance
Generate principal coordinates analysis (PCoA)

![image](https://user-images.githubusercontent.com/27017606/29298166-a1e41a62-811a-11e7-945e-cf13c19deabf.png)

Choose command [<- this is already correct]
Distance Matrix artifact
Parameter set  [<- this is already correct]
Number of permutations
Correlation method
Metadata category 

![image](https://user-images.githubusercontent.com/27017606/29298216-0b926a72-811b-11e7-92f7-3ac793de2418.png)

Choose command [<- this is already correct]
Distance Matrix artifact
Parameter set  [<- this is already correct]
Number of permutations
Analysis method
     PERMANOVA
     ANOSIM
Metadata category
Comparison type
     Non-pairwise
     Pairwise

![image](https://user-images.githubusercontent.com/27017606/29298291-8f8a5696-811b-11e7-9d20-c25705929171.png)

Custom-axis Emperor plot

![image](https://user-images.githubusercontent.com/27017606/29298305-a99e916e-811b-11e7-9fd8-c8a8d5b98fe4.png)

Choose command [<- this is already correct]
PCoA artifact
Parameter set  [<- this is already correct]
Custom axis

**Comment by antgonza** [comment]
@josenavas, can this be closed?

**Comment by josenavas** [comment]
Yes - fixed here: https://github.com/qiita-spots/qp-qiime2/pull/18
