### ISSUE TITLE
Workflow diagram fails to update when too many commands are added simulatneously

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2239]

**Comment by antgonza** [comment]
do you have an example or screenshots? How many do we need to add to reproduce this?

**Comment by adswafford** [comment]
Not sure;  I capped out just now on
https://qiita.ucsd.edu/analysis/description/12797/#

Once I get through adding the rest of the processes on this one, I can
count up to the breaking point and record how to reproduce

--
Austin D. Swafford, PhD
Director of Research, Center for Microbiome Innovation
Jacobs School of Engineering *| *UC San Diego
O: 858-246-2906

*Follow @CMIDigest*

<http://ow.ly/kiac30dUAnc>    <http://ow.ly/fXyB30dUAoS>
<http://ow.ly/dKO130dUAuB>

<http://ow.ly/EyXz30dUAvl>

**Comment by adswafford** [comment]
So it looks like after 10 commands it actually stops adding jobs.

In the workflow contstruction diagram, I had 10 different filtering
conditions to do. Then  I wanted to add 1 alpha diversity command, 1 beta
diversity command, with 1 pcoa and 1 beta correlation children. I only got
through 2 of the 10 filtered bioms before the display stopped updating, and
none of the alpha or beta jobs appear to have started when I clicked
Process.



--
Austin D. Swafford, PhD
Director of Research, Center for Microbiome Innovation
Jacobs School of Engineering *| *UC San Diego
O: 858-246-2906

*Follow @CMIDigest*

<http://ow.ly/kiac30dUAnc>    <http://ow.ly/fXyB30dUAoS>
<http://ow.ly/dKO130dUAuB>

<http://ow.ly/EyXz30dUAvl>

**Comment by antgonza** [comment]
Thanks. Haven't looked at the code but 10 sounds like a parameter somewhere, what will be a better value for this? As you can imagine infinite is not a good value, and even 10 is a lot of processing happening at once. What about just adding a message?

**Comment by adswafford** [comment]
Message works for me.

--
Austin D. Swafford, PhD
Director of Research, Center for Microbiome Innovation
Jacobs School of Engineering *| *UC San Diego
O: 858-246-2906

*Follow @CMIDigest*

<http://ow.ly/kiac30dUAnc>    <http://ow.ly/fXyB30dUAoS>
<http://ow.ly/dKO130dUAuB>

<http://ow.ly/EyXz30dUAvl>

**Comment by adswafford** [comment]
Is this fixed? Updating to Nov 1 milestone for testing and closing if fixed

**Comment by antgonza** [comment]
Seems to be fixed, reopen if you see it.
