### ISSUE TITLE
Update Qiita help documentation: analysis background info/recommendations

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2272]
Ideally we can provide enough information to guide users as to which types or analyses are appropriate to use (e.g. Prism-style help doc: http://jarikson.ru/mash/Prism4%20Folder/Manuals/StatisticsGuide.pdf ) though clearly more limited.

Anyone have some articles to suggest as a stand-in in the meantime?

**Comment by antgonza** [comment]
We believe this has been fixed in the latests version of the documentation and currently deployed in the qiita-rc.
