### ISSUE TITLE
Attaching files to preparation allows beta, alpha, etc

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#2280]
Just noticed that when selecting the type of data that will be attached to a preparation, alpha diversity vectors, beta diversity results, and others are available options. See screencapture:

<img width="644" alt="screen shot 2017-09-12 at 9 22 23 pm" src="https://user-images.githubusercontent.com/375307/30359618-d9e3f1d8-9800-11e7-960d-621442949d99.png">

**Comment by antgonza** [comment]
This should be part of the artifact type definition.

**Comment by antgonza** [comment]
Fixed in  https://github.com/biocore/qiita/pull/2478
