### ISSUE TITLE
EBI submission of metagenomic data

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2284]
Right now we can only submit after demux - demux of per sample fastq applies quality filtering for 16S - not appropriate for shotgun.  What do we need to do to submit per sample fastq to EBI?  Add a button?

**Comment by ackermag** [comment]
I need to do this now for Katie (study 11212 prep 3580).  Is this a hard fix?

**Comment by antgonza** [comment]
Not sure. My suggestion will be to try it by hand first so we can assess complexity and validity of fields, let's discuss internally to set a date to do this by hand submission.

**Comment by antgonza** [comment]
closed here: https://github.com/biocore/qiita/pull/2303
