### ISSUE TITLE
Search over mixed integer/varchar fields

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#229]
Currently the search engine does not take into account what datatype is stored in a column. Search will need to lookup the datatype as well as column names from `study_sample_columns` table and make sure the comparison can be done. For example: `pH > 4` currently fails because some studies have high, med, low for ph, not numbers.

**Comment by antgonza** [comment]
This is related to the old search functionality, which has been superseded by redbiom. Closing.
