### ISSUE TITLE
study name with spaces

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2290]
As you might remember study names are unique in the system so I just came up with a couple of studies that have the same name but with spaces. For example: "My Name" vs. "My Name ". This really confused me using the GUI cause they basically look the same. Thus, the question is: should we strip names and don't allow spaces before/after and multiple spaces or just add "" in the title display of the study section.

**Comment by josenavas** [comment]
I'm ok with stripping the names and checking for an empty string.

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/2467
