### ISSUE TITLE
Redbiom search issues in Qiita-rc

### ISSUE THREAD

**Issue by tanaes** [biocore/qiita#2304]
Updating as I find them. 

1. searching metadata for two words separated by a space causes search to freeze -- infinite spinning wheel.

**Comment by tanaes** [comment]
2. searching for taxa doesn't seem to work. 

<img width="707" alt="screenshot" src="https://user-images.githubusercontent.com/8292608/30655171-05a60fa6-9de5-11e7-89c8-0e86a1f5c860.png">

<img width="694" alt="screenshot" src="https://user-images.githubusercontent.com/8292608/30655174-0914b3d6-9de5-11e7-8ae4-622781b224a0.png">

**Comment by tanaes** [comment]
3. Typos: 

"Taxon: The search will be only on close reference" -> "Taxon: The search will be only on **closed** reference"

"Warning! No samples where found!" -> "Warning! no samples **were** found"

**Comment by antgonza** [comment]
closed here https://github.com/biocore/qiita/pull/2306
