### ISSUE TITLE
Closed-Ref searches to Silva actually using Greengenes fasta?

### ISSUE THREAD

**Issue by tanaes** [biocore/qiita#2310]
I've been trying to do this 18S analysis in dribs and drabs for a week and thought I was going crazy, because I swore I was picking Silva but the biom kept specifying Greengenes. 

Then I looked at the parameter paths:

![screenshot](https://user-images.githubusercontent.com/8292608/30710877-c5b118d2-9ebb-11e7-8095-38e925481baf.png)

@josenavas, hopefully an easy fix for RC?

**Comment by ackermag** [comment]
Perhaps we should check UNITE as well

**Comment by josenavas** [comment]
Fixed
