### ISSUE TITLE
analysis: taxonomy is dropped after BIOM processing

### ISSUE THREAD

**Issue by tkosciol** [biocore/qiita#2313]
While analysing closed-ref BIOM, taxonomy information gets dropped from the file after each step (e.g. after rarefaction). As a result, it's impossible to generate taxa-summary on any processed/filtered BIOM.

It's a QIIME2 problem, but can be easily fixed on the Qiita side.

**Comment by josenavas** [comment]
Fixed here: https://github.com/qiita-spots/qp-qiime2/pull/19
