### ISSUE TITLE
BUG: qiita_db.software.Parameters equality

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#2317]
In working with the redbiom loading mechanisms, we discovered that trim length is in some studies an integer, and in some studies a string. That type difference presents downstream issues for redbiom as we distinguish contexts by the hash of the processing parameters and `150 != u"150"`. That can be worked around, however, this type difference is indicative of a bug within `qiita_db` when assessing the [equality](https://github.com/biocore/qiita/blob/5b54aa7e445dd38b34373d9aa72481ffa7d214a4/qiita_db/software.py#L1318-L1337) of two `Parameters` instances. See below for an example of the type difference observed between two studies:

```python
In [16]: for a in qiita_db.study.Study(850).artifacts():
    ...:     if a.processing_parameters is not None and 'length' in a.processing_parameters.values:
    ...:         print(a.processing_parameters.values)
    ...:
{'input_data': 171, 'length': 100}
{'input_data': 171, 'length': 90}

In [17]: for a in qiita_db.study.Study(11360).artifacts():
    ...:     if a.processing_parameters is not None and 'length' in a.processing_parameters.values:
    ...:         print(a.processing_parameters.values)
    ...:
{'input_data': u'34913', 'length': u'150'}
{'input_data': u'35044', 'length': u'150'}
```

**Comment by josenavas** [comment]
Fixed in the last release with the normalization of the parameters.
