### ISSUE TITLE
Include the Torque job identifier in the job output

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#2319]
In investigating `83832042-3263-4329-a868-8cc62981b488`, I noticed that output files do not describe the job identifier. This identifier is invaluable for post mortem. One possibility would be to tag the job output files. I'm not sure how `qsub` is being used right now, but setting this up in the submission scripts should be feasible. Alternatively, the job identifier can be collected from `qsub` off the system call directly so that it can be stored after the fact:

```bash
$ job=$(echo "hostname" | qsub)
$ echo $job
491375.barnacle.ucsd.edu
```

**Comment by antgonza** [comment]
This is now part of the qiita system. Closing.
