### ISSUE TITLE
Web API Endpoint to programmatically upload biom for a study

### ISSUE THREAD

**Issue by mwang87** [biocore/qiita#2320]
Web API to upload a biom file (or provide a URL for qiita to pull down the file) would be useful for a service like GNPS to export biom file for metabolomics analysis to be analyzed easily in Qiita directly and easily for GNPS users.

**Comment by antgonza** [comment]
In theory, and actually in practice, this is possible via:
- Having a

**Comment by antgonza** [comment]
Sorry, fat fingers. I think the main problem is that to be able to add a biom we first need a study with a sample info file and prep info file; you can add a biom to a prep. So perhaps adding we can allow study, sample and prep info creation via the API or some way figure out how to transfer that info back and forth. 

Now, this doesn't actually solve the issue with GNPS as it doesn't have sample information (not sure about prep) so I think if we add the raw data to Qiita, then send the info for processing to GNPS, then send back the biom, will be the best way forward. 

@mwang87, what do you think?

**Comment by ElDeveloper** [comment]
@antgonza, I think those points are covered by the REST API endpoints that @wasade and I put together a few months ago. See [here](https://github.com/biocore/qiita/blob/master/qiita_pet/handlers/rest/study_preparation.py#L52) and [here for the full list of endpoints](https://github.com/biocore/qiita/blob/master/qiita_pet/handlers/rest/__init__.py#L23).

The main problem is that these are not exposed to users outside of Qiita, exposing this might take some work.

**Comment by antgonza** [comment]
Right, thanks. We could start with only internal and go from there ...

**Comment by mwang87** [comment]
Cool, that makes sense. Are internal APIs just not exposed by blocking ports or could we just have a credentialing process?

**Comment by josenavas** [comment]
I just want to drop my 2 cents here. As per previous discussions with @mwang87 and others we agreed that creating a plugin would be the best way of connecting the 2 systems. Following this route, no new development in Qiita should be done as the plugin infrastructure should be complete.

**Comment by ElDeveloper** [comment]
The process to create credentials for a given user is not exposed to the 
public, so we would have to figure out something on a case-by-case 
basis, which I'm sure we can do :)

**Comment by ElDeveloper** [comment]
^ Right, that's a more sustainable alternative.

**Comment by mwang87** [comment]
@josenavas Yes, I think it would be great if users are starting at Qiita with also sequencing data. I do also think there are a lot of people that come from the mass spectrometry side that would like to have access to the statistical tools available at Qiita that are not familiar with the platform but are familiar with GNPS. Currently, we automatically generate a subset of emperor features, but I want to avoid recreating all the analysis features that are already implemented in Qiita.

**Comment by antgonza** [comment]
plugin will be the best. Figuring out how to "request" sample/prep info from GNPS users, will be the best. As you know, without metadata analysis are impossible. BTW we have this: https://github.com/qiita-spots/qtp-mass-spec
