### ISSUE TITLE
Submit both forward and reverse reads fastq files to QIITA

### ISSUE THREAD

**Issue by mentorwan** [biocore/qiita#2324]
We tried to submit already demultiplexed RAW files to QIITA associated with one project. The RAW files have already been demultiplexed. Each sample has two RAW files. I know the preparation metadata file, it can include run_prefix with correct sample run_prefix. But does it support for both forward and reverse reads? Does QIITA have workaround to handle that submission? Thanks for help.

**Comment by josenavas** [comment]
Hi @mentorwan. You should be able to upload per sample FASTQs both forward and reverse files - if the run prefix contains the common prefix for both files (fwd/rev) it will populate the list automatically.

I will close the issue - if you need more help with this issue, feel free to drop an email to qiita.help@gmail.com.
