### ISSUE TITLE
Deleting analysis artifact doesn't delete from network view until page refresh

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2332]
Steps to reproduce:
Open a previous analysis
Select and artifact
Delete the artifact
Network view flashes, but artifact still shows
Select again to delete and click delete
Get error: Error loading artifact information: error The object with ID '35805' does not exists in table 'artifact'

Should update and not continue to be shown. Perhaps this will be fixed with the auto-refresh of the page?

**Comment by antgonza** [comment]
Auto-refresh should fix it. Can you delete the nove Milestone and assign the correct Milestone? Thanks

**Comment by adswafford** [comment]
Oops, thought that I'd clicked it from the filtered list. Should be set. And autorefresh is #2185 for record-keeping on here.

**Comment by antgonza** [comment]
Closing in favor of https://github.com/biocore/qiita/issues/2185 so we have a single entry for all the auto-reloads.
