### ISSUE TITLE
Bioms don't provide trim length information when selecting samples for analysis

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2333]
Bioms should provide time length information so users can make informed decisions when adding .biom files to a study.
![capture](https://user-images.githubusercontent.com/27017606/31421062-1bef3de4-adfa-11e7-901c-d8cf8dcdc2c1.PNG)

**Comment by antgonza** [comment]
We are gonna create a extra patch for fixing the discrepancies, it will be run on the qiita-test or rc system before deploy.

**Comment by antgonza** [comment]
closed by https://github.com/biocore/qiita/pull/2356
