### ISSUE TITLE
Upload Files page: Error 500 on reload after deleting file

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2334]
Steps to reproduce:
Upload file
Navigate to another page
Return to Upload Files page
Select the file and delete it
Refresh page with browser button
Error 500 appears

**Comment by antgonza** [comment]
Confirmed the error. However, IMOO this is a complete PEBCAK: Basically, the user has to:
1. Ignore to not use the browser buttons
2. Delete something and they reload the page
3. Once the page is gonna be reloaded, confirm _twice_, that they want to resubmit the last page - cause this is a POST command.

Anyway, the solution is pretty simple:
Do not raise this error here: https://github.com/biocore/qiita/blob/master/qiita_db/util.py#L505 and simply don't rename the file.

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/2466
