### ISSUE TITLE
Allow users to upload .xlsx instead of just .tsv

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2337]
It would be useful for users to be able to import .xlsx files into Qiita and then choose which sheet to read the metadata from when associating.

We can use:
https://bitbucket.org/openpyxl/openpyxl
or
http://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.read_excel.html if we have pandas in the environment already?

I put a Dec 2017 deadline as this will be needed for the V1 output from the Metadata Wizard.

**Comment by wasade** [comment]
Easiest is assuming information is only in the first sheet and to just disregard sheets altogether. A feature enhancement in the future could be to allow users to specify the sheet (or sheets) to use.

**Comment by adswafford** [comment]
That works for me.

**Comment by antgonza** [comment]
Fixed here: https://github.com/biocore/qiita/pull/2599
