### ISSUE TITLE
Automatically try to convert whatever the user puts into the collection_timestamp column to our preferred format

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2338]
By far the most common issue users run into when importing their metadata into Qiita is that Excel, especially Mac Excel screws up the date format. Can we just catch it on the way in so it automatically converts from (M)M/(D)D/YYYY (HH:MM) to YYYY-MM-DD (HH:MM). 

Try-except loops with the built in functions should do it: https://stackoverflow.com/questions/19068269/how-to-convert-a-string-date-into-datetime-format-in-python

Along with a final check for an EBI-null term in case it's Missing: restricted access, not collected, etc.

If the user really screws up the format, then they're on their own for now.

**Comment by antgonza** [comment]
I think this is covered as much as possible, see: https://github.com/biocore/qiita/issues/1885. The issue with the specific case you point: (M)M/(D)D is an impossible one as if someone writes 3/8, how do you know if 3 is month or day? Thus, we decided to cover all the options + documentation. See [collection_timestamp](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html#required-fields-for-ebi-submission)
