### ISSUE TITLE
Infos about processing errors

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2340]
I was very excited when I saw "beta_group_significance" for sample analyses. After trying several times for the Manary study, I always get an error in the "Active Jobs" overview and no new nodes in the workflow.
Unfortunately, the only information I can obtain is that the process "errored", but I have no idea why. How can a user figure out what to correct / change to make this analysis work?

**Comment by antgonza** [comment]
Can you share one of your job ids so we can traceback? Thanks!

**Comment by antgonza** [comment]
We fixed the error reporting and now it's clearer, when an error actually happens. Thanks for reporting!
