### ISSUE TITLE
Upload Files page: status shows upload finished incorrectly

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2346]
Steps to reproduce:
Drag and drop metadata (txt) and fastq files into Upload FIles box
When txt (presumably) have finished uploading, the status changes to "Upload Finished" though most of the files are of course not finished.

![capture](https://user-images.githubusercontent.com/27017606/31525585-226314d4-af76-11e7-9303-d729f11b1aa4.PNG)

**Comment by josenavas** [comment]
fixed in dev
