### ISSUE TITLE
check processing parameter for analysis merging

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2353]
[Currently](https://github.com/biocore/qiita/blob/master/qiita_db/analysis.py#L797) we are merging based on processing pipeline but not parameters.

**Comment by antgonza** [comment]
- [ ] for the discrepancy between reference id and using the file paths: TBD 
- [ ] for the merging of the artifacts: the user will select during creation how to merge and the system should have enough information so they users knows what's ok to merge 
- [ ] the system should know that different processing references do not have a tree - no phylogenetic analysis

**Comment by josenavas** [comment]
Solved in the "dev" branch
