### ISSUE TITLE
Send an email to the qiita email account when a user requests approval

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#2358]
Source the email from the config file.

**Comment by charles-cowart** [comment]
Just to clarify, is this approval for when the owner of an analysis wants to make it public, and is requesting approval from the Qiita admin? At first, I thought this was regarding when new users create their accounts; I noticed that there doesn't appear to be an email sent to qiita-admin to validate the account.

**Comment by antgonza** [comment]
This is for when the user wants to make move a study from sandbox to private ... Note that currently you can see the list in the Admin menu but ideally we will know via an email ...

**Comment by charles-cowart** [comment]
Present plan is to have an email sent to qiita.help@

**Comment by antgonza** [comment]
It will be good if this is part of the configuration and not hardcoded ...
