### ISSUE TITLE
create a "mapping_file" filepath_type

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2361]
Currently the mapping file for an analysis is stored as plain_text, which could potentially create conflicts. Ideally, all mapping files are gonna be names as they should: sample_info_file, prep_info_file, qiime_mapping_file ...

**Comment by josenavas** [comment]
just for clarification - you're asking for q filepath_type?

**Comment by antgonza** [comment]
Yup, edited the title for clarity

**Comment by antgonza** [comment]
This issue was opened 3+ years ago and the potential conflict hasn't happened + we are not creating the QIIME1 merged mapping file per study (reducing the "potential" conflict). Thus, closing.
