### ISSUE TITLE
Fix writing on Upload Files Page

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2364]
"fastq or fastq.gz (gziped fastq) for sequences. Note that zip files can not be processed” should be: “fastq or fastq.gz (gzipped fastq) for sequences. Note that ‘.zip’
 files can not be processed."

So: add another p to "gziped" and add a period at the end of the sentence

**Comment by antgonza** [comment]
Hey @stephanieorch, @josenavas and I are wondering if you want us to add quotes between .zip and a . at the end of each point in the list? Thanks!

**Comment by stephanieorch** [comment]
Yes for the quotes around .zip and a . at the end of the first point.

**Comment by antgonza** [comment]
Closed by https://github.com/biocore/qiita/pull/2369
