### ISSUE TITLE
Bug: (CSS) header menu hides page

### ISSUE THREAD

**Issue by auberginekenobi** [biocore/qiita#2380]
Bug: It looks like the web header (Analysis, Study, More info, Current and Future Releases, Redbiom, Downloads) can run onto a second line, which obstructs parts of the underlying display which is specific to the page displayed.  Screenshot attached.

Bug reproduced using Google Chrome when the 'downloads' bar is open at the bottom of the page.
Probably an easy fix related to CSS or Bootstrap (it looks like you're using Bootstrap) parameters.
![image](https://user-images.githubusercontent.com/5943686/32192787-72ea86da-bd72-11e7-90da-e4b38a6db979.png)

**Comment by antgonza** [comment]
Thanks for reporting! 

This was fixed in the last release, same page with full display, then reducing it and then reloading page: 
![fixed](https://user-images.githubusercontent.com/2014559/34950886-b1ab7262-f9d1-11e7-9e97-767ec1f3803f.gif)
