### ISSUE TITLE
PITA: Need better interaction with sample information and study/analysis management

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2393]
Encountered a new painful situation:
1. Existing study with existing, analyzed prep
2. New samples from the same study are sequenced, so a second prep needs to be created
3. Download the metadata file and add in blanks/controls/etc. and any unlisted samples found in the prep
4. Upload correct prep info file and incorrect metadata file (just user error)
5. Update sample information (not having noticed the user error)
6. Attempt to add new preparation and receive error message that there are samples in the prep information file that are not found in the sample information (thus revealing the user error)
7. Return to sample information and discover that there are hundreds of samples added that are not part of this study
8. To fix it, instinct is to find an undo button (but there isn't one)
9. Next is to delete the sample information file and replace it with the correct one (can't do this since samples have been processed)
10. Third is to realize that the only way out of this situation is to delete hundreds of samples one-by-one
11. Since that solution is a pain, download raw sequences and reupload into new study along with correct sample and prep information 
12.  To avoid confusion, attempt to delete old study but find that this is blocked since analyses exist
13. Persevering, user finds analysis done on this study, and tries to delete, but can't because it contains artifacts
14. User realizes that the only way to delete the analysis is to delete artifacts one-by-one
15. User gives up and leaves old analysis and old study in place and renames "Do not use" as a self note 
16. User goes to new study and spends extra CPU time reprocessing the same set of data and generating the same biom tables

All of this results in a lot of frustration and data-duplication. We'll likely need a few issues to address this situation, but I wanted to throw it out there so we can discuss the best way to avoid this since it highlights many of the usability challenges in managing studies and data in the current system.

**Comment by antgonza** [comment]
Thanks. 

It sounds like the issue comes cause samples were added by mistake and you can't bulk delete. A few options:
- don't make mistakes 😄 
- add a button to purge samples not in any prep, list them and ask confirmation from user, my preference.
- allow to select multiple samples and delete them, issue here is if the user selects samples that are in a prep
- other?

**Comment by josenavas** [comment]
I like the button to delete all samples not found in any prep. I think that would solve this issue. In the confirmation from user, I would have a div listing the samples that are going to be deleted.

**Comment by adswafford** [comment]
Ha, well for the first one there is alwasy [this issue](https://www.goodreads.com/quotes/67089-you-can-t-make-anything-idiot-proof-because-idiots-are-so)

I think the sample purge would work for now, but is a sample info reversion possible in the future?

**Comment by antgonza** [comment]
Anything and everything is possible! However, the issue in this case is in which cases/situations we should allow it. Imagine that the user, by mistake, adds info it shouldn't have, then erases/updates it via a new sample info. If we allow for previous restore, this might be a problem.

**Comment by antgonza** [comment]
@adswafford, I think we can close this one as now we can sort by prep, select multiple samples and delete in bulk ... if you don't agree, please reopen and add which functionality is missing. Thanks!
