### ISSUE TITLE
UTF-8 chars in title break analysis

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2398]
First detected by @sjanssen2. 

Basically, if your title has a UTF8 char, the analysis breaks during validation (my guess is that this will be fine for Q2).

**Comment by josenavas** [comment]
Can you provide more information about the error?

**Comment by antgonza** [comment]
Yup, if your study is named: `Antonio’s study` vs. `Antonio's study` you will get something like this:
https://qiita.ucsd.edu/analysis/description/14608/ (only owners and admins can see it)
