### ISSUE TITLE
store biom qza during analysis

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2409]
currently we only store/generate biom but a qza will be useful

**Comment by adswafford** [comment]
Prioritizing this since it directly impacts Q2 users.

**Comment by antgonza** [comment]
I think this should be done _after_ having Q2 load automatically in Qiita ...

**Comment by adswafford** [comment]
Gotcha; I thought that both this and the Q2 automatic loading would be targeted to complete with/in time for the Q2 paper submission. Is the loading automatically delayed until after the Q2 paper is submitted instead? And if so, is a target of the Nov 2018 update reasonable?

**Comment by antgonza** [comment]
This is not a single place solution as plugins needed to change; however, the required changes are done and were demo on today's meeting; thus, moving to a new milestone.

**Comment by antgonza** [comment]
Closed in the qiita 4.19 release to be deployed on May 15, 2019.
