### ISSUE TITLE
"Add to Analysis" button missing on public studies for non-admin accounts

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2418]
Steps to reproduce:
1. https://qiita.ucsd.edu/study/description/232#
2. Click on the closed-ref BIOM
In my admin account I see:
![image](https://user-images.githubusercontent.com/27017606/33733405-8c9730c6-db3e-11e7-9850-88cf8e2f6f70.png)

In my basic account I see:
![image](https://user-images.githubusercontent.com/27017606/33733456-b1314c5a-db3e-11e7-84ee-a3708846c9b1.png)

But if I go to a public biom in one of the basic account's private studies (https://qiita.ucsd.edu/study/description/11269) this is the view on both accounts:
![image](https://user-images.githubusercontent.com/27017606/33733515-dd4a703c-db3e-11e7-9212-6453455a7806.png)

**Comment by josenavas** [comment]
Fixed in dev
