### ISSUE TITLE
Highlight selected Prep

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2444]
Fully processed studies (i.e. one closedref + 2*3 deblur biom tables) with multiple preps make it hard to know which prep is currently selected. I was looking at 10485 with 6 preps and wanted to download all 6 150nt ref-hit deblur tables to merge and analyse them outside of QIITA. Accidentally, I downloaded one table twice and missed one. 
I think we could help avoiding this if the GUI would somehow highlight which prep is currently selected.

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/2464
