### ISSUE TITLE
In summary page there is no space between value and number of entries 

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2448]
so value 193  for 398 entries looks like 193398 for all samples.  Attached screenshot.
<img width="393" alt="elevation error" src="https://user-images.githubusercontent.com/2014592/34316559-d0725788-e74d-11e7-91b4-f52c4cc787bc.png">

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/2462
