### ISSUE TITLE
Validation of New Analysis Takes a Long Time

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2451]
The creation of a new analysis takes a long time to load due to the validation step. It would be great to either add a line saying that it will take longer than 15 minutes to load or decrease the amount of time it takes.

**Comment by antgonza** [comment]
Yup, this is, as you pointed out, due to the validation step. To be more accurate is due to the fact that the validation also creates the summary now. The performance issue has been addressed in the latest version of Qiime2 and should be available in the next release.

**Comment by antgonza** [comment]
This was solved during the last deploy by updating to qiime2-2017.12.
