### ISSUE TITLE
Page describing sample/prep info file doesn't specify column name limitations

### ISSUE THREAD

**Issue by tanaes** [biocore/qiita#2461]
Just noticed that [this page](https://qiita.ucsd.edu/static/doc/html/tutorials/prepare-information-files.html#sample-information-file) describes the required fields, but doesn't specify legal/illegal characters in column names.

**Comment by antgonza** [comment]
Thanks for reporting. 

Now, on that page there is a yellow banner with the restrictions, and each field has a Description, like: `Identifies a sample. It is the primary key and must be unique. Allowed characters are alphabetic [A-Za-z], numeric [0-9], and periods`. Thus, not sure which other limitation/restrictions we are missing ...

**Comment by antgonza** [comment]
We believe this has been fixed in the latests version of the documentation and currently deployed in the qiita-rc.
