### ISSUE TITLE
Analyzing Guide Redundancy 

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2485]
We've already covered "Analysis workflows" in the "Analyzing Samples " section as well as the CMI tutorial. We should keep "Qiita now uses QIIME2 plugins for analysis" section and move it to the "Analyzing Samples" section and then just completely delete "Analyzing Guides."

**Comment by antgonza** [comment]
This was fixed and deployed in the release-candidate, if it needs more changes please open a new issue.
