### ISSUE TITLE
Qimme Mapping File Button Misleading

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2495]
When you're adding your sample information, there is a drop down for if your upload is a QIIME mapping file. However, it does not treat it as a QIIME mapping file (where usually it would be able to accept the file as BOTH the prep and sample information file). Instead, you had to break it apart into 2 files.

**Comment by antgonza** [comment]
I don't follow this issue. A QIIME mapping file is basically the combination of sample/prep info file into one. Thus, Qiita takes that QIIME mapping file and splits it in 2: sample/prep.

**Comment by stephanieorch** [comment]
It does not split it into 2. When I upload it and I go to the sample information page it shows up. So I click on it and the samples appear. However, there is no "Add preparation information" button. So I have to reupload the file for the button to appear. Then, when I add it to the prep section, it says I have duplicate columns. I think the base of this issue is from #2452 .

**Comment by antgonza** [comment]
Got it, yes. Same issue, thanks for clarifying and will close this one.
