### ISSUE TITLE
Add python 3 back in to travis CI

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#250]
Removed because biom was not python 3 compatible (see biocore/biom#535), which is breaking the qiita build when testing with python 3.

However, when biom becaomse python 3 compatible, we should add it back in here, too.

**Comment by adswafford** [comment]
Haha, so it looks like the py3 upgrade has been in the work for 3 years now... Flagging for input so we can prioritize appropiately.

**Comment by antgonza** [comment]
Closed in the qiita 4.19 release to be deployed on May 15, 2019.
