### ISSUE TITLE
Expand get_artifacts_information details

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#2505]
Just spoke with @antgonza, and this method is fantastic especially for aligning with redbiom contexts. There are two additional fields that would be invaluable to have:

- `platform` so we can differentiate between Illumina, 454, etc
- `target_gene` so we can differentiate between 16S, 18S, etc

It would also be pleasant to have a short command-line safe variant of the `algorithm` key. For example, artifact `27698` reports `"Deblur (Reference phylogeny for SEPP: Greengenes_13.8, BIOM: reference-hit.biom) | Trimming (length: 150)"`. The whitespace and the "|" would be annoying on the command line. A stable shortname though would be fantastic, something like "deblur_gg138_referencehit_illumina_16S_V4_150nt"

**Comment by antgonza** [comment]
Closed by: https://github.com/biocore/qiita/pull/2545
