### ISSUE TITLE
Add information about the file type/pairs required for adding data to a study

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2506]
The help documentation does not contain information stating that we require qual files for .fasta or .fna submissions though it is implicit at various points. Can a section be added on the file types that are acceptable?

We may also want to include some notes for uploading biom tables, including troubleshooting when IDs don't match and how to use biom-format to get around this (sub-optimal, but the only option at the moment)

**Comment by stephanieorch** [comment]
The reason I didn't add this information to the help document is that it's already on the upload page. So, for the first part or your point, do you think it may be better to add a bullet point on the upload page making that note qual files are required when submitting .fasta or .fna files. Or we can do both?

**Comment by adswafford** [comment]
The upload page says "Currently we can process (fastq, fastq.gz, txt, tsv, sff, fasta, fna, qual, biom):
fastq or fastq.gz (gzipped fastq) for sequences. Note that '.zip' files can not be processed.
tab separated text files for sample and prep templates, the extension should be txt."

so it would be ideal to both update this with bullet points to show what goes with what and to have more verbose explanation in the help docs. 

Something like:
Sequencing data: .fastq/fastq.gz, .fna/.fasta + .qual, .sff
Metadata: .txt,(tab-separated), .tsv, .xlsx
Feature tables: .biom

**Comment by antgonza** [comment]
This was solved in the last release.
