### ISSUE TITLE
.fna support gone?

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2509]
We currently allow users to upload .fna+qual for processing, but the option is no longer present on the dropdown to select for associating sequences with a prep, e.g. Study 11640

![image](https://user-images.githubusercontent.com/27017606/36440812-7a7997ae-1625-11e8-8e09-c4cc1e64b2a4.png)

We should either remove the information that says we take .fna/qual (and maybe add some instructions on how to make fastq from .fna+.qual?) or enable this in the dropdown menu again.

**Comment by antgonza** [comment]
Yup, but note that this might be a mistake. Also note that the solution is to change the DB and/or plugin [here](https://github.com/qiita-spots/qtp-target-gene/blob/master/qtp_target_gene/__init__.py#L24). BTW if we allow upload I would make both fna/qual a requirement.

**Comment by adswafford** [comment]
@josenavas Do you know if this is a bug or a feature? It looks like the fasta format (but not the qual?) is in the QTP.
