### ISSUE TITLE
Summarize Taxa Not Working

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2520]
My summarizing taxa on closed reference data is not working. For example, analysis ID 16071, Job# 97db8ffe-14fa-47a2-b30c-a22989d92f09. Stopped at Step 1 of 4: Collecting information with the error message: biom table doesn't have taxonomy. But it does have taxonomy so not sure why its not working.

**Comment by antgonza** [comment]
Closing because after further review the uploaded file doesn't have observation metadata AKA taxonomy so the message error is correct.
