### ISSUE TITLE
Feature Detail Not Displaying Everything

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2521]
The feature detail tab under analysis ID 16071 only shows 22 features when there are more than that.

**Comment by antgonza** [comment]
This is an issue between the iframe in qiita and the iframe within the html from the Qiime2 html. Note that currently you can open in a new window, click on the blue button on top of the visualization, and you'll get the normal behavior.

**Comment by antgonza** [comment]
This is a duplicate of https://github.com/biocore/qiita/issues/2499
