### ISSUE TITLE
Allow Pausing of Automatic Refresh

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2524]
There are multiple times while running an analysis where the automatic refresh is annoying. For example, when I try to work with artifacts, when it refreshes it zooms out so I have to find my artifact again. It would be nice if there was a "PAUSE" button next to the automatic refresh countdown so I don't feel rushed when I'm running or editing my analysis.

**Comment by antgonza** [comment]
Closed by: https://github.com/biocore/qiita/pull/2540
