### ISSUE TITLE
Problematic visual display when viewing errors

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2526]
Additional characters are visible in display when viewing the errors from the prep info page - from processing graphical interface.  Screenshot attached.
![screenshot_error_deblur_visual interface](https://user-images.githubusercontent.com/2014592/37782660-a76e8858-2db0-11e8-91f7-410521159463.png)

**Comment by antgonza** [comment]
This was brought up recently by @tkosciol; the issue is that when the window is slow, the menu gets displayed in 2 rows and hides the top of the content ...
