### ISSUE TITLE
Animation Still Connects Hidden Samples

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2527]
When using emperor, when I hide samples on the visibility tab then use the animation tab, the hidden samples still connect with each other. You can see in the photo how there are lines that connect empty space (where the hidden samples are). 
<img width="856" alt="screen shot 2018-03-22 at 12 19 53 pm" src="https://user-images.githubusercontent.com/31080457/37793281-6b417352-2dcb-11e8-9119-3bb91b150677.png">
This makes longitudinal analyses very difficult to run in Qiita. It would be great if we would made the connecting lines hidden too.

**Comment by antgonza** [comment]
This is an emperor issue, moving there:
https://github.com/biocore/emperor/issues/652
