### ISSUE TITLE
Add Analysis ID Number to Analyses Page

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2528]
It would be great to add the analysis ID to the analysis page just like how the study ID is displayed on the study page.

**Comment by antgonza** [comment]
This was solved in the last deploy. Now, shown in analysis listing:
![screen shot 2018-04-18 at 9 35 09 am](https://user-images.githubusercontent.com/2014559/38942412-f3221d50-42eb-11e8-9086-ed236c5babd1.png)


and main analysis page:
![screen shot 2018-04-18 at 9 35 01 am](https://user-images.githubusercontent.com/2014559/38942397-ea0769f0-42eb-11e8-90a5-ab57c0ce93ec.png)
