### ISSUE TITLE
Easily Change Name of Artifact

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2531]
It would be nice if when you went to edit the name of the artifact, the original name was already highlighted so you could easily change it without either 1) having to highlight and delete the whole name or 2) having to press the backspace a ton of times to delete it. I think this would make editing names a lot easier.

**Comment by adswafford** [comment]
This looks like an extension of #2173 that was closed back in Dec

**Comment by antgonza** [comment]
Thanks @stephanieorch for reporting and @adswafford for catching. @stephanieorch does this feature don't work anymore?

**Comment by stephanieorch** [comment]
I don't think these are the same issues. If I understand correctly the prior issue was just so you can easily update the current name. What I was hoping to do was when you click edit, the current name is automatically highlighted so when I want to change the name I only have to press delete once for the entire name to be deleted. This would really help when you plan on changing the default names.

**Comment by antgonza** [comment]
Got it! The name is there but not highlighted ... thanks!

**Comment by stephanieorch** [comment]
Yes. This will make it easy to delete all of the text in the box since people will be changing the default names to a (probably) completely different name.

**Comment by antgonza** [comment]
Closed by https://github.com/biocore/qiita/pull/2541
