### ISSUE TITLE
Processing Network: Add Automatic Zoom Adjustment After Adding New Command

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2554]
The processing network doesn't zoom out after adding a command. So you have to either zoom out yourself or pull the screen so that you can click on the next artifact. This can be burdensome when running long workflows. It would be nice if, after you add a command, the processing network automatically adjusts the zoom so you can easily click on the new artifact to add your next command.

**Comment by adswafford** [comment]
@antgonza and @charles-cowart , how easy/hard would it be to implement the focus to a node like in this example:
http://visjs.org/examples/network/other/animationShowcase.html

**Comment by charles-cowart** [comment]
Not sure yet. This example is using the same graphics toolkit we use in
Qiita, that I do know. I can dig into it sometime this week.

**Comment by antgonza** [comment]
It should be pretty straightforward but it might be tricky to control/account for multiple outputs; for example how to focus when the output is only one artifact (PCoA and most commands) or multiple (deblur/core-diversity/shogun) ...

**Comment by charles-cowart** [comment]
Note - the desired result is once a new artifact is created, the viewer would recenter on that artifact.

**Comment by antgonza** [comment]
New requests:
- [ ] Add support for certain jobs to be executed locally in the head node, even on systems submitting jobs on Torque. This would involve an environment variable that could be set, and metadata added to a table to direct which jobs should be run where. [Original](https://github.com/biocore/qiita/issues/2859)
