### ISSUE TITLE
Adding Command Twice

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2555]
When I try to add a command twice, I do not get an error message and the "Run" button appears. However, the actual object representing this command does not show up on the processing network and when I click run nothing happens and the run button doesn't disappear.

**Comment by antgonza** [comment]
I can't reproduce this error; could you send a step by step way to reproduce? Thanks!

**Comment by stephanieorch** [comment]
No longer having this issue on Qiita.

**Comment by antgonza** [comment]
Thanks!
