### ISSUE TITLE
include processing information in analysis

### ISSUE THREAD

**Issue by tkosciol** [biocore/qiita#2558]
Right now it's possible to infer `qiita_study_id` and `qiita_prep_id` from analysis mapping file, but for people who merged multiple studies which were done using a variety of processing options, it's not possible to look up how exactly the input BIOM artifact has been processed.

This information is displayed before the analysis is created so it must be recorded somewhere. Exposing it to users later would be useful.

**Comment by tkosciol** [comment]
*some* of the info is in the mapping file, but not in GUI. Namely, `qiita_study_id` is in the mapping file, but there is no way to just view it in GUI.

What is not stored at all, is the processing info, so if someone generated a meta-analysis from various studies, it is not possible afaik to figure out what were the original artifacts used for this.

**Comment by stephanieorch** [comment]
I was asked at the Qiita meeting held on 8/29/18 to label issues I find crucial as "must-have". I am unable to add a label but I believe this is a must-have.
