### ISSUE TITLE
Beta group significance working in Qiime2 but not Qiita

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2568]
When I run the same beta group significance in Qiita and Qiime2. Qiita fails but Qiime2 works.

Qiita command: type_of_feed_7_d with job ID: b6d6d8ce-ed07-4330-b6bd-09b9defc571b
Error in beta group significance Std out: Std err: Plugin error from diversity: bottom cannot be >= top Debug info has been saved to /projects/qiita_data/tmp/qiime2-q2cli-err-yo5h4bed.log

Qiime command: qiime diversity beta-group-significance --i-distance-matrix beta_diversity.qza --m-metadata-file merge.tsv --m-metadata-column type_of_feed_7_d --o-visualization beta_group_sig.qzv
no error.

**Comment by stephanieorch** [comment]
It works on qiime2-2017.12 if I change --m-metadata-column to --m-metadata-category.

**Comment by antgonza** [comment]
K, thanks for checking.

**Comment by antgonza** [comment]
This was solved in the latests release as we updated qiime2.
