### ISSUE TITLE
Redbiom returning wrong number of artifacts

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2569]
When searching with Redbiom, the number of artifacts returned can greatly exceed the logical number necessary to access for the sample(s) searched for.

Steps to reproduce:
1) Go to qiita.ucsd.edu/redbiom
2) Enter "where anonymized_name == '000065978' "
3) Result:
![image](https://user-images.githubusercontent.com/27017606/39147460-7f4ab250-46ee-11e8-8d07-cc089c4fc963.png)

**Comment by antgonza** [comment]
Right, that number is showing the total number of artifacts in the study vs. how many have that sample ...

**Comment by adswafford** [comment]
Shouldn't it just show the number of artifacts with the sample? And likely the retrieval of all the artifacts is contributing to #2571 right?

**Comment by antgonza** [comment]
Agree, should be the number of artifacts with that sample

**Comment by antgonza** [comment]
I'm trying to figure out how to solve this and realized that I need some help from @wasade, asking here in case that we need input from others on how to better display the info or where to solve but happy to move to PM.

Anyway, in the specific example @adswafford used, we are basically looking in the sample template for `anonymized_name == '000065978'`, which in praxis it applies to all artifact/samples; however, ideally, we will only return the artifacts where this value exists. Another example for clarity, let's imagine that we have 2 preps, one with stool and another with oral; if we look for fecal in the sample info file both artifacts will be found (cause both have fecal in their sample info file).

Thoughts?

**Comment by antgonza** [comment]
ping @wasade

**Comment by wasade** [comment]
How can the a sample be both oral and fecal?

Doesn't qiita have mechanisms in place to determine what artifacts a set of
samples exist in? It seems unnecessary to use redbiom for that

**Comment by antgonza** [comment]
Ha! Just realized that my example can be confusing, sorry! The idea here is that in a study X, with prep A (artifact a) and prep B (artifact b) and a sample with anonymized_name == '000065978' in prep A; if you search for anonymized_name == '000065978', that will return study X but it will not give you that it only exists in prep A (artifact a). Please PM if this doesn't make sense.

Anyway, the point is that I'm not sure if redbiom can actually return the prep or artifact where anonymized_name == '000065978' is found. Obviously, we can recover this info within Qiita but just wondering if better/faster via redbiom as currently qiita will use SQL queries to figure it out.

**Comment by wasade** [comment]
If you know the context, you can do this. There isn't support if you do not
know the context
