### ISSUE TITLE
Filtering based on numbers doesn't understand < or > signals

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2572]
When I try to filter by age I have to do 1 number at a time because Qiita isn't recognizing the greater than or less than signs. The only signs the filtering command recognizes (based on what I've been using) are != and =.

**Comment by antgonza** [comment]
Do you have an example we can check? Perhaps a failure? Thanks!

**Comment by stephanieorch** [comment]
I can create one now. It doesn't fail or give an error, it's output just isn't correct. I've spoken to Tomasz about this before and we went through multiple ways to write the SQLite WHERE-clause, but it never worked. For example: Analysis ID: 16655 job ID: 72992a63-97e3-4d63-8172-b0a06ae234cc where I did age < 8 which created artifact ID: 52281. This artifact still contains ages > 8.

**Comment by adswafford** [comment]
I think this is more a documentation issue/a Qiime2 filtering issue unless the same filter terms do work in Qiime2? This should work if all the numbers are being interpreted as numbers afaik

**Comment by antgonza** [comment]
Just tested and is working in the new release; my example: `age >= 41 and age <= 71`.

Before the filtering:
<img width="816" alt="before" src="https://user-images.githubusercontent.com/2014559/48585509-18bf9480-e8ea-11e8-8856-eb092a315597.png">

After:
<img width="788" alt="after" src="https://user-images.githubusercontent.com/2014559/48585508-18bf9480-e8ea-11e8-9a3f-06a8994c010c.png">
