### ISSUE TITLE
Alpha Diversity Category Not in Order

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2573]
The alpha diversity category isn't in alphabetical order. This makes it difficult to find the category you're looking for when you have a lot of metadata.

**Comment by antgonza** [comment]
Could you add a screenshot of where you are seeing this issue?

**Comment by stephanieorch** [comment]
I apologize I did not see your prior post. Here is a screenshot of my categories when I run alpha diversity on Qiita.

<img width="218" alt="screen shot 2018-05-16 at 8 55 12 am" src="https://user-images.githubusercontent.com/31080457/40128942-d7368498-58e7-11e8-978a-83fa99371441.png">

**Comment by antgonza** [comment]
Got it, thanks! Note that this is something that comes from Qiime2 and I _think_ they solved it on the 06.2018 release. Closing here as this will be "fixed" once we push the newest Qiime2 version.
