### ISSUE TITLE
count of unique types of artifact in list of studies

### ISSUE THREAD

**Issue by tsonipeled** [biocore/qiita#2602]
feature request:

in the list of studies
https://qiita.ucsd.edu/study/list/

Under the column heading " expand for analysis" there are numerals and it is not  clearly defined what these numerals represent. It seems that these are the number of different types of artifacts available for each study, right?  Perhaps indicate that in the column heading?

Thanks for considering.

**Comment by antgonza** [comment]
@tsonipeled, thanks for the suggestion. The issue is the space that more text will take, do you have a recommendation for the new text?

cc-ing: @adswafford and @tkosciol in case they have any advice on this.

**Comment by tsonipeled** [comment]
something short, like "# of file types" or "Artifact count"  or something.   Whatever it is that those numbers are.
