### ISSUE TITLE
Include link to EMP protocol in tutorial

### ISSUE THREAD

**Issue by mortonjt** [biocore/qiita#2608]
It would be nice to include a link to the [EMP protocol](http://press.igsb.anl.gov/earthmicrobiome/protocols-and-standards/16s/) on the [prep template tutorial](https://qiita.ucsd.edu/emp/static/doc/html/tutorials/prepare-information-files.html).  This could help users figure out which primers they are actually supposed to use in their study

**Comment by adswafford** [comment]
@stephanieorch can you help?
