### ISSUE TITLE
qiime2 required for qtp-biom plugin installation

### ISSUE THREAD

**Issue by mflynn-lanl** [biocore/qiita#2609]
When I ran: `pip install git+https://github.com/qiita-spots/qtp-biom`
I got the following error:
```
Collecting qiime2 (from qtp-biom==0.1.0.dev0)
  Could not find a version that satisfies the requirement qiime2 (from qtp-biom==0.1.0.dev0) (from versions: )
No matching distribution found for qiime2 (from qtp-biom==0.1.0.dev0)
```
I tried installing qiime2 separately but it requires python 3.6 while the qiita environment uses python 2.7

**Comment by antgonza** [comment]
Hi @mflynn-lanl,

One of the main ideas behind Qiita is that you can have as many conda/virtualenv environments in your machine to satisfy as many plugins as needed and avoid dependency hell. In other words, you can have as many virtual environments as you need based on the plugins you want.

Anyway, good examples of this are (pointing to their Travis install instructions):
- [Deblur](https://github.com/qiita-spots/qp-deblur/blob/master/.travis.yml)
- [Shogun](https://github.com/qiita-spots/qp-shogun/blob/master/.travis.yml)
Note how in both, we install qiita in a Python 2.7 [environment](https://github.com/qiita-spots/qp-deblur/blob/master/.travis.yml#L15) and and the plugin in another Python 3 [environment](https://github.com/qiita-spots/qp-deblur/blob/master/.travis.yml#L29).

Now, for a basic install of qiita (for development) you don't need to have any plugins installed (the tests data comes with some basic "plugins") but to have all tests pass you would need the qtp-biom, here the [install instructions](https://github.com/biocore/qiita/blob/master/.travis.yml#L56).

Hope this helps.
