### ISSUE TITLE
Under documents, the Qiimp link does not work

### ISSUE THREAD

**Issue by shaekin** [biocore/qiita#2632]
The Qiimp link under documents does not work.  This also affects the "next" button at the bottom of the Getting Started Guide.

**Comment by shaekin** [comment]
The Qiimp link also disappears if you have selected Processing Data, redbiom, Analyzing samples, frequently asked questions, Glossary, references, Qiita philosophy (this one also capitalizes the redbiom link for some reason), Administrator tutorials, developer tutorials, and Resources (which also capitalizes redbiom).

**Comment by adswafford** [comment]
@stephanieorch Can you fix?

**Comment by stephanieorch** [comment]
this issue has already been brought up and should have been fixed in PR #2643
