### ISSUE TITLE
 Status code: "500" - Internal Server Error when searching for 'cheese' in redbiom

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2634]
Examples listed on appear to be working but a search for 'cheese' gives an internal server error.

![image](https://user-images.githubusercontent.com/27017606/43213288-1ed4c672-8feb-11e8-85cb-9cff3b81eadc.png)

**Comment by antgonza** [comment]
It seemed that we had a misconfiguration on some of the workers after a restart and that it has been solved. Thanks for the report!
