### ISSUE TITLE
Qiita Tree Not Working (but didn't check recently)

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2653]
Study 11712: ID: 51945

Study 11713: ID: 50560

**Comment by shaekin** [comment]
Qiita tree is still not working, tested on qiita-rc this morning (9/18/18)

**Comment by antgonza** [comment]
Could you clarify not working? What are the steps you did? This might be helpful: https://forum.qiime2.org/t/transferring-qiita-artifacts-to-qiime2/4790

**Comment by shaekin** [comment]
This is under qiita, so not a qiime command, but the default tree available for commands in qiita.  Here is a screenshot of the process I used to try to run it for Faith's PD:
![image](https://user-images.githubusercontent.com/31516412/45716473-db3dc580-bb4b-11e8-954a-1306678a6aa3.png)

**Comment by antgonza** [comment]
Got it, the confusion is that the issue described here is that the tree in the studies listed above did not work with Qiime2 import; which was an old issue.

Just to be clear, in analysis we cannot use phylogenetic measurements for deblur, only for close reference. cc-ing @charles-cowart as this is one of the issues he's gonna work during the next release cycle as discussed with @adswafford; just to be clear, the task is adding/using deblur trees for analysis.

**Comment by shaekin** [comment]
Okay got it!  That actually clears up a lot of confusion!  Thank you!

-Shae

**Comment by antgonza** [comment]
Clarified with the users; thus, closing.
