### ISSUE TITLE
review qtp validations for low hanging speed ups

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2675]
during today's meeting @wasade pointed out that it seems like the validation steps for demux and bioms takes longer than some of the processing steps. A possible improvement is to not use skbio for reading files but reading them directly ...

**Comment by josenavas** [comment]
Can the improvement be done directly in skbio to improve the performance globally rather than just in the qtp? Will help to reduce duplication of efforts.

**Comment by antgonza** [comment]
Closing as during the last couple of deployments we have improved performance of all the qtp.
