### ISSUE TITLE
Null owner

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2690]
Why is the owner shown as "null" in the study list view
![screenshot from 2018-10-02 15-50-40](https://user-images.githubusercontent.com/11960616/46352961-511d5300-c65b-11e8-8252-811050353d1d.png)
but set to a concrete value when looking at its details?

![screenshot from 2018-10-02 15-51-28](https://user-images.githubusercontent.com/11960616/46352990-61353280-c65b-11e8-9525-fe473ddc3200.png)

**Comment by antgonza** [comment]
Cause that User/Person has no name registered in the system ...

**Comment by antgonza** [comment]
.. and perhaps related to https://github.com/biocore/qiita/issues/304, as the study owners are different than the users of the system ...
