### ISSUE TITLE
Add Google Drive Upload to Qiita Upload Page

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2693]
Currently, you can upload files from your desktop or using scp. However, many labs have their sequencing data on their business google drives. If there was a way to upload documents from google drive it would save a lot of time for these users.

**Comment by justinshaffer** [comment]
If you have a business / academic email account, you can use Google Drive File Stream to do this. This will allow you to access your Google Drive as if it were an external storage device.

https://support.google.com/drive/answer/7329379?hl=en

**Comment by antgonza** [comment]
Thanks @justinshaffer! If I understand correctly, then this will mean that users can simply drag/drop to Qiita, right?

**Comment by justinshaffer** [comment]
Yep. I just started using it myself. You can path to it in terminal, and
drag and drop as you said.

Justin

**Comment by stephanieorch** [comment]
Yes, this is great! Thank you.

**Comment by antgonza** [comment]
Great, closing then ...
