### ISSUE TITLE
Add SILVA tree as phylogenetic tree option in analysis

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2697]
Users are able to do closed reference processing using the SILVA tree. But when they go to analyze these samples using phylogenetic metrics, the only available phylogenetic tree is the greengenes one- which spits out an error. So you need to add the SILVA tree to the phylogenetic tree analysis options when using data that was processed using the SILVA tree.

**Comment by rob-knight** [comment]
Note that SILVA, Greengenes and RDP all agreed in principle to use the GTDB taxonomy so developer effort would likely be best spent moving towards that goal than on legacy taxonomies.

On Dec 19, 2018, at 10:27 AM, Justin Shaffer <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree that adding the SILVA phylogeny for using with SILVA taxonomy would be very useful. Alternatively, if there was some way to match the SILVA taxonomy to the existing Greengenes phylogeny - that may also work.

I also see an argument here for including some sort of ITS phylogeny that matches the UNITE taxonomy. Issues inherent to that locus prevent the construction of a phylogeny across all of the taxonomy, but there may be a way to construct a unit-branch-length tree based on taxonomic hierarchy that would produce a pseudo-phylogeny that could be used in phylogenetic diversity analyses.

**Comment by antgonza** [comment]
Bringing to the top and we should do this with silva 132.

**Comment by justinshaffer** [comment]
SILVA recently released 138.1
https://www.arb-silva.de/documentation/release-1381/

Also QIIME2 now has a SILVA release 128 SEPP database on their resources page:
https://docs.qiime2.org/2020.8/data-resources/

I bring up the second point just to see if we want to implement it for any testing.

**Comment by antgonza** [comment]
Closing this in favor of https://github.com/biocore/qiita/issues/3037 as when we update we will also need to add the tree.
