### ISSUE TITLE
Add software version to bulk release

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2713]
Hi,
I am crawling through the rich data treasure of qiita in terms of the "public BIOM and metadata files". Many studies now have deprecated Deblur tables. I wonder how I can tell apart the deprecated ones from the current ones?
Thanks
Stefan

**Comment by sjanssen2** [comment]
![screenshot from 2018-10-25 12-04-45](https://user-images.githubusercontent.com/11960616/47492873-4c108580-d84e-11e8-842c-816c0560839d.png)

**Comment by sjanssen2** [comment]
e.g. for qiita_study_id==10541, Prep information 2079 - ID 2079 (16S)
How can I know if either "deblur reference hit table (ID: 60647)" or "dflt_name (ID: 28786)" is the deprecated one, when looking into the file QIITA-public-071518-010140.txt?

**Comment by antgonza** [comment]
Excellent point! Currently, there is not an easy way to do this; however, deblur 1.0.4 goes from 26532 to 56394 and 1.1.0 from 56423 to 63237. I'm gonna rename the issue to reflect that we need to incorporate the software version in the merging scheme and the merging scheme into the release. Thanks for reporting.

**Comment by antgonza** [comment]
I have added the group input label so we discuss the implication of this change (adding version) to the archiving mechanism in Qiita.
