### ISSUE TITLE
Deleting multiple artefacts to reprocess requires delete back to linked data artefact

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#2734]
It is really tedious and time-consuming to delete all the generated artefacts back down the tree.
An option to delete back to the linked data would be helpful when reprocessing

**Comment by antgonza** [comment]
While doing our annual clean up, I realized that there is a chance that the current implementation will not work. It will try to erase a parent with children.

It will be better to do something like this:
```
 [Artifact.delete(aaa) for aaa in sorted([aa.id for aa in Artifact(63406).descendants.nodes()], reverse=True)]
```

**Comment by antgonza** [comment]
Implemented https://github.com/antgonza/qiita/commit/a9990160430179bfa6fce0fce0ddb09ddfcea419
