### ISSUE TITLE
Add study id to stats map

### ISSUE THREAD

**Issue by stephanieorch** [biocore/qiita#2741]
When you go on Qiita and select "stats" under "More info" it brings up a map of the world. If you zoom out of this map and keep zooming out, it doesn't stop when the entire world is shown. Instead, the continents keep repeating....

**Comment by antgonza** [comment]
That has always been the behavior, which AFAIK it's the default in all this kind of apps. Now, do you have a suggestion for a better behavior?

**Comment by stephanieorch** [comment]
I would make it so you could no longer zoom out when the whole world is displayed.

**Comment by antgonza** [comment]
Adding in case it's useful. After a bunch of google searches it's clear that this is not an easy thing to do in OL, the new library we are using - cause it's open source.

A few good reads:
- https://openlayers.org/en/latest/examples/min-zoom.html
- https://stackoverflow.com/questions/23682286/zoomtoextent-openlayers-3
- https://github.com/openlayers/openlayers/issues/6648
- https://openlayersbook.github.io/ch09-taking-control-of-controls/example-05.html

Anyway adding the group input label so we can discuss.

**Comment by stephanieorch** [comment]
Going to add an additional thought here. Not sure if it's too difficult but... It would be really cool if you could click on the objects on the map and see the qiita study ID they came come. Maybe even the type of sample it is (if it's given). It's not necessary but considering how many papers have been coming out saying that location matters it could be a really cool addition!

**Comment by antgonza** [comment]
Agree, that could be cool but currently we are displaying public/private but if we decide to only show public here: https://github.com/biocore/qiita/issues/2689, we could add.
