### ISSUE TITLE
Color deprecated analysis artifacts black

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2747]

**Comment by adswafford** [comment]
Realized today when looking at an older artifact why we were concerned about this suggestion; every 2 months any artifact older than two months will show up as black/deprecated since Qiime2 will be updated, is that right?

**Comment by rob-knight** [comment]
I thought we were doing different colors for “newer version available” vs “bug found”?

On Dec 5, 2018, at 10:05 PM, adswafford <notifications@github.com<mailto:notifications@github.com>> wrote:


Realized today when looking at an older artifact why we were concerned about this suggestion; every 2 months any artifact older than two months will show up as black/deprecated since Qiime2 will be updated, is that right?

**Comment by rob-knight** [comment]
Shouldn’t those messages be more clearly distinguished as “a newer version of the software is available, which may or may not change results” vs “this artifact was produced by a software version with a known bug and the results are wrong, please re-run with the newer version” or similar?

On Dec 6, 2018, at 7:27 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>> wrote:


Current behavior:

  1.  If the software is marked as deprecated (for a bug for example) the circle is going to be black and when you click on the artifact we will get a "Warning, the software that generated this artifact is deprecated as a new version is available."
  2.  If the software is not marked as deprecated (just a new version is installed) the circle is going to be white (normal) and when you click on the artifact we will get a "Warning, the software that generated this artifact is deprecated as a new version is available."

We can change the color and message of those artifacts that fall into (2), suggestions are welcome. Note that the current "color schema" is:
[screen shot 2018-12-06 at 8 23 34 am]<https://user-images.githubusercontent.com/2014559/49593342-92b6cc80-f930-11e8-9150-92ab5082b12f.png>

**Comment by antgonza** [comment]
Thanks, we'll use those messages, what about color? Should we leave as white?
