### ISSUE TITLE
Require new accounts to agree to the terms and conditions with pop up

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2765]

**Comment by antgonza** [comment]
@adswafford Not sure if necessary, we already have text that says that clicking on the verification email means that you are accepting the terms/conditions: https://github.com/biocore/qiita/blob/master/qiita_pet/handlers/auth_handlers.py#L55. If you agree, can you close?

**Comment by antgonza** [comment]
@adswafford, ping on this ...

**Comment by adswafford** [comment]
Sorry, thought I'd messaged: no need for this after all
