### ISSUE TITLE
md5sum for artifact files

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2774]
I've downloaded a biom table a while ago, published a paper with these data and today someone requested information on how to reproduce results. I forgot to rename the suggested filename back than to include the artifact ID :-/ And the raw biom file also does not hold this information - at least not when using `biom summarize-table`. Thus, I have to compare md5 hash values. 
Could qiita somehow show those hash values for the file to download. That would save me downloading several files to computing and compare the md5s.

**Comment by justinshaffer** [comment]
In addition, it would be super helpful to have the file sizes displayed when given the option to download.
