### ISSUE TITLE
add Penguin McHelper to qiita

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#280]
So we can review new pages/additions/etc online.

**Comment by antgonza** [comment]
@emperor-helper This issue has almost 6 months open, do you have any updates?

**Comment by emperor-helper** [comment]
I don't.

**Comment by adswafford** [comment]
@ElDeveloper is this still an issue?

**Comment by antgonza** [comment]
Yup. The idea here is that it automatically deploys Qiita in our test servers ...

**Comment by antgonza** [comment]
I think this has been superseded by our deploy schedule and qiita-rc; thus, closing.
