### ISSUE TITLE
'Delete Job' Button

### ISSUE THREAD

**Issue by charles-cowart** [biocore/qiita#2800]
As part of what Gail and Jeff asked for, a Delete Job button is now much easier to do, with the addition of the ext_job_id column in the ProcessingJobs table. A Delete Job button handler could map the qiita id to Torque's job id, and issue a 'qdel' command. Would need to verify with Antonio how to clean up Qiita after a running job; my guess is that we could consider a deleted job as a job that error'ed out. However, we wouldn't want to post an error message in that case.

**Comment by antgonza** [comment]
point 3 on second list here: https://github.com/biocore/qiita/issues/2782
