### ISSUE TITLE
New User validation

### ISSUE THREAD

**Issue by charles-cowart** [biocore/qiita#2815]
Users appear to be following a link in their confirmation email and being taken back to the Qiita homepage, and not getting their permissions raised from 5 to 4 in the database.

**Comment by antgonza** [comment]
@charles-cowart, can you give an example of this issue? How difficult is to solve? Is this related to portals?

**Comment by charles-cowart** [comment]
After ‘Create User’ button is pressed, no message is given and the user is simply taken back to home. User will likely assume next step is to log in with created account and then will get the following error message:

![image](https://user-images.githubusercontent.com/42684307/54583726-55071c80-49d2-11e9-8741-846866c26685.png)

Once I look in my mail folder, find the activation email, and click on link, I get the following message:

![image](https://user-images.githubusercontent.com/42684307/54583731-5d5f5780-49d2-11e9-813f-720520fd03b4.png)

It seems like the broken link in the email was a momentary thing. I logged without problem, and confirmed in the database I am now level 4. The only improvement I can see is to present the user with a screen similar to this one from NanoHub:

![nanohub](https://user-images.githubusercontent.com/42684307/54583829-b0d1a580-49d2-11e9-9624-99a3a0203876.png)

Currently working on this.

**Comment by antgonza** [comment]
Thanks! Agree on adding. Note that the link issue might be while registering with portals, could you try?

**Comment by charles-cowart** [comment]
Confirmed w/Antonio that of the two other portals (EMP, Sloan), that Sloan's BASE_URL is misconfigured in its portal_config file. Jeff made the change and restarted. Confirmed Sloan and EMP portals are both returning the user to the front page.

**Comment by charles-cowart** [comment]
Pushing a PR that redirects the user to the front page, but with a green status window message (see below):
![bob](https://user-images.githubusercontent.com/42684307/54643396-08fcbc00-4a54-11e9-904d-d87f550f31ef.png)

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/2842

**Comment by antgonza** [comment]
Closed in the qiita 4.19 release to be deployed on May 15, 2019.
