### ISSUE TITLE
Migrate EBI Import codes from GUI to Qiita Plugin

### ISSUE THREAD

**Issue by charles-cowart** [biocore/qiita#2826]
EBI Import codes currently execute in Tornado's process space, and need to be moved to a Qiita plugin.

- [ ] Have EBI Import artifact automatically call Trim, Deblur. A good way to know if EBI import failed is if Trim fails. If the new artifact can create a Trim processing job, etc. that would be beneficial.

- [ ] Framework for EBI import needed in Qiita self-plugin. Charlie will create an empty framework to support EBI import as a Qiita self-plugin.

- [ ] Enhance documentation for installation, configuration, and security of plugins. Enhance documentation to describe the contents of plugin configuration files, where they should be placed, how keys can be generated, how to create whatever python environment is needed, etc.

- [ ] Test cases for EBI import. Test cases for EBI import as it is currently developed. We will migrate these as we migrate EBI import from code living in the GUI to a Qiita plugin.

Will assign Den as a co-assignee, once he is added as a contributor.

**Comment by charles-cowart** [comment]
#2827 #2825 #2824 #2823 are subtasks of this task

**Comment by antgonza** [comment]
@charles-cowart, just FYI, this is the original issue about this: https://github.com/biocore/qiita/issues/2322 ... I'm going to transfer this list there so we only one one issue about this.
