### ISSUE TITLE
Ensure unique IDs for metaanalysis

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#283]
...in the case of the same samples run on multiple sequencing platforms, the resulting IDs need to remain unique.

**Comment by antgonza** [comment]
I think this is not resolved for meta-analysis. Let's imagine that we have 1 sample that was ran with 454 and Illumina named: 'sample1', you preprocess and process, then you will have 2 otu tables with study-id.sample1, then you want to do a meta-analysis of both. This will result in a merge of the 2 samples ...

**Comment by josenavas** [comment]
Can we then change the title of the issue? It no longer applies to the sample/prep template upload (that is checked) it applies to when the OTU table for meta-analysis are created.

**Comment by antgonza** [comment]
Done.

**Comment by antgonza** [comment]
Closing this in favor of: https://github.com/biocore/qiita/issues/1236
