### ISSUE TITLE
Enable wild cards for scp file transfer?

### ISSUE THREAD

**Issue by FranckLejzerowicz** [biocore/qiita#2840]
Hi,
Would it be possible/easy to allow the use of wildcards for only uploading specific files from a folder and not only the full folder (and hence avoid user to create specific folders to import on the server).
Thanks
Best
Franck
<img width="1228" alt="Screen Shot 2019-03-12 at 3 38 24 PM" src="https://user-images.githubusercontent.com/29630133/54241105-65ecf500-44dd-11e9-9744-800ca74166d7.png">

**Comment by antgonza** [comment]
The code will automatically download all valid formats from a given folder so no need for wildcards or specific files. Note that the instructions have the valid formats and ask to have a single folder for all the valid formats:
<img width="1219" alt="Screen Shot 2019-03-12 at 4 46 41 PM" src="https://user-images.githubusercontent.com/2014559/54241480-abfa8680-44e6-11e9-861d-e6cc5a3439cc.png">
