### ISSUE TITLE
Add twitter feed sidebar to sitebase.html

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#285]
Probably not necessary for logged out people (but could be cool to have for logged out people displaying public study additions, etc.)

**Comment by squirrelo** [comment]
This is going in as part of the analysis messaging. Here are the steps as I see them:
* Every user has a redis key of `user:msgs` that holds a max of 10 messages
* Each message is a tuple of `(message, timestamp)`
* Show the 10 newest messages on the main page for each logged in user, with a link to a new page to see all 100.
* Add `user.add_message(msg)` function to add a message to the redis list. If more than 100 found, pop the oldest one. 
* In separate pull request(s) add messaging hooks for:
[] Shared study updated
[] Shared analysis updated
[] Analysis underlying data changed
[] New feature added to site

Note these will be more general messages, along the lines of "Underlying data on `analysis` has changed" with a link to the analysis and more details on the analysis results page.

If this is all that is needed, I can get this done relatively quickly.

**Comment by antgonza** [comment]
I think that makes sense. What about the user being able to delete messages that they do not want to see anymore?

**Comment by squirrelo** [comment]
You can't delete tweets, so you can't delete messages. I can add a "hide messages" link to hide them from the main page if they are unwanted.

**Comment by antgonza** [comment]
OK thanks. Just to confirm, they keep hidden when you changes pages, right?

**Comment by squirrelo** [comment]
It will be a system setting for the user, which means I probably need to add a column to the DB to track that.

**Comment by antgonza** [comment]
What about adding in redis?

**Comment by squirrelo** [comment]
Then it gets lost when redis restarts, which I guess isn't too bad.

**Comment by wasade** [comment]
Why would it get lost?

You can delete tweets btw

**Comment by squirrelo** [comment]
Ok, well for system messages it doesn't make sense to me that a user could delete them. Also, I thought redis was memory only, so it doesnt persist? Or does it write back to disk every so often?

**Comment by wasade** [comment]
it writes to disk at configuration defined intervals. so it has
persistence, but it is not reliable in the sense that there is potential
for data loss for things not committed to disk. for messages like this, i
think we can tolerate that

**Comment by josenavas** [comment]
:+1:
