### ISSUE TITLE
deblur/SEPP biom files lack taxonomy

### ISSUE THREAD

**Issue by tanaes** [biocore/qiita#2852]
When doing a meta-analysis with deblur tables, the artifacts come with the insertion phylogeny enabling phylogenetic analyses, but lack taxonomy metadata -- and there is no mechanism in Analysis for adding it back. This restricts the taxonomy-dependent Analysis commands to closed-ref tables. 

It would be nice to have taxonomy metadata in the deblur artifacts, too.

**Comment by antgonza** [comment]
A method to assign taxonomy has been added to qp-qiime2 and should be available after the next release ...

**Comment by antgonza** [comment]
Closed in the qiita 4.19 release to be deployed on May 15, 2019.
