### ISSUE TITLE
Allow anonymous access to public pages.

### ISSUE THREAD

**Issue by gavinmdouglas** [biocore/qiita#2858]
I'm having trouble determining the full link to certain downloads on qiita. I'm interested in downloading large zipped folders with wget on a server rather than downloading them locally through my browser (which does work).

For instance, the download link for "All QIIME maps and BIOMs" (based on "Copy Link Address") for study 11212 (https://qiita.ucsd.edu/study/description/11212#) is: https://qiita.ucsd.edu/download_study_bioms/11212

However, running wget with that link just returns the HTML of that page. Is there a way to get a link to the actual zipfile being downloaded?

Thanks,

Gavin

**Comment by antgonza** [comment]
Dear @gavinmdouglas,

Thank you for posting this issue. 

Sadly we currently only support downloads via a log in user. 

Anyway, we discussed this during our Qiita meeting and decided that we should allow for anonymous access so you can directly download public studies. By the way, if you are interested in CLI downloads, you could use [redbiom](https://github.com/biocore/redbiom).

Thus, renaming this issue.

**Comment by gavinmdouglas** [comment]
Ok thanks for clarifying @antgonza

**Comment by antgonza** [comment]
Hi @gavinmdouglas,

We had a quick online conversation about this issue and we realized that the fastest way forward was to simply open a new end point for public data so people could wget/curl public studies. This new functionality will be deployed on 07/15/19.

If you want to check how it will work visit: https://github.com/biocore/qiita/pull/2909

Cheers,
