### ISSUE TITLE
Collapse table by taxonomy fails 

### ISSUE THREAD

**Issue by RodolfoSalido** [biocore/qiita#2860]
I rarefied and filtered a BIOM table and then tried collapsing features by taxonomy at the class level but got the following error. 

Analysis ID:22818

Error executing Collapse features by their taxonomy at the specified level: ['Traceback (most recent call last):\n', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/qiita_client/plugin.py", line 255, in __call__\n qclient, job_id, job_info[\'parameters\'], output_dir)\n', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/qiita_client/plugin.py", line 100, in __call__\n return self.function(qclient, server_url, job_id, output_dir)\n', ' File "/home/qiita/qiita_spots/qp-qiime2/qp_qiime2/qp_qiime2.py", line 365, in call_qiime2\n for i in fout.ids(axis=\'observation\')}\n', ' File "/home/qiita/qiita_spots/qp-qiime2/qp_qiime2/qp_qiime2.py", line 365, in \n for i in fout.ids(axis=\'observation\')}\n', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/biom/table.py", line 1395, in metadata\n idx = self.index(id, axis=axis)\n', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/biom/table.py", line 1444, in index\n raise UnknownIDError(id, axis)\n', "biom.exception.UnknownIDError: The observation ID 'k__Archaea;p__Crenarchaeota;c__Thaumarchaeota' could not be found in the BIOM table.\n"]

**Comment by antgonza** [comment]
Hi @RodolfoSalido, thank you for opening. This is a bug within the qp-qiime2 plugin as it's trying to carry the taxonomy assignment to the new artifacts, we'll fix for the next release scheduled for mid May.

**Comment by antgonza** [comment]
This is being fixed in this PR: https://github.com/qiita-spots/qp-qiime2/pull/42

**Comment by antgonza** [comment]
Closed in the qiita 4.19 release to be deployed on May 15, 2019.
