### ISSUE TITLE
Add q2 metabolomics as processing option?

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2862]
Since q2-metagenomics is now available in the Qiime2 library (https://library.qiime2.org/plugins/q2-metabolomics/10/) can it be added, at least for admins, as a processing option once we're using Qiime2 for metagenomic data processing which I think was planned for the May update?

**Comment by antgonza** [comment]
At this stage we are only loading Q2 core plugins as this assures us having full support and compatibility as we move between Q2/plugin versions. Please coordinate with the Q2 plugin developers to verify when and if their plugin will become part of the core; once this is done, the plugin will be automatically added to Qiita. 

BTW this is part of the Q2 "raw data" processing which is not going to be available until the next (not the one we are currently working on) release.
