### ISSUE TITLE
Error when deleting multiple samples from a study

### ISSUE THREAD

**Issue by charles-cowart** [biocore/qiita#2885]
If a study has a large number of samples, such that the list of samples extends beyond the windowed space for the samples list, any samples marked for deletion that cannot be currently viewed do not get deleted when the user presses the delete button. As a side note, the number of studies in the delete button's confirmation dialog also reflect the smaller set.

**Comment by antgonza** [comment]
I can't reproduce this locally, could you add a gif showing it? Thanks!

**Comment by antgonza** [comment]
@charles-cowart and @ElDeveloper, are this and this https://github.com/biocore/qiita/issues/2885 issues related?

**Comment by ElDeveloper** [comment]
huh?

**Comment by antgonza** [comment]
Just wondering if those 2 issues are related cause they have to do with selecting/deleting samples ... perhaps not ...

**Comment by charles-cowart** [comment]
Uh, unless I'm missing something, this is issue #2885 that we're discussing things in. We'd need the second issue to make a comparison.

**Comment by antgonza** [comment]
duh! https://github.com/biocore/qiita/issues/2886

**Comment by charles-cowart** [comment]
It sounds like what @ackermag and I are referring to is the sample information file, while Yoshiki might be referring to prep. Gail and I are going to try recreating this issue this week.

**Comment by adswafford** [comment]
Steps to reproduce failure to delete:
1. add ~20 spurious samples to a study with hundreds of additional samples
2. locate these samples on the sample-prep summary view in the sample information page
3. select several samples and scroll down to where the samples are not visible
4. click the delete button

![QiitaGoogleChrome5_14_2019_odd_delete](https://user-images.githubusercontent.com/27017606/57743428-e1a02500-7679-11e9-97ef-93b1468e0ecf.gif)

Steps to produce failure to select all:
1. open any study with >53 samples
2. click the select all check box
3. scroll down and see that only the first 53 samples have been selected

![QiitaGoogleChrome5_14_2019](https://user-images.githubusercontent.com/27017606/57743148-cf71b700-7678-11e9-8658-18d524b464ec.gif)
