### ISSUE TITLE
Error when trying to filter samples from table. 

### ISSUE THREAD

**Issue by RodolfoSalido** [biocore/qiita#2899]
Qiita fails to filter samples from table and displays the following error. 

`Error executing Filter samples from table [filter_samples]: ['Traceback (most recent call last):\n', ' File "/home/qiita/miniconda3/envs/qiime2.2019.4/lib/python3.6/site-packages/qiita_client/plugin.py", line 266, in __call__\n qclient, job_id, job_info[\'parameters\'], output_dir)\n', ' File "/home/qiita/miniconda3/envs/qiime2.2019.4/lib/python3.6/site-packages/qiita_client/plugin.py", line 105, in __call__\n return self.function(qclient, server_url, job_id, output_dir)\n', ' File "/home/qiita/qiita_spots/qp-qiime2/qp_qiime2/qp_qiime2.py", line 468, in call_qiime2\n copyfile(tree_fp, new_tree_fp)\n', ' File "/home/qiita/miniconda3/envs/qiime2.2019.4/lib/python3.6/shutil.py", line 120, in copyfile\n with open(src, \'rb\') as fsrc:\n', "FileNotFoundError: [Errno 2] No such file or directory: '/projects/qiita_data/BIOM/74350/from_74315_insertion_tree.relabelled.tre'\n"]`

Screenshot:
![Screen Shot 2019-06-05 at 1 10 49 PM](https://user-images.githubusercontent.com/13193891/58986979-62db6b00-8793-11e9-8ffa-8e94b6eeb52a.png)

**Comment by RodolfoSalido** [comment]
When I tried downloading my files from Qiita to run on Qiime2 I couldn't download my phylogeny tree.

![Screen Shot 2019-06-05 at 2 45 23 PM](https://user-images.githubusercontent.com/13193891/58992839-bacc9e80-87a0-11e9-97ba-887b8adfa480.png)

**Comment by antgonza** [comment]
Thank you for the report. 

I looked into what could have caused this issue and I have no idea. Anyway, I have recovered the file and you should be able to redo your job in Qiita or download the file ... I'm gonna leave this issue open in case it happens again.

**Comment by antgonza** [comment]
Closing as we haven't had any other reports about this.
