### ISSUE TITLE
when adding a prep/sample info file make sure there is only one sample-id

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2906]
Turns out that if your mapping has the columns: sample_name and sample-id the system will load the file correctly, add the map and use sample_name as the main identifier; however, it will also add sample-id as a valid column and during processing these 2 columns will be merged/confused and nothing will be able to be processed successfully. 

Proposed solution: do not allow to add both (remove sample-id automatically) and warn users. 

cc: @justinshaffer, @adswafford; thoughts?

**Comment by justinshaffer** [comment]
Hi Antonio,

Thanks! I think your proposed solution sounds great. As long as the warning
makes clear which of the two variables remains, it should be equally clear
to the user which can be used for downstream filtering, etc.

Best,

Justin

**Comment by adswafford** [comment]
Yep, agree.
