### ISSUE TITLE
Convert status tables to have same convention as other constraint tables

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#292]
Currently the status tables do not follow the same convention as the filepath_type and other constraint tables. This means we can't use the convert_to_id and convert_from_id functions on the status tables. Needs to be fixed so we can use these functions.

**Comment by squirrelo** [comment]
We agree this needs to happen, as soon as the 3 main issues currently on the table are resolved.

**Comment by antgonza** [comment]
Closing in favor of: https://github.com/biocore/qiita/issues/410
