### ISSUE TITLE
Access to OTU sequences

### ISSUE THREAD

**Issue by aghozlane** [biocore/qiita#2949]
Dear Qiita developpers

We would like to search some 16S sequences in process data of qiita. Is there anyway to do it ?

**Comment by antgonza** [comment]
Please send questions to qiita.help@gmail.com. 

Suggest checking: 
- https://github.com/biocore/redbiom. 
- https://qiita.ucsd.edu/static/doc/html/redbiom.html
- https://qiita.ucsd.edu/redbiom/
