### ISSUE TITLE
timestamp for artifacts

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2974]
I thought completed an analysis some years ago. Of course paper submission got delayed and I am now asked to re-do some parts with a few additional samples. Thus, I'd like to know if I produced certain artifacts two years ago or three month ago - but I don't see an easy way to obtain this information.

Wouldn't it be great if Qiita could somehow indicate the time stamp for an artifact?

**Comment by antgonza** [comment]
@sjanssen2, if you click in any artifact; you will get a "Show processing information" button; then, if you click it you will see all the parameters + the timestamp of when the artifact was generated, like:
<img width="1138" alt="Screen Shot 2020-02-10 at 1 48 35 PM" src="https://user-images.githubusercontent.com/2014559/74188785-65d50800-4c0c-11ea-903e-5f97bc7dac2a.png">

**Comment by antgonza** [comment]
@sjanssen2, can we close this issue or is there any outstanding features?

**Comment by sjanssen2** [comment]
@antgonza if I had only seen this button :-)
