### ISSUE TITLE
wrong file size in display?

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#2977]
I just uploaded a file to qiita (fastq.gz) which shows in my HPC's (gpfs file system) terminal as:
`-rw-r--r--. 1 jansses ukdbork 14665415 Mar  9 14:30 PR17-A-S105_R1.fastq.gz` 
On my local laptop, it is `-rw-r--r--  1 sjanssen sjanssen  14665415 Mar  9 14:30  PR17-A-S105_R1.fastq.gz`.
However, once I uploaded it to qiita, and I check in the "Upload Files" section, its file size is displayed as `(14.7 MB)` (see below screenshot). However, I think it should be computed as `14665415/(1024^2) ~ 13.99`, but I figure what happens is `14665415/(1000^2) ~ 14.7`.
Bug or feature: [https://en.wikipedia.org/wiki/Mebibyte](https://en.wikipedia.org/wiki/Mebibyte)?
![Untitled](https://user-images.githubusercontent.com/11960616/76220024-0cfe8c80-6217-11ea-806d-0ba273cc26e2.png)

I'd prefer the 1024 version, since thus it would be easier to compare (by filesize) if all files have been transferred completely from my remote server to qiita. (Individual MD5 sums would be even better)

**Comment by antgonza** [comment]
I think 1024 is  better, thank you for catching and reporting!

**Comment by antgonza** [comment]
Looking at the code we are actually using the humanize package so we don't do the conversions and checking [their documentation](https://pypi.org/project/humanize/) the options are:
```
>>> import humanize
>>> humanize.naturalsize(1000000)
'1.0 MB'
>>> humanize.naturalsize(1000000, binary=True)
'976.6 KiB'
>>> humanize.naturalsize(1000000, gnu=True)
'976.6K'
```

I'm gonna issue a PR with `gnu=True`
