### ISSUE TITLE
Worst installation documentation ever 

### ISSUE THREAD

**Issue by Leob44** [biocore/qiita#3024]
Impossible to install :(

**Comment by antgonza** [comment]
Hi @Leob44,

Sorry that you are having such trouble with the installation! Can you send us the errors you are getting? 

Anyway, in case it helps, Qiita is a really complex server side software with multiple dependencies and requirements, which makes it not really intended for a "regular" computer or user to install and run for production. However, it's meant to run just fine on a laptop or small computer for development. For example, for every single PR and release, we install Qiita from scratch in travis, you can follow all the steps here: https://github.com/biocore/qiita/blob/master/.travis.yml. 

Hope this helps and looking forward to hear from you.

**Comment by antgonza** [comment]
Closing as it has been 23 days since the last update.
