### ISSUE TITLE
Updating WGS prep files adds "BarcodeSequence", LinkerPrimerSequence" to prep file

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#3035]
This should not happen with WGS preps.

**Comment by ackermag** [comment]
It may just be the warning message that needs to be removed - the columns were not downloaded or in the prep info summary page despite the warning

**Comment by antgonza** [comment]
Qiita no longer automatically produces QIIME1 or merges per preparation sample/prep files; thus, this no longer applies. 
Changed implemented in: https://github.com/biocore/qiita/pull/3043
