### ISSUE TITLE
Alpha rarefaction curves - issue with using 'Artifact tree...' when designating a non-phylogenetically informed metric

### ISSUE THREAD

**Issue by justinshaffer** [biocore/qiita#3039]
Hello,

When attempting to generate alpha rarefaction curves, I notice that when selecting 'Artifact tree, if exists' as the phylogenetic tree option, but using a metric that does not require a tree, that the following error is generated:

Error executing Alpha rarefaction curves [alpha_rarefaction]: ['Traceback (most recent call last):\n', ' File "/home/qiita/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiita_client/plugin.py", line 266, in __call__\n qclient, job_id, job_info[\'parameters\'], output_dir)\n', ' File "/home/qiita/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiita_client/plugin.py", line 105, in __call__\n return self.function(qclient, server_url, job_id, output_dir)\n', ' File "/home/qiita/qiita_spots/qp-qiime2/qp_qiime2/qp_qiime2.py", line 346, in call_qiime2\n if not fpath.endswith(\'.qza\'):\n', "AttributeError: 'NoneType' object has no attribute 'endswith'\n"]

... most likely because there is no artifact tree because the data are 18S. This does not happen when using the default GG tree. However, it would be nice to have the option for the phylogenetic tree not matter when using a non-phylogenetically informed metric. Not sure if this is possible but just wanted to bring this to your attention.

You can see the error here, but note that there are two failed artifacts so just make sure to check them both:

https://qiita.ucsd.edu/analysis/description/32263/

Thank you

**Comment by antgonza** [comment]
Fair enough, this should fix it: https://github.com/qiita-spots/qp-qiime2/pull/55

**Comment by antgonza** [comment]
Fixed by https://github.com/qiita-spots/qp-qiime2/pull/55
