### ISSUE TITLE
Upload files to a new study is taking so long

### ISSUE THREAD

**Issue by negin1986** [biocore/qiita#3044]
I tried to upload a biom file that is very small (~200kb) and I left it for one full day and the percentage sign did not change at all. Why is that?

**Comment by antgonza** [comment]
Hi @negin1986, 

Could you send us an email to qiita.help@gmail.com with your study id so we can take a closer look (*)? AFAIK there is nothing that should make uploading any kind of files hard or slower ...

Closing here as the plan is to follow up via email.

(*)
<img width="462" alt="footer" src="https://user-images.githubusercontent.com/2014559/98552512-c658aa80-225b-11eb-9385-6dc780d53939.png">

**Comment by negin1986** [comment]
Thank you for your reply. I just sent an email.
