### ISSUE TITLE
prep file with sample infos

### ISSUE THREAD

**Issue by sjanssen2** [biocore/qiita#3055]
if I download the prep file for ID 9771, I - as of today - get a table that additionally contains metadata from the sample information table. Is this a feature (I don't have to manually merge the sample infos to the technical prep infos) or a bug (because now pandas complains about duplicated keys, when doing so manually)?

**Comment by antgonza** [comment]
A side effect of yesterday's release/deployment. Thank you for catching and reporting. 

Basically, your prep was still pointing the merged sample/prep file (QIIME map), which is now deprecated. The easiest to fix is to simply regenerate the files in that prep - which I already did for your preparation and currently doing for all others affected by this. Could you check that the prep file is correct now? Just re-download.

**Comment by sjanssen2** [comment]
works for me, i.e. prep file contains only technical prep information, but no longer sample infos. Thanks!
Do I understand you correctly, that this was due to bad timing? Do I have to worry about other preps being affected?

**Comment by antgonza** [comment]
No need to worry about other preps/studies - it should be fine now.
