### ISSUE TITLE
Better feedback on wrong params in test env

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#312]
The unit tests depend on data files that live in qiita_db/support_files/test_data, but if you change the BASE_DATA_DIR in your qiita config file, then it looks in the wrong place.

Tests should write out whatever files they need (and then subsequently remove them), rather than depending on files to be located in a particular location.

**Comment by antgonza** [comment]
Changing title after feedback from @biocore/qiita-dev: "Better feedback on wrong params in test env". Basically, the solution for this will be to explicitly say what's wrong and ask the user to change it.

**Comment by antgonza** [comment]
I guess this was added some time ago but this issue was never closed. Note that we even have [a test checking for this](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template/test/test_base_metadata_template.py#L119).

**Comment by antgonza** [comment]
By mistake, added the message for another issue I was closing.

Anyway, this should be closed too as we have improved that feedback over time; if there are any other improvements please add them as new issues. Thanks.
