### ISSUE TITLE
Port iter_file_via_list_of_dicts to QIIME/scikit-bio

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#336]
This seems like a generally useful function that could fit either in QIIME or scikit-bio.

**Comment by antgonza** [comment]
Well, this function was removed from the EBI code as is not needed anymore. If you want to move it, you can find the code [here](https://github.com/biocore/qiita/blob/f5f595c397a5885ca6a8f673afd6d1f582e7658f/qiita_ware/ebi.py#L47). 

@ElDeveloper can we close as this is an issue that should be in skbio?

**Comment by ElDeveloper** [comment]
Thanks @antgonza, it seems like then we are not using it anymore here, so then we don't have an immediate use-case for it?
