### ISSUE TITLE
Make sure that PrepTemplate and SampleTemplate does not have columns in common

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#388]
as part of the metadata validation.

**Comment by antgonza** [comment]
I think this should be easy to implement if:
1. We check that sample template doesn't have any of the prep template required fields, and
2. We check that the prep doesn't have any overlapping columns names
Note that we need sample_name to relate both templates.

However, is not clear for me what should we do with the columns (1151) of the studies (224) that already have this problem. From a quick look it seems that 99% of them are fields that shouldn't be in the prep template but they are.

The SQLs I used to examine this, just for reference:

`select st.study_id, st.column_name, pt.prep_template_id from qiita.study_sample_columns as st join qiita.study_prep_template as stpt on st.study_id=stpt.study_id left join qiita.prep_columns as pt on stpt.prep_template_id=pt.prep_template_id where st.column_name=pt.column_name;`

`select distinct st.study_id from qiita.study_sample_columns as st join qiita.study_prep_template as stpt on st.study_id=stpt.study_id left join qiita.prep_columns as pt on stpt.prep_template_id=pt.prep_template_id where st.column_name=pt.column_name;`

**Comment by josenavas** [comment]
It may be worth double-checking, but I _think_ this is no longer an issue since we are adding a suffix to the prep template columns when we generate the qiime mapping file, which was where the problem appeared.

**Comment by antgonza** [comment]
Got it, didn't know that was the issue. However, I think it will be nice to not have duplicated information ...

**Comment by josenavas** [comment]
Not sure, but is possible that the information is not duplicated, is just that the columns have the same name (probably a bad design but can happen...)

**Comment by antgonza** [comment]
Again, possible but not desirable. Some of the column names are: year, collection_timestamp, center_name, watertimebarn; which clearly should be sample and not prep metadata.

**Comment by antgonza** [comment]
Turns out that this is more important than expected: if the sample info file has barcode/barcodesequence, it will take precedence over the prep info and will be reused. Moving to Alpha 0.3.

**Comment by josenavas** [comment]
what would be the proper handling? Raising an error or raising a warning?

**Comment by antgonza** [comment]
Note that also run_prefix matter. Error/Warning: I would say halt prep info addition until after the columns are not overlapping. Objections?

**Comment by ackermag** [comment]
I think that Antonio's suggestion is good.   How are we handling qiime mapping file addition where that information was (historically duplicated in both sample and prep with addition of _prep appended)?  Or was this already taken care of?
