### ISSUE TITLE
Implement qiita-db investigation object

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#40]
@squirrelo assigning to you as I already know that you are working on it

**Comment by ElDeveloper** [comment]
Fixed a while ago ... see [qiita_db/investigation.py](https://github.com/biocore/qiita/blob/e70868291d69cd9bb05c9b440ba46af6d96bacbd/qiita_db/investigation.py)

**Comment by squirrelo** [comment]
It's skeletonized but not actually fleshed out.

**Comment by ElDeveloper** [comment]
Oh ...

**Comment by antgonza** [comment]
closing this in favor of: https://github.com/biocore/qiita/issues/1393
