### ISSUE TITLE
Check for reference files before downloading them in qiita_env

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#425]
See #395.  Basically, what is needed, is to be able to predict what the file will be called (we already know it will be located in the `base_data_dir`), and then check for the existence of that file before downloading.

**Comment by antgonza** [comment]
This issue is being superseded by https://github.com/biocore/qiita/issues/1748 as then we will not require to download the references as part of the install and it will be part of the configuration/setup of the plugins. Closing.
