### ISSUE TITLE
preprocessed_status of "failed" for RawData could link to log_id

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#431]
See #427, and the comment:

> We might be able to standardize this, by having state be (status, log_id) where status is one of {'not_preprocessed', 'preprocessing', 'success', 'failed'} and log_id is None for all cases except failed, which has a reference to an actual log id in the qiita.logging table (probably the log_id from the job that was doing the preprocessing?)

regarding the setter for preprocessing_status

**Comment by antgonza** [comment]
This has been superseded by the processing job functionality AKA doesn't apply anymore.
