### ISSUE TITLE
Create a function for parsing templates consistently

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#449]
Although we are using the pandas dataframe from_csv parser, we are using multiple parameters that should be consistent across the project.

**Comment by antgonza** [comment]
During the string refactor we centralized all read/write functions to be all string and not duplicated. Please reopen if you think this is not accurate and list the places where this is not centralized. I looked around and could only find 3 instances of read_csv (2 tests, 1 in actual code) and 3 of to_cvs (1 for analysis - merging tables, 1 for code, and 1 for tests).
