### ISSUE TITLE
Refactor r_server

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#462]
Technically it is `r_client` as it is an instance of `Redis` and is a client to the Redis server

**Comment by antgonza** [comment]
@wasade could you elaborate on what kind of refactor is needed. A ToDo list will be great.

**Comment by wasade** [comment]
Rename r_server to r_client

**Comment by antgonza** [comment]
I looked everywhere in the code and couldn't find r_server, only r_client ... so closing!
