### ISSUE TITLE
Meta-analyses should use the last raw_data element

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#465]
We should not use the zero-th element as we are right now because that would be the oldest group of data that was uploaded, not the latest (which is the desirable case).

See the query in `Analysis._build_mapping_file`.

**Comment by antgonza** [comment]
@squirrelo https://github.com/biocore/qiita/pull/865 addressed this issue, right?

**Comment by squirrelo** [comment]
Yes

**Comment by josenavas** [comment]
#865 was not merged

**Comment by josenavas** [comment]
Solving as part of my latest PR: #1021
