### ISSUE TITLE
Use standardized reference to study name

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#469]
The uploaded studies right now are in the form PI_study_info or publication tile:
Study_name:  Bangladesh_Entamoeba_Gilchrist_Petri_Haque or Study_Title: Assessing the microbial community associated with intestinal pathogens.
Personally I think the Study name is more informative and easier to track.

**Comment by antgonza** [comment]
@ackermag I'm not sure this is a bug with qiita or an issue with how the EMP studies were created in the old db. Also note that you can edit all those titles via qiita. Closing for now as I think this is an old issue that doesn't apply anymore.
