### ISSUE TITLE
Upload JS var is not quite right on study_description.html

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#475]
[this line](https://github.com/biocore/qiita/blob/master/qiita_pet/templates/study_description.html#L128) is not quite right. If you go to a study description, and open the JS console in chrome, it complains about a syntax error.

**Comment by antgonza** [comment]
I do not think this is an issue any more, closing for now. Note that the pointed line doesn't even exist anymore. @adamrp please reopen if you think this shouldn't be closed.
