### ISSUE TITLE
Add built environment to Environmental Packages multiselect on Create Study

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#477]
Thanks for pointing this out @ackermag! What is the exact term we should use in the list? `built-environment`?

**Comment by antgonza** [comment]
I guess this was added some time ago but this issue was never closed. Note that we even have [a test checking for this](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template/test/test_base_metadata_template.py#L119).
