### ISSUE TITLE
fuzzy search on metatdata upload

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#481]
It would be awesome if, when metadata files are uploaded, each column is fuzzy-searched against all existing fields, and the system makes suggestions.  E.g., "You entered ph. We already have a column called pH. Use pH instead?" and then the user can select "yes" or "no" (default to..... yes?  thoughts?)

**Comment by squirrelo** [comment]
http://www.postgresql.org/docs/9.1/static/fuzzystrmatch.html

leaving this here

**Comment by squirrelo** [comment]
More to leave here: https://pypi.python.org/pypi/fuzzywuzzy/0.6.0
```python
from fuzzywuzzy import process

>>> x = [r[0] for r in conn.execute_fetchall('select column_name from qiita.study_sample_columns')]
>>> process.extractBests('text', x, score_cutoff=70, limit=2)
[('texture', 90)]

>>> process.extractBests('altitiue', x, score_cutoff=70, limit=2)
[('altitude', 88), ('latitude', 75)]

>>> process.extractBests('altitiue', x, score_cutoff=80, limit=2)
[('altitude', 88)]
```
With python-Levenshtein installed it's really, really fast too. Would be two more dependencies, however, but they are pip installable.

**Comment by antgonza** [comment]
Metadata search has been completely removed from Qiita as this falls into redbiom ... closing.
