### ISSUE TITLE
Add methods to check the level of a User object

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#493]
The User object should have methods to check whether a user is of a certain level or not i. e. `is_admin` to replace the equivalent `User.level == 'admin'`. The rationale here is that as we begin to grow the size of the codebase we will begin to see more statements that read `User.level == 'xxxxx'` to restrict/allow the rendering of certain parts of a template.

**Comment by antgonza** [comment]
closing in favor of: https://github.com/biocore/qiita/issues/493
