### ISSUE TITLE
EFO

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#494]
Is the EFO very important?  Currently, we are creating studies just passing 1 as the EFO id, since we don't have the EFO ontology.  Also, it is a required parameter on `Study.create`.  However, loading all the old studies into qiita is going to be very time consuming if we have to, for all 600+ studies, manually identify what set of terms from [the ontology](http://bioportal.bioontology.org/ontologies/EFO?p=classes&conceptid=root) pertain to that study.  For now, we are going to load things with EFO id 1, so that we can proceed with study loading and EBI submission for urgent studies, but we should either remove this requirement (I'm in favor of this), or put the structures in place to support it.

**Comment by antgonza** [comment]
@rob-knight should we remove Experimental Factor Ontology (EFO)?

BTW this is required in the study creation but as far as I can tell it's not actually sent or used by EBI.

**Comment by rob-knight** [comment]
If it is not used then yes: I suspect it's in the category of nice idea but
too hard to actually enter or use...

On Oct 10, 2015, at 10:53 AM, Antonio Gonzalez <notifications@github.com>
wrote:

@rob-knight <https://github.com/rob-knight> should we remove Experimental
Factor Ontology (EFO)?

BTW this is required in the study creation but as far as I can tell it's
not actually sent or used by EBI.

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/494#issuecomment-147112631>.

**Comment by antgonza** [comment]
As a group we decided to remove it from the code!
