### ISSUE TITLE
Freezer status metadata

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#5]
(from Rob) It would be REALLY useful to be able to detect which samples we had dna and/or physical specimen left over in the freezer.

**Comment by antgonza** [comment]
How do we want to deal with this? These are not required fields for any of the templates and it sounds more like a standard that we want to impose in the template generation (perhaps in the weblab) and not in Qiita.

**Comment by josenavas** [comment]
I think this should be move to the labadmin project - qiita is not a labadmin site to deal how our freezers are organized.

**Comment by ackermag** [comment]
This will be fairly easy to track for studies sequenced by us in the wetlab
but will not be generally available.  Right now I usually assume that the
physical specimen is not available unless it is AGP (potentially available)
or a study I am familiar with (like Jess M soils) where I know there is
physical specimen.  Many times we have to return the specimen to the
collaborator and have no knowledge of what happens to it.


On Mon, Oct 12, 2015 at 9:09 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> How do we want to deal with this? These are not required fields for any of
> the templates and it sounds more like a standard that we want to impose in
> the template generation (perhaps in the weblab) and not in Qiita.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/5#issuecomment-147448228>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
From your replies it sounds like we can close as it's not longer within the scope of the template validations. Please, reopen if you think otherwise.
