### ISSUE TITLE
Make queue stats available - to track upload

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#503]

**Comment by nbokulich** [comment]
I second this comment. This was a feature from qiime-db that I felt was useful. If something crashes/disconnects half way through an upload, or if you need to stop for any other reason, it is good to know which files uploaded successfully and which were interrupted.

**Comment by adamrp** [comment]
This is partially ameliorated by the fact that the uploader is now resumable (and I believe the resumability is resilient enough that even given an unexpected connection loss, it will still be able to resume; is that accurate @antgonza?)

**Comment by antgonza** [comment]
Yup, you can also pause it, change networks, etc. This will work well
under two conditions: do not terminate your session (log out) and do
not refresh the page. However, let us know if it doesn't work well for you.

**Comment by antgonza** [comment]
@ackermag @nbokulich do you think the current solution works or will you like to have something different? If different, could you give specific suggestions? Thanks!

**Comment by nbokulich** [comment]
I think the current solution works, but it is not immediately apparent
(i.e., while the pause button is there, it is not clear that, e.g., the
upload will continue following a prolonged interruption or break in
connection). Adding something like check marks to show which files have
finished uploading could be useful, if merely esthetic.

**Comment by antgonza** [comment]
That makes sense, thanks. This should be easy to solve by adding some info in the upload page.
