### ISSUE TITLE
Admin page to view the logging table

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#508]
Currently have to view log entries manually.

**Comment by antgonza** [comment]
@wasade do you still feel that we need a command to retrieve this? I think is not needed cause if you have access to the terminal, you also have access to the db and could run commands in there.

**Comment by wasade** [comment]
When debugging a critical system failure, the difference between these two scenarios is monumental:

```bash
$ qiita log | more
```

and

```bash
$ psql -d qiita
> \d foo
> \d bar
> --- look at about 20 tables to figure out what you need to join
> select asdfasdfasdfasd  -- screw up about 20 times getting the query right
```

**Comment by antgonza** [comment]
See your point.
