### ISSUE TITLE
Use glyphicon glyphicon-arrow-left for the back button on metadata overview

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#509]
See #474 and [this page](http://getbootstrap.com/components/)

**Comment by gregcaporaso** [comment]
I think this looks a little odd:

![screenshot 2015-03-09 17 51 56](https://cloud.githubusercontent.com/assets/192372/6567463/09a92546-c685-11e4-970b-adf3bc4f8744.png)

I think it'd be better to just rely on the browser's *Back* button.

**Comment by gregcaporaso** [comment]
It sounds like the browser back button doesn't always work, so will submit this change.
