### ISSUE TITLE
Check dropbox for filename conflicts on EBI submit

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#517]
The way EBI works is by having a single, flat directory where all our files are uploaded.  This means that if we have two studies and there are samples names that are shared between studies (which is common for BLANK samples), the submit will fail because the there will be a filename collision.  Therefore, we should check the dropbox before attempting submission to make sure that there will be no collisions.

**Comment by antgonza** [comment]
I think this issue doesn't apply anymore as we are prepending all samples with study_id. Thus, the only time there is going to be a collision is if we resubmit the study, which is fine. Please reopen if you think this is not solved.
