### ISSUE TITLE
Use transaction blocks during item insertion

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#527]
Pull request #512 added in the ability to use transaction blocks for SQL commands. We should use these when creating new items into the database that take multiple SQL commands (e.g. a new sample template or a new prep template) so we can maintain database integrity.

**Comment by antgonza** [comment]
I think this is already solved so closing. If you think there are parts that still need this modification could you list them? Thanks.

**Comment by squirrelo** [comment]
This is exactly what I said I would do in the meeting yesterday.

**Comment by ElDeveloper** [comment]
Just to add, any object inserting data into the DB, should also log and handle insertion failues (using the Log object).

**Comment by squirrelo** [comment]
Fixed as part of transaction addition.
