### ISSUE TITLE
Show links to all the sequence files of artifacts used in an analysis

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#534]
Ideally being able to grab the sequences from a meta-analysis.

**Comment by antgonza** [comment]
This issue has been changing focus during it's life; the latests is to download all the sequences from a meta-analysis. IMOO this has been surpassed as a requirement for the system + the BIOM Qiita artifact stores deblur sequences as their ids for a meta-analysis of deblured sequences; in other words, the biom table has the sequences as ids; thus, allowing to have all sequences from the study. Additionally, now an analysis builds a tree on the fly, when possible. Anyway, I think this can be closed.

@ElDeveloper, what do you think?

**Comment by ElDeveloper** [comment]
Although I don't have this use-case, I believe users could still want to use the sequences for an alternative sequence clustering method. Which is not something you would want to do from deblurred sequences.

**Comment by antgonza** [comment]
OK, I would not recommend users to do that but sounds like a fair use case, what about showing in the analysis a link to the raw data that generated each artifact being used? This will allow users to select which raw data they want to download ...

**Comment by ElDeveloper** [comment]
Yes, I think that would likely be helpful. Only missing point to something like that would be to also provide the preparation files so that the sequences could be processed as needed with any barcode/primer/linker information.

**Comment by antgonza** [comment]
Got it, thanks! Should we provide prep information or full qiime1 mapping files?

**Comment by ElDeveloper** [comment]
Come to think of it, that information would already be included as part of the mapping file used for analysis. Therefore linking to all the sequence files of studies (where sequences can be shared) would probably be sufficient.

**Comment by antgonza** [comment]
The analysis/meta-analysis page contains a summary of all the studies used to create it. Each row contains a link to the study page, which then provides a single link to download all the raw data, if the owner allowed to download the raw data, and/or bioms, with sample and prep information files. Thus, a user can download with 2 clicks each of the studies raw data for any given meta-analysis. 

Example here; taken from: https://qiita.ucsd.edu/analysis/description/15093/ 
![studies_public_analysis](https://user-images.githubusercontent.com/2014559/67636996-db0a1080-f89b-11e9-8882-c93d59d707ef.gif)

Thus, closing.
