### ISSUE TITLE
SQLConnectionHandler and scikit-bio 0.2.1

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#551]
Currently we depend on 0.1.4, which does not have this utility function. Once the qiime PR for skbio 0.2.1 compatibility is in, we need to also update qiita to support it and add the call to that utility function to the SQLConnection handler.

**Comment by antgonza** [comment]
This is not fixed, right?

**Comment by ElDeveloper** [comment]
I don't think I understand the issue at all :L

**Comment by squirrelo** [comment]
There's an explicit flatten function defined in the sql handler that can be replaced by scikit bio now that it's updated.

**Comment by ElDeveloper** [comment]
Aaaaahhhhh, got it, thanks for explaining. Whatever happened to
glowing-dangerzone? Are we not gonna use that project anymore?

**Comment by josenavas** [comment]
That's probably my fault... We need to take a look if there is any open issues in there and change qiita to use it. I will assign the issue to myself and try to tackle it this week!

**Comment by squirrelo** [comment]
Depricated in newer versions of skbio, so closing.
