### ISSUE TITLE
Add information to the Help link

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#571]
- Geolocation tool (@teravest can you provide the link to the tool that you found the other day).
- What are these characters in my sample/prep template? We discussed with @rob-knight that we should systematically convert all non-UTF-8 characters and replace them with a set of characters like `XXXX`.

In some sense this should be geared, at first, to EMP-collaborators/users.

Please add anything I may have missed.

**Comment by antgonza** [comment]
@ElDeveloper can we close this?

**Comment by ElDeveloper** [comment]
Yes
