### ISSUE TITLE
Be able to (re)name prep templates

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#597]
Even so that the id is useful, it will be better if we could name raw data. For example, if an experiment has 2 raw datas be able to name them V2 and V4 or whatever.

**Comment by antgonza** [comment]
When this issue was created renaming the raw data made sense, now it should be the prep template. Renaming the issue.

**Comment by josenavas** [comment]
As discussed in here https://github.com/biocore/qiita/pull/1241#issuecomment-109338432 we should do this for any object of the study:
- [ ] PrepTemplate
- [ ] RawData
- [ ] PreprocessedData
- [ ] ProcessedData

**Comment by antgonza** [comment]
Solved in: https://github.com/biocore/qiita/pull/1738
