### ISSUE TITLE
scikit-bio warnings while running the test suite

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#619]
We should remove these:

```
/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/skbio/parse/sequences/fasta.py:135: UserWarning: `parse_fasta` is deprecated and will be removed in scikit-bio 0.3.0. Please update your code to use `skbio.io.read(fh, format='fasta')` to obtain a generator of `BiologicalSequence` objects (or subclasses, see the `constructor` parameter).
  "subclasses, see the `constructor` parameter).", UserWarning)
/Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/skbio/parse/sequences/fastq.py:125: UserWarning: `parse_fastq` is deprecated and will be removed in scikit-bio 0.3.0. Please update your code to use `skbio.io.read(fh, format='fastq')` to obtain a generator of `BiologicalSequence` objects (or subclasses, see the `constructor` parameter).
  "subclasses, see the `constructor` parameter).", UserWarning)
..../Users/yoshikivazquezbaeza/.virtualenvs/qiita/lib/python2.7/site-packages/skbio/format/sequences/fastq.py:71: UserWarning: `format_fastq_record` is deprecated and will be removed in scikit-bio 0.3.0. Please update your code to use `skbio.io.write`.
  UserWarning)
```

**Comment by antgonza** [comment]
This is still present in the latests builds but I can not reproduce it in my local machine, any idea of why this can be?

**Comment by ElDeveloper** [comment]
Not sure what that may be happening, maybe you are using an older
version of scikit-bio one which doesn't raise the deprecation warnings?

**Comment by antgonza** [comment]
Nop, using the latest repo version. Perhaps the issue comes from skbio
and not from qiita, are you using the latest repo or package version?

**Comment by ElDeveloper** [comment]
I'm using the 0.2.2 but Travis is using 0.2.1, so maybe that's why you
are not seeing the warnings in your system?

**Comment by antgonza** [comment]
That's my guess, could you test with the latest repo version?

**Comment by ElDeveloper** [comment]
I just installed scikit-bio 0.2.2-dev and I could not see any warnings
when running the full test suite, so maybe updating the version in
setup.py is the solution?

**Comment by antgonza** [comment]
Yes but I think it will be better to wait for the next release of
skbio, what do you think? BTW this issue should be closed as this is
really a skbio issue.

**Comment by ElDeveloper** [comment]
I agree on waiting for the next release. However, the reason why I
opened this issue here is because the deprecation warnings indicated
that we were using soon to be deprecated function calls.

**Comment by antgonza** [comment]
Yes but those calls are internal to skbio, it's own internal functions
are calling depricated versions. There is nothing we need to solve
within qiita.

**Comment by ElDeveloper** [comment]
Hmmm, that seems odd, but if we don't have those in the code-base then
we should be good to go then.
