### ISSUE TITLE
Select previous raw data menu should have a "non selected" default

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#637]
When you go to the study description page the menu that displays other raw datas you have access to is an empty box. This box should have a placeholder that reads something like: `Create new raw data` or `New raw data` or `Non selected`.

![screen shot 2014-11-18 at 4 41 57 pm](https://cloud.githubusercontent.com/assets/375307/5098315/eb05826e-6f41-11e4-9e2c-0a87c254de8e.png)

**Comment by antgonza** [comment]
@ElDeveloper can we close this? The selectors are completely different now.

**Comment by ElDeveloper** [comment]
Yeah, makes sense.
