### ISSUE TITLE
suggested rarefied level

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#650]
From @clozupone. Rewriting: add a way to know the sequences per sample in a meta-analysis before defining the rarefaction level.

**Comment by gregcaporaso** [comment]
What if you store the number of sequences per sample in the database, and then when the user selects their samples you could display the histogram of number of sequences per sample? To assist the user in making their choice, you could annotate (e.g.) the 10th, 20th, 25th, 50th, 75th, 80th, 90th percentiles in that distribution and note what fraction of their samples they'd discard with each level.

**Comment by rob-knight** [comment]
Great idea!


On Mar 11, 2015, at 7:23 PM, Greg Caporaso <notifications@github.com<mailto:notifications@github.com>> wrote:


What if you store the number of sequences per sample in the database, and then when the user selects their samples you could display the histogram of number of sequences per sample? To assist the user in making their choice, you could annotate (e.g.) the 10th, 20th, 25th, 50th, 75th, 80th, 90th percentiles in that distribution and note what fraction of their samples they'd discard with each level.

**Comment by wasade** [comment]
Just an extension, I like the thought of storing within the BIOM table
similar to how we store stats in the demux files. Since we're pending a
minor release for biom, we could actually just get this lumped in as a new
option to the table summarizer (--save-stats). Fetching the stats would not
require a parse of the table, just opening the h5py file. However, storing
in the db is light as well, but it puts the stats further away from the
actual data they represent.

**Comment by antgonza** [comment]
I have been thinking about this and I can see the benefits of the described approaches. However, thinking pragmatically about this, the histograms need to be good but not prefect. With this in mind, what about adding a step in the processing step (otu picking) so a default histogram is generated and we add this information to the process data table as an array or ints? The default histogram can be from 0->50K (we can discuss this or we can create a histogram of all the current biom tables so we get a better range) with 100 or 1K points. With this approach we can quickly display the histogram of one biom but more importantly can show histograms of each process data and the combination of all for metaanalyses. Finally, this solution is really easy to implement and has minimal DB changes. What do you think?

**Comment by wasade** [comment]
This should break down to:

Table = load_table(foo)
Res = hist(table.sum(axis='sample'))

Recommend storing the bar positions and height instead of a PDF so that the
visual can be changed in UI if needed, but path of least resistance is just
generate the image for display

**Comment by antgonza** [comment]
Yes, simple addition. We could store positions and height with the default 10 values and on merge we simply display the combination. Note that this might not work well when you start filtering down samples by metadata ...

**Comment by gregcaporaso** [comment]
I've got code for this (and for making the plots interactive) - code here
<https://github.com/gregcaporaso/q2d2/blob/master/q2d2/__init__.py#L265>,
example image attached. Feel free to use - just throw an attribution in as
a comment.

[image: Inline image 1]

**Comment by clozupone** [comment]
Sounds great!

On Oct 23, 2015, at 9:09 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Yes, simple addition. We could store positions and height with the default 10 values and on merge we simply display the combination. Note that this might not work well when you start filtering down samples by metadata ...

**Comment by antgonza** [comment]
Solved in https://github.com/biocore/qiita/pull/1738. 

Now, every artifact has it's own summary. For example a biom has:
<img width="842" alt="screen shot 2016-04-03 at 8 47 49 am" src="https://cloud.githubusercontent.com/assets/2014559/14232993/e0aed9e2-f978-11e5-8c6c-5807fe8bd5b9.png">
Which should help you decide your rarefaction level.
