### ISSUE TITLE
Focus on the PI validation on study creation/edition does not work

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#664]
Looks like an issue in bootstrap. We need to take a deeper look

**Comment by antgonza** [comment]
Just to expand on the explanation of the issue (took me some time to understand it):
When creating a study if Principal investigator is not set (doesn't have any value), the form doesn't submit but it doesn't tell you that this info is missing.

**Comment by gregcaporaso** [comment]
This turns out to not be a quick fix after some discussion. @squirrelo, reassigning to you, thanks for the help!
