### ISSUE TITLE
raw_data download

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#685]
From @adamrp: 
For each study, we need to do a demultiplexing WITHOUT quality filtering so that the user is only provided the option to download the raw sequences that pertain to that study.

**Comment by antgonza** [comment]
AFAIK this issue was related to EBI and as https://github.com/biocore/qiita/issues/1116 has been closed, I'm closing this one. Please open if you feel this is not accurate.

**Comment by josenavas** [comment]
I don't think it is accurate. The problem is that currently users cannot download their own raw data - but I'm unsure why shouldn't we allow to download the raw data files (without demultiplexing). The interface currently doesn't allow this, and I'm unsure if the new interface fixes, so re-opening.

**Comment by antgonza** [comment]
Good point. Let's discuss it in the meeting.

**Comment by antgonza** [comment]
Solved in: https://github.com/biocore/qiita/pull/1738. Note that the solution is that only the owner, guest and admins can download.
