### ISSUE TITLE
Add system documentation

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#694]
We need to add documentation that describes the site, it should be Sphinx generated and include guides on:

- [x] How to create a study and upload data to a study.
- [ ] How to create a meta-analysis.
- [x] What data formats do we expect.
- [ ] How to clean-up metadata using Google Refine

A link to the documentation should be provided from the Help button.

**Comment by antgonza** [comment]
Closing this as we have documentation and specific issues for the missing points.
