### ISSUE TITLE
Potential security issue on checking `is_local_request`

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#719]
From @wasade:

> @antgonza @ElDeveloper, I think we want to modify the nginx config to pass on host. See here and here. The issue is that I think the XSRF stuff in tornado (which we should enable if it isn't already) could muck with nginx. The specific issue with this line is that without XSRF, I believe this line is a potential security issue as headers can be spoofed. However, I don't think the consequences are great

Specific line (not pointing the code in case the line # changes):

``` python
is_local_request = ('localhost' in self.request.headers['host'] or '127.0.0.1' in self.request.headers['host'])
```

**Comment by antgonza** [comment]
closing in favor of https://github.com/biocore/qiita/issues/507
