### ISSUE TITLE
Do we really need portal type?

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#720]
Right now is hard coded.

**Comment by antgonza** [comment]
From internal conversation:
All studies should be accessed from at least one "master portal", so power users don't have to search through several to find the study they're looking for. However, we should allow branding different portals, for exaple: EMP, Sloan, american gut, likely others in future

**Comment by josenavas** [comment]
The resolution in this is "YES, we need it". Ideally we want to be able to change the look in the page based on portal type, and the studies shown are based on the portal type.
