### ISSUE TITLE
SQL exception when adding a prep template in which IDs do not overlap with sample template

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#739]
Here is the message I got back:

"Error running SQL query: INSERT INTO qiita.common_prep_info (prep_template_id, sample_id, center_name, center_project_name, emp_status_id) VALUES (%s, %s, %s, %s, %s) ARGS: [(2L, '2.861.C13.5.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.C15.dec08', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.C17.dec08', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.C18.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.C4.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.C4.mar09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.CS.dec08', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.H10.4.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.H10.mar09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.H4.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.H4.mar09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.U10.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.U70.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.U80.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.X10.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.X10.mar09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.X52.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.X60.dec08', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.X70.jul09', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.X83.dec08', 'ANL', 'Moore_Yucatan_cenotes', 1), (2L, '2.861.XS.dec08', 'ANL', 'Moore_Yucatan_cenotes', 1)] Error: insert or update on table "common_prep_info" violates foreign key constraint "fk_common_prep_info" DETAIL: Key (sample_id)=(2.861.C13.5.jul09) is not present in table "required_sample_info"."

**Comment by squirrelo** [comment]
fixed in pull request #870
