### ISSUE TITLE
display better error when emp status is not correct

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#741]
Currently the user get an 500 error but it should get the actual error so it can be fixed and the possible options accepted.

**Comment by squirrelo** [comment]
Is this still applicable as that column is no longer required?

**Comment by josenavas** [comment]
Yes, as nothing has been merged to solve this. Re-assigning to me as I will solve it. If you see more issues related with the metadata, please, assign to me so I can fix them during my metadata refactor.

**Comment by antgonza** [comment]
@josenavas can we close this?
