### ISSUE TITLE
Should scrub empty rows before parsing templates

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#746]
Excel has a habit of leaving empty rows resulting in full rows of `Nan` in the `DataFrame`s

**Comment by ElDeveloper** [comment]
Hmm, just tested and if the rows are empty, these will be dropped if they are loaded with `load_template_to_dataframe`, however when I added a few spaces to some of the cells the rows were kept. To fix this issue, we need to remove rows that have no sample identifier.

**Comment by antgonza** [comment]
Seems reasonable to me.

**Comment by wasade** [comment]
+1
