### ISSUE TITLE
Improve feedback on what required_sample_info_status is

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#747]
Users are not sure what to put there or what to do with the error if the field is filled out incorrectly.

**Comment by squirrelo** [comment]
Is this still an issue, as that column no longer exists? Or has this now moved to processed_data_status?

**Comment by josenavas** [comment]
I need to remove the column. Still not fixed, soon.

**Comment by ackermag** [comment]
So I shouldn't be adding that column?


On Wed, Apr 29, 2015 at 3:13 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> Closed #747 <https://github.com/biocore/qiita/issues/747>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/747#event-293509184>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by ElDeveloper** [comment]
AFAIK you are correct, @josenavas can confirm.

**Comment by josenavas** [comment]
Correct, the column is no longer needed! You can take a look to the updated [wiki page](https://github.com/biocore/qiita/wiki/Preparing-Qiita-template-files) to see the new columns! Hopefully these changes makes your work easier!
