### ISSUE TITLE
when unlinking files do not remove but return to upload folder

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#748]

**Comment by antgonza** [comment]
After taking a look at this issue, we have 3 options: (1) rename and change the remove_filepath methods within the rawdata so they move the files to the upload folder, (2) add a flag (move_to_upload_folder=True) to those methods so the files are not removed but moved, or (3) leave those methods as they are and create new ones with the requested functionality. @josenavas @wasade what do you think?

**Comment by josenavas** [comment]
My vote goes for (1), but we should be able to delete files from the upload folder.

**Comment by antgonza** [comment]
OK, thanks. Agree about the upload folder but that's a separate issue.

**Comment by josenavas** [comment]
:+1:

**Comment by antgonza** [comment]
@josenavas After a second look I think it will be better to write a new methods to replace purge_filepaths to move_filepaths_to_upload_folder, mainly because the raw data will still remove the file paths but at the end we can simply replace that function so the files get moved vs. purged.
