### ISSUE TITLE
PNGs being saved to qiita user's home dir

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#761]
Somehow, png files (which look like results of alpha rarefaction) are being saved into the qiita user's home directory (there are currently ~1500 files in the directory).  This might require a database data patch to fix, as some of the files might be associated to results in the DB.

**Comment by adamrp** [comment]
This is actually a QIIME issue (see biocore/qiime#1852), which has been addressed (see pull biocore/qiime#1862), so updating to 1.9.0 on qiita.colorado.edu should resolve this issue. The png files that were being generated are not in the filepaths table on terrance, so I do not think a patch will be required.

**Comment by antgonza** [comment]
The system has been updated and this doesn't happen any more.
