### ISSUE TITLE
Make sure that filepaths are added to the DB without spaces

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#762]
And any other weird character. Any file path provided by the user can potentially include weird and space characters, breaking the calls to the qiime commands. @antgonza found this while adding a reference set to the database, but this issue impacts any filepath stored in the database.

**Comment by antgonza** [comment]
@josenavas has this been fixed?

**Comment by josenavas** [comment]
I don't think there is any specific check in place yet...

**Comment by antgonza** [comment]
Closing in favor of: https://github.com/biocore/qiita/issues/1570. Basically, the same issue.
