### ISSUE TITLE
Error messages are being logged with a large number of characters

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#775]
There have been a few error messages showing up in the logging table that are so large that they cannot be displayed on the user interface and psql is having trouble printing this to the screen.

Try something like to see what I mean:

```
select time, length(msg) from logging order by time desc limit 50;
````

Do not try to get the full msg string, otherwise you will lock your psql session.

**Comment by antgonza** [comment]
Suggest doing: http://stackoverflow.com/questions/5331320/psql-save-results-of-command-to-a-file
for debugging.

**Comment by ElDeveloper** [comment]
Thanks @antgonza. @squirrelo also suggested doing:

```
SELECT SUBSTRING(msg, 0, 1000) from logging ORDER BY time desc limit 10;
```

Which also works.
