### ISSUE TITLE
prep_template_filepath should have unique constraint

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#779]
this table (and probably several others that reference the filepath table) should have unique constraints. In this case, the unique constraint should be on prep_template_id

**Comment by ElDeveloper** [comment]
@adamrp, would you mind commenting if this is still true.

**Comment by adamrp** [comment]
Yes, I believe so. Right now, there is no unique constraint on the `filepath_id` column of the prep_template_filepath table. This means that multiple prep template IDs can reference the same file.

So far, we don't have this problem on live (no filepaths are referenced by multiple prep templates), but it would be good to get this preventative measure in place.

The same goes for other tables referencing the filepath table -- the assumption being that we typically don't want to reference the same file multiple times in such tables.

**Comment by antgonza** [comment]
I just checked all the tables in the current version of the html and all have this FR constrain. Closing.
