### ISSUE TITLE
Prep templates not deleting correctly

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#781]
We need to make the delete function (and really all the stuf like it) a transaction block. We are already seeing issues where everything but the actual reference in the `prep_template` table is deleted, causing issues with processing.

**Comment by antgonza** [comment]
Can this be closed? I think this was addressed in https://github.com/biocore/qiita/pull/866 and https://github.com/biocore/qiita/pull/850, right? If not please describe what's missing.

**Comment by josenavas** [comment]
Not really... I think the deletion of the prep templates should be also a transaction block. I used transaction blocks for template creation, but not deletion...

**Comment by antgonza** [comment]
OK, thanks for checking.
