### ISSUE TITLE
Sample template headers are limited in length

### ISSUE THREAD

**Issue by borax** [biocore/qiita#785]
I'd like to have the full OTU taxonomic assignment (down to genus) as a header and the corresponding relative abundances of that OTU in each sample filling down the column in the sample template so that I can color PCoA plots by OTU abundance later on. However, I get this error message upon submitting my sample template.

"Error running SQL query: INSERT INTO qiita.study_sample_columns (study_id, column_name, column_type) VALUES (%s, %s, %s) ARGS: [(10080, 'root_p__cyanobacteria_c__chloroplast_o__streptophyta_f___g__', 'float8') 
# Insert rest of my long headers here
] Error: value too long for type character varying(100)

Is it possible to allow longer headers?

Thanks!

**Comment by adamrp** [comment]
Yes, we should do that. Right now, it is limited to 100 characters, but this is not necessary. We should create an SQL patch that updates that column.

**Comment by ackermag** [comment]
previously was limited to 35 characters....

On Wed, Jan 7, 2015 at 5:45 PM, adamrp <notifications@github.com> wrote:

> Yes, we should do that. Right now, it is limited to 100 characters, but
> this is not necessary. We should create an SQL patch that updates that
> column.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/785#issuecomment-69119094>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
ackermag@ucsd.edu

**Comment by adamrp** [comment]
That may have been a limitation of the QIIME database, but it is not enforced by QIIME itself, and I do not see any reason to enforce this limitation in Qiita -- unless we are relying on tools that impose this limitation, but AFAIK we are not.

**Comment by ackermag** [comment]
Agree - just saying...

On Wed, Jan 7, 2015 at 6:02 PM, adamrp <notifications@github.com> wrote:

> That may have been a limitation of the QIIME database, but it is not
> enforced by QIIME itself, and I do not see any reason to enforce this
> limitation in Qiita -- unless we are relying on tools that impose this
> limitation, but AFAIK we are not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/785#issuecomment-69120469>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
ackermag@ucsd.edu
