### ISSUE TITLE
add more to text file downloads of taxa tables?

### ISSUE THREAD

**Issue by ksteenwerth** [biocore/qiita#787]
Hello:

Is it possible to add information indicating project name, datasets used, date of processing and analysis in QIITA to text files of taxonomic tables that are downloaded from QIITA? Could the taxonomic level be annotated on the downloaded text file of the taxonomic table (and graph) as well so it can be determined at a glance (phyla, class, family...)? Notation on parameters that we might be able to change prior to generation of the table, versions of QIIME and GreenGenes used to generate the table (as this is required during publication) on a downloaded text file could also be helpful. The same information would be helpful for the graphs and downloaded, especially when returning to datasets in the distant future. Certainly, we should plan to record this information and it will be in QIITA, I'm assuming, but it could still be helpful for documenting efforts. Just a thought - but I do understand if there are other reasons related to data analysis prohibiting this step.

Will OTU tables be available in the future?

Thank you -
Kerri

**Comment by antgonza** [comment]
Decision to make the info available via the summary so it can be downloaded as a html.

**Comment by antgonza** [comment]
This was addressed when we moved to a Qiime2 analytical plugin:

![screen shot 2017-11-28 at 4 14 22 pm](https://user-images.githubusercontent.com/2014559/33349465-697a0692-d457-11e7-8d15-0c488d493a73.png)
