### ISSUE TITLE
Cannot download and re-upload a prep template

### ISSUE THREAD

**Issue by ChristineLowe** [biocore/qiita#790]
Hi,

During the MoBE workshop I loaded a prep workbook that successfully demultiplexed my data.  I downloaded the Prep template and tried to reupload it as a test after having troubles with the demultiplexing.  When you try to re-add this prep template in the raw data tab you get the error message:

An error occurred parsing the prep template: 10079_prep_146_20150107-145042.txt
Error running SQL query: INSERT INTO qiita.common_prep_info (prep_template_id, sample_id, center_name, center_project_name, emp_status_id) VALUES (%s, %s, %s, %s, %s) ARGS: [(159L, '10079.10079.Amendglobalreg1dust1', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust10', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust11', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust12', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust13', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust14', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust15', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust16', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust17', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust18', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust19', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust2', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust20', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust21', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust22', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust3', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust4', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust5', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust6', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust7', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust8', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3), (159L, '10079.10079.Amendglobalreg1dust9', 'Agriculture and Agri-Food Canada', 'SLOAN Microbiology of the built environment', 3)] Error: insert or update on table "common_prep_info" violates foreign key constraint "fk_common_prep_info" DETAIL: Key (sample_id)=(10079.10079.Amendglobalreg1dust1) is not present in table "required_sample_info".

I believe that it should be possible to upload prep templates downloaded from qiita.

Another problem may be that the "Primer" column in the original prep template is changed to "linkerprimersequence" when the file is downloaded.  

Thanks,

**Comment by josenavas** [comment]
Hi @ChristineLowe 

When you download the prep template from Qiita, the sample_names have been changed by prefixing them with the study id. In your case, the original sample name was `Amendglobalreg1dust1`, and it was changed to `10079.Amendglobalreg1dust1`. When you re-upload it, it gets changed again prefixing the study id `10079.10079.Amendglobalreg1dust1`. The system is trying to search that sample name on your sample template, and it cannot find it; so that's why it is failing. Try removing the `10079` from all your sample names in your prep template and you will be able to re-upload it.

The change of `Primer` to `linkerprimersequence` is done in order to normalize that column name, so we accept both names.

**Comment by ElDeveloper** [comment]
Maybe we should offer a way to download unmodified templates.

Yoshiki Vázquez-Baeza

**Comment by antgonza** [comment]
I think the most convenient thing for users will be to accept already valid files as input so basically:
- If all the samples in the study or prep template already have the study_id. prefix, do not add, and
- Accept either primer or linkerprimersequence as input

**Comment by adamrp** [comment]
I thought the plan here was to leave the sample names as they were when they were uploaded, and only add the `study_id.` prefix when doing a meta-analysis, to ensure that sample names are unique when multiple studies are being analyzed using the same prep/sample templates?

**Comment by antgonza** [comment]
That's not the case.

**Comment by squirrelo** [comment]
No, the names are stored with the prefix, but we need to strip it off when downloading so we can keep things consistent, since it's something we add internally for tracking purposes.

**Comment by adamrp** [comment]
FWIW, I think we should go the other way with this (append the study_id prefixes only when necessary, i.e., during a meta analysis) rather than always. That is, unless there is a bunch of code I'm not yet familiar with that depends on these prefixes existing for all sample_ids.

**Comment by antgonza** [comment]
In my experience, after doing a lot of meta-analysis, we should always
append the study_id, and have "easy" ways, like the a simple
validation, to not add them. I can honestly say that I can't think in
a case that not having it will be helpful for the user or anyone.
However, I can see the confusion about it if we do not have
documentation for  it.

**Comment by josenavas** [comment]
One of the goals of prefixing the sample ids with the study id is to ensure that the sample ids are unique at DB level. I'm going to start working on this issue now, I hope to get something in later today.
