### ISSUE TITLE
Naming of columns in the Prep template

### ISSUE THREAD

**Issue by ChristineLowe** [biocore/qiita#791]
Hi,

In the original Qiime mapping file you were required to provide the linkerprimer in a single column.  In the Qiita prep template provided (https://docs.google.com/spreadsheets/d/1hKgz5cAk8KtN92mginROYXpAHH1gJtAPsYUBV0T66iM/edit#gid=522299903) these are listed in separate columns.  However if you separate your linker from the primer as the columns indicate the data is not able to be demultiplexed as it finds errors in the primer sequence.  The DNA sequence in the Primer column must be the linkerprimer for demultiplexing to successfully occur.  The description of this column should reflect this.   

It is good to note that if you download a successfully uploaded prep template that this column is renamed to linkerprimer.  

Thanks,

**Comment by josenavas** [comment]
Hi @ChristineLowe 

Probably the naming is confusing, but you should put your Linker and Primer under Primer (that's why we rename primer to `linkerprimersequence`.

Hope this helps!

**Comment by antgonza** [comment]
This is an issue with the general instructions and how it is in handled in qiita vs. how it was in the old qiime db, we need to come to an agreement of how we will deal with this as a group.

**Comment by antgonza** [comment]
@ChristineLowe I think this issue has been solved by the tutorial documentation: http://qiita.ucsd.edu/static/doc/html/tutorials/prepare-templates.html, what do you think?

**Comment by ackermag** [comment]
Does this mean that linker and primer are not required in prep_template?

On Sun, Oct 11, 2015 at 6:31 PM, Antonio Gonzalez <notifications@github.com>
wrote:

> @ChristineLowe <https://github.com/ChristineLowe> I think this issue has
> been solved by the tutorial documentation:
> http://qiita.ucsd.edu/static/doc/html/tutorials/prepare-templates.html,
> what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/791#issuecomment-147270875>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment]
Yes, they are not. However, this will not allow you to preprocess. The idea is that different data types can have different requirements and preprocessing pipelines.

**Comment by antgonza** [comment]
Closing as we reached an agreement and added to the documentation. Please reopen if you think otherwise.
