### ISSUE TITLE
QIIME sample id naming constraints are not enforced

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#792]
Sample identifiers can include underscores and the system will not raise an error.

**Comment by antgonza** [comment]
Stop adding issues!!

**Comment by ackermag** [comment]
Can we define these constraints?
Gail

On Wed, Jan 7, 2015 at 5:53 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> Sample identifiers can include underscores and the system will not raise
> an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/792>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
ackermag@ucsd.edu

**Comment by ElDeveloper** [comment]
This website has more information: http://qiime.org/documentation/file_formats.html

Yoshiki Vázquez-Baeza
