### ISSUE TITLE
Send emails informing users when processing is done

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#794]
Large amount of requests for emails sent when raw data, preprocessing, and processing is done, as well as when analyses are done processing.

**Comment by antgonza** [comment]
Where do we want to have this? The options I see are: MOI, callback function at the end of pipeline, or somewhere else (not sure where) 

cc @wasade @josenavas @squirrelo

**Comment by antgonza** [comment]
@wasade I think this should be in qiita.

The places we want to have emails sent are:
- [ ] link files to raw data
- [ ] preprocessing
- [ ] processing
- [ ] meta-analysis, per job? I think a single one once all the jobs are done should be sufficient

**Comment by wasade** [comment]
Seems reasonable. Was there something specific you'd like me to comment on?

**Comment by antgonza** [comment]
No really, at this point I'm not sure why I added @wasade ...

**Comment by wasade** [comment]
hahaa :)

**Comment by cuttlefishh** [comment]
Would be nice to have this. Seems very useful to users.

**Comment by antgonza** [comment]
closing in favor of https://github.com/biocore/qiita/issues/2054
