### ISSUE TITLE
Add-person Fields too narrow on half-screen window

### ISSUE THREAD

**Issue by jwdebelius** [biocore/qiita#806]
I was setting up a study last night, and needed to add a person. With my browser occupying half my screen, the fields were narrow, but a lot of the browser space was unused.

![Screen shot](https://www.dropbox.com/s/bivqlo2u98qd55e/Screen%20Shot%202015-01-19%20at%209.33.18%20PM.png)

**Comment by antgonza** [comment]
@jwdebelius, want to solve this issue but not sure how to reproduce and the screenshot is gone. Could you let me know? Thanks.

**Comment by jwdebelius** [comment]
It looks like Bootstrap has fixed the problem, thanks.

**Comment by antgonza** [comment]
Thank you!
