### ISSUE TITLE
Verification email has hardcoded URL

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#810]
When I registered at qiita.colorado.edu, I receieved an email with a verification link for qiita.colorado.edu. When I clicked the link, it of course did not work; when I change the URL manually to qiita.ibdmdb.org, it works.

**Comment by squirrelo** [comment]
Already taken care of by the commit "make base URL a config option" https://github.com/biocore/qiita/commit/fe95acb20d72f78c283457b431cf6bdbba6fbef9
