### ISSUE TITLE
sortmerna preindexed references

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#811]
Currently we are using the fna reference, which means that every single picking indexes the reference. We should be using the already indexed files.

**Comment by josenavas** [comment]
Adding here what needs to happen for this to be in, so we can keep track:
- [ ] Modify the DB to support the SortMeRNA indexed database (#1155)
- [ ] Modify the CLI interface to accept the SortMeRNA indexed database
- [ ] Create a qiita_ware command to index the DB (done in the cluster)
- [ ] Add a 24.py patch that will index the database for the already existing DBs using the previous command.
- [ ] Modify the processing pipeline to use the reference database if it already exists

**Comment by josenavas** [comment]
Moving this to alpha 0.3

**Comment by antgonza** [comment]
Closing in favor of: https://github.com/biocore/qiita/issues/1748. Note that the resolution is basically to discard the reference DB and use the local paths to reference them. Thus, this will be solved then.
