### ISSUE TITLE
Ability to set options for analyses

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#812]
We need to let users to set options for alpha diversity etc. before running the analysis. It will default to defaults but tweaking should be allowed.

**Comment by squirrelo** [comment]
Here is the proposed change to the database. It removes the options from the command table and instead adds another table for storing the options and related information for them.

![screen shot 2015-01-29 at 9 30 52 pm](https://cloud.githubusercontent.com/assets/3079066/5971240/95eeedce-a7fe-11e4-9744-1eeec9559d58.png)

**Comment by antgonza** [comment]
:+1:

**Comment by adamrp** [comment]
Looks good to me

**Comment by antgonza** [comment]
@josenavas @squirrelo can we close this? If not, could you describe what's missing? Thanks.

**Comment by squirrelo** [comment]
The UI for actually changing the options still isn't in master, so this still is not complete.

**Comment by antgonza** [comment]
Solved in the current analysis pipeline.
