### ISSUE TITLE
adding a previously added raw data, adds all available raw datas to that user

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#817]

**Comment by squirrelo** [comment]
Could you explain this one a bit more? I'm not quite sure what that means.

**Comment by antgonza** [comment]
Yup. Let's say that you have 5 studies and all of them have raw data and 3 of them have processed raw data. Then you create a new study and you want to link one of the 2 not processed raw data to this new one, when you select it the 3 processed raw data get linked to your new study. Note that I haven't really looked into what's causing this but I'm describing the GUI behavior.

**Comment by antgonza** [comment]
Figure it out, will issue a PR soon.
