### ISSUE TITLE
Allow to share and edit general study info

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#819]
If a study, let's say an EMP study, has a misspelling in the name or has the wrong metadata only admins can updated them as they are public. It will be great if we can share them so the owner of the samples can review this and also allow them to make changes.

**Comment by squirrelo** [comment]
This may open a can of worms since our entire logic from the beginning has been "Once this is public only admins can touch it." If we start letting people edit public studies themselves, it goes against this logic, since public studies are supposed to be set in stone unless admin action is taken.

**Comment by josenavas** [comment]
@squirrelo There is some information that does not generate any problem. E.g. if something that simple like the study name is misspelled or the contact information is wrong, the user should be able to change that. Other things like metadata and/or environmental packages are more tricky, so we should not allow to change those things.

**Comment by adamrp** [comment]
@josenavas when adding samples to a new meta analysis, the user is allowed to search for any column (including the study name or the contact information). What criteria are we using to determine which columns are safe to change?

**Comment by josenavas** [comment]
@adamrp good point. This type of issues require a lot of thinking/discussion of the implications

**Comment by antgonza** [comment]
Closing as we will not allow due to the complexities here ... and as we have fixed most/all(?) EMP studies ...
