### ISSUE TITLE
Duplicate sample templates error?

### ISSUE THREAD

**Issue by borax** [biocore/qiita#820]
I have encountered an error in processing my sample template. I uploaded a version that had some formatting errors, tried to correct them, and then uploaded a new version of my sample template. I received this error:

Error running SQL query: INSERT INTO qiita.required_sample_info (study_id, sample_id, physical_location, has_physical_specimen, has_extracted_data, sample_type, required_sample_info_status_id, collection_timestamp, host_subject_id, description, latitude, longitude) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) ARGS: [(10091, '10091.0.71', 'UC Davis', False, True, 'Feces', 4, '12/1/13 13:30', 'Davis', 'unknown', 38, 122)

#Insert rest of my samples and metadata here

] Error: duplicate key value violates unique constraint "idx_required_sample_info_1" DETAIL: Key (sample_id)=(10091.0.71) already exists.

I believe this issue has something to do with having uploaded and tried to process the sample template twice (since it seems to be referencing a sample that I know is not duplicated in my sample template), but I may be wrong.

Help?

**Comment by antgonza** [comment]
Thanks you for reporting this, I believe this is related to: https://github.com/biocore/qiita/issues/749 

Anyway, the current solution is to remove those samples by hand. Could you send me an email to antgonza@gmail.com for coordination?

**Comment by adamrp** [comment]
@antgonza was there any followup on this discussion?

**Comment by borax** [comment]
@antgonza and I emailed back and forth a bit, he found a few problems in my sample template, I fixed them, and re-ran it through Qiita. I got another error (similar to the above one) that I can't explain, and I emailed him about it. I am waiting to hear back.

**Comment by ackermag** [comment]
This is the same error that Nick was getting and relates to a very old bug
- soultion to Nick's problem was to create a new study


On Tue, Mar 10, 2015 at 12:39 PM, Zachery Lewis <notifications@github.com>
wrote:

> @antgonza <https://github.com/antgonza> and I emailed back and forth a
> bit, he found a few problems in my sample template, I fixed them, and
> re-ran it through Qiita. I got another error (similar to the above one)
> that I can't explain, and I emailed him about it. I am waiting to hear back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/820#issuecomment-78131538>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by ElDeveloper** [comment]
This is no longer an issue.

**Comment by antgonza** [comment]
Just to clarify, the issue was that the insertion of sample/prep
templates was done outside a transaction so if something failed after
a insertion was successful, the next time around the system will
report that X sample was already added. This issue was solved by the
introduction of queues and we purge the system of all these failed
samples.

**Comment by borax** [comment]
I tried again today and got what seems like a very similar error message:

An error occurred parsing the sample template: Secretor_Sample_Template3.txt
Error running SQL query in queue CREATE_SAMPLE_TEMPLATE_10091: INSERT INTO qiita.required_sample_info (study_id, sample_id, physical_location, has_physical_specimen, has_extracted_data, sample_type, required_sample_info_status_id, collection_timestamp, host_subject_id, description, latitude, longitude) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) ARGS: (10091, '10091.0.71', 'UC Davis', False, True, 'Feces', 4, '12/1/13 13:30', 'Davis', 'unknown', 38.2458, 122.6314) Error: duplicate key value violates unique constraint "idx_required_sample_info_1" DETAIL: Key (sample_id)=(10091.0.71) already exists.

Is this a legacy of the fact that my project was created before you applied the fix, or does it mean your fix didn't work? Or is this unrelated?
