### ISSUE TITLE
update/modify metadata

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#822]
I think we need to be able to update metadata (update values) at any point or status of the samples. However, we should have some limitations based on adding/removing samples. Add allowed at any point but remove will only be allowed if not public. 

Some other pointers from @josenavas:
Correcting data of existing studies (i.e. host_common_name is unknown but it has to have a different value) and adding new samples (ie. more samples have been collected, they are added to the sample template and a new prep template is added). Also allow

**Comment by wasade** [comment]
Will be adding in methods at the `qiita_db` level shortly. Have logic/tests in place but working on improving consistency with the existing API

**Comment by antgonza** [comment]
Just so whoever address this knows: the main backend functionality was added by @wasade here https://github.com/biocore/qiita/pull/824

**Comment by squirrelo** [comment]
I'm going to subsume this as also the ability to add samples to a pre-existing study, as that came up in the meeting today.

**Comment by josenavas** [comment]
Re-opening. Currently it only applies to sample templates. This should be able in prep templates, specially for missing data in case of EBI submission (e.g. `center_name`)

**Comment by squirrelo** [comment]
Can you add this to the alpha 0.1 or 0.2 zenhub queue, whichever is appropriate?

**Comment by josenavas** [comment]
I'm not using zenhub sorry...

**Comment by josenavas** [comment]
We are able to modify everything, so I think this can be safely closed. I open a new issue to keep track of the UI changes to allow this on prep templates (https://github.com/biocore/qiita/issues/1130) and another issue to keep track of the user notification when the template information changes (https://github.com/biocore/qiita/issues/1129)
