### ISSUE TITLE
password reset does not work

### ISSUE THREAD

**Issue by clozupone** [biocore/qiita#828]
I forgot my QIITA password and so I hit the "Forgot password" link. I got a link in my e-mail to reset the password, but when I go to that link, there is no option to reset the password.

**Comment by antgonza** [comment]
The issue is that if there is a message on the system, either
sysmessage or lock, the reset and the submit to VAMPS/EBI stop
working.

@clozupone, I have cleared the message we had system wide, now you can
reset your password.

**Comment by clozupone** [comment]
Thanks Antonio!

On Feb 7, 2015, at 8:08 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>>
 wrote:

The issue is that if there is a message on the system, either
sysmessage or lock, the reset and the submit to VAMPS/EBI stop
working.

@clozupone, I have cleared the message we had system wide, now you can
reset your password.
