### ISSUE TITLE
Samples column should not be sorted lexicographically

### ISSUE THREAD

**Issue by mwhall** [biocore/qiita#831]
In the study results table (such as http://qiita.colorado.edu/study/public/), the Samples column reports the number of samples in the study. It currently sorts lexicographically, but this is not very useful. It should sort numerically.

**Comment by adamrp** [comment]
This is due to the subpackage we are using to display those tables. Not
sure whether the sort can be changed to natsort easily, but we will
investigate. Thanks for pointing that out!

**Comment by adamrp** [comment]
Quick googling (no time to implement/test right now) turns up this plug-in:

http://datatables.net/plug-ins/sorting/natural

**Comment by ElDeveloper** [comment]
As far as I remember, there is a way to pass your own sorting function.

**Comment by squirrelo** [comment]
Here is how to do it: http://datatables.net/plug-ins/sorting/

**Comment by adamrp** [comment]
Still requires the natural sorting plug in (which I linked in my previous
post), unless I'm misreading?

**Comment by squirrelo** [comment]
"The main DataTables package includes sorting functions for strings, dates, numeric and currency data..." so this just says how to format it to use the numeric sort.
