### ISSUE TITLE
If email verification code expires, user is stuck in limbo

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#833]
If you attempt to register and get to the stage where the system sends you a verification code via email, but then you do not verify your email address in the allotted time, you cannot proceed with the system. You cannot create a new user because the user technically already exists (and user_level = 5), and you cannot verify the email address because the verification code in the email has expired.

Possible solutions:
1) If the verification code expires and the user has not verified their email address, then remove the user from the system.
2) If someone tries to create a new user and the user already exists, but is unverified (user_level=5), then allow the creation of the user, and send a new verification code to the email address specified.

I vote for option 1. Thoughts?

**Comment by wasade** [comment]
:+1: on 1

**Comment by josenavas** [comment]
:+1: on 1

**Comment by antgonza** [comment]
:+1: for 1

**Comment by adamrp** [comment]
Okay, I think that's enough of a consensus. I will also have it send the unverified user another email saying that they have been removed from the system because they failed to verify their email address.

**Comment by ElDeveloper** [comment]
Why do the verification code has to expire? I would expect for it to be
active until I verify my account. Although the two options seem
reasonable, they don't seem optimal, just my two cents.

**Comment by adamrp** [comment]
My mistake -- they don't expire; I was confusing this with pass reset codes, which do expire. I misidentified the issue because I was using the verification email I got from qiita.ibdmdb.org, which linked me to qiita.colorado.edu (this hardcoded URL was fixed in fe95acb, but confused me one last time here!)

**Comment by ElDeveloper** [comment]
:weary:
