### ISSUE TITLE
Should we be able to re-use the raw data at the RawData obj level or at filepath level?

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#851]
The original discussion started here: https://github.com/biocore/qiita/pull/842#issuecomment-73766532

For completeness, I would provide another more complex example:

We have 3 studies:
- Study A has one raw data object X with one fastq file L
- Study B has one raw data object Y with one fastq file M
- Study C has half of the samples on fastq file L and the other half on fastq file M.

With the current set up, study C is forced to have two different prep templates and share the two RawData objects (X and Y). From my point of view, the optimal solution for study C will be to have a single prep template with RawData Z, which includes file L and M.

The other solution with the current set up, is that study C creates a raw data Z with fastq files L and M and the other two studies re-use that RawData. However, those studies will have a an extra fastq file that they don't need at all and I'm unsure what is the implication when running split libraries under these circumstances.

What other @biocore/qiita-dev think?

**Comment by antgonza** [comment]
Can you check what are the implications of the second case? I _think_ there
are none.

**Comment by antgonza** [comment]
@josenavas I think the artifact idea solved this, right?

**Comment by josenavas** [comment]
Yup!
