### ISSUE TITLE
shared status shouldn't be by study but by processed data

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#855]
This issue was initially discussed in https://github.com/biocore/qiita/pull/850 but we realized that this will require bigger modifications to actually work well.

Description:
Let's imagine that a study has 2 raw datas (A/B) and 2 prep templates (1/2) in each one (for clarity, we will have A1, A2, B1, and B2). Then the users makes public the study because A1 was published, then all the other raw datas + prep templates will also be public, which is not OK. What we will need to have is that the user makes public a process data, then all the files that generated that "biom" become public. We will display public studies based on their public process data.

**Comment by josenavas** [comment]
The proposed changes will be to add the "status" property in a per-object basis, and the study one can automatically populated (or removed) by looking at the status of its objects.

Pros:
- Once the Metadata has been accepted, the user can make public any analysis, (pre)process data that has been already published while he is working in other unpublished work within the same study.
- We are going to avoid study duplication: in case that a user has some published data but he is working a follow-up unpublished work, he can still work in the same study.

Cons:
- HORRIBLE database/codebase changes.

Even the amount of work behind this issue is considerable. I would suggest that this issue is really important and should be solved ASAP, before the code base continues growing...

**Comment by ElDeveloper** [comment]
> The proposed changes will be to add the "status" property in a per-object basis, and the study one can automatically populated (or removed) by looking at the status of its objects.

:fire: :scream: :running: :skull:

How much more complex is the system going to become if we add this
feature? Are the benefits much larger than the amount of
work/modifications we need to do to accommodate this?

I'm not worried about the work or modifications, I'm worried about this
complicating the way users interact with their datasets.

**Comment by antgonza** [comment]
I agree with @ElDeveloper, I think the users should only be able to
make public 1 thing: the processed data and the permissions should
carry down. Per object seems tooooo complicated, without any benefits,
at least that I can see clearly.

**Comment by josenavas** [comment]
Ok. I agree with the solution that we want to do it per processed data (not by per prep template - as the title says).

The only reason why I suggested in a per object basis is in the case that the user used the system to upload some sequences and then submit those sequences to EBI. Then those sequences are publicly available on EBI, and I think it would be also useful to be publicly available on QIITA.

What do you think about this case?

**Comment by antgonza** [comment]
Excellent point but we also need to check the map file so we can submit to
EBI and we do that by PCoAs ...

**Comment by josenavas** [comment]
I don't think that @ackermag is using PCoA to validate that the metadata is correct and giving access to upload to EBI... Although probably we want to change that.

Sometimes people is doing analyses outside qiita and they just want to use it to upload their data and make it publicly accessible, rather than performing the entire analysis on qiita...

**Comment by antgonza** [comment]
If someone that we do not know want to do that, I think they should
use their own EBI submission protocol ...

**Comment by josenavas** [comment]
Fair enough! So if I understand correctly this is the changed proposed:

Add the status to the processed data object and once the user makes that public, that processed data and preprocessed data, raw data and prep/sample template becomes public, right?

**Comment by antgonza** [comment]
I think so but also the study.

**Comment by squirrelo** [comment]
There may be an issue cascading it all the way down to the raw data level, since one raw data can have multiple studies, and some may still be private. I know @wasade was working on a way to remove study-specific sequences which may bypass this problem; did that get merged?

**Comment by wasade** [comment]
?

**Comment by antgonza** [comment]
Good point, perhaps make public up to demultiplex sequences.

**Comment by squirrelo** [comment]
Sorry, I remember you working on some demultiplex sequence stuff a few months back, but don't remember if it would apply here, hence the ping.

**Comment by wasade** [comment]
demux files don't know anything about permissions. it would be very nice if the files were assured to only contain samples for a single study

**Comment by josenavas** [comment]
The demux files should contain samples only for a single study, as they are the result of split libraries, so you cannot have the samples of another study (it is not in the mapping file/sample template).

However, the raw fastq files is another story... Probably we want to put some developer effort on getting a demultiplexed raw fastq file?

**Comment by wasade** [comment]
ah, that is annoying. That would have been nice to push upstream to qiime: have splitlib generate a raw fastq containing only the raw sequences that correspond to prep

**Comment by adamrp** [comment]
Yes, I think separating split libraries into two scripts (1 - Demux; 2 - Quality Filter) would solve this issue, but in the past that suggestion has been met with resistance on the grounds that it would require scanning the files multiple times. However, possibly the workflow object that @wasade put together a while back would allow this to happen in a pipelined fashion where the quality filtering of the pipeline could be disabled?

**Comment by wasade** [comment]
we won't be able to get splitlib changes into qiime 1.9.x, so i dont think we should pursue it. 2.0 is also likely a ways out. if this is critical, we should just do a naive pass back over the input file

**Comment by adamrp** [comment]
Thinking about this more... does the main motivation for this issue *actually* happen? When has it happened that a user needs to make public (in Qiita) a single raw data?

**Comment by antgonza** [comment]
It hasn't happen but it will happen as people do not get all the
different raw datas at once and some times they publish one while the
other is still in processing/analysis.

**Comment by josenavas** [comment]
I think in the old database we had a couple of studies which were technically the same study, but one was 16S and the other 18S. The 16S data was published and they're working with the 18S data. In the old database they had to create two different studies, while here they can all the data in the same study which simplifies work and integrity issues (they will have a single sample template). Sounds that reasonable?

**Comment by ackermag** [comment]
Often when studies have more than one data type, not all of the samples are
sequenced with each technology making it very difficult to combine in one
study because the sample template would be different for each data type.


On Mon, Feb 23, 2015 at 10:25 AM, josenavas <notifications@github.com>
wrote:

> I think in the old database we had a couple of studies which were
> technically the same study, but one was 16S and the other 18S. The 16S data
> was published and they're working with the 18S data. In the old database
> they had to create two different studies, while here they can all the data
> in the same study which simplifies work and integrity issues (they will
> have a single sample template). Sounds that reasonable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/855#issuecomment-75600656>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
However, we can add samples to the sample template using the PR that @squirrelo is working on

**Comment by josenavas** [comment]
Also, note that the whole goal of Qiita is to be able to combine different data types in a single meta-analysis, and the system is built to support multiple data types in a single study.

**Comment by adamrp** [comment]
I guess my question is this: if there are two different raw data (using your example, one is 16S and the other 18S), and the 16S gets published, what is the value to the user to make that one public in Qiita? It's already published elsewhere.

Is the anticipated value that we will at some point implement the ability for people to search and select from public raw data when they are creating a study (N.B.: study, not analysis)?

**Comment by josenavas** [comment]
Note that the original issue here is not raw data, is processed data... The conversation deviated...

**Comment by adamrp** [comment]
Ah that's probably my fault, sorry! I can see a clear use for having individual processed data public (for sample searches during analysis creation).

So, just to confirm we're all on the same pae, making a processed data public would also require exposing the sample and prep templates' information (thereby making them public by extension) since that's what people will be searching on.

**Comment by josenavas** [comment]
Yup!

**Comment by adamrp** [comment]
Okay, thanks for bringing me up to speed on this one :smile:

**Comment by antgonza** [comment]
@josenavas, how is this coming along?

**Comment by josenavas** [comment]
It's coming...

**Comment by josenavas** [comment]
:goberserk:
