### ISSUE TITLE
Single study analysis shortcut

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#858]
If we want qiita to replace qiime as a frontend, we need to be able to quickly do an analysis on a single study. If we have a way to jump from the study page directly to an analysis sample selection using only that study, it would speed up the analysis process.

**Comment by josenavas** [comment]
:+1:

**Comment by adamrp** [comment]
:+1: good idea -- similar functionality has regularly been requested by users at presentations

**Comment by ElDeveloper** [comment]
I was thinking about this yesterday. All it should take is a QIIME
mapping file and an OTU table. No need to create a study, should be a
standalone analysis "object".

**Comment by josenavas** [comment]
I don't think we need a new object. The current analysis object already supports this.

**Comment by squirrelo** [comment]
Yup, we just need the search/sample selection page to auto-filter to just that study on analysis creation, which isn't too bad.

**Comment by josenavas** [comment]
I'm not sure if auto-filter is the best solution. Probably will be easier to go to that page and have all the samples already selected?

**Comment by squirrelo** [comment]
Ah, I meant auto-filter as in it already has the search done to just have that study displayed for sample selection. We're on the same page I think, just different wording.

**Comment by josenavas** [comment]
Nope, my suggestion was to have all the samples already selected (i.e. added on the left panel). So if he wants to remove some sample, he has to go and remove it, instead of select which one does he wants.

Also I would suggest that the shortcut should be done in 2 ways:
 * Per processed data basis
 * Per study basis (selecting all the processed data available)

**Comment by squirrelo** [comment]
Ah, that makes sense. Agree.

**Comment by adswafford** [comment]
Reiterating that this is an important feature to have to remove tedious clicking for simple actions. Will lower the energy barrier for use.

**Comment by antgonza** [comment]
Let's discuss during the next Qiita meeting how to solve this issue. The main discussion points are:
- [ ] What to do with the process button in the artifact display that is shown in the artifact summary within the study - currently is there but there is no extra analysis you can do/apply.
- [ ] Do we add a single click analysis button or do we add the biom to the list of studies that you will create an analysis from? I like the second option better but let's discuss it.
- [ ] I'm not really sure what #2232 means ...

**Comment by adswafford** [comment]
#2232 is basically your point 2 in the last comment. So if I have a biom selected in the processing workflow diagram and I want to add it to the list for creating a new analysis, there should be a button or some mechanism for adding it without having to go the "View Studies" page, re-enter the study ID, find the biom on the list and click the add button. #2232  also suggests that we could make this a right-click option on the biom artifacts in the network.

**Comment by josenavas** [comment]
Replace the "Process" button in the study pipeline with a "Add to analysis" button. This makes clear that the BIOM table is the endpoint of the processing pipeline and it is easy to add the BIOM table to the analysis.

**Comment by antgonza** [comment]
Closed in: https://github.com/biocore/qiita/pull/2286
