### ISSUE TITLE
Ability to dump the current database

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#861]
It would be nice if we could have a way, possibly on an admin pane, to dump the current contents of the qiita.colorado.edu database. That way we have a lot of data to test with on local machines.

**Comment by antgonza** [comment]
This could be an issue with IRB so I think we shouldn't allow this. If you want to have a full system we could put somewhere the EMP loading files/instructions.

**Comment by wasade** [comment]
@squirrelo, :+1:, though note that you can just do this direct on the cmd line with `pg_dump`

@antgonza, I'm not aware of IRB concerns with any of the qiita data

**Comment by squirrelo** [comment]
can you pg_dump without access to the server?

**Comment by wasade** [comment]
no, but don't all admins have access?

On Mon, Mar 2, 2015 at 8:47 AM, Joshua Shorenstein <notifications@github.com

**Comment by squirrelo** [comment]
To get around the IRB issue, we could only dump the public studies and analyses.

**Comment by antgonza** [comment]
@wasade and I discussed and we are not storing any info in the DB that should cause problems with IRB. However, I agree that we should only download public everything.

**Comment by antgonza** [comment]
To make this work properly we will need to also download all the raw/demux/biom files and as discussed during today's meeting that's too much data, currently ~20T (not something easy to download) so closing this issue.
