### ISSUE TITLE
Permissions for results downloads

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#869]
This issue was identified by @antgonza (and possibly others), so please add comments if I describe this incorrectly.

Currently, analysis results are viewable by anyone that does a little bit of URL hacking, even if they should not have access to the analysis.

**Comment by antgonza** [comment]
That is correct. Basically, the handler checks for permissions of the
main template but the actual result files are accessible by anyone.

**Comment by adamrp** [comment]
@squirrelo and others, is the `/results/(.*)` URI only for analysis results, or are there other types of results that might need to be retrieved through that URI?

**Comment by antgonza** [comment]
AFAIK only results.

**Comment by squirrelo** [comment]
Yes, should only be analysis results.

**Comment by adamrp** [comment]
okay, thanks!
