### ISSUE TITLE
issue with ebi submission 

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#883]
We have a blind failure in qiita where submissions to EBI will not be successful cause we only accept https://github.com/biocore/qiita/blob/master/qiita_ware/ebi.py#L374 so if the template has Ilumina or IlluMina it will not work. What will be the best solution? Note that to have the studies that we want got to EBI without a problem we could update the DB (so it is ILLUMINA) or the code (so it accepts any casing).

**Comment by squirrelo** [comment]
A simple `str.upper()` would do it, but having the database be consistent would be better.

**Comment by rob-knight** [comment]
Update to make compatible with EBI terminology?


On Feb 24, 2015, at 6:20 PM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>> wrote:


We have a blind failure in qiita where submissions to EBI will not be successful cause we only accept https://github.com/biocore/qiita/blob/master/qiita_ware/ebi.py#L374 so if the template has Ilumina or IlluMina it will not work. What will be the best solution? Note that to have the studies that we want got to EBI without a problem we could update the DB (so it is ILLUMINA) or the code (so it accepts any casing).

**Comment by antgonza** [comment]
Had to really look into this issue so we can solve and it turns out
that the code is case insensitive, which is fine, but the real issue
is that Illumina is really 'Illumina ': it has a space. We need to
remove white spaces from values.

**Comment by adamrp** [comment]
IMHO, this should be checked on template upload. So, strip all values upon upload. Agree/disagree?

**Comment by antgonza** [comment]
Agree.
