### ISSUE TITLE
EBI submission incorrectly reporting metadata headers

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#884]
Seems to be a count of all the cells in the mapping file, not just number of columns

**Comment by JWDebelius** [comment]
I will attempt this.

**Comment by JWDebelius** [comment]
Issue only occurs on the live db. It a test instance, the problem is fixed.

It looks like production switches number of samples and number of metadata fields.

@antgonza, @josenavas: can you please advise?

Thanks!

**Comment by antgonza** [comment]
@JWDebelius and I took a look and the issue is that
SampleTemplate.metadata_headers is returning all headers and not only
the ones for that study.
