### ISSUE TITLE
Buttons are trying to write checks they can't cash

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#903]
Several buttons in the study user interface are active even if clicking them will lead to an error. For an example go to the sample template section of a study with no uploaded files, and press `Process sample template` or `Add samples to study`, both will error in a non-descriptive way. The solution is to either disable the buttons or show an error message at the top indicating that you need to select a file from the drop-down menu.

This same problem will happen if no file is selected, but I think this problem cannot occur as an entry is always selected in this menu.

**Comment by antgonza** [comment]
This has been solved by the new GUI. If you see still unresolved issues please add a new issue with a list of what needs to be fixed.
