### ISSUE TITLE
Change qiita user ids

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#905]
Last week while  @antgonza and I were working on installing Qiita on a new machine, we noticed that if a users changes their email, they are essentially losing access to everything they own. This is because the primary key is the email. I believe this should be changed such that the user id is independent from the email.

**Comment by josenavas** [comment]
Can a user change its email? Doesn't the database fail on udpate?

**Comment by ElDeveloper** [comment]
Yeah, they can't. And I think they should be able to do it.

**Comment by antgonza** [comment]
What about adding an UPDATE cascade to the tables?

**Comment by josenavas** [comment]
That would make the trick and it is a minimal change to the database.

**Comment by adamrp** [comment]
Keep in mind that people sign in with their email addresses, and most of the cookies (I think) are stored based on this email address, so the user will have to be logged out immediately after changing their email address

In general, I don't like the idea of allowing users to change the email address associated with their account, since too much depends on it and it doesn't seem like a feature we're desperate to have.

**Comment by josenavas** [comment]
Good point @adamrp 
Also, there are a lot of sites where your sign-in is based on your email, so we don't add more complexity to the system...

**Comment by antgonza** [comment]
Agree on the fact that we are not desperate to have AKA low priority
issue. However, I can see the benefit of allowing this: changing
institutions.

**Comment by wasade** [comment]
That is a fairly low frequency thing to do though...

most websites doing let you arbitrarily change your username. some do, like
github, but i can only imagine what type of pain that was to put in place
and to do it correctly

**Comment by wasade** [comment]
stupid commenting from email being treated differently...

**Comment by antgonza** [comment]
I think we can close this issue as people can register with a new email and if they really want to see all their studies with the new account they could share it or make them public.
