### ISSUE TITLE
accept sample_name (lower case) and SAMPLE_NAME (upper case in sample and prep templates

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#908]

**Comment by antgonza** [comment]
I think we should accept any kind of casing for required fields but respect casing for other columns. For example: sample_name and SAMPLE_NAME will point to the same thing but other ones like AA, Aa, aa  should stay different, see https://github.com/biocore/qiita/issues/439

**Comment by adamrp** [comment]
:+1:

**Comment by josenavas** [comment]
:+1: I think the changes go in here: https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template.py#L2128

**Comment by adamrp** [comment]
@josenavas that's for generating the QIIME mapping file, but I think the original issue posted by @ackermag is about the uploading of sample and prep templates. Please correct me if I'm wrong.

**Comment by adamrp** [comment]
Oh I see -- I think changes will *also* be required there. Thanks for pointing that out :smile:

**Comment by ackermag** [comment]
Correct - only applies to upload of sample and prep.  Specifically -
download of AGP from dbase renders uppercase column headers.  Really
annoying when I don't remember.

On Mon, Mar 9, 2015 at 7:04 PM, adamrp <notifications@github.com> wrote:

> Oh I see -- I think changes will *also* be required there. Thanks for
> pointing that out [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/908#issuecomment-77983140>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by adamrp** [comment]
@squirrelo already has a PR in for something very similar, so assigning to him
