### ISSUE TITLE
small interface suggestions from qiita install fest at biocore 15.3

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#913]
``qiita-admin`` makes more sense to me as a command name than ``qiime_env`` (and it's easier to type, b/c ``-`` only requires one key and ``_`` requires two).

**Comment by gregcaporaso** [comment]
Related: when running:

```
qiita_env start_cluster qiita_general
```

Could ``qiita_general`` be the default? And/or can it be called ``qiita-default``?

**Comment by gregcaporaso** [comment]
@jairideout and I were both confused with this error message:

```
$ qiita_env start_cluster qiita_demo
Usage: qiita_env start_cluster [OPTIONS] CLUSTERS...

Error: Invalid value for "clusters": invalid choice: qiita_demo. (choose from qiita_general)
```

I think this error message would be better if it looked like:

```
Error: Unknown cluster choice: qiita_demo

Valid choices are: 
 qiita_general
```

**Comment by wasade** [comment]
The choices formatting is left to click and out of our control

**Comment by wasade** [comment]
:+1: on others (-admin and - in cluster names)

**Comment by adamrp** [comment]
:+1: to dashes in place of underscores in cluster names. No strong feelings about `qiita_env` vs. `qiita-admin`, although if we keep `qiita_env`, I would :+1: changing it to `qiita-env`

Some other thoughts:
We currently have these subgroups of the top-level `qiita` click group:
```
db
ebi
log
maintenance
ware
webserver
```

What does @biocore/qiita-dev think of the following organizational changes:
- Move `log` into the `maintenance` group
- Move `ebi` into the `ware` group.
- Create a `pet` group as a subgroup directly under `qiita` (same level as `db` and `ware`)
- Move `webserver` into the new `pet` group

**Comment by ElDeveloper** [comment]
I like this new organization!

**Comment by josenavas** [comment]
:+1: @adamrp

**Comment by josenavas** [comment]
And I actually like more `qiita-admin`
