### ISSUE TITLE
Button missing when modifying "Shared With These Users"

### ISSUE THREAD

**Issue by Jorge-C** [biocore/qiita#919]
On the list of "your studies", clicking modify in the column "Shared With These Users" displays a pop up, and after modifying it hitting enter saves the changes, but there is no UI button to accept/cancel the changes.

**Comment by Jorge-C** [comment]
Maybe a quick-fix?

**Comment by adamrp** [comment]
The current implementation immediately applies your changes as you add and remove users from the chosen multiselect using AJAX, so there is no confirm/cancel button. If this is not desirable, then it could be changed. Thoughts?

**Comment by ElDeveloper** [comment]
I think adding some text to describe this behaviour, would be
sufficient.

**Comment by squirrelo** [comment]
Agree, just some text saying it automatically updates would be fine.

**Comment by ElDeveloper** [comment]
Fixed as part of #919
