### ISSUE TITLE
Rename beta diversity index.html something more descriptive.

### ISSUE THREAD

**Issue by JWDebelius** [biocore/qiita#927]
Otherwise, new users will be confused and misrepresent their data.

**Comment by ElDeveloper** [comment]
What file are you referring to? Are you referring to the emperor plot?

**Comment by JWDebelius** [comment]
Yes. The emperor plot for both weighed and unweighted UniFrac both display as "index.html"... There is currently no way other than opening the files to determine which metric was used.

**Comment by ElDeveloper** [comment]
Hmmm, yeah that is true, though I don't know if this should be changed
in the name of the HTML file or in the name of the folder, for example:

qiita.microbio.me/foo/bar/unweighted-unifrac/index.html
qiita.microbio.me/foo/bar/euclidian/index.html
qiita.microbio.me/foo/bar/weighted-unifrac/index.html

I think this would make more sense.

**Comment by JWDebelius** [comment]
Right now, the file path isn't included in the results display, just the
file name.

So, I can think of three potential solutions for the issue of displaying
confusing file paths. There are probably others.


   1. Display the full file path, so the name gets displayed. Personally, I
   think this is an inelegant solution and might be a security risk.
   2. Add a metric annotation. This would work okay in the database,
   although it might require special handlers for beta diversity, and may work
   okay depending on how files are downloaded. If they're downloaded as html
   files alone, this is not a good solution. If you download the full
   directory, it's an okay solution.
   3. Change the file names to be more reflective of the data being
   processed. The current handlers and page layout would remain the same.
   Having a different name in each of the downloaded folders likely isn't an
   issue unless you're firing off some sort of automated script. I suspect
   that's a special case for most users, rather than the norm. But, at this
   point, I think it probably becomes a Qiime or Emperor issue.

**Comment by antgonza** [comment]
Emperor outputs index.html because this way you can simply pass the
folder name in a server and automatically displays that page. So IMOO
the solution will be to replace the content of the link (what's
between <a></a>) for the folder name that contains the index.html
output for all beta diversity results. In @ElDeveloper suggestion:
```
<a href="qiita.microbio.me/foo/bar/unweighted-unifrac/index.html>unweighted-unifrac</a>
<a href="qiita.microbio.me/foo/bar/euclidian/index.html>euclidian</a>
<a href="qiita.microbio.me/foo/bar/weighted-unifrac/index.html>weighted-unifrac</a>
```

**Comment by ElDeveloper** [comment]
Yeah, this seems like a nice solution!

**Comment by antgonza** [comment]
This has been solved, right? 
<img width="313" alt="screen shot 2015-08-13 at 10 15 33 am" src="https://cloud.githubusercontent.com/assets/2014559/9255085/520a64e0-41a4-11e5-9ec6-a8f9728d659f.png">

**Comment by josenavas** [comment]
I put that quick fix in place, I don't know if we want to do something more intelligent or if the current solution is good enough

**Comment by antgonza** [comment]
Nobody has comment anything about this for a while now, thus closing. Open if you believe this hasn't been solved.
