### ISSUE TITLE
Will pulling names from a database for PI and Lab Person scale? 

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#928]
These drop down boxes are going to get out of hand. Is the plan to update this at some point (it'll probably work fine for a little while). Related to #925.

**Comment by ackermag** [comment]
Would be better to have search function - I think


On Mon, Mar 9, 2015 at 7:09 PM, Greg Caporaso <notifications@github.com>
wrote:

> These drop down boxes are going to get out of hand. Is the plan to update
> this at some point (it'll probably work fine for a little while). Related
> to #925 <https://github.com/biocore/qiita/issues/925>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/928>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by adamrp** [comment]
What do you mean by out of hand? Do you mean too much data to fit in a dropdown (technical limitation), or do you mean inconvenient for the user? I'm not familiar with the technical limitations of the combo boxes we are using (or alternatives such as Chosen). As for inconvenience for user, the dropdown is filtered as you type to display only (fuzzy) matches. @ackermag it effectively is a search already, since it only displays (partial) matches to what you type.

**Comment by gregcaporaso** [comment]
> Do you mean too much data to fit in a dropdown (technical limitation), 
> or do you mean inconvenient for the user?

Both, I think, but the fuzzy matching search will help a lot.

**Comment by wasade** [comment]
+1

**Comment by gregcaporaso** [comment]
Ok, so if the fuzzy match search is already in place let's close this one for now and re-open if it becomes a problem. I'll close, but @adamrp, if I'm misunderstanding and that's not already in place can you re-open?

**Comment by ackermag** [comment]
As far as I am aware it is in place - I want to avoid a long list of
contributors to read through.  Sorry @adamrp <username: era-drop-215
password: J7XoQJ8I NEW PASSWORD 6N6VsPNF> I forgot that fuzzy search was in
place.


On Wed, Mar 11, 2015 at 8:11 PM, Greg Caporaso <notifications@github.com>
wrote:

> Ok, so if the fuzzy match search is already in place let's close this one
> for now and re-open if it becomes a problem. I'll close, but @adamrp
> <https://github.com/adamrp>, if I'm misunderstanding and that's not
> already in place can you re-open?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/928#issuecomment-78416542>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by wasade** [comment]
Please don't post passwords...

**Comment by ElDeveloper** [comment]
@ackermag I've deleted your comment, sorry for doing that.
