### ISSUE TITLE
documentation is needed on how to prepare a sample template

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#933]
I'm trying to use qiita to do a test analysis, and I don't know what fields I need to have in my sample template. It sounds like this documentation doesn't currently exist.

**Comment by ackermag** [comment]
Does not exist - I can help tomorrow


On Mon, Mar 9, 2015 at 10:17 PM, Greg Caporaso <notifications@github.com>
wrote:

> I'm trying to use qiita to do a test analysis, and I don't know what
> fields I need to have in my sample template. It sounds like this
> documentation doesn't currently exist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/933>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by gregcaporaso** [comment]
This also may ultimately be a place where @jairideout's [keemai](https://github.com/jairideout/keemei) project could be useful. It's a Google Spreadsheets-based QIIME mapping file validator that he's been working on as a side project, so could give users information in realtime about warnings/errors in their sample templates/mapping files.

**Comment by rob-knight** [comment]
That sounds awesome!


On Mar 9, 2015, at 11:02 PM, Greg Caporaso <notifications@github.com<mailto:notifications@github.com>> wrote:


This also may ultimately be a place where @jairideout<https://github.com/jairideout>'s keemai<https://github.com/jairideout/keemei> project could be useful. It's a Google Spreadsheets-based QIIME mapping file validator that he's been working on as a side project, so could give users information in realtime about warnings/errors in their sample templates/mapping files.

**Comment by ackermag** [comment]
Can I work with him to develop it?

On Mon, Mar 9, 2015 at 11:02 PM, Greg Caporaso <notifications@github.com>
wrote:

> This also may ultimately be a place where @jairideout
> <https://github.com/jairideout>'s keemai
> <https://github.com/jairideout/keemei> project could be useful. It's a
> Google Spreadsheets-based QIIME mapping file validator that he's been
> working on as a side project, so could give users information in realtime
> about warnings/errors in their sample templates/mapping files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/933#issuecomment-78000508>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by gregcaporaso** [comment]
That should work, let's talk to him about it when he comes online today.

**Comment by gregcaporaso** [comment]
This is in progress [here](https://github.com/biocore/qiita/wiki/Preparing-Qiita-template-files).

**Comment by antgonza** [comment]
I'm closing this as we have this documented. It was added here: https://github.com/biocore/qiita/pull/1191
