### ISSUE TITLE
load_template_to_dataframe should check for duplicated columns

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#937]
Although #744 prevented the duplicated columns from being silently removed, it didn't add a check to make sure that there were no duplicated columns. The solution is to add a check and raise an exception with the names of the duplicated columns.

**Comment by Jorge-C** [comment]
Revisit when #930 is merged.

**Comment by antgonza** [comment]
@Jorge-C #930 was merged, can we close?

**Comment by Jorge-C** [comment]
Yes, this is solved.
