### ISSUE TITLE
processing sample template requires that latitude and longitude has a decimal

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#938]
For example, ``latitude`` of 40 does not work, but 40.0 does work. Is this intentional, or that that requirement be relaxed?

**Comment by adamrp** [comment]
Probably not intentional -- I'll look into it, I think ints should be acceptabe, too.

**Comment by adamrp** [comment]
I'm not observing this behavior on my system. I used a sample template I  know worked and changed one of he latitudes to 40 (no decimal), and the sample template loaded correctly.

@gregcaporaso What was the error message you were receiving?

**Comment by gregcaporaso** [comment]
It looks like this happens when all values are ints, but maybe not when some are not ints. The same thing happens for ``longitude``. The error message is illustrated here:

![screenshot 2015-03-11 16 12 42](https://cloud.githubusercontent.com/assets/192372/6608988/a2d3bbe8-c809-11e4-83fa-119c69e3ce80.png)
