### ISSUE TITLE
.tsv should be an allowed upload extension

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#939]
This is the default for outputting from Google Spreadsheets as tab-separated text, so it'd be convenient to support this extension.

**Comment by adamrp** [comment]
Valid upload extensions are set [in the configuration file](https://github.com/biocore/qiita/blob/master/qiita_core/support_files/config_test.txt#L37), but do you think it should be a default upload extension? I think that makes sense if google spreadsheets outputs files with this extension by default.

**Comment by adamrp** [comment]
Verified that files produced do have the TSV extension. I'll add this to the default configuration file.
