### ISSUE TITLE
Sample template selection could only allow relevant file extensions 

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#940]
If the file extensions that are allowed for upload are restricted, we can internally make some choices about which files are suggested for processing sample templates (etc). Currently ``.fna`` files are suggested for this:

![screenshot 2015-03-10 10 55 27](https://cloud.githubusercontent.com/assets/192372/6581462/4e456bd0-c714-11e4-9e99-a67b6195e302.png)

**Comment by adamrp** [comment]
:+1:

**Comment by gregcaporaso** [comment]
It looks like that doesn't work yet:

![screenshot 2015-03-11 20 13 27](https://cloud.githubusercontent.com/assets/192372/6611596/2c38f350-c82b-11e4-8f66-19d97dfa63e4.png)

![screenshot 2015-03-11 20 13 41](https://cloud.githubusercontent.com/assets/192372/6611598/3130298c-c82b-11e4-864a-a35d79526aa4.png)
