### ISSUE TITLE
Server web sockets don't work on Safari

### ISSUE THREAD

**Issue by JWDebelius** [biocore/qiita#946]
Running on OS X 10.10.

**Comment by JWDebelius** [comment]
Running on Mac OS X 10.10

**Comment by antgonza** [comment]
Which version of Safari?

**Comment by JWDebelius** [comment]
Sorry, I thought I changed the name. Version 8.0.3 (10600.3.18)

**Comment by wasade** [comment]
Just to note, this is not websockets as other websockets work.

On a related note, the version of safari on OSX 10.8.5 is incompatible is
that it is < version 7

**Comment by antgonza** [comment]
Not sure what the best solution for this. Should we just allow
Chrome/Firefox? Both are for free ...

**Comment by wasade** [comment]
Embedded emperor won't work for me in chrome, albeit my browser is tweaky

On Tue, Mar 10, 2015 at 11:30 PM, Antonio Gonzalez <notifications@github.com

**Comment by antgonza** [comment]
Trash that computer?

**Comment by wasade** [comment]
That thought has crossed my mind on occasion

On Tue, Mar 10, 2015 at 11:43 PM, Antonio Gonzalez <notifications@github.com
