### ISSUE TITLE
taxa summaries does not work in meta analysis

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#948]
This may be an issue with QIIME 1.9 itself, not qiita

*** ERROR RAISED DURING STEP: Plot Taxonomy Summary
Command run was:
plot_taxa_summary.py -i /projects/qiita_data/job/150_summarize_taxa_through_plots.py_output_dir/164_analysis_16S_L2.txt,/projects/qiita_data/job/150_summarize_taxa_through_plots.py_output_dir/164_analysis_16S_L3.txt,/projects/qiita_data/job/150_summarize_taxa_through_plots.py_output_dir/164_analysis_16S_L4.txt,/projects/qiita_data/job/150_summarize_taxa_through_plots.py_output_dir/164_analysis_16S_L5.txt,/projects/qiita_data/job/150_summarize_taxa_through_plots.py_output_dir/164_analysis_16S_L6.txt -o /projects/qiita_data/job/150_summarize_taxa_through_plots.py_output_dir/taxa_summary_plots/ 
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
File "/home/qiita/qiime/scripts/plot_taxa_summary.py", line 278, in 
main()
File "/home/qiita/qiime/scripts/plot_taxa_summary.py", line 274, in main
resize_nth_label, label_type, include_html_legend)
File "/home/qiita/qiime/qiime/plot_taxa_summary.py", line 1138, in make_all_charts
resize_nth_label, label_type, include_html_legend))
File "/home/qiita/qiime/qiime/plot_taxa_summary.py", line 1073, in get_counts
label_type, include_html_legend))
File "/home/qiita/qiime/qiime/plot_taxa_summary.py", line 861, in make_HTML_table
props={'title': title})
File "/home/qiita/qiime/qiime/plot_taxa_summary.py", line 466, in make_area_bar_chart
fig = figure(figsize=(plot_width, plot_height))
File "/opt/matplotlib/1.1.0/lib/python2.7/site-packages/matplotlib/pyplot.py", line 343, in figure
**kwargs)
File "/opt/matplotlib/1.1.0/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 80, in new_figure_manager
window = Tk.Tk()
File "/opt/python-2.7.3/lib/python2.7/lib-tk/Tkinter.py", line 1685, in __init__
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

)
Python output: None
Standard output: 
Standard error: 

Job FINISH_ANALYSIS_164: Error
Job results: ImpossibleDependency()
Python output: None
Standard output: 
Standard error:

**Comment by jairideout** [comment]
matplotlib defaults to a GUI backend, which requires a display. The matplotlib backend needs to be set to "agg". You can fix this by adding/changing the following line in the matplotlib rc file:

```
backend : agg
```

See [here](http://matplotlib.org/users/customizing.html) and [here](http://matplotlib.org/faq/troubleshooting_faq.html#locating-matplotlib-config-dir) for details on how to configure matplotlib.

We were previously forcing the backend to "agg" in earlier scikit-bio versions, which caused a number of issues. In the latest QIIME-compatible release (0.2.3), we stopped forcing the backend since this is really a matplotlib configuration issue and will vary from system to system.

**Comment by antgonza** [comment]
What will be the best solution? Obviously, I can change directly in
the server but this might be an issue in all qiita deploys ...

**Comment by jairideout** [comment]
That's a great question! I'm not sure of a good/easy way for Qiita for force a specific backend in all cases.

With the current setup, it shouldn't be an issue for systems with displays (e.g., local Qiita installs), and I think that it's fair to expect people installing Qiita on a headless server (e.g., sysadmins) to configure matplotlib for their specific setup (using a matplotlib rc file).

**Comment by antgonza** [comment]
It will be great to fix this for all qiita installation, perhaps add:
```
import matplotlib as mpl
mpl.rcParams['backend'] = 'agg'
```
in one of the __init__.py

Anyway, in the meantime I added a matplotlibrc to the server

**Comment by antgonza** [comment]
Should we add this in the qiita documentation as part of the installation and call it good?

**Comment by josenavas** [comment]
Agree on adding to documentation, in local machines that should not be an issue, it would be only clusters.
