### ISSUE TITLE
could the input format for the sample collection time be ISO 8601? 

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#954]
http://en.wikipedia.org/wiki/ISO_8601

**Comment by antgonza** [comment]
The title has ISO 9601 but the link has ISO 8601, which one are you suggesting?

**Comment by wasade** [comment]
I don't believe ISO 9601exists?

**Comment by gregcaporaso** [comment]
Sorry, typo fixed in the title.

**Comment by antgonza** [comment]
This is basically the original report of https://github.com/biocore/qiita/issues/1885, closing this one as the other has more info.
