### ISSUE TITLE
Longitude values are often incorrectly signed

### ISSUE THREAD

**Issue by avoorhis** [biocore/qiita#960]
I've noticed when receiving metadata into VAMPS that the longitude values are positive values when often they should be negative. This drastically affects where they show up on the map. Of course the values CAN be positive so making them all negative is not the answer. 
I think the solution will be both letting users know (in the wiki) when describing decimal degrees (E vs W longitude) and perhaps validating by coordinating the ENVO:location with negative or positive values.

**Comment by antgonza** [comment]
Thanks @avoorhis, we believe we have fixed as much as we can, closing for now.
