### ISSUE TITLE
Sample Preprocessing UI Issues

### ISSUE THREAD

**Issue by jwdebelius** [biocore/qiita#962]
- [ ] Make the "Back to study/accept these files" button as prominent as the delete button on the "upload page".
- [ ] Provide more sign-posting for the pre-processing steps. Do not assume your user will know what all the dropdowns/boxes mean.
- [ ] If you run your browsers at less than full screen, you miss entire pieces of the pre-processing page.
- [ ] Upload a directory

**Comment by antgonza** [comment]
We want to solve these points but we are not sure if they are already solved in the newer interface. Would it be possible to recheck them? Thanks!

BTW the upload a directory, our guess is that you want to upload a lot of files at once, right? If that's the case, you could do this by selecting all the files either by drag-and-drop or the selecting the files. Do you think and update to the documentation will be helpful?

**Comment by antgonza** [comment]
Closing. Please add individual issues for anything you feel we are still missing. Thank you for all your suggestions.
