### ISSUE TITLE
sql_connection.py error reporting is misleading 

### ISSUE THREAD

**Issue by wdwvt1** [biocore/qiita#965]
Multiple error types are caught by line 153. Specifically, if the database has been dropped, the error will still report that it can't find the right user. As an example: 

``` bash
qiita_env make --no-load-ontologies
qiita_env drop 
qiita webserver start
```

results in the error:
`RuntimeError: Can't connect to database; user `wdwvt` is not known. Your QIITA configuration file, located at `/Users/wdwvt/src/qiita/config_test.txt` must specify the correct user, via the `USER` parameter under the `[postgres]` header. Please refer to `INSTALL.md` in the QIITA base directory.`

**Comment by wdwvt1** [comment]
An additional error message can get caught by this that we should fail nicely with:
```
could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```
This happens when `redis-server` hasn't been started and one tries to start the webserver.

**Comment by antgonza** [comment]
That error is postgres, no?

**Comment by wdwvt1** [comment]
yes - you are absolutely right.

**Comment by antgonza** [comment]
@josenavas, could you check if still an issue?

**Comment by antgonza** [comment]
This has been solved. Now it reports if the server is not reachable or if the role is not created independently.
