### ISSUE TITLE
add field indicating if a study is currently being processed 

### ISSUE THREAD

**Issue by wdwvt1** [biocore/qiita#968]

**Comment by josenavas** [comment]
@wdwvt1 this is in the study description page? i.e. some icon next to the study title so you know it's being processed?

**Comment by wdwvt1** [comment]
yes - or perhaps even a timer indicating how long it has been running?

**Comment by josenavas** [comment]
good idea!

**Comment by antgonza** [comment]
Since we moved every processing step to run on workers we always show the state of the sample/prep info files AKA being updated. Closing.
