### ISSUE TITLE
"Event-Based Data" options are not clear

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#973]
I'm trying to do a testing with _Moving Pictures of the Human Microbiome_ and I'm not sure which option to choose. This needs to be clearly documented.

**Comment by antgonza** [comment]
https://docs.google.com/document/d/1u7kwLP31NM513-8xwpwvLbSQxYu0ehI6Jau1APR13e0/edit#heading=h.ghm5n8t4ys8t

**Comment by gregcaporaso** [comment]
Ah, I had no idea that document existed! 

Note that More info > Help points to the wiki (which I think would be a great place to write the documentation, as it would facilitate contributions from non-coders).

**Comment by gregcaporaso** [comment]
It would be good if there were options that didn't involve interventions (e.g., for *Moving Pictures*).

**Comment by squirrelo** [comment]
Agreed, that google doc should probably move to the wiki

**Comment by antgonza** [comment]
Not sure when the info was actually added to the docs but they are there: https://qiita.ucsd.edu/static/doc/html/gettingstartedguide/index.html?highlight=event%20based%20data#creating-a-study.
