### ISSUE TITLE
OTU picking failure: test_db should use qiime_default_reference files

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#976]
OTU picking failed in when I got to the OTU picking step because the test database doesn't have the reference files included. Now that we depend on QIIME 1.9.0, we can get these files from there. For example:

```
In [3]: from qiime_default_reference import get_reference_sequences

In [4]: get_reference_sequences()
Out[4]: '/Users/caporaso/.virtualenvs/qiita/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta'
```

Also, note that these are the defaults for the OTU pickers now, so you could skip passing `-r` and `-t` to the OTU pickers if you want.

**Comment by antgonza** [comment]
This issue has been superseded by the current code. Closing.
