### ISSUE TITLE
when starting an analysis, it is necessary to show the biom summarize-table results to pick the rarefaction depth

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#977]
It sounds like it is not possible to get that information from within Qiita right now, so it not possible to figure out how to set the rarefaction depth. I was only able to figure this out by looking for biom table path, and then passing that to ``biom summarize-table`` on the command line.  Am I missing that information somewhere?

**Comment by antgonza** [comment]
Related to: https://github.com/biocore/qiita/issues/650

**Comment by wasade** [comment]
I think it would be good to cache stats in the biom hdf5 file. Can be done
w/o violating format

**Comment by antgonza** [comment]
Closing in favor of: https://github.com/biocore/qiita/issues/650
