### ISSUE TITLE
naming and layout of analysis types is confusing, as is flow through an analysis workflow

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/qiita#978]
Preprocessed data, processed data, meta-analysis (in the case where you're only analyzing one data set) aren't the most clear terms to me. 

You also end up needing to jump around the interface a lot to do things. 

After I finished the "processing" of my samples, it wasn't clear that I had to now create a "meta-analysis" to do alpha/beta diversity, etc. When I figured that out, I found that I didn't have the information to choose a rarefaction depth (#977). Then, on this page:

![screenshot 2015-03-11 19 12 04](https://cloud.githubusercontent.com/assets/192372/6610860/86dce5d6-c822-11e4-83d5-c767c94e235b.png)

I did my search, and then didn't know that I had to go to the top-left to _Select samples_, and then top-left again to _Continue_. I also found it kind of annoying that I had to search for the samples that I just uploaded and processed, but it does make sense now that I understand it better. That could be facilitated for example by having options that would let me view all "processed data" sets.

**Comment by rob-knight** [comment]
Thanks Greg. I'd like to note to the dev team that multiple people including me have raised these issues before. This time we will fix them.

Rob


On Mar 11, 2015, at 7:19 PM, Greg Caporaso <notifications@github.com<mailto:notifications@github.com>> wrote:


Preprocessed data, processed data, meta-analysis (in the case where you're only analyzing one data set) aren't the most clear terms to me.

You also end up needing to jump around the interface a lot to do things.

After I finished the "processing" of my samples, it wasn't clear that I had to now create a "meta-analysis" to do alpha/beta diversity, etc. When I figured that out, I found that I didn't have the information to choose a rarefaction depth (#977<https://github.com/biocore/qiita/issues/977>). Then, on this page:

[https://cloud.githubusercontent.com/assets/192372/6610860/86dce5d6-c822-11e4-83d5-c767c94e235b.png]<https://cloud.githubusercontent.com/assets/192372/6610860/86dce5d6-c822-11e4-83d5-c767c94e235b.png>

I did my search, and then didn't know that I had to go to the top-left to Select samples, and then top-left again to Continue. I also found it kind of annoying that I had to search for the samples that I just uploaded and processed, but it does make sense now that I understand it better. That could be facilitated for example by having options that would let me view all "processed data" sets.

**Comment by gregcaporaso** [comment]
My analysis failed last night, and I'm not sure why. It's not clear how to debug these types of failures:

![screenshot 2015-03-12 09 10 23](https://cloud.githubusercontent.com/assets/192372/6622106/c55db9d2-c897-11e4-9e89-a4e11e1b1210.png)

**Comment by gregcaporaso** [comment]
Also, note that that is a screenshot of the full window on the left size. The text is being cutoff on that side of the page.

**Comment by antgonza** [comment]
Do you have a valid tree and not a place holder?

**Comment by gregcaporaso** [comment]
No idea - that's my point.

**Comment by gregcaporaso** [comment]
That seems like it's probably the cause, so this is related to #976.

**Comment by antgonza** [comment]
This has been fixed and made clear with the improvements in the analysis pipelines.
