### ISSUE TITLE
EBI submissions are not sending Description

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#983]
This is a problem as the resulting mapping files are not compatible with QIIME's `merge_mapping_files.py`

**Comment by antgonza** [comment]
Just discussed this with @wasade and realized that as EBI defines their submissions "description" is part of the SAMPLE and not part of the SAMPLE_ATTRIBUTES section; described here: https://www.ebi.ac.uk/ena/submit/preparing-xmls#sample. Based on this, description is actually added to the submissions but not as SAMPLE_ATTRIBUTES, thus parsers need to be aware of this. Closing as the issue has been clarified.
