### ISSUE TITLE
PR #980 creates bug: metadata template errors on boolean conversion

### ISSUE THREAD

**Issue by JWDebelius** [biocore/qiita#985]
![screen shot 2015-03-13 at 2 33 09 pm](https://cloud.githubusercontent.com/assets/5534846/6647651/eeb7cbdc-c98d-11e4-9213-ac4bb0007547.png)

**Comment by antgonza** [comment]
Note that this is an _urgent_ bug as it prevents templates to be loaded

**Comment by ElDeveloper** [comment]
I just had a look and this is not really a bug, but instead a bug fix.

What seems to be happening is that values have to "truly" be booleans in order for them to not be flagged by Qiita as invalid, previously the values were being checked for the correct type in the following way:

```python
In [13]: import pandas as pd

In [14]: x = pd.Series(['y', 'y', 'n'])

In [15]: x.dtype
Out[15]: dtype('O')

In [17]: np.issubdtype(x.dtype, np.bool)
Out[17]: True

```

However, the problem with this approach is that although the `dtype` attribute of the `Series` object is `object`, it is still a subdtype of the `np.bool` type, which is not really the way we were expecting this to be validated, thus any arbitrary string was working, see this example:

```python

In [21]: y = pd.Series([':L', ':D', ':0'])

In [22]: np.issubdtype(y.dtype, np.bool)
Out[22]: True
```

The current solution in place is actually making sure that values are actually boolean types as it checks on a per-value basis and using Python's built-in `isinstance`.

The most common problem will be with templates that include values like `'y'` to represent `True` and or `'n'` to represent `False`. To fix this `y`s should be replaced with the word `TRUE` or `True` and `n`s should be replaced with the word `FALSE` or `False`.

**Comment by JWDebelius** [comment]
If this is prevalent in prep/sample templates that go back 5+ years, this restriction is going to create a headache.
Could a pandas apply layer be introduced to support Boolean conversions?

**Comment by antgonza** [comment]
Agree that will be nice to have 'y' -> True but the solution doesn't
seem straightforward in Pandas. Basically, you will need to do a map
on all the values you want to check, which perhaps will not be that
terrible ...

**Comment by josenavas** [comment]
Note that there is the past and the future... If the issue is that the prep/sample templates that go back 5+ years are not supported, si easy enough to write a script that we can execute outside of the system to fix those templates, but do not modify the system to support this. This way, we can avoid repeating the mistakes that where done in the old database...

**Comment by antgonza** [comment]
Agree but note that this will help novice users add their metadata.
Again, this can be also solved by fixing all templates and be
extremely clear in the documentation.

**Comment by josenavas** [comment]
:+1: on extremely clear documentation...

**Comment by squirrelo** [comment]
Agree with not supporting old versions and having an outside converter to clean up any older templates. If we can enforce metadata through pandas and other means in qiita, we should. 

Also agree we need extremely clear documentation.

**Comment by JWDebelius** [comment]
The pandas solution is actually quite straight forward:

```def convert_binary(x):
    if x in {'y', 'yes', 'Y', 'Yes', 'YES', True}:
         return True
    elif x in {'n', 'no', 'N', 'No', 'NO', False}:
         return False
    else:
         raise ValueError('Value is not boolean.')

for c in binary_cols:
    df[c].apply(convert_binary)```

Finding and replacing in an excel column is possible, but not something you want to do if you're in a hurry and already angry at a system that is clearly broken because your data is a reasonable facsimile of what is asked for.

**Comment by JWDebelius** [comment]
Alternatively,

```python

>>> df = pd.DataFrame({'Bool Col': ['y']*10, 'Str Col': ['I hate cats']*10},index=np.arange(0, 10))
>>> df
  Bool Col      Str Col
0     y     I hate cats
1     y     I hate cats
2     y     I hate cats
3     y     I hate cats
4     y     I hate cats
5     y     I hate cats
6     y     I hate cats
7     y     I hate cats
8     y     I hate cats
9     y     I hate cats

>>> for  c in ['Bool Col']:
...    df[c] = df[c].apply(lambda x: bool(x))

>>>df['Bool Col']
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: Bool Col, dtype: bool

```

**Comment by ElDeveloper** [comment]
I'm all for adding this as long as we are aware that the *feature creep*
of this function is increasing by the week.

**Comment by squirrelo** [comment]
We need a separate function for validation then with this in it, since this would be a first-line to getting everything standardized. I wouldn't call this feature creep so much as maintaining functionality that already existed.
