### ISSUE TITLE
shopping cart

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#989]
After talking with @rob-knight and @gregcaporaso I think the nicest solution to make the system easier to generate meta-analysis is to have something similar to a shopping cart. This will mean that the search capability in the "My Studies", "Public Studies" and "Metaanalysis" should be merged into one. With this you could select the studies/samples you are interested (from a single or any of these pags) and then create a meta-analysis with x parameters. Then if the user wants to reuse this meta-analysis to change parameters or add/remove study/samples we can simple add those studies to the shopping cart. 

Another option will be to have a simple search and a complex query one. This will mean to merge "My Studies" and "Public Studies" and then have the current meta-analysis search as the complex querying.

What do you think?

**Comment by squirrelo** [comment]
This may not work because you could be building multiple analyses at once, which would convolute where you need to put the samples for the shopping cart. I have some ideas on making the sample selection interface easier, and we should probably discuss all this at the qiita meeting this week.

**Comment by rob-knight** [comment]
Sounds plausible although I have suffered through some awful cart interfaces...


On Mar 16, 2015, at 9:44 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>> wrote:


After talking with @rob-knight<https://github.com/rob-knight> and @gregcaporaso<https://github.com/gregcaporaso> I think the nicest solution to make the system easier to generate meta-analysis is to have something similar to a shopping cart. This will mean that the search capability in the "My Studies", "Public Studies" and "Metaanalysis" should be merged into one. With this you could select the studies/samples you are interested (from a single or any of these pags) and then create a meta-analysis with x parameters. Then if the user wants to reuse this meta-analysis to change parameters or add/remove study/samples we can simple add those studies to the shopping cart.

Another option will be to have a simple search and a complex query one. This will mean to merge "My Studies" and "Public Studies" and then have the current meta-analysis search as the complex querying.

What do you think?

**Comment by squirrelo** [comment]
After talking through the issue, I think we can get something working for alpha 0.1 to show off a playlist-like design for this.

**Comment by antgonza** [comment]
Closed by https://github.com/biocore/qiita/pull/1108
