### ISSUE TITLE
Create a citation list for analysis.

### ISSUE THREAD

**Issue by jwdebelius** [biocore/qiita#991]
Since it's biocore's policy that users cite each of the tools that are used, there should be a download file which lists the tools used in an analysis. For example, if I use closed reference picking with UClust against greenness 13_8 and then calculate PD whole tree diversity and unweighted UniFrac distance, I should probably cite UClust, Greengenes, PD whole tree, UniFrac and QIIME. It would be great to have a link these citations.

I'd also really like  it if meta analyses could include the citation link for the PMID, if submitted. That way, people can also cite the studies they're handling. Although, if an environmental study doesn't have a PMID, should there be another way to add a citation?

**Comment by antgonza** [comment]
superseded by https://github.com/biocore/qiita/issues/2344
