### ISSUE TITLE
WebSockets will not work over HTTPS

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#993]
If the server is being accessed through HTTPS, anything that relies on WebSockets will fail silently and only show an error on the JavaScript command line. The most important feature that's unavailable when this happens is being able to submit jobs.

```javascript
[blocked] The page at 'https://qiita.ibdmdb.org/analysis/wait/1' was loaded over HTTPS, but ran insecure content from 'ws://qiita.ibdmdb.org/moi-ws/': this content should also be loaded over HTTPS. moi.js:77
Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

For more information, see [this issue in moi](https://github.com/biocore/mustached-octo-ironman/issues/16) and this [StackOverflow question](http://stackoverflow.com/q/25496039/379593).

**Comment by squirrelo** [comment]
The fix seems to just be to use `wss://` but we need to know when to use that vs the standard.

**Comment by ElDeveloper** [comment]
I tried by changing moi.js and compute_waiting.html to use wss but no
luck either.

**Comment by wasade** [comment]
Some info if you google "tornado was". Are the certs etc setup in
webserver.py?

**Comment by ElDeveloper** [comment]
I tried this out, but it didn't work either.

**Comment by ElDeveloper** [comment]
I was able to verify that the websockets in fact work using Safari 8.xxxx. It seems that the problem is arising from the fact that the interface is not being properly updated and gives a misleading impression of nothing happening. My guess is that the creation of the HTML elements is not working.

**Comment by squirrelo** [comment]
Needs to be verified, but may have been solved by #1058

**Comment by ElDeveloper** [comment]
How can that be? I don't recall any changes to the webserver's configuration to take in a certificate.

**Comment by squirrelo** [comment]
Oh, I thought you had the certs up and it was just a ws:// vs wss:// issue. My bad.

**Comment by ElDeveloper** [comment]
Np, it's really both things. We should add a parameter to the config
file such that you can set what the certificates, etc you want to use
are.

**Comment by antgonza** [comment]
Now we are using https and we don't have this issue, @ElDeveloper can we close?

**Comment by ElDeveloper** [comment]
Yes, I believe this is the case, since we now have the system work with HTTPS.

**Comment by Allan-Nava** [comment]
with heroku how can I fix `SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`?
