### ISSUE TITLE
split_libraries.py for multiple fasta files not working

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#994]
The current workflow is:
1. process_sff.py of each SFF
2. Generate a basic mapping file for each SFF
3. split_libraries.py
4. convert_fastaqual_fastq.py so we get all the required files

The issue is that step 2, in specific _get_qiime_minimal_mapping, generates a mapping file for each SFF (run_prefix) and only passes to step 3 the last one generated. This function is called by both fastq and fasta processing so I think the easiest will be to simply get all the files generated and merge them into 1 using merge_mapping_files.py if step 2 returns more than 2 paths. Other option is to not allow run_prefix in fasta.

**Comment by wasade** [comment]
Merging isn't safe if same barcodes are used

**Comment by antgonza** [comment]
Yes, that's a specific point in the [documentation](http://qiime.org/scripts/split_libraries.html) and rethinking about this the best will be to run split_libraries.py on each file and then concatenate all the outputs.
