### ISSUE TITLE
Another random test failure

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#995]
```
======================================================================
FAIL: test_categories (qiita_db.test.test_metadata_template.DecoratedClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_db/test/test_metadata_template.py", line 1311, in test_categories
    self.assertEqual(obs, exp)
AssertionError: Items in the second set but not the first:
'longitude'
```
Not sure why this is happening, but very rarely it will just fail to find that column in tests.

**Comment by antgonza** [comment]
cause, the order changes depending on different things. That test
should be assertEqualItems

**Comment by squirrelo** [comment]
Cna you get a pull request in to fix that really fast? Thanks.

**Comment by squirrelo** [comment]
Looking at the failure again, it's not failing because of order, it's failing because of a missing item. I don't think assertEqualItems will fix that.

**Comment by antgonza** [comment]
I think it should, let see the tests of #996 ...

**Comment by squirrelo** [comment]
problem is it's rare, so it may pass for that test

**Comment by josenavas** [comment]
`assertEqualItems` should not fix the issue. Note that although it's `assertEqual` it is comparing 2 sets, so no order exists. However, why will be columns randomly dropped?
