### ISSUE TITLE
Explore alternatives for storing sample metadata

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#997]
Once there are no required columns common to all studies (`collection_timestamp`, `is_emp`, etc), a different storage mechanism could be used instead of the solution we have in place. In previous iterations, MongoDB, CouchDB, etc have been explored but in order to decide which technology we will use, a proper benchmark will have to be put in place.

**Comment by wasade** [comment]
This also represents a large change to the code base and does not remove
our dependence on postgres (ontologies, users, etc). What are the benefits
to adding on a nosql solution for the metadata?

**Comment by antgonza** [comment]
@ElDeveloper could you comment?

**Comment by josenavas** [comment]
There has been some discussion on using Cassandra. There is currently a limitation in how we store the metadata (i.e. the number of columns). We need to modify how this is stored, and I think this is a discussion that is better if it happens in a meeting.

**Comment by ElDeveloper** [comment]
@antgonza, one of the other ideas here is to stop using SQL data types and convert things on the fly. Converting things and storing them as specific data types has resulted rather problematic and this was an idea we were throwing around a while ago.

**Comment by josenavas** [comment]
:+1: that will allow us to also store the data as (sample_id, column_name, value) which is something that @wasade already though we're doing. This will remove the limitation of the columns and will allow us to do a sparse representation of the data (no need to store the nulls)

**Comment by antgonza** [comment]
This issue has 2 topics:
1. Changing pgsql to another technology: we decided that this is hard and more cause we are not experts on all other technologies we need to test so staying with what we know will be the easiest and we can always revisit in the future.
2. Changing how we store data so we don't define data types: we store everything as string now.

I think we can close this now. Please open a new issue if you feel otherwise.

**Comment by josenavas** [comment]
@antgonza isn't this related to the work that you're doing on representing the DB information using a different DB structure? My comment from Oct 12 points out to something that you're implementing.

**Comment by antgonza** [comment]
Not sure, perhaps? I think this issue was about testing other technologies ... either way, we are doing this with psql.
